#Requires -Version 5.1
[CmdletBinding()]
param([Parameter(Mandatory=$true)][string]$InvocationManifest,[switch]$Preflight,[switch]$Publish)
Set-StrictMode -Version Latest
$ErrorActionPreference='Stop'
function Require([bool]$Condition,[string]$Message){if(-not$Condition){throw $Message}}
function Sha([string]$Path){(Get-FileHash -LiteralPath $Path -Algorithm SHA256 -ErrorAction Stop).Hash}
function Need([object]$Value,[string]$Name){$p=$Value.PSObject.Properties[$Name];if($null-eq$p){throw "Publication invocation missing $Name"};$p.Value}
function Repo([string]$Root,[string]$Relative){Require (-not[IO.Path]::IsPathRooted($Relative)) "Dependency must be repository-relative: $Relative";$prefix=[IO.Path]::GetFullPath($Root).TrimEnd('\')+'\';$path=[IO.Path]::GetFullPath((Join-Path $prefix $Relative.Replace('/','\')));Require ($path.StartsWith($prefix,[StringComparison]::OrdinalIgnoreCase)) "Dependency escapes repository: $Relative";$path}
function Pinned([string]$Path,[string]$Hash,[string]$Label){Require (Test-Path -LiteralPath $Path -PathType Leaf) "$Label absent: $Path";Require ((Sha $Path)-ceq$Hash) "$Label hash changed"}
function Drive([string]$Share){$ps=Get-PSDrive -Name U -PSProvider FileSystem -ErrorAction Stop;$disk=Get-CimInstance Win32_LogicalDisk -Filter "DeviceID='U:'" -ErrorAction Stop;Require ([string]$ps.DisplayRoot-ceq$Share) 'Persistent U: DisplayRoot changed';Require ([string]$disk.ProviderName-ceq$Share-and[int]$disk.DriveType-eq4) 'Persistent U: provider identity changed'}
function Pending([string]$Root){@(Get-ChildItem -LiteralPath $Root -File -ErrorAction Stop|Where-Object{$_.Name-cmatch'\.ready\.zip(?:\.upload)?$'})}
function ZipManifest([string]$Path){Add-Type -AssemblyName System.IO.Compression.FileSystem;$zip=[IO.Compression.ZipFile]::OpenRead($Path);try{$entry=$zip.GetEntry('PORTAL_REQUEST_MANIFEST.json');Require ($null-ne$entry-and$entry.Length-ge2-and$entry.Length-le1048576) 'Request manifest ZIP entry absent or oversized';$reader=New-Object IO.StreamReader($entry.Open(),(New-Object Text.UTF8Encoding($false,$true)),$true);try{$reader.ReadToEnd()|ConvertFrom-Json}finally{$reader.Dispose()}}finally{$zip.Dispose()}}
function New-Json([string]$Path,[object]$Value){Require (-not(Test-Path -LiteralPath $Path)) "Create-new JSON exists: $Path";[IO.File]::WriteAllText($Path,(($Value|ConvertTo-Json -Depth 24)+[Environment]::NewLine),(New-Object Text.UTF8Encoding($false)))}
Require ($Preflight-xor$Publish) 'Specify exactly one of -Preflight or -Publish';Require ([string]$PSVersionTable.PSEdition-ceq'Desktop'-and[int]$PSVersionTable.PSVersion.Major-eq5-and[int]$PSVersionTable.PSVersion.Minor-eq1) 'Publisher requires Windows PowerShell 5.1'
$project=[IO.Path]::GetFullPath((Join-Path $PSScriptRoot '..\..'));$expected=Join-Path $PSScriptRoot 'O3F16R28G1_PUBLISH_INVOCATION.json';$invPath=[IO.Path]::GetFullPath($InvocationManifest);Require ($invPath.Equals($expected,[StringComparison]::OrdinalIgnoreCase)) 'Publication invocation path changed';$inv=Get-Content -LiteralPath $invPath -Raw|ConvertFrom-Json
Require ([string](Need $inv 'schema')-ceq'argos_ocv03_o3f16r28g1_publish_invocation_v1'-and[string](Need $inv 'state')-ceq'FROZEN_O3F16R28G1_EXACTLY_ONCE_PUBLICATION') 'Publication invocation identity changed';Require ([string](Need $inv 'publisherSha256')-ceq(Sha $PSCommandPath)) 'Publisher bytes changed';Require ([int](Need $inv 'maximumPublications')-eq1-and-not[bool](Need $inv 'requestRetryAuthorized')) 'Publication authority changed'
$requestId=[string](Need $inv 'requestId');Require ($requestId-cmatch'^REQ_[0-9]{8}T[0-9]{9}Z_[0-9A-F]{12}$') 'Request ID shape changed';$source=[IO.Path]::GetFullPath([string](Need $inv 'sourceZip'));$sourceHash=[string](Need $inv 'sourceZipSha256');$sourceBytes=[int64](Need $inv 'sourceZipBytes');Pinned $source $sourceHash 'Source ZIP';Require ((Get-Item -LiteralPath $source).Length-eq$sourceBytes) 'Source ZIP bytes changed'
$manifest=ZipManifest $source;Require ([string]$manifest.schema-ceq'argos_project_portal_request_manifest_v1'-and[string]$manifest.requestId-ceq$requestId-and[string]$manifest.targetRole-ceq'JBOD'-and[string]$manifest.jobClass-ceq'MAINTENANCE_PATCH') 'Request identity changed';Require ([bool]$manifest.reviewOnly-and-not[bool]$manifest.trainingEligible-and-not[bool]$manifest.xmlEligible-and-not[bool]$manifest.productionEligible-and-not[bool]$manifest.productionRoutingEnabled-and-not[bool]$manifest.requestRetryAuthorized) 'Request authority widened'
$routePath=Repo $project ([string](Need $inv 'routeGatePath'));$preactionPath=Repo $project ([string](Need $inv 'preactionGatePath'));$rehearsalPath=Repo $project ([string](Need $inv 'rehearsalGatePath'));$priorPath=Repo $project ([string](Need $inv 'priorTerminalGatePath'))
Pinned $routePath ([string](Need $inv 'routeGateSha256')) 'Route gate';Pinned $preactionPath ([string](Need $inv 'preactionGateSha256')) 'Preaction gate';Pinned $rehearsalPath ([string](Need $inv 'rehearsalGateSha256')) 'Rehearsal gate';Pinned $priorPath ([string](Need $inv 'priorTerminalGateSha256')) 'Prior terminal gate'
$route=Get-Content -LiteralPath $routePath -Raw|ConvertFrom-Json;$preaction=Get-Content -LiteralPath $preactionPath -Raw|ConvertFrom-Json;$rehearsal=Get-Content -LiteralPath $rehearsalPath -Raw|ConvertFrom-Json;$prior=Get-Content -LiteralPath $priorPath -Raw|ConvertFrom-Json
Require ([string]$route.state-ceq'PASS_O3F16R28G1_COMPLETE_ROUTE_PATH_GATE'-and[string]$route.requestId-ceq$requestId-and[int]$route.payloadFileCount-eq33-and-not[bool]$route.routeImplementationChanged) 'Route gate changed'
Require ([string]$preaction.state-cmatch'^PASS_' -and[string]$rehearsal.state-ceq'PASS_O3F16R28G1_EXACT_PACKAGED_REHEARSAL') 'Preaction or packaged rehearsal gate changed';Require ([string]$prior.requestId-ceq'REQ_20260903T233132021Z_2FA7A30A3BB4'-and[bool]$prior.responseSignatureVerified) 'Prior golden request is not signed-terminal'
$share='\\shm-cifs\Department\DE-1302_FAB_BE_Engineering\60_Saw_VI_Sort\600_General\Joshua.conn\AVI_Images\Argos\Uploads\InspectionRevs';Require ([string](Need $inv 'expectedPersistentShare')-ceq$share) 'Publication share changed';Drive $share
$requestRoot='U:\ProjectPortalRO\requests';Require (Test-Path -LiteralPath $requestRoot -PathType Container) 'Project Portal request root unavailable';$ready=Join-Path $requestRoot ($requestId+'.ready.zip');$upload=$ready+'.upload';$gatePath=Join-Path $PSScriptRoot 'O3F16R28G1_PUBLISH_GATE.json';$attemptPath=Join-Path $PSScriptRoot 'O3F16R28G1_PUBLISH_ATTEMPT.json';Require (-not(Test-Path -LiteralPath $gatePath)) 'Publication gate already exists';Require (-not(Test-Path -LiteralPath $attemptPath)) 'Publication attempt already consumed'
$pending=@(Pending $requestRoot);Require ($pending.Count-eq0) ('Publication blocked by pending request: '+(($pending|ForEach-Object{$_.Name})-join', '));Require (-not(Test-Path -LiteralPath $upload)-and-not(Test-Path -LiteralPath $ready)) 'Exact request path already exists'
$pre=[ordered]@{schema='argos_ocv03_o3f16r28g1_publish_preflight_v1';createdUtc=[DateTime]::UtcNow.ToString('o');state='PASS_O3F16R28G1_EXACTLY_ONCE_PUBLICATION_PREFLIGHT';requestId=$requestId;sourceZip=$source;sourceZipBytes=$sourceBytes;sourceZipSha256=$sourceHash;pendingRequestCount=0;expectedPersistentShare=$share;uploadPath=$upload;readyPath=$ready;publicationCountMaximum=1;requestRetryAuthorized=$false;mutationsPerformed=$false;reviewOnly=$true;productionRoutingEnabled=$false}
if($Preflight){$pre|ConvertTo-Json -Depth 10;return}
$attempt=[ordered]@{schema='argos_ocv03_o3f16r28g1_publish_attempt_v1';createdUtc=[DateTime]::UtcNow.ToString('o');state='STARTED_O3F16R28G1_SINGLE_PUBLICATION_ATTEMPT';requestId=$requestId;sourceZipSha256=$sourceHash;sourceZipBytes=$sourceBytes;attemptCount=1;committedBeforeExternalWrite=$true;requestRetryAuthorized=$false};New-Json $attemptPath $attempt
$input=[IO.File]::Open($source,[IO.FileMode]::Open,[IO.FileAccess]::Read,[IO.FileShare]::Read);$output=$null;try{$output=New-Object IO.FileStream($upload,[IO.FileMode]::CreateNew,[IO.FileAccess]::Write,[IO.FileShare]::None);$input.CopyTo($output,1048576);$output.Flush()}finally{if($null-ne$output){$output.Dispose()};$input.Dispose()}
Require ((Get-Item -LiteralPath $upload).Length-eq$sourceBytes-and(Sha $upload)-ceq$sourceHash) 'Upload verification failed; retained as no-retry hold';Drive $share;$transition=@(Pending $requestRoot);Require ($transition.Count-eq1-and$transition[0].FullName.Equals($upload,[StringComparison]::OrdinalIgnoreCase)-and-not(Test-Path -LiteralPath $ready)) 'Queue changed before commit; upload retained as no-retry hold';[IO.File]::Move($upload,$ready)
$readyObserved=Test-Path -LiteralPath $ready -PathType Leaf;if($readyObserved){Require ((Get-Item -LiteralPath $ready).Length-eq$sourceBytes-and(Sha $ready)-ceq$sourceHash) 'Published request verification failed; no retry authorized'}
$gate=[ordered]@{schema='argos_ocv03_o3f16r28g1_publish_gate_v1';createdUtc=[DateTime]::UtcNow.ToString('o');state='PASS_O3F16R28G1_PUBLISHED_EXACTLY_ONCE_AWAITING_MATCHING_SIGNED_RESPONSE';disposition='PENDING_GATE';requestId=$requestId;sourceZip=$source;publishedPath=$ready;publishedBytes=$sourceBytes;publishedSha256=$sourceHash;publicationCount=1;createNewUpload=$true;atomicSameDirectoryUploadToReadyRename=$true;readyObservedAfterCommit=$readyObserved;overwritePerformed=$false;automaticRetryAuthorized=$false;mappingCreatedOrRemoved=$false;sourceMutationOrDeletionPerformed=$false;existingTaskOrProcessActionCount=0;imageBytesRead=$false;providerActivated=$false;holdsAutomaticallyCleared=$false;reviewOnly=$true;trainingEligible=$false;xmlEligible=$false;productionEligible=$false;productionRoutingEnabled=$false};New-Json $gatePath $gate;$gate|ConvertTo-Json -Depth 12
