[CmdletBinding()]
param([switch]$Preflight,[switch]$Rehearsal,[string]$InvocationManifest='')

$ErrorActionPreference='Stop';Set-StrictMode -Version Latest
if(([bool]$Preflight)-eq([bool]$Rehearsal)){throw 'Specify exactly one of -Preflight or -Rehearsal.'}
$project='C:\Users\joshua.conn\Desktop\ArgosDev\ArgosEdgeLab';$root=Join-Path $project 'work\R8';$requestId='REQ_R8';$requestRoot=Join-Path $root 'signed_short\REQ_R8.ready';$testRoot='C:\R8E1';$installedRoot='C:\ProgramData\ArgosEdgeLabRO\AllWaferProcessorV2';$helperDestination=Join-Path $installedRoot 'R8.ps1';$runnerDestination=Join-Path $installedRoot 'Run-JbodAllWaferProcessor.ps1'
$target=Join-Path $requestRoot 'payload\C2R.ps1';$targetSha='3B5FE09081FC4545420B16874D675525A3647785EFD4B1294562ABEE18E6BEC4';$runnerTarget=Join-Path $requestRoot 'payload\Run-JbodAllWaferProcessor.ps1';$runnerTargetSha='46661DB0FC7F12AE7146067403390AF7CC7D0DD933A67C601C56E0EECB4FE9A4';$runnerOldSha='6B61A415DF2F6852C290ABD0F794E86BE13B270A91E9E86E005B76A468404F1C';$manifestSha='3174326BBA1813189BA2F6E4662B6DD95DDE7F68F8408FCEA91C47649E8A3FF6';$worker=Join-Path $project 'work\JBOD_ENDPOINT_MAINTENANCE_PATH_C1E\pkg\payload\W.ps1';$workerSha='244A5ECD88020BF80C217271368C836E0AB82E7B76FDEA9D0D9AC07E0AA034E6'
$requestVerifier=Join-Path $project 'work\PROJECT_PORTAL_REVIEW_ONLY\scripts\Test-SignedPortalPackage.ps1';$responseVerifier=Join-Path $project 'work\PROJECT_PORTAL_REVIEW_ONLY\scripts\Test-SignedPortalResponse.ps1';$public=Join-Path $project 'work\PROJECT_PORTAL_REVIEW_ONLY\enrollment\ARGOS_PROJECT_PORTAL_LAPTOP_SIGNER_PUBLIC.cer';$identityPath=Join-Path $project 'work\PROJECT_PORTAL_REVIEW_ONLY\state\LAPTOP_SIGNING_IDENTITY.json';$gatePath=Join-Path $root 'C2R_EXACT_ENDPOINT_GATE.json'
$sourceConfig=Join-Path $project 'work\JBOD_LOT_VALIDATE_C2V3\pkg\payload\PROCESSOR_CONFIG.json';$sourceRunner=Join-Path $project 'work\JBOD_METADATA_ROOT_CONSUMERS_C1D2\pkg\payload\Run-JbodAllWaferProcessor.ps1';$sourceInventory=Join-Path $project 'work\JBOD_METADATA_ROOT_CONSUMERS_C1D2\pkg\payload\Invoke-JbodAllWaferInventory.ps1';$sourceImporter=Join-Path $project 'work\JBOD_INSITE_HOLD_ATTEMPT_FIX_C2H\pkg\payload\Import-JbodLiveInsiteSnapshot.ps1'
if($Rehearsal-and-not[string]::IsNullOrWhiteSpace($InvocationManifest)){$i=Get-Content -LiteralPath ([IO.Path]::GetFullPath($InvocationManifest)) -Raw|ConvertFrom-Json;if([string]$i.schema-ne'argos_r8_endpoint_test_invocation_v1'){throw 'R8 endpoint-test invocation schema changed.'};$requestRoot=[IO.Path]::GetFullPath([string]$i.requestRoot);$testRoot=[IO.Path]::GetFullPath([string]$i.testRoot);$target=Join-Path $requestRoot 'payload\C2R.ps1';$runnerTarget=Join-Path $requestRoot 'payload\Run-JbodAllWaferProcessor.ps1';$gatePath=[IO.Path]::GetFullPath([string]$i.gatePath)}
foreach($p in @($requestRoot,$target,$runnerTarget,$worker,$requestVerifier,$responseVerifier,$public,$identityPath,$sourceConfig,$sourceRunner,$sourceInventory,$sourceImporter)){if(-not(Test-Path -LiteralPath $p)){throw "R8 endpoint prerequisite missing: $p"}}
if((Get-FileHash -Algorithm SHA256 $target).Hash-ne$targetSha-or(Get-FileHash -Algorithm SHA256 $runnerTarget).Hash-ne$runnerTargetSha-or(Get-FileHash -Algorithm SHA256 (Join-Path $requestRoot 'PORTAL_REQUEST_MANIFEST.json')).Hash-ne$manifestSha-or(Get-FileHash -Algorithm SHA256 $worker).Hash-ne$workerSha){throw 'R8 endpoint pinned input changed.'}
if(Test-Path -LiteralPath $testRoot){throw "Fresh C2R endpoint root required: $testRoot"}
if($Preflight){[ordered]@{schema='argos_c2r_endpoint_preflight_v1';createdUtc=[DateTime]::UtcNow.ToString('o');state='PASS_C2R_EXACT_ENDPOINT_PREFLIGHT';requestId=$requestId;requestManifestSha256=$manifestSha;endpointWorkerSha256=$workerSha;allowCreate=$true;approvedTargetIdempotence=$true;mutationsPerformed=$false;reviewOnly=$true;productionRoutingEnabled=$false}|ConvertTo-Json -Depth 5;return}
$utf8=New-Object Text.UTF8Encoding($false);$identity=Get-Content -Raw $identityPath|ConvertFrom-Json
function Write-Json([string]$Path,[object]$Value){$parent=Split-Path -Parent $Path;if(-not(Test-Path $parent)){[void](New-Item -ItemType Directory -Path $parent -Force)};[IO.File]::WriteAllText($Path,(($Value|ConvertTo-Json -Depth 24)+[Environment]::NewLine),$utf8)}
function New-LotState([int]$NotReady){if($NotReady){[pscustomobject]@{catalogGeneratedUtc='2026-08-21T16:20:00Z';queueRows=10;confirmedPhysical=10;overlayPhysicalMatches=10;catalogRows=20;metadataMatchedCatalogRows=20;staleMatchedInsiteRows=0;notReadyMatchedRows=20;scribeHoldRows=6;routeStates=@([pscustomobject]@{state='HOLD_FRONTSIDE_APPEARANCE_ROUTE_NOT_YET_QUALIFIED';count=14},[pscustomobject]@{state='HOLD_SCRIBE_CONFIRMATION_REQUIRED_BEFORE_DETECTOR';count=6})}}else{[pscustomobject]@{catalogGeneratedUtc='2099-08-21T16:21:00Z';queueRows=10;confirmedPhysical=10;overlayPhysicalMatches=10;catalogRows=20;metadataMatchedCatalogRows=20;staleMatchedInsiteRows=0;notReadyMatchedRows=0;scribeHoldRows=0;routeStates=@([pscustomobject]@{state='READY_FRONTSIDE_SCRATCH_TEST_REVIEW_ONLY_PROCESSING';count=10},[pscustomobject]@{state='READY_BACKSIDE_REVIEW_ONLY_PROCESSING';count=10})}}}
function New-Fixture([string]$Name,[bool]$Inject){
    $base=Join-Path (Join-Path $testRoot $Name) 'fixture';$processor=Join-Path $base 'p';[void](New-Item -ItemType Directory -Path (Join-Path $processor 'processor') -Force);Copy-Item $sourceConfig (Join-Path $processor 'PROCESSOR_CONFIG.json');Copy-Item $sourceRunner (Join-Path $processor 'Run-JbodAllWaferProcessor.ps1');Copy-Item $sourceInventory (Join-Path $processor 'Invoke-JbodAllWaferInventory.ps1');Copy-Item $sourceImporter (Join-Path $processor 'Import-JbodLiveInsiteSnapshot.ps1');Write-Json (Join-Path $processor 'processor\PROCESSOR_STATUS.json') ([ordered]@{state='WATCHING';updatedUtc=[DateTime]::UtcNow.ToString('o');currentIdentity='';reviewOnly=$true;xmlExportEnabled=$false})
    $runner=Join-Path $processor 'Run-JbodAllWaferProcessor.ps1';$task=[pscustomobject]@{name='ArgosEdgeLab.AllWaferProcessor.ReviewOnly.V2';taskPath='\';principal='SYSTEM';state='Running';definitionSha256=('B'*64);actions=@([pscustomobject]@{execute='powershell.exe';arguments=('-File "'+$runner+'" -ConfigPath "'+(Join-Path $processor 'PROCESSOR_CONFIG.json')+'"')})};$before=[pscustomobject]@{processId=101;creationUtc='2026-08-20T01:00:00Z';commandLine='processor'};$after=[pscustomobject]@{processId=202;creationUtc='2026-08-20T06:00:00Z';commandLine='processor'}
    $path=Join-Path $base 'INVOCATION.json';Write-Json $path ([ordered]@{schema='argos_c2r_rehearsal_v1';processorRoot=$processor;expectedInventorySha256=(Get-FileHash -Algorithm SHA256 -LiteralPath $sourceInventory).Hash;expectedImporterSha256=(Get-FileHash -Algorithm SHA256 -LiteralPath $sourceImporter).Hash;tasksBefore=@($task);tasksAfter=@($task);processesBefore=@($before);processesAfter=@($after);lotStateBefore=(New-LotState 20);lotStateAfter=(New-LotState 0);failAfterAuthorization=$Inject});return $path
}
function Set-Destination([string]$Mode){if(Test-Path $helperDestination){Remove-Item $helperDestination -Force};if($Mode-eq'old'){Copy-Item $sourceRunner $runnerDestination -Force;return};if($Mode-eq'target'){Copy-Item $target $helperDestination -Force;Copy-Item $runnerTarget $runnerDestination -Force;return};if($Mode-eq'bad'){[IO.File]::WriteAllText($runnerDestination,"# UNAPPROVED R8`r`n",$utf8);return};throw "Unknown mode: $Mode"}
function Invoke-Case([string]$Name,[string]$Mode,[string]$Expected,[bool]$Inject){
    $case=Join-Path $testRoot $Name;foreach($r in @('incoming','processed','responses','state')){[void](New-Item -ItemType Directory -Path (Join-Path $case $r) -Force)};Set-Destination $Mode;$helperBefore=if(Test-Path $helperDestination){(Get-FileHash -Algorithm SHA256 $helperDestination).Hash}else{''};$runnerBefore=(Get-FileHash -Algorithm SHA256 $runnerDestination).Hash;Copy-Item $requestRoot (Join-Path $case 'incoming') -Recurse
    $config=[ordered]@{schema='argos_project_portal_endpoint_config_v1';role='JBOD';reviewOnly=$true;productionRoutingEnabled=$false;incomingRoot=Join-Path $case 'incoming';processedRoot=Join-Path $case 'processed';responseOutbox=Join-Path $case 'responses';stateRoot=Join-Path $case 'state';requestVerifierPath=$requestVerifier;laptopSignerCertificatePath=$public;endpointSignerThumbprint=[string]$identity.thumbprint;endpointSignerStoreLocation='CurrentUser';approvedMaintenanceRoots=@($installedRoot);approvedDataRoots=@();status=[ordered]@{tasks=@();hashFiles=@();jsonFiles=@();logs=@()};handlers=@()};$configPath=Join-Path $case 'ENDPOINT_CONFIG.json';Write-Json $configPath $config;$inv=New-Fixture $Name $Inject;$prior=$env:ARGOS_C2R_REHEARSAL_MANIFEST
    try{$env:ARGOS_C2R_REHEARSAL_MANIFEST=$inv;& powershell.exe -NoProfile -ExecutionPolicy Bypass -File $worker -ConfigPath $configPath -Once;if($LASTEXITCODE-ne0){throw "C2R endpoint process failed: $Name"}}finally{$env:ARGOS_C2R_REHEARSAL_MANIFEST=$prior}
    $responses=@(Get-ChildItem (Join-Path $case 'responses') -Directory -Filter '*.ready');if($responses.Count-ne1){throw "R8 response count failed: $Name"};& powershell.exe -NoProfile -ExecutionPolicy Bypass -File $responseVerifier -PackagePath $responses[0].FullName -EndpointCertificatePath $public -ExpectedSourceRole JBOD -ExpectedRequestId $requestId|Out-Null;if($LASTEXITCODE-ne0){throw "R8 response signature failed: $Name"};$response=Get-Content -Raw (Join-Path $responses[0].FullName 'PORTAL_RESPONSE_MANIFEST.json')|ConvertFrom-Json;if([string]$response.state-ne$Expected){throw "R8 endpoint state mismatch: $Name / $($response.state)"};$helperAfter=if(Test-Path $helperDestination){(Get-FileHash -Algorithm SHA256 $helperDestination).Hash}else{''};$runnerAfter=(Get-FileHash -Algorithm SHA256 $runnerDestination).Hash
    if($Expected-eq'PASS_MAINTENANCE_PATCH'){if($helperAfter-ne$targetSha-or$runnerAfter-ne$runnerTargetSha){throw "R8 targets absent: $Name"};$stdout=Get-Content -Raw (Join-Path $responses[0].FullName 'MAINTENANCE.stdout.txt')|ConvertFrom-Json;if([string]$stdout.state-ne'PASS_JBOD_PROCESSOR_RUNNER_FIX_AND_REFRESH_R8'-or-not[bool]$stdout.processorTaskRestarted-or[int]$stdout.staleMatchedInsiteRowsAfter-ne0-or[int]$stdout.notReadyMatchedRowsAfter-ne0-or[int]$stdout.metadataMatchedCatalogRows-ne20){throw "R8 stdout contract failed: $Name"}}
    elseif($Mode-eq'bad'-and($helperAfter-ne$helperBefore-or$runnerAfter-ne$runnerBefore)){throw 'R8 unapproved refusal mutated a destination.'}elseif($Inject-and($helperAfter-ne$helperBefore-or$runnerAfter-ne$runnerBefore)){throw 'R8 runtime failure did not roll back exact predecessor state.'}
    [pscustomobject]@{case=$Name;mode=$Mode;endpointState=[string]$response.state;helperBeforeSha256=$helperBefore;helperAfterSha256=$helperAfter;runnerBeforeSha256=$runnerBefore;runnerAfterSha256=$runnerAfter;responseId=[string]$response.responseId;signatureVerified=$true}
}
[void](New-Item -ItemType Directory -Path $testRoot);[void](New-Item -ItemType Directory -Path $installedRoot -Force);$initialHelper=Test-Path $helperDestination;$helperBackup=Join-Path $testRoot 'INITIAL_HELPER.ps1';if($initialHelper){Copy-Item $helperDestination $helperBackup};$initialRunner=Test-Path $runnerDestination;$runnerBackup=Join-Path $testRoot 'INITIAL_RUNNER.ps1';if($initialRunner){Copy-Item $runnerDestination $runnerBackup};$results=New-Object Collections.Generic.List[object]
try{$results.Add((Invoke-Case 'approved_old' 'old' 'PASS_MAINTENANCE_PATCH' $false));$results.Add((Invoke-Case 'target_idempotent' 'target' 'PASS_MAINTENANCE_PATCH' $false));$results.Add((Invoke-Case 'unapproved' 'bad' 'FAILED' $false));$results.Add((Invoke-Case 'runtime_failure_rollback' 'old' 'FAILED' $true));$results.Add((Invoke-Case 'control_after_failure' 'old' 'PASS_MAINTENANCE_PATCH' $false));$gate=[ordered]@{schema='argos_r8_exact_endpoint_gate_v1';createdUtc=[DateTime]::UtcNow.ToString('o');state='PASS_R8_EXACT_ENDPOINT_GATE';requestId=$requestId;requestManifestSha256=$manifestSha;endpointWorkerSha256=$workerSha;approvedOldPredecessorExercised=$true;targetIdempotenceAccepted=$true;unapprovedPredecessorRefusedBeforeMutation=$true;runtimeVerifierFailureRolledBack=$true;controlAfterRuntimeFailurePassed=$true;responseSignaturesVerified=$results.Count;results=$results.ToArray();taskFixtureOnly=$true;sourceDeletionPerformed=$false;otherInspectionTasksChanged=$false;waferAborted=$false;reviewOnly=$true;productionRoutingEnabled=$false};Write-Json $gatePath $gate}
finally{if($initialHelper){Copy-Item $helperBackup $helperDestination -Force}elseif(Test-Path $helperDestination){Remove-Item $helperDestination -Force};if($initialRunner){Copy-Item $runnerBackup $runnerDestination -Force}elseif(Test-Path $runnerDestination){Remove-Item $runnerDestination -Force};$resolved=Resolve-Path $testRoot -ErrorAction SilentlyContinue;if($null-ne$resolved-and$resolved.Path-eq'C:\R8E1'){Remove-Item $testRoot -Recurse -Force}}
Get-Content -Raw $gatePath
