[CmdletBinding()]param([switch]$Preflight,[switch]$Build)
$ErrorActionPreference='Stop';Set-StrictMode -Version Latest;if(@($Preflight,$Build|Where-Object{$_}).Count-ne1){throw 'Specify exactly one mode.'}
$root=Split-Path -Parent $MyInvocation.MyCommand.Path;$source=Join-Path $root 'signed_o3b3\REQ_O3B3.ready';$final=Join-Path $root 'final';$partial=Join-Path $root 'final.partial';$zipName='REQ_O3B3.ready.zip';$cert=Join-Path (Split-Path -Parent $root) 'PROJECT_PORTAL_REVIEW_ONLY\enrollment\ARGOS_PROJECT_PORTAL_LAPTOP_SIGNER_PUBLIC.cer'
$expected=[ordered]@{'PORTAL_REQUEST_MANIFEST.json'='73F4DE9D834B556F920E60E2C43F1ED2896DDCF9D9CFD118803C649386F28692';'PORTAL_REQUEST_MANIFEST.sig'='4802C8138425828071080CA5A54A8D75361CA7B24441FD1B94F41D11093FE920';'payload/E.ps1'='50F44439FEB90314D63620D6501E6C9650A0D3ADDDA2F3EEA227987D9E717E12';'payload/W.ps1'='047BB0D79999F1FF2A9FF9373C9B34C9A7BDE82AAFE0605E1929A10ACBEBF988'}
$definition=Join-Path $root 'pkg\MAINTENANCE_DEFINITION.json';$entryGate=Join-Path $root 'O3B3_ENTRYPOINT_REHEARSAL_GATE.json';$queueGate=Join-Path (Split-Path -Parent $root) 'JBOD_ENDPOINT_MAINTENANCE_PATH_C1E\C1E_QUEUE_SAFETY_PASS.json';$routeGate=Join-Path (Split-Path -Parent $root) 'FIDUCIAL_JBOD_INVENTORY_CAPABILITY_FIC1\FIC1_COMPLETE_ROUTE_GATE.json'
$pins=[ordered]@{definition='F2198637959CFBAB6657A0263F9C84677B9B477F1E1A0954B4265827DDCCBD1A';entryGate='B23E4648B842BED59A89A68FCB3761CCF9C4F394CF96EC4B05EECB197E80C377';queueGate='170015C259C3EC8FC0B369F070748A555336F8FB312636819B7F99EBCE85A65D';routeGate='32AFF1FD7DCC1FA96A9C245FB3385EC7C01484B03B6A70C01C3F92064C0C8C83'}
function Sha([string]$p){(Get-FileHash -LiteralPath $p -Algorithm SHA256).Hash};foreach($p in @($source,$cert,$definition,$entryGate,$queueGate,$routeGate)){if(-not(Test-Path -LiteralPath $p)){throw "O3B3 final prerequisite missing: $p"}}
foreach($pair in @(@($definition,$pins.definition),@($entryGate,$pins.entryGate),@($queueGate,$pins.queueGate),@($routeGate,$pins.routeGate))){if((Sha $pair[0])-ne$pair[1]){throw "O3B3 gate changed: $($pair[0])"}}
$entryValue=Get-Content $entryGate -Raw|ConvertFrom-Json;$queueValue=Get-Content $queueGate -Raw|ConvertFrom-Json;$routeValue=Get-Content $routeGate -Raw|ConvertFrom-Json
if([string]$entryValue.state-ne'PASS_O3B3_ENTRYPOINT_REHEARSAL'-or[string]$queueValue.state-ne'PASS_JBOD_PORTAL_QUEUE_RECOVERY_V2_1_REHEARSAL'-or[string]$routeValue.state-ne'PASS_FIC1_COMPLETE_ROUTE_GATE'-or[string]$routeValue.endpointWorkerTargetSha256-ne'750022568C62C2C049D04CE0D49E2FD52B5030A9701D8E453152129EB48D6F08'){throw 'O3B3 inherited gate contract failed.'}
$files=@(Get-ChildItem -LiteralPath $source -Recurse -File);if($files.Count-ne4){throw 'O3B3 signed file count changed.'};foreach($item in $expected.GetEnumerator()){$p=Join-Path $source $item.Key.Replace('/','\');if((Sha $p)-ne$item.Value){throw "O3B3 signed file changed: $($item.Key)"}}
if((Test-Path -LiteralPath $final)-or(Test-Path -LiteralPath $partial)){throw 'O3B3 final path collision.'};$planned=@((Join-Path $partial $zipName),(Join-Path $partial 'extract\payload\Invoke-ArgosProjectPortalEndpointWorker.ps1'),(Join-Path $final ($zipName+'.gate.json')));$pathGate=& (Join-Path (Split-Path -Parent (Split-Path -Parent $root)) 'utilities\Confirm-ArgosPathBudget.ps1') -CandidatePath $planned -ReservedSuffixCharacters 32 -AsJson|ConvertFrom-Json;if([string]$pathGate.state-ne'PASS_PATH_BUDGET'){throw 'O3B3 final path budget failed.'}
if($Preflight){[ordered]@{schema='argos_o3b3_final_preflight_v1';state='PASS_O3B3_FINAL_PREFLIGHT';signedFiles=$files.Count;pathState=$pathGate.state;mutationsPerformed=$false;reviewOnly=$true;productionRoutingEnabled=$false}|ConvertTo-Json;return}
Add-Type -AssemblyName System.IO.Compression;Add-Type -AssemblyName System.IO.Compression.FileSystem;[void](New-Item -ItemType Directory -Path $partial);$zip=Join-Path $partial $zipName;$extract=Join-Path $partial 'extract';[IO.Compression.ZipFile]::CreateFromDirectory($source,$zip,[IO.Compression.CompressionLevel]::Optimal,$false);[IO.Compression.ZipFile]::ExtractToDirectory($zip,$extract)
foreach($item in $expected.GetEnumerator()){$p=Join-Path $extract $item.Key.Replace('/','\');if((Sha $p)-ne$item.Value){throw "O3B3 ZIP file changed: $($item.Key)"}}
$manifestPath=Join-Path $extract 'PORTAL_REQUEST_MANIFEST.json';$signaturePath=Join-Path $extract 'PORTAL_REQUEST_MANIFEST.sig';$certificate=New-Object Security.Cryptography.X509Certificates.X509Certificate2($cert);$rsa=[Security.Cryptography.X509Certificates.RSACertificateExtensions]::GetRSAPublicKey($certificate);try{$signaturePassed=$rsa.VerifyData([IO.File]::ReadAllBytes($manifestPath),[IO.File]::ReadAllBytes($signaturePath),[Security.Cryptography.HashAlgorithmName]::SHA256,[Security.Cryptography.RSASignaturePadding]::Pkcs1)}finally{$rsa.Dispose();$certificate.Dispose()};if(-not$signaturePassed){throw 'O3B3 signature verification failed.'}
$manifest=Get-Content $manifestPath -Raw|ConvertFrom-Json;if([string]$manifest.requestId-ne'REQ_O3B3'-or[string]$manifest.jobClass-ne'MAINTENANCE_PATCH'-or@($manifest.files).Count-ne2-or@($manifest.changes).Count-ne1-or@($manifest.entryPointMutations).Count-ne1-or@($manifest.entryPointOutputs).Count-ne1-or@($manifest.allowedTaskActions).Count-ne0-or@($manifest.allowedProcessActions).Count-ne0){throw 'O3B3 manifest contract failed.'};foreach($relative in @('payload/E.ps1','payload/W.ps1')){$tokens=$null;$errors=$null;[void][Management.Automation.Language.Parser]::ParseFile((Join-Path $extract $relative.Replace('/','\')),[ref]$tokens,[ref]$errors);if(@($errors).Count){throw "O3B3 ZIP parser failed: $relative"}}
$gate=[ordered]@{schema='argos_o3b3_final_package_gate_v1';createdUtc=[DateTime]::UtcNow.ToString('o');state='PASS_O3B3_FINAL_PACKAGE_GATE';requestId='REQ_O3B3';requestZip='work/OPENCV_BACKSIDE_NOTCH_STATUS_O3B3/final/REQ_O3B3.ready.zip';requestZipBytes=(Get-Item $zip).Length;requestZipSha256=(Sha $zip);requestManifestSha256=$expected['PORTAL_REQUEST_MANIFEST.json'];requestSignatureSha256=$expected['PORTAL_REQUEST_MANIFEST.sig'];entrypointSha256=$expected['payload/E.ps1'];workerPredecessorSha256='750022568C62C2C049D04CE0D49E2FD52B5030A9701D8E453152129EB48D6F08';workerTargetSha256=$expected['payload/W.ps1'];signatureVerified=$true;exactZipExtractionPassed=$true;entrypointRehearsalGateSha256=$pins.entryGate;queueGateSha256=$pins.queueGate;routeGateSha256=$pins.routeGate;publicationAuthorized=$false;reviewOnly=$true;productionRoutingEnabled=$false};[IO.File]::WriteAllText((Join-Path $partial ($zipName+'.gate.json')),($gate|ConvertTo-Json -Depth 8),(New-Object Text.UTF8Encoding($false)));Move-Item -LiteralPath $partial -Destination $final;$gate|ConvertTo-Json -Depth 8
