[CmdletBinding()]param([switch]$Preflight,[switch]$Gate)
$ErrorActionPreference='Stop';Set-StrictMode -Version Latest;if(@($Preflight,$Gate|Where-Object{$_}).Count-ne1){throw 'Specify exactly one mode.'}
$root=Split-Path -Parent $MyInvocation.MyCommand.Path;$work=Split-Path -Parent $root;$entry=Join-Path $root 'pkg\payload\E.ps1';$targetWorker=Join-Path $root 'pkg\payload\W.ps1';$priorWorker=Join-Path $work 'FIDUCIAL_JBOD_INVENTORY_CAPABILITY_FIC1\pkg\payload\W.ps1';$provider=Join-Path $work 'OPENCV_OLS4\Invoke-OCV00DeepestAliasInventory.ps1';$fixtureRoot='C:\O3B3T';$gatePath=Join-Path $root 'O3B3_ENTRYPOINT_REHEARSAL_GATE.json'
$h=[ordered]@{entry='50F44439FEB90314D63620D6501E6C9650A0D3ADDDA2F3EEA227987D9E717E12';target='047BB0D79999F1FF2A9FF9373C9B34C9A7BDE82AAFE0605E1929A10ACBEBF988';prior='750022568C62C2C049D04CE0D49E2FD52B5030A9701D8E453152129EB48D6F08';provider='DFF2B3A54E9C6D30A003CF4CFC283FECA0F104B5D5A2929296A81D283CAA5675'}
function Sha([string]$p){(Get-FileHash -LiteralPath $p -Algorithm SHA256).Hash};foreach($pair in @(@($entry,$h.entry),@($targetWorker,$h.target),@($priorWorker,$h.prior),@($provider,$h.provider))){if((Sha $pair[0])-ne$pair[1]){throw "O3B3 dependency changed: $($pair[0])"}}
if($Preflight){if(Test-Path $fixtureRoot){throw 'O3B3 fixture root exists.'};if(Test-Path $gatePath){throw 'O3B3 gate exists.'};[ordered]@{schema='argos_o3b3_test_preflight_v1';state='PASS_O3B3_TEST_PREFLIGHT';mutationsPerformed=$false}|ConvertTo-Json;return}
if(Test-Path $fixtureRoot){throw 'O3B3 fixture collision.'};[void](New-Item -ItemType Directory -Path $fixtureRoot)
function New-Case([string]$Name,[bool]$Target=$false,[bool]$Corrupt=$false){$case=Join-Path $fixtureRoot $Name;$portal=Join-Path $case 'portal';$processor=Join-Path $case 'processor';[void](New-Item -ItemType Directory -Path (Join-Path $portal 'bin') -Force);[void](New-Item -ItemType Directory -Path $processor -Force);$worker=Join-Path $portal 'bin\Invoke-ArgosProjectPortalEndpointWorker.ps1';Copy-Item -LiteralPath $(if($Target){$targetWorker}else{$priorWorker}) -Destination $worker;Copy-Item -LiteralPath $provider -Destination (Join-Path $processor 'OCV03_MetadataProviderV1.ps1');if($Corrupt){[IO.File]::AppendAllText($worker,'X',(New-Object Text.UTF8Encoding($false)))};[pscustomobject]@{case=$case;portal=$portal;processor=$processor;worker=$worker;output=Join-Path $processor 'OCV03_O3B3_STATUS_CAPABILITY.json'}}
function Manifest([object]$Case,[bool]$Fail=$false){$path=Join-Path $Case.case 'invocation.json';$value=[ordered]@{schema='argos_o3b3_entrypoint_invocation_v1';portalRoot=$Case.portal;processorRoot=$Case.processor;failAfterSwap=$Fail};[IO.File]::WriteAllText($path,($value|ConvertTo-Json),(New-Object Text.UTF8Encoding($false)));$path}
function Run([string]$Manifest,[switch]$AsPreflight){$invoke=@{InvocationManifest=$Manifest};if($AsPreflight){$invoke.Preflight=$true}else{$invoke.Rehearsal=$true};(& $entry @invoke|Out-String)|ConvertFrom-Json}
$success=New-Case 'success';$successResult=Run (Manifest $success);if([string]$successResult.state-ne'PASS_O3B3_STATUS_METADATA_CAPABILITY_INSTALLED'-or(Sha $success.worker)-ne$h.target-or-not(Test-Path $success.output)){throw 'O3B3 success failed.'}
$rollback=New-Case 'rollback';$injected=$false;try{[void](Run (Manifest $rollback $true))}catch{$injected=$_.Exception.Message-like'*INJECTED_O3B3_FAILURE_AFTER_SWAP*'};if(-not$injected-or(Sha $rollback.worker)-ne$h.prior-or(Test-Path $rollback.output)){throw 'O3B3 rollback failed.'}
$idempotent=New-Case 'idempotent' $true;$idempotentResult=Run (Manifest $idempotent);if([bool]$idempotentResult.workerChanged-or(Sha $idempotent.worker)-ne$h.target){throw 'O3B3 idempotent failed.'}
$refusal=New-Case 'unapproved' $false $true;$refused=$false;try{[void](Run (Manifest $refusal) -AsPreflight)}catch{$refused=$_.Exception.Message-like'*worker predecessor refused*'};if(-not$refused-or(Test-Path $refusal.output)){throw 'O3B3 refusal failed.'}
$gateRecord=[ordered]@{schema='argos_o3b3_entrypoint_rehearsal_gate_v1';createdUtc=[DateTime]::UtcNow.ToString('o');state='PASS_O3B3_ENTRYPOINT_REHEARSAL';entrypointSha256=$h.entry;workerSha256=$h.target;cases=@('SUCCESS','ROLLBACK_AFTER_SWAP','IDEMPOTENT_TARGET','UNAPPROVED_REFUSAL');taskActions=@();processActions=@();imageBytesRead=$false;sourceHashingPerformed=$false;mutationsPerformed='LOCAL_FIXTURE_ONLY';reviewOnly=$true;productionRoutingEnabled=$false};[IO.File]::WriteAllText($gatePath,($gateRecord|ConvertTo-Json -Depth 6),(New-Object Text.UTF8Encoding($false)));$gateRecord|ConvertTo-Json -Depth 6
