#Requires -Version 5.1
[CmdletBinding(DefaultParameterSetName='Preflight')]
param([Parameter(ParameterSetName='Preflight')][switch]$Preflight,[Parameter(Mandatory=$true,ParameterSetName='Build')][switch]$Build)
Set-StrictMode -Version Latest
$ErrorActionPreference='Stop'
$project=[IO.Path]::GetFullPath((Join-Path $PSScriptRoot '..\..'));$sourceRoot=Join-Path $project 'work\OPENCV_BACKSIDE_NOTCH_O3B10';$root='C:\R31VAL2PK';$payload=Join-Path $root 'payload';$gatePath=Join-Path $PSScriptRoot 'R31VAL2_BUILD_GATE.json';$parentGatePath=Join-Path $PSScriptRoot 'R31VAL1_BUILD_GATE.json';$parentGateHash='933095F855147DAB679DE803EAD7A116262A32FCBAD625081F769931E0C27A78';$newInvokeHash='3A9E080638EDDA9D7E5566E56C7B2E0B47C4D227F3433ADCA143354B83B7A2CB';$newContractHash='D1D551068DE648D905A767A33566DEB8CFC90369894BF89FB774ED0BBA38F45D'
function Sha([string]$Path){(Get-FileHash -LiteralPath $Path -Algorithm SHA256 -ErrorAction Stop).Hash}
function Write-NewJson([string]$Path,[object]$Value){if(Test-Path -LiteralPath $Path){throw "Create-new path exists: $Path"};[IO.File]::WriteAllText($Path,(($Value|ConvertTo-Json -Depth 20)+[Environment]::NewLine),(New-Object Text.UTF8Encoding($false)))}
if(-not(Test-Path -LiteralPath $parentGatePath -PathType Leaf)-or(Sha $parentGatePath)-ne$parentGateHash){throw 'R31VAL2 parent payload lock absent or changed.'};$parent=Get-Content -LiteralPath $parentGatePath -Raw|ConvertFrom-Json;if([string]$parent.state-ne'PASS_R31VAL1_UNSIGNED_ALL_CURRENT_RECIPE_PACKAGE_BUILT'-or[int]$parent.payloadFileCount-ne26){throw 'R31VAL2 parent payload lock state changed.'}
$sources=[ordered]@{};foreach($row in @($parent.payloadFiles)){if([string]$row.path-in@('Invoke-R31VAL1.ps1','R31VAL1_CONTRACT.json')){continue};if([string]$row.path-eq'C.json'){$path='C:\R21P5\payload\C.json'}elseif([string]$row.path-like'Detect-*'-or[string]$row.path-in@('BACKSIDE_NOTCH_CONFIG_R13.json','R18_REGRESSION_CASES.json')){$path=Join-Path $sourceRoot ([string]$row.path)}else{$path=Join-Path $PSScriptRoot ([string]$row.path)};$sources[[string]$row.path]=@($path,[string]$row.sha256)};$sources['Invoke-R31VAL2.ps1']=@((Join-Path $PSScriptRoot 'Invoke-R31VAL2.ps1'),$newInvokeHash);$sources['R31VAL2_CONTRACT.json']=@((Join-Path $PSScriptRoot 'R31VAL2_CONTRACT.json'),$newContractHash)
foreach($name in $sources.Keys){$path=[string]$sources[$name][0];if(-not(Test-Path -LiteralPath $path -PathType Leaf)-or(Sha $path)-ne[string]$sources[$name][1]){throw "R31VAL2 source absent or changed: $name"}}
if($Preflight){[ordered]@{schema='argos_o3b21_r31val2_build_preflight_v1';state='PASS_R31VAL2_BUILD_PREFLIGHT';buildRoot=$root;payloadFileCount=$sources.Count;exactCaseCount=298;maximumConcurrentChildren=4;syntheticTestCount=80;maximumTotalSeconds=1200;targetExecuted=$false;mutationsPerformed=$false}|ConvertTo-Json;return}
if(Test-Path -LiteralPath $root){throw 'R31VAL2 build root exists.'};if(Test-Path -LiteralPath $gatePath){throw 'R31VAL2 build gate exists.'};[void](New-Item -ItemType Directory -Path $payload -Force);foreach($name in $sources.Keys){[IO.File]::Copy([string]$sources[$name][0],(Join-Path $payload $name),$false)};$actual=@(Get-ChildItem -LiteralPath $payload -File|Sort-Object Name);if($actual.Count-ne26){throw 'R31VAL2 payload cardinality failed.'}
$definition=[ordered]@{targetRole='JBOD';jobClass='MAINTENANCE_PATCH';maxResultBytes=134217728;entryPoint='payload/Invoke-R31VAL2.ps1';changes=@([ordered]@{source='payload/C.json';destination='C:/ProgramData/ArgosEdgeLabRO/AllWaferProcessorV2/PROCESSOR_CONFIG.json';approvedPredecessorSha256=@('CDFD888129D0144C9942D027B0C4583FEEF3619D6D65B060B3001686357879D8');installedSha256='CDFD888129D0144C9942D027B0C4583FEEF3619D6D65B060B3001686357879D8';allowCreate=$false});allowedTaskActions=@();rehearsal=[ordered]@{requiredState='PASS_O3B21_R31VAL2_EXACT_298_EXECUTIONS_COMPLETE'}};Write-NewJson (Join-Path $root 'DEFINITION.json') $definition
$payloadFiles=@($actual|ForEach-Object{[ordered]@{path=$_.Name;bytes=$_.Length;sha256=Sha $_.FullName}});$gate=[ordered]@{schema='argos_o3b21_r31val2_build_gate_v1';createdUtc=[DateTime]::UtcNow.ToString('o');state='PASS_R31VAL2_UNSIGNED_EXACT_298_PACKAGE_BUILT';root=$root;payloadFileCount=26;payloadFiles=$payloadFiles;entrySha256=$newInvokeHash;runnerSha256='24D1BF4B04182C9EC38DF141F0F31B0046E09D7873CA18359C4B76072069EC54';contractSha256=$newContractHash;detectorSha256='34476F0109CE68FB6365A7C650CC6FFF2B874B64A38EAA0DA09542261427BCA7';definitionSha256=Sha (Join-Path $root 'DEFINITION.json');exactCaseCount=298;currentRecipeCount=265;frozenCaseCount=32;maximumConcurrentChildren=4;syntheticTestCount=80;sameBytesCarrier=$true;installedSemanticChange=$false;taskOrProcessActionCount=0;pythonCacheLeafCount=0;signed=$false;published=$false;targetExecuted=$false;mutationsPerformed=$false};Write-NewJson $gatePath $gate;$gate|ConvertTo-Json -Depth 10
