#Requires -Version 5.1
[CmdletBinding()]
param([switch]$Preflight, [switch]$Build)
Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'
function Assert-G1([bool]$Value,[string]$Message){if(-not$Value){throw $Message}}
function Hash-G1([string]$Path){(Get-FileHash -LiteralPath $Path -Algorithm SHA256 -ErrorAction Stop).Hash}
function Pin-G1([string]$Path,[string]$Hash){Assert-G1 (Test-Path -LiteralPath $Path -PathType Leaf) "Missing R25G1 dependency: $Path";Assert-G1 ((Hash-G1 $Path)-eq$Hash) "Changed R25G1 dependency: $Path"}
$count=0;if($Preflight){$count++};if($Build){$count++};Assert-G1 ($count-eq1) 'Select exactly one R25G1 action.'
$requestId='REQ_20260901T161846627Z_6B71EECCA831'
$project=[IO.Path]::GetFullPath((Join-Path $PSScriptRoot '..\..'))
$entry=Join-Path $PSScriptRoot 'R25G1_E.ps1';$marker=Join-Path $PSScriptRoot 'R25G1_M.json'
Pin-G1 $entry '2FBD3D885E89B40B780BF4756D3EAB51553852499A1FBDC4BD4C956AC6F937B2';Pin-G1 $marker 'C283095BC100AF11DE378CFD8D963BAE67A9E022F88AD24B49893422CCD46453'
$identityPath=Join-Path $project 'work\PROJECT_PORTAL_REVIEW_ONLY\state\LAPTOP_SIGNING_IDENTITY.json';Pin-G1 $identityPath '3FD8164D1869375156FB7566D206FEAB97AE8A9E7D377B0AD4E03739ED697289'
$identity=Get-Content -LiteralPath $identityPath -Raw|ConvertFrom-Json;$thumb=([string]$identity.thumbprint).Replace(' ','').ToUpperInvariant();$cert=Get-Item -LiteralPath ("Cert:\CurrentUser\My\$thumb") -ErrorAction Stop;Assert-G1 ([bool]$cert.HasPrivateKey) 'R25G1 signer private key is absent.'
$stage='C:\R25G1';$partial=Join-Path $stage ($requestId+'.partial');$ready=Join-Path $stage ($requestId+'.ready');$final='C:\R25G1A';$zip=Join-Path $final ($requestId+'.ready.zip')
foreach($path in @($stage,$partial,$ready,$final,$zip)){Assert-G1 (-not(Test-Path -LiteralPath $path)) "R25G1 create-new path exists: $path"}
if($Preflight){[ordered]@{state='PASS_R25G1_BUILD_PREFLIGHT';requestId=$requestId;stageRoot=$stage;finalRoot=$final;entrypointSha256=Hash-G1 $entry;markerSha256=Hash-G1 $marker;allowedTaskActions=@('RESTART:ArgosProjectPortal.Gateway.ShareBridge.RO');requestRetryAuthorized=$false;mutationsPerformed=$false;reviewOnly=$true;productionRoutingEnabled=$false}|ConvertTo-Json -Depth 6;return}
[void](New-Item -ItemType Directory -Path (Join-Path $partial 'payload'));Copy-Item -LiteralPath $entry -Destination (Join-Path $partial 'payload\E.ps1') -ErrorAction Stop;Copy-Item -LiteralPath $marker -Destination (Join-Path $partial 'payload\M.json') -ErrorAction Stop
$records=@([ordered]@{path='payload/E.ps1';bytes=[int64](Get-Item -LiteralPath $entry).Length;sha256=Hash-G1 $entry},[ordered]@{path='payload/M.json';bytes=[int64](Get-Item -LiteralPath $marker).Length;sha256=Hash-G1 $marker})
$created=[DateTimeOffset]::UtcNow
$manifest=[ordered]@{schema='argos_project_portal_request_manifest_v1';requestId=$requestId;createdUtc=$created.ToString('o');expiresUtc=$created.AddHours(24).ToString('o');targetRole='GATEWAY';jobClass='MAINTENANCE_PATCH';handler='SIGNED_REVIEW_ONLY_PATCH_V1';maxResultBytes=1048576;reviewOnly=$true;trainingEligible=$false;xmlEligible=$false;productionEligible=$false;productionRoutingEnabled=$false;credentialsIncluded=$false;signerThumbprint=$thumb;signatureAlgorithm='RSA-SHA256-PKCS1';files=$records;entryPoint='payload/E.ps1';changes=@([ordered]@{source='payload/E.ps1';destination='C:\ProgramData\ArgosGatewayMaintenanceRO\managed\R25G1.ps1';approvedPredecessorSha256=@('2FBD3D885E89B40B780BF4756D3EAB51553852499A1FBDC4BD4C956AC6F937B2');installedSha256='2FBD3D885E89B40B780BF4756D3EAB51553852499A1FBDC4BD4C956AC6F937B2';allowCreate=$true},[ordered]@{source='payload/M.json';destination='C:\ProgramData\ArgosGatewayMaintenanceRO\managed\R25G1.marker.json';approvedPredecessorSha256=@('C283095BC100AF11DE378CFD8D963BAE67A9E022F88AD24B49893422CCD46453');installedSha256='C283095BC100AF11DE378CFD8D963BAE67A9E022F88AD24B49893422CCD46453';allowCreate=$true});allowedTaskActions=@('RESTART:ArgosProjectPortal.Gateway.ShareBridge.RO');rehearsal=[ordered]@{requiredState='PASS_R25G1_CURRENT_REQUEST_SHAREBRIDGE_RESTART_REHEARSAL'};requestRetryAuthorized=$false}
$utf8=New-Object Text.UTF8Encoding($false);$bytes=$utf8.GetBytes(($manifest|ConvertTo-Json -Depth 32));[IO.File]::WriteAllBytes((Join-Path $partial 'PORTAL_REQUEST_MANIFEST.json'),$bytes);$rsa=[Security.Cryptography.X509Certificates.RSACertificateExtensions]::GetRSAPrivateKey($cert);try{$sig=$rsa.SignData($bytes,[Security.Cryptography.HashAlgorithmName]::SHA256,[Security.Cryptography.RSASignaturePadding]::Pkcs1)}finally{$rsa.Dispose()};[IO.File]::WriteAllBytes((Join-Path $partial 'PORTAL_REQUEST_MANIFEST.sig'),$sig)
Move-Item -LiteralPath $partial -Destination $ready -ErrorAction Stop;[void](New-Item -ItemType Directory -Path $final);Add-Type -AssemblyName System.IO.Compression.FileSystem;[IO.Compression.ZipFile]::CreateFromDirectory($ready,$zip,[IO.Compression.CompressionLevel]::Optimal,$false)
[ordered]@{state='PASS_R25G1_FRESH_SIGNED_DIRECT_PACKAGE';requestId=$requestId;zipPath=$zip;zipBytes=[int64](Get-Item -LiteralPath $zip).Length;zipSha256=Hash-G1 $zip;manifestSha256=Hash-G1 (Join-Path $ready 'PORTAL_REQUEST_MANIFEST.json');signatureSha256=Hash-G1 (Join-Path $ready 'PORTAL_REQUEST_MANIFEST.sig');requestRetryAuthorized=$false;reviewOnly=$true;productionRoutingEnabled=$false}|ConvertTo-Json -Depth 6
