#Requires -Version 5.1
[CmdletBinding()]
param([switch]$Preflight, [switch]$Build)
Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'
function Assert-G3([bool]$Value,[string]$Message){if(-not$Value){throw $Message}}
function Hash-G3([string]$Path){(Get-FileHash -LiteralPath $Path -Algorithm SHA256 -ErrorAction Stop).Hash}
function Pin-G3([string]$Path,[string]$Hash){Assert-G3 (Test-Path -LiteralPath $Path -PathType Leaf) "Missing R21G3 dependency: $Path";Assert-G3 ((Hash-G3 $Path)-eq$Hash) "Changed R21G3 dependency: $Path"}
$count=0;if($Preflight){$count++};if($Build){$count++};Assert-G3 ($count-eq1) 'Select exactly one R21G3 action.'
$requestId='REQ_20260831T153300000Z_21A5E991C603'
$project=[IO.Path]::GetFullPath((Join-Path $PSScriptRoot '..\..'))
$entry=Join-Path $PSScriptRoot 'R21G2_E.ps1';$marker=Join-Path $PSScriptRoot 'R21G2_M.json'
Pin-G3 $entry '6078F956EC3DF67C9FAFC366913681F7AC1BEE63C6A32064ABF0A6354473A11B';Pin-G3 $marker '4C214E7D77D8F47C1FD7404BF221BE13C0C554D051F7D871E41E3BCB38BFEC93'
$identityPath=Join-Path $project 'work\PROJECT_PORTAL_REVIEW_ONLY\state\LAPTOP_SIGNING_IDENTITY.json';Pin-G3 $identityPath '3FD8164D1869375156FB7566D206FEAB97AE8A9E7D377B0AD4E03739ED697289'
$identity=Get-Content -LiteralPath $identityPath -Raw|ConvertFrom-Json;$thumb=([string]$identity.thumbprint).Replace(' ','').ToUpperInvariant();$cert=Get-Item -LiteralPath ("Cert:\CurrentUser\My\$thumb") -ErrorAction Stop;Assert-G3 ([bool]$cert.HasPrivateKey) 'R21G3 signer private key is absent.'
$stage='C:\R21G3';$partial=Join-Path $stage ($requestId+'.partial');$ready=Join-Path $stage ($requestId+'.ready');$final='C:\R21G3A';$zip=Join-Path $final ($requestId+'.ready.zip')
foreach($path in @($stage,$partial,$ready,$final,$zip)){Assert-G3 (-not(Test-Path -LiteralPath $path)) "R21G3 create-new path exists: $path"}
if($Preflight){[ordered]@{state='PASS_R21G3_BUILD_PREFLIGHT';requestId=$requestId;stageRoot=$stage;finalRoot=$final;entrypointSha256=Hash-G3 $entry;markerSha256=Hash-G3 $marker;allowedTaskActions=@('RESTART:ArgosProjectPortal.Gateway.ShareBridge.RO');mutationsPerformed=$false;reviewOnly=$true;productionRoutingEnabled=$false}|ConvertTo-Json -Depth 6;return}
[void](New-Item -ItemType Directory -Path (Join-Path $partial 'payload'));Copy-Item -LiteralPath $entry -Destination (Join-Path $partial 'payload\E.ps1') -ErrorAction Stop;Copy-Item -LiteralPath $marker -Destination (Join-Path $partial 'payload\M.json') -ErrorAction Stop
$records=@([ordered]@{path='payload/E.ps1';bytes=[int64](Get-Item -LiteralPath $entry).Length;sha256=Hash-G3 $entry},[ordered]@{path='payload/M.json';bytes=[int64](Get-Item -LiteralPath $marker).Length;sha256=Hash-G3 $marker})
$created=[DateTimeOffset]::UtcNow
$manifest=[ordered]@{schema='argos_project_portal_request_manifest_v1';requestId=$requestId;createdUtc=$created.ToString('o');expiresUtc=$created.AddHours(24).ToString('o');targetRole='GATEWAY';jobClass='MAINTENANCE_PATCH';handler='SIGNED_REVIEW_ONLY_PATCH_V1';maxResultBytes=1048576;reviewOnly=$true;trainingEligible=$false;xmlEligible=$false;productionEligible=$false;productionRoutingEnabled=$false;credentialsIncluded=$false;signerThumbprint=$thumb;signatureAlgorithm='RSA-SHA256-PKCS1';files=$records;entryPoint='payload/E.ps1';changes=@([ordered]@{source='payload/E.ps1';destination='C:\ProgramData\ArgosGatewayMaintenanceRO\managed\R21G3.ps1';approvedPredecessorSha256=@('6078F956EC3DF67C9FAFC366913681F7AC1BEE63C6A32064ABF0A6354473A11B');installedSha256='6078F956EC3DF67C9FAFC366913681F7AC1BEE63C6A32064ABF0A6354473A11B';allowCreate=$true},[ordered]@{source='payload/M.json';destination='C:\ProgramData\ArgosGatewayMaintenanceRO\managed\R21G3.marker.json';approvedPredecessorSha256=@('4C214E7D77D8F47C1FD7404BF221BE13C0C554D051F7D871E41E3BCB38BFEC93');installedSha256='4C214E7D77D8F47C1FD7404BF221BE13C0C554D051F7D871E41E3BCB38BFEC93';allowCreate=$true});allowedTaskActions=@('RESTART:ArgosProjectPortal.Gateway.ShareBridge.RO');rehearsal=[ordered]@{requiredState='PASS_R21G2_CURRENT_REQUEST_SHAREBRIDGE_RESTART_REHEARSAL'};requestRetryAuthorized=$false}
$utf8=New-Object Text.UTF8Encoding($false);$bytes=$utf8.GetBytes(($manifest|ConvertTo-Json -Depth 32));[IO.File]::WriteAllBytes((Join-Path $partial 'PORTAL_REQUEST_MANIFEST.json'),$bytes);$rsa=[Security.Cryptography.X509Certificates.RSACertificateExtensions]::GetRSAPrivateKey($cert);try{$sig=$rsa.SignData($bytes,[Security.Cryptography.HashAlgorithmName]::SHA256,[Security.Cryptography.RSASignaturePadding]::Pkcs1)}finally{$rsa.Dispose()};[IO.File]::WriteAllBytes((Join-Path $partial 'PORTAL_REQUEST_MANIFEST.sig'),$sig)
Move-Item -LiteralPath $partial -Destination $ready -ErrorAction Stop;[void](New-Item -ItemType Directory -Path $final);Add-Type -AssemblyName System.IO.Compression.FileSystem;[IO.Compression.ZipFile]::CreateFromDirectory($ready,$zip,[IO.Compression.CompressionLevel]::Optimal,$false)
[ordered]@{state='PASS_R21G3_FRESH_SIGNED_DIRECT_PACKAGE';requestId=$requestId;zipPath=$zip;zipBytes=[int64](Get-Item -LiteralPath $zip).Length;zipSha256=Hash-G3 $zip;manifestSha256=Hash-G3 (Join-Path $ready 'PORTAL_REQUEST_MANIFEST.json');signatureSha256=Hash-G3 (Join-Path $ready 'PORTAL_REQUEST_MANIFEST.sig');reviewOnly=$true;productionRoutingEnabled=$false}|ConvertTo-Json -Depth 6
