#Requires -Version 5.1
[CmdletBinding()]
param([switch]$Preflight,[switch]$Collect)
Set-StrictMode -Version Latest
$ErrorActionPreference='Stop'
if([bool]$Preflight-eq[bool]$Collect){throw 'Specify exactly one mode.'}
function Require([bool]$Condition,[string]$Message){if(-not$Condition){throw $Message}}
function Sha([string]$Path){(Get-FileHash -LiteralPath $Path -Algorithm SHA256 -ErrorAction Stop).Hash}
function Required([object]$Object,[string]$Name){$property=$Object.PSObject.Properties[$Name];if($null-eq$property){throw "Required property absent: $Name"};$property.Value}
$project=[IO.Path]::GetFullPath((Join-Path $PSScriptRoot '..\..'));$requestId='REQ_20260902T002021713Z_1A03204809E3';$responseId='R_CF5E264DE71A_20260902002709584_f7714032';$sourceZip='U:\ProjectPortalRO\responses\R_CF5E264DE71A_20260902002709584_f7714032.ready.zip';$zipBytes=2485;$zipHash='2FC41A63C9972680E258C7A8AFC55C057620B97A0240813040472930156928BF';$ready=Join-Path $PSScriptRoot 'r32c953l1_response';$partial=$ready+'.partial';$gate=Join-Path $PSScriptRoot 'R32C953L1_SIGNED_TERMINAL_LAUNCH_GATE.json';$verifier=Join-Path $project 'work\PROJECT_PORTAL_REVIEW_ONLY\scripts\Test-SignedPortalResponse.ps1';$certificate=Join-Path $project 'work\PROJECT_PORTAL_REVIEW_ONLY\enrollment\active\JBOD_ENDPOINT_SIGNER.cer'
foreach($path in @($sourceZip,$verifier,$certificate)){Require (Test-Path -LiteralPath $path -PathType Leaf) "R32C953L1 collection dependency absent: $path"};Require ((Get-Item -LiteralPath $sourceZip).Length-eq$zipBytes-and(Sha $sourceZip)-eq$zipHash) 'R32C953L1 response ZIP changed.'
Add-Type -AssemblyName System.IO.Compression.FileSystem;$archive=[IO.Compression.ZipFile]::OpenRead($sourceZip);try{$entry=$archive.GetEntry('PORTAL_RESPONSE_MANIFEST.json');Require ($null-ne$entry-and$entry.Length-le65536) 'R32C953L1 response manifest absent or too large.';$reader=New-Object IO.StreamReader($entry.Open(),[Text.Encoding]::UTF8,$true);try{$manifest=$reader.ReadToEnd()|ConvertFrom-Json}finally{$reader.Dispose()}}finally{$archive.Dispose()}
Require ([string](Required $manifest 'requestId')-eq$requestId-and[string](Required $manifest 'responseId')-eq$responseId-and[string](Required $manifest 'state')-eq'PASS_MAINTENANCE_PATCH'-and[string](Required $manifest 'sourceRole')-eq'JBOD'-and[bool](Required $manifest 'reviewOnly')-and-not[bool](Required $manifest 'productionRoutingEnabled')) 'R32C953L1 terminal manifest contract changed.'
$resumePartial=Test-Path -LiteralPath $partial -PathType Container;foreach($path in @($ready,$gate)){Require (-not(Test-Path -LiteralPath $path)) "R32C953L1 create-new target exists: $path"}
if($Preflight){[ordered]@{schema='argos_o3b21_r32c953l1_response_collection_preflight_v1';state='PASS_R32C953L1_RESPONSE_COLLECTION_PREFLIGHT';requestId=$requestId;responseId=$responseId;sourceZipBytes=$zipBytes;sourceZipSha256=$zipHash;exactPartialResume=$resumePartial;mutationsPerformed=$false;reviewOnly=$true;productionRoutingEnabled=$false}|ConvertTo-Json;return}
if(-not$resumePartial){[void](New-Item -ItemType Directory -Path $partial);[IO.Compression.ZipFile]::ExtractToDirectory($sourceZip,$partial)};& $verifier -PackagePath $partial -EndpointCertificatePath $certificate -ExpectedSourceRole JBOD -ExpectedRequestId $requestId|Out-Null
$stdoutPath=Join-Path $partial 'MAINTENANCE.stdout.txt';$stderrPath=Join-Path $partial 'MAINTENANCE.stderr.txt';$resultPath=Join-Path $partial 'RESULT.json';foreach($path in @($stdoutPath,$stderrPath,$resultPath)){Require (Test-Path -LiteralPath $path -PathType Leaf) "R32C953L1 response file absent: $path"};Require ((Get-Item -LiteralPath $stderrPath).Length-eq0-and(Get-Item -LiteralPath $stdoutPath).Length-le1048576) 'R32C953L1 maintenance output bounds changed.'
$lines=@(Get-Content -LiteralPath $stdoutPath);Require ($lines.Count-eq1) 'R32C953L1 stdout line count changed.';$execution=$lines[0]|ConvertFrom-Json;$maintenance=Get-Content -LiteralPath $resultPath -Raw|ConvertFrom-Json
Require ([string](Required $execution 'state')-eq'PASS_R32C953L1_FRESH_EXACT_953_BACKSIDE_CORPUS_LAUNCHED'-and[int](Required $execution 'expectedPairCount')-eq953-and[int](Required $execution 'currentInventoryPairCount')-eq978-and[int](Required $execution 'excludedPairCount')-eq25-and[int](Required $execution 'sourceProblemCount')-eq0) 'R32C953L1 signed launch cardinality contract changed.'
Require ([string](Required $execution 'selectionTestState')-eq'PASS_R32_FROZEN_953_SELECTION_7_OF_7'-and[int](Required $execution 'selectionTestCount')-eq7-and[int](Required $execution 'syntheticDetectorTestCount')-eq95-and[bool](Required $execution 'ownedProcessStarted')-and-not[bool](Required $execution 'existingTaskOrProcessActionPerformed')-and-not[bool](Required $execution 'sourceImagesMutated')-and-not[bool](Required $execution 'automaticRetryAuthorized')-and-not[bool](Required $execution 'holdsCleared')) 'R32C953L1 launch safety contract changed.'
Require ([int](Required $execution 'pid')-gt0-and-not[string]::IsNullOrWhiteSpace([string](Required $execution 'creationTimeUtc'))-and[string](Required $execution 'runtimeRoot')-eq'D:/R32C953RT'-and[string](Required $execution 'outputRoot')-eq'D:/R32C953') 'R32C953L1 owned worker evidence changed.'
Require ([string](Required $maintenance 'state')-eq'PASS_MAINTENANCE_PATCH'-and[int](Required $maintenance 'exitCode')-eq0-and[bool](Required $maintenance 'reviewOnly')-and-not[bool](Required $maintenance 'productionRoutingEnabled')) 'R32C953L1 maintenance result changed.'
Move-Item -LiteralPath $partial -Destination $ready;$value=[ordered]@{schema='argos_o3b21_r32c953l1_signed_terminal_launch_gate_v1';collectedUtc=[DateTime]::UtcNow.ToString('o');state='PASS_R32C953L1_SIGNED_EXACT_953_CORPUS_LAUNCHED';requestId=$requestId;responseId=$responseId;responseZipBytes=$zipBytes;responseZipSha256=$zipHash;responseManifestSha256=Sha (Join-Path $ready 'PORTAL_RESPONSE_MANIFEST.json');signedResponseVerified=$true;endpointState='PASS_MAINTENANCE_PATCH';executionState=[string]$execution.state;currentInventoryPairCount=[int]$execution.currentInventoryPairCount;excludedPairCount=[int]$execution.excludedPairCount;expectedPairCount=[int]$execution.expectedPairCount;sourceProblemCount=[int]$execution.sourceProblemCount;selectionTestState=[string]$execution.selectionTestState;selectionTestCount=[int]$execution.selectionTestCount;syntheticDetectorTestCount=[int]$execution.syntheticDetectorTestCount;workerPid=[int]$execution.pid;workerCreationTimeUtc=[string]$execution.creationTimeUtc;runtimeRoot=[string]$execution.runtimeRoot;outputRoot=[string]$execution.outputRoot;progressPath=[string]$execution.progressPath;sourceMutationPerformed=$false;sourceDeletionPerformed=$false;existingTaskOrProcessActionPerformed=$false;providerActivationPerformed=$false;holdsAutomaticallyCleared=$false;automaticRetryAuthorized=$false;reviewOnly=$true;trainingEligible=$false;xmlEligible=$false;productionEligible=$false;productionRoutingEnabled=$false};[IO.File]::WriteAllText($gate,(($value|ConvertTo-Json -Depth 10)+[Environment]::NewLine),(New-Object Text.UTF8Encoding($false)));$value|ConvertTo-Json -Depth 10
