#Requires -Version 5.1
[CmdletBinding()]
param([switch]$Preflight,[switch]$Collect)
Set-StrictMode -Version Latest
$ErrorActionPreference='Stop'
if([bool]$Preflight-eq[bool]$Collect){throw 'Specify exactly one mode.'}
function Require([bool]$Condition,[string]$Message){if(-not$Condition){throw $Message}}
function Sha([string]$Path){(Get-FileHash -LiteralPath $Path -Algorithm SHA256 -ErrorAction Stop).Hash}
function Required([object]$Object,[string]$Name){$property=$Object.PSObject.Properties[$Name];if($null-eq$property){throw "Required property absent: $Name"};$property.Value}
$project=[IO.Path]::GetFullPath((Join-Path $PSScriptRoot '..\..'));$requestId='REQ_20260902T000345586Z_B6D71E241DEC';$responseId='R_0406D7E11960_20260902001030856_e5789c66';$sourceZip='U:\ProjectPortalRO\responses\R_0406D7E11960_20260902001030856_e5789c66.ready.zip';$zipBytes=3163;$zipHash='BD667D4FC4604F82C883F383095EBCB8D50776CAF7FE6D9A66555AF8EC19A056';$ready=Join-Path $PSScriptRoot 'r32t1_response';$partial=$ready+'.partial';$gate=Join-Path $PSScriptRoot 'R32T1_SIGNED_TERMINAL_RESULT_GATE.json';$verifier=Join-Path $project 'work\PROJECT_PORTAL_REVIEW_ONLY\scripts\Test-SignedPortalResponse.ps1';$certificate=Join-Path $project 'work\PROJECT_PORTAL_REVIEW_ONLY\enrollment\active\JBOD_ENDPOINT_SIGNER.cer'
foreach($path in @($sourceZip,$verifier,$certificate)){Require (Test-Path -LiteralPath $path -PathType Leaf) "R32T1 collection dependency absent: $path"};Require ((Get-Item -LiteralPath $sourceZip).Length-eq$zipBytes-and(Sha $sourceZip)-eq$zipHash) 'R32T1 response ZIP changed.'
Add-Type -AssemblyName System.IO.Compression.FileSystem;$archive=[IO.Compression.ZipFile]::OpenRead($sourceZip);try{$entry=$archive.GetEntry('PORTAL_RESPONSE_MANIFEST.json');Require ($null-ne$entry-and$entry.Length-le65536) 'R32T1 response manifest absent or too large.';$reader=New-Object IO.StreamReader($entry.Open(),[Text.Encoding]::UTF8,$true);try{$manifest=$reader.ReadToEnd()|ConvertFrom-Json}finally{$reader.Dispose()}}finally{$archive.Dispose()}
Require ([string](Required $manifest 'requestId')-eq$requestId-and[string](Required $manifest 'responseId')-eq$responseId-and[string](Required $manifest 'state')-eq'PASS_MAINTENANCE_PATCH'-and[string](Required $manifest 'sourceRole')-eq'JBOD'-and[bool](Required $manifest 'reviewOnly')-and-not[bool](Required $manifest 'productionRoutingEnabled')) 'R32T1 terminal manifest contract changed.'
foreach($path in @($ready,$partial,$gate)){Require (-not(Test-Path -LiteralPath $path)) "R32T1 create-new target exists: $path"}
if($Preflight){[ordered]@{schema='argos_o3b21_r32t1_response_collection_preflight_v1';state='PASS_R32T1_RESPONSE_COLLECTION_PREFLIGHT';requestId=$requestId;responseId=$responseId;sourceZipBytes=$zipBytes;sourceZipSha256=$zipHash;mutationsPerformed=$false;reviewOnly=$true;productionRoutingEnabled=$false}|ConvertTo-Json;return}
[void](New-Item -ItemType Directory -Path $partial);[IO.Compression.ZipFile]::ExtractToDirectory($sourceZip,$partial);& $verifier -PackagePath $partial -EndpointCertificatePath $certificate -ExpectedSourceRole JBOD -ExpectedRequestId $requestId|Out-Null
$stdoutPath=Join-Path $partial 'MAINTENANCE.stdout.txt';$stderrPath=Join-Path $partial 'MAINTENANCE.stderr.txt';$resultPath=Join-Path $partial 'RESULT.json';foreach($path in @($stdoutPath,$stderrPath,$resultPath)){Require (Test-Path -LiteralPath $path -PathType Leaf) "R32T1 response file absent: $path"};Require ((Get-Item -LiteralPath $stderrPath).Length-eq0-and(Get-Item -LiteralPath $stdoutPath).Length-le16777216) 'R32T1 maintenance output bounds changed.'
$lines=@(Get-Content -LiteralPath $stdoutPath);Require ($lines.Count-eq2) 'R32T1 stdout line count changed.';$execution=$lines[0]|ConvertFrom-Json;Require ([string]$lines[1]-eq'PASS_O3B21_R32T1_ONE_EXECUTION_COMPLETE') 'R32T1 terminal token changed.';$maintenance=Get-Content -LiteralPath $resultPath -Raw|ConvertFrom-Json;$summary=Required $execution 'summary'
Require ([string](Required $execution 'state')-eq'PASS_O3B21_R32T1_ONE_EXECUTION_COMPLETE'-and[string](Required $execution 'detectorGateState')-eq'PASS_R32T1_RESIDUE_ALIGNMENT'-and[int](Required $execution 'caseCount')-eq1-and[int](Required $execution 'syntheticTestCount')-eq95) 'R32T1 signed execution contract changed.'
Require ([string](Required $summary 'state')-eq'PASS_R32T1_RESIDUE_ALIGNMENT'-and[int](Required $summary 'pairedCandidateCount')-eq1-and[double](Required $summary 'angleDifferenceDegrees')-le1.5-and[string](Required (Required $summary 'multiPairExteriorCleanResolution') 'state')-eq'PASS_UNIQUE_BOTH_CHANNELS_EXTERIOR_CLEAR_PAIR'-and-not[bool](Required $summary 'sourceMutationPerformed')) 'R32T1 detector outcome did not pass.'
Require ([string](Required $maintenance 'state')-eq'PASS_MAINTENANCE_PATCH'-and[int](Required $maintenance 'exitCode')-eq0-and[bool](Required $maintenance 'reviewOnly')-and-not[bool](Required $maintenance 'productionRoutingEnabled')) 'R32T1 maintenance result changed.'
Move-Item -LiteralPath $partial -Destination $ready;$value=[ordered]@{schema='argos_o3b21_r32t1_signed_terminal_result_gate_v1';collectedUtc=[DateTime]::UtcNow.ToString('o');state='PASS_R32T1_SIGNED_RESIDUE_ALIGNMENT';requestId=$requestId;responseId=$responseId;responseZipBytes=$zipBytes;responseZipSha256=$zipHash;responseManifestSha256=Sha (Join-Path $ready 'PORTAL_RESPONSE_MANIFEST.json');signedResponseVerified=$true;endpointState='PASS_MAINTENANCE_PATCH';executionState=[string]$execution.state;detectorState=[string]$summary.state;resolvedMeanAngleDegrees=[double]$summary.resolvedMeanAngleDegrees;frozenC15Run4NotchAngleDegrees=[double]$summary.frozenC15Run4NotchAngleDegrees;angleDifferenceDegrees=[double]$summary.angleDifferenceDegrees;pairedCandidateCount=[int]$summary.pairedCandidateCount;multiPairResolutionState=[string]$summary.multiPairExteriorCleanResolution.state;summarySha256=[string]$execution.summarySha256;sourceMutationPerformed=$false;sourceDeletionPerformed=$false;existingTaskOrProcessActionPerformed=$false;providerActivationPerformed=$false;holdsAutomaticallyCleared=$false;automaticRetryAuthorized=$false;reviewOnly=$true;trainingEligible=$false;xmlEligible=$false;productionEligible=$false;productionRoutingEnabled=$false};[IO.File]::WriteAllText($gate,(($value|ConvertTo-Json -Depth 10)+[Environment]::NewLine),(New-Object Text.UTF8Encoding($false)));$value|ConvertTo-Json -Depth 10
