#Requires -Version 5.1
[CmdletBinding()]
param([switch]$Preflight,[switch]$PackageLeafPreflight)
Set-StrictMode -Version Latest
$ErrorActionPreference='Stop'
function Require([bool]$Condition,[string]$Message){if(-not$Condition){throw $Message}}
function Sha([string]$Path){(Get-FileHash -LiteralPath $Path -Algorithm SHA256 -ErrorAction Stop).Hash}
$python='D:\AFCV1\rt\python.exe';$pythonHash='7D96A4ED35D6E596CD9DD8933FEAFC66349CC21F75BE3B15C89FD336E50140C1';$contract=Join-Path $PSScriptRoot 'R31VAL2_CONTRACT.json';$contractHash='D1D551068DE648D905A767A33566DEB8CFC90369894BF89FB774ED0BBA38F45D';$runner=Join-Path $PSScriptRoot 'Run-R31ValidationBatch.py';$runnerHash='24D1BF4B04182C9EC38DF141F0F31B0046E09D7873CA18359C4B76072069EC54';$detector=Join-Path $PSScriptRoot 'Detect-BacksideNotchOpenCvR31.py';$detectorHash='34476F0109CE68FB6365A7C650CC6FFF2B874B64A38EAA0DA09542261427BCA7';$config=Join-Path $PSScriptRoot 'BACKSIDE_NOTCH_CONFIG_R13.json';$configHash='27010B75F2E5CCB601E710A63D73F5483072F6EB797F9D72A0632F993E6E4AD3';$frozen=Join-Path $PSScriptRoot 'R18_REGRESSION_CASES.json';$frozenHash='7F2BF805CC35893B307557680251A94A49F28305E20E3735931F064E82650DF4';$output='D:\R31VAL2'
$tests=@(@((Join-Path $PSScriptRoot 'Test-BacksideNotchOpenCvR28.py'),'0BF3E7DE98D586833FA392D686ADFA4CB341F73672B6C7113728604E2AD4901F','PASS_R28_PACKAGED_SYNTHETIC_33_OF_33'),@((Join-Path $PSScriptRoot 'Test-BacksideNotchOpenCvR29.py'),'C62054EFC2C2F573D48C452196D28B18B6BC5C0045DCA45CD2ABA1269FD1E1E7','PASS_R29_PACKAGED_SYNTHETIC_13_OF_13'),@((Join-Path $PSScriptRoot 'Test-BacksideNotchOpenCvR30.py'),'E22233AEA4FA9757448B6BE27119E557C16D05CFEE05E67BD4941BFD29EBEA8B','PASS_R30_PACKAGED_SYNTHETIC_13_OF_13'),@((Join-Path $PSScriptRoot 'Test-BacksideNotchOpenCvR31.py'),'AB66EA7229238195BABF48AB11BB21922FDF2F807EEB52B5C9B8C828B0272A9D','PASS_R31_PACKAGED_SYNTHETIC_21_OF_21'))
foreach($pin in @(@($contract,$contractHash),@($runner,$runnerHash),@($detector,$detectorHash),@($config,$configHash),@($frozen,$frozenHash))+$tests){Require (Test-Path -LiteralPath $pin[0] -PathType Leaf) "Package dependency absent: $($pin[0])";Require ((Sha $pin[0])-eq$pin[1]) "Package dependency changed: $($pin[0])"}
if($PackageLeafPreflight){[ordered]@{schema='argos_o3b21_r31val2_package_leaf_preflight_v1';state='PASS_R31VAL2_EXACT_PACKAGED_LEAVES';exactCaseCount=298;maximumConcurrentChildren=4;syntheticTestCount=80;imageDecoded=$false;processStarted=$false;mutationsPerformed=$false}|ConvertTo-Json -Compress;return}
Require ($env:COMPUTERNAME-eq'A1025645101') 'R31VAL2 reached the wrong computer.';Require (Test-Path -LiteralPath $python -PathType Leaf) 'Pinned Python runtime absent.';Require ((Sha $python)-eq$pythonHash) 'Pinned Python runtime changed.';Require (-not(Test-Path -LiteralPath $output)) 'Create-new R31VAL2 output exists.'
if($Preflight){[ordered]@{schema='argos_o3b21_r31val2_target_preflight_v1';state='PASS_R31VAL2_TARGET_PREFLIGHT';outputRoot=$output;exactCaseCount=298;maximumConcurrentChildren=4;maximumTotalSeconds=1200;imageDecoded=$false;sourceHashingPerformed=$false;processStarted=$false;mutationsPerformed=$false;reviewOnly=$true}|ConvertTo-Json -Compress;return}
foreach($test in $tests){$start=New-Object Diagnostics.ProcessStartInfo;$start.FileName=$python;$start.Arguments=('-B "{0}"'-f$test[0]);$start.WorkingDirectory=$PSScriptRoot;$start.UseShellExecute=$false;$start.CreateNoWindow=$true;$start.RedirectStandardOutput=$true;$start.RedirectStandardError=$true;$process=New-Object Diagnostics.Process;$process.StartInfo=$start;Require $process.Start() 'R31VAL2 synthetic test did not start.';$stdout=$process.StandardOutput.ReadToEndAsync();$stderr=$process.StandardError.ReadToEndAsync();Require ($process.WaitForExit(120000)) 'R31VAL2 synthetic test timed out.';Require ($process.ExitCode-eq0) ('R31VAL2 synthetic test failed: '+$stderr.Result);Require ($stdout.Result.Trim()-eq$test[2]) 'R31VAL2 synthetic test state changed.';$process.Dispose()}
$arguments=('-B "{0}" --contract "{1}" --frozen-cases "{2}" --detector "{3}" --config "{4}" --python "{5}" --output "{6}" --maximum-dimension 2400 --maximum-per-case-seconds 180'-f$runner,$contract,$frozen,$detector,$config,$python,$output);$start=New-Object Diagnostics.ProcessStartInfo;$start.FileName=$python;$start.Arguments=$arguments;$start.WorkingDirectory=$PSScriptRoot;$start.UseShellExecute=$false;$start.CreateNoWindow=$true;$start.RedirectStandardOutput=$true;$start.RedirectStandardError=$true;$process=New-Object Diagnostics.Process;$process.StartInfo=$start;$timer=[Diagnostics.Stopwatch]::StartNew();Require $process.Start() 'R31VAL2 validation runner did not start.';$stdout=$process.StandardOutput.ReadToEndAsync();$stderr=$process.StandardError.ReadToEndAsync();if(-not$process.WaitForExit(1200000)){try{$process.Kill()}catch{};throw 'R31VAL2 validation runner timed out.'};$timer.Stop();Require ($process.ExitCode-eq0) ('R31VAL2 validation runner failed: '+$stderr.Result)
$summaryPath=Join-Path $output 'SUMMARY.json';Require (Test-Path -LiteralPath $summaryPath -PathType Leaf) 'R31VAL2 summary absent.';$summary=Get-Content -LiteralPath $summaryPath -Raw|ConvertFrom-Json;Require ([int]$summary.caseCount-eq298) 'R31VAL2 result cardinality changed.';Require ([int]$summary.currentRecipeCount-eq265) 'R31VAL2 current recipe cardinality changed.';Require ([string]$summary.state-in@('PASS_R31VAL1_ALL_EXPECTED_OUTCOMES','HOLD_R31VAL1_OUTCOME_MISMATCH')) 'R31VAL2 result state invalid.';Require (-not[bool]$summary.sourceMutationPerformed) 'R31VAL2 source mutation reported.'
[ordered]@{schema='argos_o3b21_r31val2_signed_execution_v1';state='PASS_O3B21_R31VAL2_EXACT_298_EXECUTIONS_COMPLETE';detectorGateState=[string]$summary.state;outputRoot=$output;elapsedSeconds=[Math]::Round($timer.Elapsed.TotalSeconds,3);caseCount=298;frozenCaseCount=32;sameScanControlCount=1;currentPatternedFrontCount=[int]$summary.currentPatternedFrontCount;currentUnpatternedFrontCount=[int]$summary.currentUnpatternedFrontCount;currentRecipeCount=265;syntheticTestCount=80;summary=$summary;summarySha256=Sha $summaryPath;sourceMutationPerformed=$false;sourceDeletionPerformed=$false;existingTaskOrProcessActionPerformed=$false;providerActivationPerformed=$false;holdsAutomaticallyCleared=$false;reviewOnly=$true;trainingEligible=$false;xmlEligible=$false;productionEligible=$false}|ConvertTo-Json -Depth 64 -Compress
'PASS_O3B21_R31VAL2_EXACT_298_EXECUTIONS_COMPLETE'
