#Requires -Version 5.1
[CmdletBinding(DefaultParameterSetName='Preflight')]
param([Parameter(ParameterSetName='Preflight')][switch]$Preflight,[Parameter(Mandatory=$true,ParameterSetName='Publish')][switch]$Publish)
Set-StrictMode -Version Latest
$ErrorActionPreference='Stop'
$requestId='REQ_20260901T221440855Z_AA1D598B751C';$source='C:\R30VAL1PK\REQ_20260901T221440855Z_AA1D598B751C.ready.zip';$sourceHash='7A69ED41EF1CCD7F0B0E63EE3609B630B09979696E93B450EF2B98B85CEC726F'
$pathGate=Join-Path $PSScriptRoot 'R30VAL1_PREPUBLICATION_PATH_GATE.json';$pathGateHash='53BF99D9722FFB05B41D92ECAAE10ED9518754F3976E066E44224F3BC756A86B';$rehearsalGate=Join-Path $PSScriptRoot 'R30VAL1_FINAL_ZIP_REHEARSAL_GATE.json';$rehearsalGateHash='A0BC376DD44B4F2ACD9FE126B7397759174DEF85CCDFDB009878DB61689AFC58'
$expected='\\shm-cifs\Department\DE-1302_FAB_BE_Engineering\60_Saw_VI_Sort\600_General\Joshua.conn\AVI_Images\Argos\Uploads\InspectionRevs';$requests='U:\ProjectPortalRO\requests';$target=Join-Path $requests ($requestId+'.ready.zip');$upload=$target+'.upload';$gate=Join-Path $PSScriptRoot 'R30VAL1_PUBLISH_GATE.json'
function Sha([string]$Path){(Get-FileHash -LiteralPath $Path -Algorithm SHA256 -ErrorAction Stop).Hash}
function New-Json([string]$Path,[object]$Value){if(Test-Path -LiteralPath $Path){throw "Create-new path exists: $Path"};[IO.File]::WriteAllText($Path,(($Value|ConvertTo-Json -Depth 20)+[Environment]::NewLine),(New-Object Text.UTF8Encoding($false)))}
foreach($pin in @(@($source,$sourceHash),@($pathGate,$pathGateHash),@($rehearsalGate,$rehearsalGateHash))){if(-not(Test-Path -LiteralPath $pin[0] -PathType Leaf)-or(Sha $pin[0])-ne$pin[1]){throw "R30VAL1 publication dependency absent or changed: $($pin[0])"}}
$pathValue=Get-Content -LiteralPath $pathGate -Raw|ConvertFrom-Json;$rehearsalValue=Get-Content -LiteralPath $rehearsalGate -Raw|ConvertFrom-Json;if([string]$pathValue.state-ne'PASS_R30VAL1_SIGNED_AND_PATH_GATED'-or[string]$pathValue.requestId-ne$requestId-or[string]$rehearsalValue.state-ne'PASS_R30VAL1_FINAL_ZIP_WINDOWS_PS51_REHEARSAL'-or[string]$rehearsalValue.requestId-ne$requestId){throw 'R30VAL1 path or rehearsal gate changed.'}
$ps=Get-PSDrive U -ErrorAction Stop;$disk=Get-CimInstance Win32_LogicalDisk -Filter "DeviceID='U:'" -ErrorAction Stop;if([string]$ps.DisplayRoot-ne$expected-or[string]$disk.ProviderName-ne$expected-or[int]$disk.DriveType-ne4){throw 'Qualified U mapping changed.'};if(-not(Test-Path -LiteralPath $requests -PathType Container)){throw 'Portal request root unavailable.'};$pending=@(Get-ChildItem -LiteralPath $requests -File -Filter '*.ready.zip' -ErrorAction Stop);if($pending.Count-ne0){throw 'Portal request root contains unresolved pending request.'};if((Test-Path -LiteralPath $target)-or(Test-Path -LiteralPath $upload)-or(Test-Path -LiteralPath $gate)){throw 'R30VAL1 create-new publication path exists.'}
$project=[IO.Path]::GetFullPath((Join-Path $PSScriptRoot '..\..'));$head=[string](& git -C $project rev-parse HEAD);$origin=[string](& git -C $project rev-parse refs/remotes/origin/codex/fiducial-opencv-d-drive);if($LASTEXITCODE-ne0-or$head-ne$origin){throw 'R30VAL1 local/origin branch tips do not match.'}
if($Preflight){[ordered]@{schema='argos_o3b21_r30val1_publish_preflight_v1';state='PASS_R30VAL1_PUBLISH_PREFLIGHT';requestId=$requestId;sourceSha256=$sourceHash;pendingRequestCount=0;branchTip=$head;caseCount=70;syntheticTestCount=59;targetExecuted=$false;mutationsPerformed=$false}|ConvertTo-Json;return}
[IO.File]::Copy($source,$upload,$false);if((Sha $upload)-ne$sourceHash){throw 'R30VAL1 upload hash changed.'};[IO.File]::Move($upload,$target);if((Sha $target)-ne$sourceHash){throw 'R30VAL1 published hash changed.'}
$value=[ordered]@{schema='argos_o3b21_r30val1_publish_gate_v1';createdUtc=[DateTime]::UtcNow.ToString('o');state='PASS_R30VAL1_PUBLISHED_EXACTLY_ONCE_AWAITING_SIGNED_RESPONSE';requestId=$requestId;publishedPath=$target;publishedSha256=$sourceHash;publishedBytes=(Get-Item -LiteralPath $target).Length;manifestSha256='1FCA6131EB7901D21A1B9743A80C2ADAF3010C4986B618D7607E3049FD5866D4';signatureSha256='E1DFFB6246609C1301BB5B362C952214EB509D4D386FF07D7BBF90377B2B23F0';publishAttemptCount=1;automaticRetryAuthorized=$false;matchingSignedTerminalResponseRequired=$true;caseCount=70;syntheticTestCount=59;reviewOnly=$true;productionRoutingEnabled=$false};New-Json $gate $value;$value|ConvertTo-Json -Depth 10
