#Requires -Version 5.1
[CmdletBinding(DefaultParameterSetName='Preflight')]
param([Parameter(ParameterSetName='Preflight')][switch]$Preflight,[Parameter(Mandatory=$true,ParameterSetName='Publish')][switch]$Publish)
Set-StrictMode -Version Latest
$ErrorActionPreference='Stop'
$requestId='REQ_20260901T215551125Z_E3A895430234';$source='C:\R29VAL1PK\REQ_20260901T215551125Z_E3A895430234.ready.zip';$sourceHash='F9803B8F4EF9747CB3EF6D14B07C0DC52AF22FAEA915E3A0DB39B1280E40B285'
$pathGate=Join-Path $PSScriptRoot 'R29VAL1_PREPUBLICATION_PATH_GATE.json';$pathGateHash='8AC4B3388553075B9B186C9A41AA1E2BD491BDB8D613B8E95FB33E3ED7220BF0';$rehearsalGate=Join-Path $PSScriptRoot 'R29VAL1_FINAL_ZIP_REHEARSAL_GATE.json';$rehearsalGateHash='13CA62C56842DB946D1387D6A49DCDA20DB410AD18B3B3F380ECADD7E371306C'
$expected='\\shm-cifs\Department\DE-1302_FAB_BE_Engineering\60_Saw_VI_Sort\600_General\Joshua.conn\AVI_Images\Argos\Uploads\InspectionRevs';$requests='U:\ProjectPortalRO\requests';$target=Join-Path $requests ($requestId+'.ready.zip');$upload=$target+'.upload';$gate=Join-Path $PSScriptRoot 'R29VAL1_PUBLISH_GATE.json'
function Sha([string]$Path){(Get-FileHash -LiteralPath $Path -Algorithm SHA256 -ErrorAction Stop).Hash}
function New-Json([string]$Path,[object]$Value){if(Test-Path -LiteralPath $Path){throw "Create-new path exists: $Path"};[IO.File]::WriteAllText($Path,(($Value|ConvertTo-Json -Depth 20)+[Environment]::NewLine),(New-Object Text.UTF8Encoding($false)))}
foreach($pin in @(@($source,$sourceHash),@($pathGate,$pathGateHash),@($rehearsalGate,$rehearsalGateHash))){if(-not(Test-Path -LiteralPath $pin[0] -PathType Leaf)-or(Sha $pin[0])-ne$pin[1]){throw "R29VAL1 publication dependency absent or changed: $($pin[0])"}}
$pathValue=Get-Content -LiteralPath $pathGate -Raw|ConvertFrom-Json;$rehearsalValue=Get-Content -LiteralPath $rehearsalGate -Raw|ConvertFrom-Json;if([string]$pathValue.state-ne'PASS_R29VAL1_SIGNED_AND_PATH_GATED'-or[string]$pathValue.requestId-ne$requestId-or[string]$rehearsalValue.state-ne'PASS_R29VAL1_FINAL_ZIP_WINDOWS_PS51_REHEARSAL'-or[string]$rehearsalValue.requestId-ne$requestId){throw 'R29VAL1 path or rehearsal gate changed.'}
$ps=Get-PSDrive U -ErrorAction Stop;$disk=Get-CimInstance Win32_LogicalDisk -Filter "DeviceID='U:'" -ErrorAction Stop;if([string]$ps.DisplayRoot-ne$expected-or[string]$disk.ProviderName-ne$expected-or[int]$disk.DriveType-ne4){throw 'Qualified U mapping changed.'};if(-not(Test-Path -LiteralPath $requests -PathType Container)){throw 'Portal request root unavailable.'};$pending=@(Get-ChildItem -LiteralPath $requests -File -Filter '*.ready.zip' -ErrorAction Stop);if($pending.Count-ne0){throw 'Portal request root contains unresolved pending request.'};if((Test-Path -LiteralPath $target)-or(Test-Path -LiteralPath $upload)-or(Test-Path -LiteralPath $gate)){throw 'R29VAL1 create-new publication path exists.'}
$project=[IO.Path]::GetFullPath((Join-Path $PSScriptRoot '..\..'));$head=[string](& git -C $project rev-parse HEAD);$origin=[string](& git -C $project rev-parse refs/remotes/origin/codex/fiducial-opencv-d-drive);if($LASTEXITCODE-ne0-or$head-ne$origin){throw 'R29VAL1 local/origin branch tips do not match.'}
if($Preflight){[ordered]@{schema='argos_o3b21_r29val1_publish_preflight_v1';state='PASS_R29VAL1_PUBLISH_PREFLIGHT';requestId=$requestId;sourceSha256=$sourceHash;pendingRequestCount=0;branchTip=$head;caseCount=39;syntheticTestCount=46;targetExecuted=$false;mutationsPerformed=$false}|ConvertTo-Json;return}
[IO.File]::Copy($source,$upload,$false);if((Sha $upload)-ne$sourceHash){throw 'R29VAL1 upload hash changed.'};[IO.File]::Move($upload,$target);if((Sha $target)-ne$sourceHash){throw 'R29VAL1 published hash changed.'}
$value=[ordered]@{schema='argos_o3b21_r29val1_publish_gate_v1';createdUtc=[DateTime]::UtcNow.ToString('o');state='PASS_R29VAL1_PUBLISHED_EXACTLY_ONCE_AWAITING_SIGNED_RESPONSE';requestId=$requestId;publishedPath=$target;publishedSha256=$sourceHash;publishedBytes=(Get-Item -LiteralPath $target).Length;manifestSha256='1501A2C140A036CDDC6916AB54112DCD3746B9F6C2773768EBA1A1A11618C52D';signatureSha256='B8F3D7969D2A9771DD8B82372B8E4E3516446C19C45DC0A6126549B655AC1D41';publishAttemptCount=1;automaticRetryAuthorized=$false;matchingSignedTerminalResponseRequired=$true;caseCount=39;syntheticTestCount=46;reviewOnly=$true;productionRoutingEnabled=$false};New-Json $gate $value;$value|ConvertTo-Json -Depth 10
