#Requires -Version 5.1
[CmdletBinding(DefaultParameterSetName='Preflight')]
param([Parameter(ParameterSetName='Preflight')][switch]$Preflight,[Parameter(Mandatory=$true,ParameterSetName='Publish')][switch]$Publish)
Set-StrictMode -Version Latest
$ErrorActionPreference='Stop'
$requestId='REQ_20260901T225534688Z_673F2FFD0E09';$source='C:\R31VAL2PK\REQ_20260901T225534688Z_673F2FFD0E09.ready.zip';$sourceHash='E107AB251E2CD4230247F69DCCC7BD0AFB1B1819AA3C1C36BB8646E30895D56B';$pathGate=Join-Path $PSScriptRoot 'R31VAL2_PREPUBLICATION_PATH_GATE.json';$pathGateHash='7A70FB923530EF4C392A79FAEC8F0531BA29306F9B4FBD4D4E286172AB2A0FD4';$rehearsalGate=Join-Path $PSScriptRoot 'R31VAL2_FINAL_ZIP_REHEARSAL_GATE.json';$rehearsalGateHash='8304A3C48302D5CBEE2A068977978B12F568F66D9ADDB8D4CF84440315971B12';$expected='\\shm-cifs\Department\DE-1302_FAB_BE_Engineering\60_Saw_VI_Sort\600_General\Joshua.conn\AVI_Images\Argos\Uploads\InspectionRevs';$requests='U:\ProjectPortalRO\requests';$target=Join-Path $requests ($requestId+'.ready.zip');$upload=$target+'.upload';$gate=Join-Path $PSScriptRoot 'R31VAL2_PUBLISH_GATE.json'
function Sha([string]$Path){(Get-FileHash -LiteralPath $Path -Algorithm SHA256 -ErrorAction Stop).Hash}
function New-Json([string]$Path,[object]$Value){if(Test-Path -LiteralPath $Path){throw "Create-new path exists: $Path"};[IO.File]::WriteAllText($Path,(($Value|ConvertTo-Json -Depth 20)+[Environment]::NewLine),(New-Object Text.UTF8Encoding($false)))}
foreach($pin in @(@($source,$sourceHash),@($pathGate,$pathGateHash),@($rehearsalGate,$rehearsalGateHash))){if(-not(Test-Path -LiteralPath $pin[0] -PathType Leaf)-or(Sha $pin[0])-ne$pin[1]){throw "R31VAL2 publication dependency absent or changed: $($pin[0])"}};$pathValue=Get-Content -LiteralPath $pathGate -Raw|ConvertFrom-Json;$rehearsalValue=Get-Content -LiteralPath $rehearsalGate -Raw|ConvertFrom-Json;if([string]$pathValue.state-ne'PASS_R31VAL2_SIGNED_AND_PATH_GATED'-or[string]$pathValue.requestId-ne$requestId-or[string]$rehearsalValue.state-ne'PASS_R31VAL2_FINAL_ZIP_WINDOWS_PS51_REHEARSAL'-or[string]$rehearsalValue.requestId-ne$requestId){throw 'R31VAL2 path or rehearsal gate changed.'}
$ps=Get-PSDrive U -ErrorAction Stop;$disk=Get-CimInstance Win32_LogicalDisk -Filter "DeviceID='U:'" -ErrorAction Stop;if([string]$ps.DisplayRoot-ne$expected-or[string]$disk.ProviderName-ne$expected-or[int]$disk.DriveType-ne4){throw 'Qualified U mapping changed.'};if(-not(Test-Path -LiteralPath $requests -PathType Container)){throw 'Portal request root unavailable.'};$pending=@(Get-ChildItem -LiteralPath $requests -File -Filter '*.ready.zip' -ErrorAction Stop);if($pending.Count-ne0){throw 'Portal request root contains unresolved pending request.'};if((Test-Path -LiteralPath $target)-or(Test-Path -LiteralPath $upload)-or(Test-Path -LiteralPath $gate)){throw 'R31VAL2 create-new publication path exists.'};$project=[IO.Path]::GetFullPath((Join-Path $PSScriptRoot '..\..'));$head=[string](& git -C $project rev-parse HEAD);$origin=[string](& git -C $project rev-parse refs/remotes/origin/codex/fiducial-opencv-d-drive);if($LASTEXITCODE-ne0-or$head-ne$origin){throw 'R31VAL2 local/origin branch tips do not match.'}
if($Preflight){[ordered]@{schema='argos_o3b21_r31val2_publish_preflight_v1';state='PASS_R31VAL2_PUBLISH_PREFLIGHT';requestId=$requestId;sourceSha256=$sourceHash;pendingRequestCount=0;branchTip=$head;exactCaseCount=298;currentRecipeCount=265;maximumConcurrentChildren=4;syntheticTestCount=80;targetExecuted=$false;mutationsPerformed=$false}|ConvertTo-Json;return};[IO.File]::Copy($source,$upload,$false);if((Sha $upload)-ne$sourceHash){throw 'R31VAL2 upload hash changed.'};[IO.File]::Move($upload,$target);if((Sha $target)-ne$sourceHash){throw 'R31VAL2 published hash changed.'};$value=[ordered]@{schema='argos_o3b21_r31val2_publish_gate_v1';createdUtc=[DateTime]::UtcNow.ToString('o');state='PASS_R31VAL2_PUBLISHED_EXACTLY_ONCE_AWAITING_SIGNED_RESPONSE';requestId=$requestId;publishedPath=$target;publishedSha256=$sourceHash;publishedBytes=(Get-Item -LiteralPath $target).Length;manifestSha256='B7C7EA8D7D7B74EDB28C86C529EE7DCE9B7599E72B12D8DBC46C25433D4A0204';signatureSha256='79CECF7BB74CA7E74350DAC34D4E1559D474B216CB04C50FD34F17FD6A665978';publishAttemptCount=1;automaticRetryAuthorized=$false;matchingSignedTerminalResponseRequired=$true;exactCaseCount=298;currentRecipeCount=265;maximumConcurrentChildren=4;syntheticTestCount=80;reviewOnly=$true;productionRoutingEnabled=$false};New-Json $gate $value;$value|ConvertTo-Json -Depth 10
