#Requires -Version 5.1
[CmdletBinding(DefaultParameterSetName='Preflight')]
param([Parameter(ParameterSetName='Preflight')][switch]$Preflight,[Parameter(Mandatory=$true,ParameterSetName='Publish')][switch]$Publish)
Set-StrictMode -Version Latest
$ErrorActionPreference='Stop'
$requestId='REQ_20260901T223823959Z_6B75D3448116';$source='C:\R31VAL1PK\REQ_20260901T223823959Z_6B75D3448116.ready.zip';$sourceHash='EAB38DB1B50C95B4A025E04D8C0F8FA7D0886D43372EE48A380DE169BBD8C198';$pathGate=Join-Path $PSScriptRoot 'R31VAL1_PREPUBLICATION_PATH_GATE.json';$pathGateHash='B51D7A05F46DE7BCF36981F495A3111601DBDECBB3F500009E3FBA6493BEB5F2';$rehearsalGate=Join-Path $PSScriptRoot 'R31VAL1_FINAL_ZIP_REHEARSAL_GATE.json';$rehearsalGateHash='40DDE88C8518D80F38098C3A52081F71ED72850799CC158237C56EBC801400D0'
$expected='\\shm-cifs\Department\DE-1302_FAB_BE_Engineering\60_Saw_VI_Sort\600_General\Joshua.conn\AVI_Images\Argos\Uploads\InspectionRevs';$requests='U:\ProjectPortalRO\requests';$target=Join-Path $requests ($requestId+'.ready.zip');$upload=$target+'.upload';$gate=Join-Path $PSScriptRoot 'R31VAL1_PUBLISH_GATE.json'
function Sha([string]$Path){(Get-FileHash -LiteralPath $Path -Algorithm SHA256 -ErrorAction Stop).Hash}
function New-Json([string]$Path,[object]$Value){if(Test-Path -LiteralPath $Path){throw "Create-new path exists: $Path"};[IO.File]::WriteAllText($Path,(($Value|ConvertTo-Json -Depth 20)+[Environment]::NewLine),(New-Object Text.UTF8Encoding($false)))}
foreach($pin in @(@($source,$sourceHash),@($pathGate,$pathGateHash),@($rehearsalGate,$rehearsalGateHash))){if(-not(Test-Path -LiteralPath $pin[0] -PathType Leaf)-or(Sha $pin[0])-ne$pin[1]){throw "R31VAL1 publication dependency absent or changed: $($pin[0])"}};$pathValue=Get-Content -LiteralPath $pathGate -Raw|ConvertFrom-Json;$rehearsalValue=Get-Content -LiteralPath $rehearsalGate -Raw|ConvertFrom-Json;if([string]$pathValue.state-ne'PASS_R31VAL1_SIGNED_AND_PATH_GATED'-or[string]$pathValue.requestId-ne$requestId-or[string]$rehearsalValue.state-ne'PASS_R31VAL1_FINAL_ZIP_WINDOWS_PS51_REHEARSAL'-or[string]$rehearsalValue.requestId-ne$requestId){throw 'R31VAL1 path or rehearsal gate changed.'}
$ps=Get-PSDrive U -ErrorAction Stop;$disk=Get-CimInstance Win32_LogicalDisk -Filter "DeviceID='U:'" -ErrorAction Stop;if([string]$ps.DisplayRoot-ne$expected-or[string]$disk.ProviderName-ne$expected-or[int]$disk.DriveType-ne4){throw 'Qualified U mapping changed.'};if(-not(Test-Path -LiteralPath $requests -PathType Container)){throw 'Portal request root unavailable.'};$pending=@(Get-ChildItem -LiteralPath $requests -File -Filter '*.ready.zip' -ErrorAction Stop);if($pending.Count-ne0){throw 'Portal request root contains unresolved pending request.'};if((Test-Path -LiteralPath $target)-or(Test-Path -LiteralPath $upload)-or(Test-Path -LiteralPath $gate)){throw 'R31VAL1 create-new publication path exists.'}
$project=[IO.Path]::GetFullPath((Join-Path $PSScriptRoot '..\..'));$head=[string](& git -C $project rev-parse HEAD);$origin=[string](& git -C $project rev-parse refs/remotes/origin/codex/fiducial-opencv-d-drive);if($LASTEXITCODE-ne0-or$head-ne$origin){throw 'R31VAL1 local/origin branch tips do not match.'}
if($Preflight){[ordered]@{schema='argos_o3b21_r31val1_publish_preflight_v1';state='PASS_R31VAL1_PUBLISH_PREFLIGHT';requestId=$requestId;sourceSha256=$sourceHash;pendingRequestCount=0;branchTip=$head;maximumCaseCount=120;syntheticTestCount=80;targetExecuted=$false;mutationsPerformed=$false}|ConvertTo-Json;return}
[IO.File]::Copy($source,$upload,$false);if((Sha $upload)-ne$sourceHash){throw 'R31VAL1 upload hash changed.'};[IO.File]::Move($upload,$target);if((Sha $target)-ne$sourceHash){throw 'R31VAL1 published hash changed.'};$value=[ordered]@{schema='argos_o3b21_r31val1_publish_gate_v1';createdUtc=[DateTime]::UtcNow.ToString('o');state='PASS_R31VAL1_PUBLISHED_EXACTLY_ONCE_AWAITING_SIGNED_RESPONSE';requestId=$requestId;publishedPath=$target;publishedSha256=$sourceHash;publishedBytes=(Get-Item -LiteralPath $target).Length;manifestSha256='A2248F813E1775B59A2D2BB09C4446B0A29903EEF0A797E76E26C365E1F83D3B';signatureSha256='2603F45054624AB9C82AB0578B6F0993D8964CC533BC0BAFF3421D9B838AE593';publishAttemptCount=1;automaticRetryAuthorized=$false;matchingSignedTerminalResponseRequired=$true;maximumCaseCount=120;syntheticTestCount=80;reviewOnly=$true;productionRoutingEnabled=$false};New-Json $gate $value;$value|ConvertTo-Json -Depth 10
