#Requires -Version 5.1
[CmdletBinding(DefaultParameterSetName='Preflight')]
param([Parameter(ParameterSetName='Preflight')][switch]$Preflight,[Parameter(Mandatory=$true,ParameterSetName='Publish')][switch]$Publish)
Set-StrictMode -Version Latest
$ErrorActionPreference='Stop'
$requestId='REQ_20260902T000345586Z_B6D71E241DEC';$source='C:\R32T1PK\REQ_20260902T000345586Z_B6D71E241DEC.ready.zip';$sourceHash='139083AD1E7893BE4E84C191B7A1F05D084C6F0CBD45672132D4FF91A35E0F9E';$pathGate=Join-Path $PSScriptRoot 'R32T1_PREPUBLICATION_PATH_GATE.json';$pathGateHash='88BD44D6787CE77F3D0DD343C4AEE3F4E0747ABB05674D228F0B6FF4F2D68CAD';$rehearsalGate=Join-Path $PSScriptRoot 'R32T1_FINAL_ZIP_REHEARSAL_GATE.json';$rehearsalGateHash='D9B1ED98E23031FAF6B947B9DB6942C9033631F3E755D594BCD877E6508F3A0F';$expected='\\shm-cifs\Department\DE-1302_FAB_BE_Engineering\60_Saw_VI_Sort\600_General\Joshua.conn\AVI_Images\Argos\Uploads\InspectionRevs';$requests='U:\ProjectPortalRO\requests';$target=Join-Path $requests ($requestId+'.ready.zip');$upload=$target+'.upload';$gate=Join-Path $PSScriptRoot 'R32T1_PUBLISH_GATE.json'
function Sha([string]$Path){(Get-FileHash -LiteralPath $Path -Algorithm SHA256 -ErrorAction Stop).Hash}
function New-Json([string]$Path,[object]$Value){if(Test-Path -LiteralPath $Path){throw "Create-new path exists: $Path"};[IO.File]::WriteAllText($Path,(($Value|ConvertTo-Json -Depth 20)+[Environment]::NewLine),(New-Object Text.UTF8Encoding($false)))}
foreach($pin in @(@($source,$sourceHash),@($pathGate,$pathGateHash),@($rehearsalGate,$rehearsalGateHash))){if(-not(Test-Path -LiteralPath $pin[0] -PathType Leaf)-or(Sha $pin[0])-ne$pin[1]){throw "R32T1 publication dependency absent or changed: $($pin[0])"}};$pathValue=Get-Content -LiteralPath $pathGate -Raw|ConvertFrom-Json;$rehearsalValue=Get-Content -LiteralPath $rehearsalGate -Raw|ConvertFrom-Json;if([string]$pathValue.state-ne'PASS_R32T1_SIGNED_AND_PATH_GATED'-or[string]$pathValue.requestId-ne$requestId-or[string]$rehearsalValue.state-ne'PASS_R32T1_FINAL_ZIP_WINDOWS_PS51_REHEARSAL'-or[string]$rehearsalValue.requestId-ne$requestId){throw 'R32T1 path or rehearsal gate changed.'}
$ps=Get-PSDrive U -ErrorAction Stop;$disk=Get-CimInstance Win32_LogicalDisk -Filter "DeviceID='U:'" -ErrorAction Stop;if([string]$ps.DisplayRoot-ne$expected-or[string]$disk.ProviderName-ne$expected-or[int]$disk.DriveType-ne4){throw 'Qualified U mapping changed.'};if(-not(Test-Path -LiteralPath $requests -PathType Container)){throw 'Portal request root unavailable.'};$pending=@(Get-ChildItem -LiteralPath $requests -File -Filter '*.ready.zip' -ErrorAction Stop);if($pending.Count-ne0){throw 'Portal request root contains unresolved pending request.'};if((Test-Path -LiteralPath $target)-or(Test-Path -LiteralPath $upload)-or(Test-Path -LiteralPath $gate)){throw 'R32T1 create-new publication path exists.'};$project=[IO.Path]::GetFullPath((Join-Path $PSScriptRoot '..\..'));$head=[string](& git -C $project rev-parse HEAD);$origin=[string](& git -C $project rev-parse refs/remotes/origin/codex/fiducial-opencv-d-drive);if($LASTEXITCODE-ne0-or$head-ne$origin){throw 'R32T1 local/origin branch tips do not match.'}
if($Preflight){[ordered]@{schema='argos_o3b21_r32t1_publish_preflight_v1';state='PASS_R32T1_PUBLISH_PREFLIGHT';requestId=$requestId;sourceSha256=$sourceHash;pendingRequestCount=0;branchTip=$head;exactCaseCount=1;syntheticTestCount=95;targetExecuted=$false;mutationsPerformed=$false}|ConvertTo-Json;return};[IO.File]::Copy($source,$upload,$false);if((Sha $upload)-ne$sourceHash){throw 'R32T1 upload hash changed.'};[IO.File]::Move($upload,$target);if((Sha $target)-ne$sourceHash){throw 'R32T1 published hash changed.'};$value=[ordered]@{schema='argos_o3b21_r32t1_publish_gate_v1';createdUtc=[DateTime]::UtcNow.ToString('o');state='PASS_R32T1_PUBLISHED_EXACTLY_ONCE_AWAITING_SIGNED_RESPONSE';requestId=$requestId;publishedPath=$target;publishedSha256=$sourceHash;publishedBytes=(Get-Item -LiteralPath $target).Length;manifestSha256='1F6140283D8FDCB402BFBBD16112A34CA88BF0C52E3A4BB539CF64C587D60ACA';signatureSha256='C41042F9501F497AE16C48455EFBD1BB6A87CF88081C85C3449839DAA6410690';publishAttemptCount=1;automaticRetryAuthorized=$false;matchingSignedTerminalResponseRequired=$true;exactCaseCount=1;syntheticTestCount=95;reviewOnly=$true;productionRoutingEnabled=$false};New-Json $gate $value;$value|ConvertTo-Json -Depth 10
