#Requires -Version 5.1
[CmdletBinding(DefaultParameterSetName='Preflight')]
param([Parameter(ParameterSetName='Preflight')][switch]$Preflight,[Parameter(Mandatory=$true,ParameterSetName='Publish')][switch]$Publish)
Set-StrictMode -Version Latest
$ErrorActionPreference='Stop'
$requestId='REQ_20260901T190628171Z_A42442F0631A';$source='C:\R27B32R3PK\REQ_20260901T190628171Z_A42442F0631A.ready.zip';$sourceSha256='6A737B8F5C49786C4F2E268E23873022F1C570B82D9045B9EBD7EB2FFB124A44'
$pathGate=Join-Path $PSScriptRoot 'R27B32R3_PREPUBLICATION_PATH_GATE.json';$pathGateSha256='DBA623B18ADA89B1EDADEADFB3B53DEE726E10F7BDBB53063F6D01EE8C2F9514';$rehearsalGate=Join-Path $PSScriptRoot 'R27B32R3_FINAL_ZIP_REHEARSAL_GATE.json';$rehearsalGateSha256='8C9E63ED4151C8479B1592259335F7B2246027F459EBCA552BABE1EE2D0A0876'
$expectedUnc='\\shm-cifs\Department\DE-1302_FAB_BE_Engineering\60_Saw_VI_Sort\600_General\Joshua.conn\AVI_Images\Argos\Uploads\InspectionRevs';$requestsRoot='U:\ProjectPortalRO\requests';$target=Join-Path $requestsRoot ($requestId+'.ready.zip');$upload=$target+'.upload';$gatePath=Join-Path $PSScriptRoot 'R27B32R3_PUBLISH_GATE.json'
function Sha([string]$Path){(Get-FileHash -LiteralPath $Path -Algorithm SHA256 -ErrorAction Stop).Hash}
function Write-NewJson([string]$Path,[object]$Value){if(Test-Path -LiteralPath $Path){throw "Create-new path exists: $Path"};[IO.File]::WriteAllText($Path,(($Value|ConvertTo-Json -Depth 8)+[Environment]::NewLine),(New-Object Text.UTF8Encoding($false)))}
if(-not(Test-Path -LiteralPath $source -PathType Leaf)-or(Sha $source)-ne$sourceSha256){throw 'R27B32R3 frozen source ZIP absent or changed.'};if(-not(Test-Path -LiteralPath $pathGate -PathType Leaf)-or(Sha $pathGate)-ne$pathGateSha256){throw 'R27B32R3 path gate absent or changed.'};if(-not(Test-Path -LiteralPath $rehearsalGate -PathType Leaf)-or(Sha $rehearsalGate)-ne$rehearsalGateSha256){throw 'R27B32R3 rehearsal gate absent or changed.'}
$pathGateValue=Get-Content -LiteralPath $pathGate -Raw|ConvertFrom-Json;$rehearsalGateValue=Get-Content -LiteralPath $rehearsalGate -Raw|ConvertFrom-Json;if([string]$pathGateValue.state-ne'PASS_R27B32R3_SIGNED_AND_PATH_GATED'-or[string]$pathGateValue.requestId-ne$requestId-or[string]$rehearsalGateValue.state-ne'PASS_R27B32R3_FINAL_ZIP_WINDOWS_PS51_REHEARSAL'-or[string]$rehearsalGateValue.requestId-ne$requestId){throw 'R27B32R3 path/rehearsal gate state or identity changed.'}
$drive=Get-PSDrive -Name U -ErrorAction Stop;$logicalDisk=Get-CimInstance Win32_LogicalDisk -Filter "DeviceID='U:'" -ErrorAction Stop;if([string]$drive.DisplayRoot-ne$expectedUnc-or[string]$logicalDisk.ProviderName-ne$expectedUnc-or[int]$logicalDisk.DriveType-ne 4){throw 'Persistent U: mapping changed.'}
if(-not(Test-Path -LiteralPath $requestsRoot -PathType Container)){throw 'Portal request root unavailable.'};$pending=@(Get-ChildItem -LiteralPath $requestsRoot -File -Filter '*.ready.zip' -ErrorAction Stop);if($pending.Count-ne 0){throw 'Portal request root contains unresolved pending request.'};if((Test-Path -LiteralPath $target)-or(Test-Path -LiteralPath $upload)){throw 'R27B32R3 publication leaf already exists.'};if(Test-Path -LiteralPath $gatePath){throw 'R27B32R3 publication gate already exists.'}
$project=Join-Path $PSScriptRoot '..\..';$head=[string](& git -C $project rev-parse HEAD);$origin=[string](& git -C $project rev-parse refs/remotes/origin/codex/fiducial-opencv-d-drive);if($LASTEXITCODE-ne 0-or$head-ne$origin){throw 'R27B32R3 local/origin branch tips do not match.'}
if($Preflight){[ordered]@{schema='argos_o3b21_r26o23_publish_preflight_v1';state='PASS_R27B32R3_PUBLISH_PREFLIGHT';requestId=$requestId;sourceSha256=$sourceSha256;pathGateSha256=$pathGateSha256;rehearsalGateSha256=$rehearsalGateSha256;pendingRequestCount=0;branchTip=$head;selectedOrdinals=@(0..31);completedR25CaseRerunCount=0;targetExecuted=$false;mutationsPerformed=$false}|ConvertTo-Json -Depth 5;return}
[IO.File]::Copy($source,$upload,$false);if((Sha $upload)-ne$sourceSha256){throw 'R27B32R3 upload hash changed.'};[IO.File]::Move($upload,$target);if((Sha $target)-ne$sourceSha256){throw 'R27B32R3 published hash changed.'}
$gate=[ordered]@{schema='argos_o3b21_r26o23_publish_gate_v1';createdUtc=[DateTime]::UtcNow.ToString('o');state='PASS_R27B32R3_PUBLISHED_EXACTLY_ONCE_AWAITING_SIGNED_TERMINAL_RESPONSE';requestId=$requestId;publishedArchivePath='work/PROJECT_PORTAL_REVIEW_ONLY/state/published_requests/'+$requestId+'.ready.zip';publishedArchiveSha256=$sourceSha256;publishedArchiveBytes=(Get-Item -LiteralPath $target).Length;signedManifestSha256='9ECC5B35824EE8D977A4666EA6352E99FC80908D76D5892F9988564EDEB65BB5';signedSignatureSha256='0CFB2A72B5648CCA232BB8054F5BD55CFF79594B677DC5C18459F7DCB7AC0E87';archiveEntryCount=18;signedPayloadFileCount=16;exactSignedManifestAndSignaturePreserved=$true;selectedOrdinals=@(0..31);completedCaseRerunCount=32;publishAttemptCount=1;automaticRetryAuthorized=$false;matchingSignedTerminalResponseRequired=$true;reviewOnly=$true;productionRoutingEnabled=$false};Write-NewJson $gatePath $gate;$gate|ConvertTo-Json -Depth 8
