#Requires -Version 5.1
[CmdletBinding(DefaultParameterSetName='Preflight')]
param([Parameter(ParameterSetName='Preflight')][switch]$Preflight,[Parameter(Mandatory=$true,ParameterSetName='Publish')][switch]$Publish)
Set-StrictMode -Version Latest
$ErrorActionPreference='Stop'
$requestId='REQ_20260901T173550248Z_264B5F546DD5';$source='C:\R25NA2PK\REQ_20260901T173550248Z_264B5F546DD5.ready.zip';$sourceSha256='99D91E4A8E39A7240C1E116FCC666A316002583A3A9272F2501BE5F1397A71FD'
$pathGate=Join-Path $PSScriptRoot 'R25NA2_PREPUBLICATION_PATH_GATE.json';$pathGateSha256='5345E6C1DC0459FF44823492D0CABCD72B2C8551BC91B2E680D2F7ACEEFCF7B1'
$expectedUnc='\\shm-cifs\Department\DE-1302_FAB_BE_Engineering\60_Saw_VI_Sort\600_General\Joshua.conn\AVI_Images\Argos\Uploads\InspectionRevs';$requestsRoot='U:\ProjectPortalRO\requests';$target=Join-Path $requestsRoot ($requestId+'.ready.zip');$upload=$target+'.upload';$gatePath=Join-Path $PSScriptRoot 'R25NA2_PUBLISH_GATE.json'
function Sha([string]$Path){(Get-FileHash -LiteralPath $Path -Algorithm SHA256 -ErrorAction Stop).Hash}
function Write-NewJson([string]$Path,[object]$Value){if(Test-Path -LiteralPath $Path){throw "Create-new path exists: $Path"};[IO.File]::WriteAllText($Path,(($Value|ConvertTo-Json -Depth 8)+[Environment]::NewLine),(New-Object Text.UTF8Encoding($false)))}
if(-not(Test-Path -LiteralPath $source -PathType Leaf)-or(Sha $source)-ne$sourceSha256){throw 'R25NA2 frozen source ZIP absent or changed.'};if(-not(Test-Path -LiteralPath $pathGate -PathType Leaf)-or(Sha $pathGate)-ne$pathGateSha256){throw 'R25NA2 path gate absent or changed.'}
$pathGateValue=Get-Content -LiteralPath $pathGate -Raw|ConvertFrom-Json;if([string]$pathGateValue.state-ne'PASS_R25NA2_SIGNED_AND_PATH_GATED'-or[string]$pathGateValue.requestId-ne$requestId){throw 'R25NA2 path gate state or identity changed.'}
$drive=Get-PSDrive -Name U -ErrorAction Stop;$logicalDisk=Get-CimInstance Win32_LogicalDisk -Filter "DeviceID='U:'" -ErrorAction Stop;if([string]$drive.DisplayRoot-ne$expectedUnc-or[string]$logicalDisk.ProviderName-ne$expectedUnc-or[int]$logicalDisk.DriveType-ne 4){throw 'Persistent U: mapping changed.'}
if(-not(Test-Path -LiteralPath $requestsRoot -PathType Container)){throw 'Portal request root unavailable.'};$pending=@(Get-ChildItem -LiteralPath $requestsRoot -File -Filter '*.ready.zip' -ErrorAction Stop);if($pending.Count-ne 0){throw 'Portal request root contains unresolved pending request.'};if((Test-Path -LiteralPath $target)-or(Test-Path -LiteralPath $upload)){throw 'R25NA2 publication leaf already exists.'};if(Test-Path -LiteralPath $gatePath){throw 'R25NA2 publication gate already exists.'}
$project=Join-Path $PSScriptRoot '..\..';$head=[string](& git -C $project rev-parse HEAD);$origin=[string](& git -C $project rev-parse refs/remotes/origin/codex/fiducial-opencv-d-drive);if($LASTEXITCODE-ne 0-or$head-ne$origin){throw 'R25NA2 local/origin branch tips do not match.'}
if($Preflight){[ordered]@{schema='argos_o3b21_r25na2_publish_preflight_v1';state='PASS_R25NA2_PUBLISH_PREFLIGHT';requestId=$requestId;sourceSha256=$sourceSha256;pathGateSha256=$pathGateSha256;pendingRequestCount=0;branchTip=$head;frozenCandidateCount=24;reusedOrdinalCount=17;missingOrdinalCount=7;completedR25CaseRerunCount=0;targetExecuted=$false;mutationsPerformed=$false}|ConvertTo-Json -Depth 5;return}
[IO.File]::Copy($source,$upload,$false);if((Sha $upload)-ne$sourceSha256){throw 'R25NA2 upload hash changed.'};[IO.File]::Move($upload,$target);if((Sha $target)-ne$sourceSha256){throw 'R25NA2 published hash changed.'}
$gate=[ordered]@{schema='argos_o3b21_r25na2_publish_gate_v1';createdUtc=[DateTime]::UtcNow.ToString('o');state='PASS_R25NA2_PUBLISHED_EXACTLY_ONCE_AWAITING_SIGNED_TERMINAL_RESPONSE';requestId=$requestId;publishedArchivePath='work/PROJECT_PORTAL_REVIEW_ONLY/state/published_requests/'+$requestId+'.ready.zip';publishedArchiveSha256=$sourceSha256;publishedArchiveBytes=(Get-Item -LiteralPath $target).Length;signedManifestSha256='5BB417C9170B16D448731A5E94D0B80924A15A19310B3CC350F4A53D2F67A35E';signedSignatureSha256='5D865DFFFFCA1A6216EFE1FBB7FE224E0F666F73514FC52629266E0A5F6B5AF2';archiveEntryCount=18;signedPayloadFileCount=16;exactSignedManifestAndSignaturePreserved=$true;reusedOrdinalCount=17;missingOrdinalCount=7;publishAttemptCount=1;automaticRetryAuthorized=$false;matchingSignedTerminalResponseRequired=$true;reviewOnly=$true;productionRoutingEnabled=$false};Write-NewJson $gatePath $gate;$gate|ConvertTo-Json -Depth 8
