#Requires -Version 5.1
[CmdletBinding(DefaultParameterSetName='Preflight')]
param([Parameter(ParameterSetName='Preflight')][switch]$Preflight,[Parameter(Mandatory=$true,ParameterSetName='Publish')][switch]$Publish)
Set-StrictMode -Version Latest
$ErrorActionPreference='Stop'
$requestId='REQ_20260901T194419032Z_A3B2CFCED96F';$source='C:\R27M12PK\REQ_20260901T194419032Z_A3B2CFCED96F.ready.zip';$sourceSha256='7EA60D41E9B7B00A50436ECC9D1D31445DC3476DEB570F29C71C323AFF37651F'
$pathGate=Join-Path $PSScriptRoot 'R27M12_PREPUBLICATION_PATH_GATE.json';$pathGateSha256='DC13E32C209F7710EC72E23446A69CB4F58501D1F63353BC168ACBABD29287CA';$rehearsalGate=Join-Path $PSScriptRoot 'R27M12_FINAL_ZIP_REHEARSAL_GATE.json';$rehearsalGateSha256='8C9140639FD5AF14197DE27628DF9F75E61F20FFA4C0AAA70650E33F92D788FD'
$expectedUnc='\\shm-cifs\Department\DE-1302_FAB_BE_Engineering\60_Saw_VI_Sort\600_General\Joshua.conn\AVI_Images\Argos\Uploads\InspectionRevs';$requestsRoot='U:\ProjectPortalRO\requests';$target=Join-Path $requestsRoot ($requestId+'.ready.zip');$upload=$target+'.upload';$gatePath=Join-Path $PSScriptRoot 'R27M12_PUBLISH_GATE.json'
function Sha([string]$Path){(Get-FileHash -LiteralPath $Path -Algorithm SHA256 -ErrorAction Stop).Hash}
function Write-NewJson([string]$Path,[object]$Value){if(Test-Path -LiteralPath $Path){throw "Create-new path exists: $Path"};[IO.File]::WriteAllText($Path,(($Value|ConvertTo-Json -Depth 8)+[Environment]::NewLine),(New-Object Text.UTF8Encoding($false)))}
if(-not(Test-Path -LiteralPath $source -PathType Leaf)-or(Sha $source)-ne$sourceSha256){throw 'R27M12 frozen source ZIP absent or changed.'};if(-not(Test-Path -LiteralPath $pathGate -PathType Leaf)-or(Sha $pathGate)-ne$pathGateSha256){throw 'R27M12 path gate absent or changed.'};if(-not(Test-Path -LiteralPath $rehearsalGate -PathType Leaf)-or(Sha $rehearsalGate)-ne$rehearsalGateSha256){throw 'R27M12 rehearsal gate absent or changed.'}
$pathGateValue=Get-Content -LiteralPath $pathGate -Raw|ConvertFrom-Json;$rehearsalGateValue=Get-Content -LiteralPath $rehearsalGate -Raw|ConvertFrom-Json;if([string]$pathGateValue.state-ne'PASS_R27M12_SIGNED_AND_PATH_GATED'-or[string]$pathGateValue.requestId-ne$requestId-or[string]$rehearsalGateValue.state-ne'PASS_R27M12_FINAL_ZIP_WINDOWS_PS51_REHEARSAL'-or[string]$rehearsalGateValue.requestId-ne$requestId){throw 'R27M12 path/rehearsal gate state or identity changed.'}
$drive=Get-PSDrive -Name U -ErrorAction Stop;$logicalDisk=Get-CimInstance Win32_LogicalDisk -Filter "DeviceID='U:'" -ErrorAction Stop;if([string]$drive.DisplayRoot-ne$expectedUnc-or[string]$logicalDisk.ProviderName-ne$expectedUnc-or[int]$logicalDisk.DriveType-ne 4){throw 'Persistent U: mapping changed.'}
if(-not(Test-Path -LiteralPath $requestsRoot -PathType Container)){throw 'Portal request root unavailable.'};$pending=@(Get-ChildItem -LiteralPath $requestsRoot -File -Filter '*.ready.zip' -ErrorAction Stop);if($pending.Count-ne 0){throw 'Portal request root contains unresolved pending request.'};if((Test-Path -LiteralPath $target)-or(Test-Path -LiteralPath $upload)){throw 'R27M12 publication leaf already exists.'};if(Test-Path -LiteralPath $gatePath){throw 'R27M12 publication gate already exists.'}
$project=Join-Path $PSScriptRoot '..\..';$head=[string](& git -C $project rev-parse HEAD);$origin=[string](& git -C $project rev-parse refs/remotes/origin/codex/fiducial-opencv-d-drive);if($LASTEXITCODE-ne 0-or$head-ne$origin){throw 'R27M12 local/origin branch tips do not match.'}
if($Preflight){[ordered]@{schema='argos_o3b21_r27m12_publish_preflight_v1';state='PASS_R27M12_PUBLISH_PREFLIGHT';requestId=$requestId;sourceSha256=$sourceSha256;pathGateSha256=$pathGateSha256;rehearsalGateSha256=$rehearsalGateSha256;pendingRequestCount=0;branchTip=$head;selectedOrdinals=@(20..31);completedCaseRerunCount=0;targetExecuted=$false;mutationsPerformed=$false}|ConvertTo-Json -Depth 5;return}
[IO.File]::Copy($source,$upload,$false);if((Sha $upload)-ne$sourceSha256){throw 'R27M12 upload hash changed.'};[IO.File]::Move($upload,$target);if((Sha $target)-ne$sourceSha256){throw 'R27M12 published hash changed.'}
$gate=[ordered]@{schema='argos_o3b21_r27m12_publish_gate_v1';createdUtc=[DateTime]::UtcNow.ToString('o');state='PASS_R27M12_PUBLISHED_EXACTLY_ONCE_AWAITING_SIGNED_TERMINAL_RESPONSE';requestId=$requestId;publishedArchivePath='work/PROJECT_PORTAL_REVIEW_ONLY/state/published_requests/'+$requestId+'.ready.zip';publishedArchiveSha256=$sourceSha256;publishedArchiveBytes=(Get-Item -LiteralPath $target).Length;signedManifestSha256='701DF15B61F499D454EA6D09F5D7447301E3565BF3ED00A2E9C85C44F45153E2';signedSignatureSha256='CA12CE21862A0D54A5168AFB5995D504A95AB144EBBDC7F65F3CFA4909E7C912';archiveEntryCount=18;signedPayloadFileCount=16;exactSignedManifestAndSignaturePreserved=$true;selectedOrdinals=@(20..31);completedCaseRerunCount=0;publishAttemptCount=1;automaticRetryAuthorized=$false;matchingSignedTerminalResponseRequired=$true;reviewOnly=$true;productionRoutingEnabled=$false};Write-NewJson $gatePath $gate;$gate|ConvertTo-Json -Depth 8
