#Requires -Version 5.1
[CmdletBinding(DefaultParameterSetName='Preflight')]
param([Parameter(ParameterSetName='Preflight')][switch]$Preflight,[Parameter(Mandatory=$true,ParameterSetName='Publish')][switch]$Publish)
Set-StrictMode -Version Latest
$ErrorActionPreference='Stop'
$requestId='REQ_20260901T204837729Z_FE997FDF83C6';$source='C:\R28C953L1PK\REQ_20260901T204837729Z_FE997FDF83C6.ready.zip';$sourceSha256='1CAA7AC2C02CB7D2F73AC2B65E385B423C88713789121E70588A835BE3E8C8EC'
$pathGate=Join-Path $PSScriptRoot 'R28C953L1_PREPUBLICATION_PATH_GATE.json';$pathGateSha256='F51C0325FB203E16BB3D63045A986E12E13693CC7DE88B806D19ACAF78DE035C';$rehearsalGate=Join-Path $PSScriptRoot 'R28C953L1_FINAL_ZIP_REHEARSAL_GATE.json';$rehearsalGateSha256='653778209EB488648000364C902DEEC8EAFB9DE33BF06FA292504D813FFDCE46'
$expectedUnc='\\shm-cifs\Department\DE-1302_FAB_BE_Engineering\60_Saw_VI_Sort\600_General\Joshua.conn\AVI_Images\Argos\Uploads\InspectionRevs';$requestsRoot='U:\ProjectPortalRO\requests';$target=Join-Path $requestsRoot ($requestId+'.ready.zip');$upload=$target+'.upload';$gatePath=Join-Path $PSScriptRoot 'R28C953L1_PUBLISH_GATE.json'
function Sha([string]$Path){(Get-FileHash -LiteralPath $Path -Algorithm SHA256 -ErrorAction Stop).Hash}
function Write-NewJson([string]$Path,[object]$Value){if(Test-Path -LiteralPath $Path){throw "Create-new path exists: $Path"};[IO.File]::WriteAllText($Path,(($Value|ConvertTo-Json -Depth 8)+[Environment]::NewLine),(New-Object Text.UTF8Encoding($false)))}
if(-not(Test-Path -LiteralPath $source -PathType Leaf)-or(Sha $source)-ne$sourceSha256){throw 'R28C953L1 frozen source ZIP absent or changed.'};if(-not(Test-Path -LiteralPath $pathGate -PathType Leaf)-or(Sha $pathGate)-ne$pathGateSha256){throw 'R28C953L1 path gate absent or changed.'};if(-not(Test-Path -LiteralPath $rehearsalGate -PathType Leaf)-or(Sha $rehearsalGate)-ne$rehearsalGateSha256){throw 'R28C953L1 rehearsal gate absent or changed.'}
$pathGateValue=Get-Content -LiteralPath $pathGate -Raw|ConvertFrom-Json;$rehearsalGateValue=Get-Content -LiteralPath $rehearsalGate -Raw|ConvertFrom-Json;if([string]$pathGateValue.state-ne'PASS_R28C953L1_SIGNED_AND_PATH_GATED'-or[string]$pathGateValue.requestId-ne$requestId-or[string]$rehearsalGateValue.state-ne'PASS_R28C953L1_FINAL_ZIP_WINDOWS_PS51_REHEARSAL'-or[string]$rehearsalGateValue.requestId-ne$requestId){throw 'R28C953L1 path/rehearsal gate state or identity changed.'}
$drive=Get-PSDrive -Name U -ErrorAction Stop;$logicalDisk=Get-CimInstance Win32_LogicalDisk -Filter "DeviceID='U:'" -ErrorAction Stop;if([string]$drive.DisplayRoot-ne$expectedUnc-or[string]$logicalDisk.ProviderName-ne$expectedUnc-or[int]$logicalDisk.DriveType-ne 4){throw 'Persistent U: mapping changed.'}
if(-not(Test-Path -LiteralPath $requestsRoot -PathType Container)){throw 'Portal request root unavailable.'};$pending=@(Get-ChildItem -LiteralPath $requestsRoot -File -Filter '*.ready.zip' -ErrorAction Stop);if($pending.Count-ne 0){throw 'Portal request root contains unresolved pending request.'};if((Test-Path -LiteralPath $target)-or(Test-Path -LiteralPath $upload)){throw 'R28C953L1 publication leaf already exists.'};if(Test-Path -LiteralPath $gatePath){throw 'R28C953L1 publication gate already exists.'}
$project=Join-Path $PSScriptRoot '..\..';$head=[string](& git -C $project rev-parse HEAD);$origin=[string](& git -C $project rev-parse refs/remotes/origin/codex/fiducial-opencv-d-drive);if($LASTEXITCODE-ne 0-or$head-ne$origin){throw 'R28C953L1 local/origin branch tips do not match.'}
if($Preflight){[ordered]@{schema='argos_o3b21_r28c953l1_publish_preflight_v1';state='PASS_R28C953L1_PUBLISH_PREFLIGHT';requestId=$requestId;sourceSha256=$sourceSha256;pathGateSha256=$pathGateSha256;rehearsalGateSha256=$rehearsalGateSha256;pendingRequestCount=0;branchTip=$head;expectedPairCount=953;syntheticTestCount=33;targetExecuted=$false;mutationsPerformed=$false}|ConvertTo-Json -Depth 5;return}
[IO.File]::Copy($source,$upload,$false);if((Sha $upload)-ne$sourceSha256){throw 'R28C953L1 upload hash changed.'};[IO.File]::Move($upload,$target);if((Sha $target)-ne$sourceSha256){throw 'R28C953L1 published hash changed.'}
$gate=[ordered]@{schema='argos_o3b21_r28c953l1_publish_gate_v1';createdUtc=[DateTime]::UtcNow.ToString('o');state='PASS_R28C953L1_PUBLISHED_EXACTLY_ONCE_AWAITING_SIGNED_LAUNCH_RESPONSE';requestId=$requestId;publishedArchivePath='work/PROJECT_PORTAL_REVIEW_ONLY/state/published_requests/'+$requestId+'.ready.zip';publishedArchiveSha256=$sourceSha256;publishedArchiveBytes=(Get-Item -LiteralPath $target).Length;signedManifestSha256='82E6676F9029F16FC7D62ED8C34090E338DE066F1E001BA0501B1463B7BDB8FE';signedSignatureSha256='B6995CC6C13AFF1E18DF3523E1935645E9CD7D00B81465811460F1CB93F83D48';archiveEntryCount=20;signedPayloadFileCount=18;exactSignedManifestAndSignaturePreserved=$true;expectedPairCount=953;syntheticTestCount=33;publishAttemptCount=1;automaticRetryAuthorized=$false;matchingSignedTerminalResponseRequired=$true;reviewOnly=$true;productionRoutingEnabled=$false};Write-NewJson $gatePath $gate;$gate|ConvertTo-Json -Depth 8
