#Requires -Version 5.1
[CmdletBinding(DefaultParameterSetName='Preflight')]
param([Parameter(ParameterSetName='Preflight')][switch]$Preflight,[Parameter(Mandatory=$true,ParameterSetName='Publish')][switch]$Publish)
Set-StrictMode -Version Latest
$ErrorActionPreference='Stop'
$requestId='REQ_20260901T182401641Z_22FCECB13ADC';$source='C:\R26O23PK\REQ_20260901T182401641Z_22FCECB13ADC.ready.zip';$sourceSha256='754FB864E58372937B7D12083F71576F160C051379F58CFB6D9A06CE6995AEE5'
$pathGate=Join-Path $PSScriptRoot 'R26O23_PREPUBLICATION_PATH_GATE.json';$pathGateSha256='D7328225BD19A2CB344A69C4B184F2CEE87917158CEE71C8589B44BEB091D2E9';$rehearsalGate=Join-Path $PSScriptRoot 'R26O23_FINAL_ZIP_REHEARSAL_GATE.json';$rehearsalGateSha256='98CDC30406B267C6480E943AA631E98E7BA2C596ABBD6E88E7EC26EA3AF193A2'
$expectedUnc='\\shm-cifs\Department\DE-1302_FAB_BE_Engineering\60_Saw_VI_Sort\600_General\Joshua.conn\AVI_Images\Argos\Uploads\InspectionRevs';$requestsRoot='U:\ProjectPortalRO\requests';$target=Join-Path $requestsRoot ($requestId+'.ready.zip');$upload=$target+'.upload';$gatePath=Join-Path $PSScriptRoot 'R26O23_PUBLISH_GATE.json'
function Sha([string]$Path){(Get-FileHash -LiteralPath $Path -Algorithm SHA256 -ErrorAction Stop).Hash}
function Write-NewJson([string]$Path,[object]$Value){if(Test-Path -LiteralPath $Path){throw "Create-new path exists: $Path"};[IO.File]::WriteAllText($Path,(($Value|ConvertTo-Json -Depth 8)+[Environment]::NewLine),(New-Object Text.UTF8Encoding($false)))}
if(-not(Test-Path -LiteralPath $source -PathType Leaf)-or(Sha $source)-ne$sourceSha256){throw 'R26O23 frozen source ZIP absent or changed.'};if(-not(Test-Path -LiteralPath $pathGate -PathType Leaf)-or(Sha $pathGate)-ne$pathGateSha256){throw 'R26O23 path gate absent or changed.'};if(-not(Test-Path -LiteralPath $rehearsalGate -PathType Leaf)-or(Sha $rehearsalGate)-ne$rehearsalGateSha256){throw 'R26O23 rehearsal gate absent or changed.'}
$pathGateValue=Get-Content -LiteralPath $pathGate -Raw|ConvertFrom-Json;$rehearsalGateValue=Get-Content -LiteralPath $rehearsalGate -Raw|ConvertFrom-Json;if([string]$pathGateValue.state-ne'PASS_R26O23_SIGNED_AND_PATH_GATED'-or[string]$pathGateValue.requestId-ne$requestId-or[string]$rehearsalGateValue.state-ne'PASS_R26O23_FINAL_ZIP_WINDOWS_PS51_REHEARSAL'-or[string]$rehearsalGateValue.requestId-ne$requestId){throw 'R26O23 path/rehearsal gate state or identity changed.'}
$drive=Get-PSDrive -Name U -ErrorAction Stop;$logicalDisk=Get-CimInstance Win32_LogicalDisk -Filter "DeviceID='U:'" -ErrorAction Stop;if([string]$drive.DisplayRoot-ne$expectedUnc-or[string]$logicalDisk.ProviderName-ne$expectedUnc-or[int]$logicalDisk.DriveType-ne 4){throw 'Persistent U: mapping changed.'}
if(-not(Test-Path -LiteralPath $requestsRoot -PathType Container)){throw 'Portal request root unavailable.'};$pending=@(Get-ChildItem -LiteralPath $requestsRoot -File -Filter '*.ready.zip' -ErrorAction Stop);if($pending.Count-ne 0){throw 'Portal request root contains unresolved pending request.'};if((Test-Path -LiteralPath $target)-or(Test-Path -LiteralPath $upload)){throw 'R26O23 publication leaf already exists.'};if(Test-Path -LiteralPath $gatePath){throw 'R26O23 publication gate already exists.'}
$project=Join-Path $PSScriptRoot '..\..';$head=[string](& git -C $project rev-parse HEAD);$origin=[string](& git -C $project rev-parse refs/remotes/origin/codex/fiducial-opencv-d-drive);if($LASTEXITCODE-ne 0-or$head-ne$origin){throw 'R26O23 local/origin branch tips do not match.'}
if($Preflight){[ordered]@{schema='argos_o3b21_r26o23_publish_preflight_v1';state='PASS_R26O23_PUBLISH_PREFLIGHT';requestId=$requestId;sourceSha256=$sourceSha256;pathGateSha256=$pathGateSha256;rehearsalGateSha256=$rehearsalGateSha256;pendingRequestCount=0;branchTip=$head;selectedOrdinals=@(23);completedR25CaseRerunCount=0;targetExecuted=$false;mutationsPerformed=$false}|ConvertTo-Json -Depth 5;return}
[IO.File]::Copy($source,$upload,$false);if((Sha $upload)-ne$sourceSha256){throw 'R26O23 upload hash changed.'};[IO.File]::Move($upload,$target);if((Sha $target)-ne$sourceSha256){throw 'R26O23 published hash changed.'}
$gate=[ordered]@{schema='argos_o3b21_r26o23_publish_gate_v1';createdUtc=[DateTime]::UtcNow.ToString('o');state='PASS_R26O23_PUBLISHED_EXACTLY_ONCE_AWAITING_SIGNED_TERMINAL_RESPONSE';requestId=$requestId;publishedArchivePath='work/PROJECT_PORTAL_REVIEW_ONLY/state/published_requests/'+$requestId+'.ready.zip';publishedArchiveSha256=$sourceSha256;publishedArchiveBytes=(Get-Item -LiteralPath $target).Length;signedManifestSha256='957F7CABFCD930F57DDE08BA6ED129F087CCD149872F041F7CB9EFD1EA596662';signedSignatureSha256='7196042A3EAE59C9E6FD1A91637B0DE5EA771A8D17AFC98CFCCAC9E94818D041';archiveEntryCount=17;signedPayloadFileCount=15;exactSignedManifestAndSignaturePreserved=$true;selectedOrdinals=@(23);completedCaseRerunCount=0;publishAttemptCount=1;automaticRetryAuthorized=$false;matchingSignedTerminalResponseRequired=$true;reviewOnly=$true;productionRoutingEnabled=$false};Write-NewJson $gatePath $gate;$gate|ConvertTo-Json -Depth 8
