#Requires -Version 5.1
[CmdletBinding(DefaultParameterSetName='Preflight')]
param([Parameter(ParameterSetName='Preflight')][switch]$Preflight,[Parameter(Mandatory=$true,ParameterSetName='Publish')][switch]$Publish)
Set-StrictMode -Version Latest
$ErrorActionPreference='Stop'
$requestId='REQ_20260902T002021713Z_1A03204809E3';$source='C:\R32C953L1PK\REQ_20260902T002021713Z_1A03204809E3.ready.zip';$sourceHash='AADEA88B0D3EE28743A2A73A573BB92565EE8197D92A151855AE24D8714BEBB8';$pathGate=Join-Path $PSScriptRoot 'R32C953L1_PREPUBLICATION_PATH_GATE.json';$pathGateHash='A52D39CD304C572DFFFA8754C410DE1301928192945DDBA1713659EDA99049FE';$rehearsalGate=Join-Path $PSScriptRoot 'R32C953L1_FINAL_ZIP_REHEARSAL_GATE.json';$rehearsalGateHash='DF42264F307278A29887CBB79E556F5469E7D50C8EC342E3A13867A801068B63';$recoveryIntent=Join-Path $PSScriptRoot 'RECOVERY_INTENT_R32C953L1.json';$recoveryIntentHash='2F0B21AFDAF91084F5DDFD0DB13ACF2BD1C58797A600A12C0504930A5A95ACAB';$expected='\\shm-cifs\Department\DE-1302_FAB_BE_Engineering\60_Saw_VI_Sort\600_General\Joshua.conn\AVI_Images\Argos\Uploads\InspectionRevs';$requests='U:\ProjectPortalRO\requests';$target=Join-Path $requests ($requestId+'.ready.zip');$upload=$target+'.upload';$gate=Join-Path $PSScriptRoot 'R32C953L1_PUBLISH_GATE.json'
function Sha([string]$Path){(Get-FileHash -LiteralPath $Path -Algorithm SHA256 -ErrorAction Stop).Hash}
function New-Json([string]$Path,[object]$Value){if(Test-Path -LiteralPath $Path){throw "Create-new path exists: $Path"};[IO.File]::WriteAllText($Path,(($Value|ConvertTo-Json -Depth 20)+[Environment]::NewLine),(New-Object Text.UTF8Encoding($false)))}
foreach($pin in @(@($source,$sourceHash),@($pathGate,$pathGateHash),@($rehearsalGate,$rehearsalGateHash),@($recoveryIntent,$recoveryIntentHash))){if(-not(Test-Path -LiteralPath $pin[0] -PathType Leaf)-or(Sha $pin[0])-ne$pin[1]){throw "R32C953L1 publication dependency absent or changed: $($pin[0])"}};$pathValue=Get-Content -LiteralPath $pathGate -Raw|ConvertFrom-Json;$rehearsalValue=Get-Content -LiteralPath $rehearsalGate -Raw|ConvertFrom-Json;if([string]$pathValue.state-ne'PASS_R32C953L1_SIGNED_AND_PATH_GATED'-or[string]$pathValue.requestId-ne$requestId-or[string]$rehearsalValue.state-ne'PASS_R32C953L1_FINAL_ZIP_WINDOWS_PS51_REHEARSAL'-or[string]$rehearsalValue.requestId-ne$requestId){throw 'R32C953L1 path or rehearsal gate changed.'}
$ps=Get-PSDrive U -ErrorAction Stop;$disk=Get-CimInstance Win32_LogicalDisk -Filter "DeviceID='U:'" -ErrorAction Stop;if([string]$ps.DisplayRoot-ne$expected-or[string]$disk.ProviderName-ne$expected-or[int]$disk.DriveType-ne4){throw 'Qualified U mapping changed.'};if(-not(Test-Path -LiteralPath $requests -PathType Container)){throw 'Portal request root unavailable.'};$pending=@(Get-ChildItem -LiteralPath $requests -File -Filter '*.ready.zip' -ErrorAction Stop);if($pending.Count-ne0){throw 'Portal request root contains unresolved pending request.'};if((Test-Path -LiteralPath $target)-or(Test-Path -LiteralPath $upload)-or(Test-Path -LiteralPath $gate)){throw 'R32C953L1 create-new publication path exists.'};$project=[IO.Path]::GetFullPath((Join-Path $PSScriptRoot '..\..'));$head=[string](& git -C $project rev-parse HEAD);$origin=[string](& git -C $project rev-parse refs/remotes/origin/codex/fiducial-opencv-d-drive);if($LASTEXITCODE-ne0-or$head-ne$origin){throw 'R32C953L1 local/origin branch tips do not match.'}
if($Preflight){[ordered]@{schema='argos_o3b21_r32c953l1_publish_preflight_v1';state='PASS_R32C953L1_PUBLISH_PREFLIGHT';requestId=$requestId;sourceSha256=$sourceHash;pendingRequestCount=0;branchTip=$head;currentPairCount=978;excludedPairCount=25;expectedPairCount=953;syntheticDetectorTestCount=95;selectionTestCount=7;targetExecuted=$false;mutationsPerformed=$false}|ConvertTo-Json;return};[IO.File]::Copy($source,$upload,$false);if((Sha $upload)-ne$sourceHash){throw 'R32C953L1 upload hash changed.'};[IO.File]::Move($upload,$target);if((Sha $target)-ne$sourceHash){throw 'R32C953L1 published hash changed.'};$value=[ordered]@{schema='argos_o3b21_r32c953l1_publish_gate_v1';createdUtc=[DateTime]::UtcNow.ToString('o');state='PASS_R32C953L1_PUBLISHED_EXACTLY_ONCE_AWAITING_SIGNED_RESPONSE';requestId=$requestId;publishedPath=$target;publishedSha256=$sourceHash;publishedBytes=(Get-Item -LiteralPath $target).Length;manifestSha256='D0AA64CD54F9AE0E350EEC79C775786B5EA9DDA1100A78EB06927B48C65939B1';signatureSha256='66E9FF24E6765C76FA40433B36FB668B01D371C1BAE481FECCC56387D71EF624';publishAttemptCount=1;automaticRetryAuthorized=$false;matchingSignedTerminalResponseRequired=$true;currentPairCount=978;excludedPairCount=25;expectedPairCount=953;syntheticDetectorTestCount=95;selectionTestCount=7;reviewOnly=$true;productionRoutingEnabled=$false};New-Json $gate $value;$value|ConvertTo-Json -Depth 10
