#Requires -Version 5.1
[CmdletBinding(DefaultParameterSetName='Preflight')]
param([Parameter(ParameterSetName='Preflight')][switch]$Preflight,[Parameter(Mandatory=$true,ParameterSetName='Sign')][switch]$Sign)
Set-StrictMode -Version Latest
$ErrorActionPreference='Stop'
$projectRoot=[IO.Path]::GetFullPath((Join-Path $PSScriptRoot '..\..'))
$root='C:\R26O23PK';$payloadRoot=Join-Path $root 'payload';$definitionPath=Join-Path $root 'DEFINITION.json';$signedRoot=Join-Path $root 'signed';$gatePath=Join-Path $PSScriptRoot 'R26O23_SIGN_GATE.json'
$identityPath=Join-Path $projectRoot 'work\PROJECT_PORTAL_REVIEW_ONLY\state\LAPTOP_SIGNING_IDENTITY.json';$publicCertificatePath=Join-Path $projectRoot 'work\PROJECT_PORTAL_REVIEW_ONLY\enrollment\ARGOS_PROJECT_PORTAL_LAPTOP_SIGNER_PUBLIC.cer';$verifierPath=Join-Path $projectRoot 'work\PROJECT_PORTAL_REVIEW_ONLY\scripts\Test-SignedPortalPackage.ps1'
$expectedDefinitionSha='AF7310371483F334DDF828A1B3EBA635FFC5CD73AA66E1AF25E945EF25A7E234'
$payloadPins=[ordered]@{
 'BACKSIDE_NOTCH_CONFIG_R13.json'='27010B75F2E5CCB601E710A63D73F5483072F6EB797F9D72A0632F993E6E4AD3';'C.json'='CDFD888129D0144C9942D027B0C4583FEEF3619D6D65B060B3001686357879D8'
 'Detect-BacksideNotchOpenCvR15.py'='F16A024EEA34F01502BD62B9C750FD6AA95D6BD75D9F8A03D07FBF7B2A0EB64C';'Detect-BacksideNotchOpenCvR17.py'='B480B40435EE80527B00074FC4E7A69F423033D5AF02DA659E9193145B6CD713';'Detect-BacksideNotchOpenCvR18.py'='DA1305841E8592FCD8AC5C6A4C5981A4BEC7AC741BA75BC47CAE3B16F5DF372A';'Detect-BacksideNotchOpenCvR20.py'='B10AC6F0E0500AC3D14713232FCEDC5C209FBACF56AD7826AF87443C2587C46C';'Detect-BacksideNotchOpenCvR21.py'='29B41CCE63BC91F99C4FFF24F2DFEECC9BDCDA8ED5314A7671EB40EEBA582A8E';'Detect-BacksideNotchOpenCvR22.py'='DB6C62727BB7E2EBBB5E8B669C5EE86D4B8960912BB66A0138F157538B59EC94';'Detect-BacksideNotchOpenCvR23.py'='AAE38F93C7C1FE16E0967713A3773E33D61488E4D02BE6794E2811624D6DCE4C';'Detect-BacksideNotchOpenCvR24.py'='BDEAA9DBA4AA5FB1DEDF5FBBFA7C8F02C1860522E713EA1BE0BDB36539401477';'Detect-BacksideNotchOpenCvR25.py'='6A7977E4DAFE692FCE6E7DE4740C94EE66D5F79ECD62FDF190CB5EE8E4862274';'Detect-BacksideNotchOpenCvR26.py'='05534929ECCCB18EA8E2E68A66CF33FA7AAF6B43CA80B6BBBD1970C3946FC1D6'
 'Invoke-R26O23.ps1'='85BDFA8383A61AB9A2167E432956E99DBBDBA381E4D2D17A860F502D84165952';'R18_REGRESSION_CASES.json'='7F2BF805CC35893B307557680251A94A49F28305E20E3735931F064E82650DF4';'R26O23_TARGET_CASE.json'='CFF942B395789E93C002D5DF57CCA60BB78A962D8CBE8863A11B2FE7FC020553'
}
function Sha([string]$Path){(Get-FileHash -LiteralPath $Path -Algorithm SHA256 -ErrorAction Stop).Hash}
function Write-NewBytes([string]$Path,[byte[]]$Bytes){if(Test-Path -LiteralPath $Path){throw "Create-new path exists: $Path"};[IO.File]::WriteAllBytes($Path,$Bytes)}
function Write-NewJson([string]$Path,[object]$Value){if(Test-Path -LiteralPath $Path){throw "Create-new path exists: $Path"};[IO.File]::WriteAllText($Path,(($Value|ConvertTo-Json -Depth 16)+[Environment]::NewLine),(New-Object Text.UTF8Encoding($false)))}
foreach($path in @($definitionPath,$identityPath,$publicCertificatePath,$verifierPath)){if(-not(Test-Path -LiteralPath $path -PathType Leaf)){throw "R26O23 signing dependency absent: $path"}}
if((Sha $definitionPath)-ne$expectedDefinitionSha){throw 'R26O23 definition hash changed.'};foreach($leaf in $payloadPins.Keys){$path=Join-Path $payloadRoot $leaf;if(-not(Test-Path -LiteralPath $path -PathType Leaf)-or(Sha $path)-ne$payloadPins[$leaf]){throw "R26O23 payload changed: $leaf"}}
if(Test-Path -LiteralPath $signedRoot){throw 'R26O23 signed root already exists.'};if(Test-Path -LiteralPath $gatePath){throw 'R26O23 sign gate already exists.'}
$definition=Get-Content -LiteralPath $definitionPath -Raw|ConvertFrom-Json;if([string]$definition.targetRole-ne'JBOD'-or[string]$definition.jobClass-ne'MAINTENANCE_PATCH'-or@($definition.changes).Count-ne 1-or@($definition.allowedTaskActions).Count-ne 0-or[string]$definition.entryPoint-ne'payload/Invoke-R26O23.ps1'-or[string]$definition.rehearsal.requiredState-ne'PASS_O3B21_R26O23_TARGET_EVIDENCE_EXECUTED'){throw 'R26O23 definition bounds changed.'}
$change=@($definition.changes)[0];if([string]$change.destination-ne'C:/ProgramData/ArgosEdgeLabRO/AllWaferProcessorV2/PROCESSOR_CONFIG.json'-or[string]$change.installedSha256-ne[string]$payloadPins['C.json']-or@($change.approvedPredecessorSha256).Count-ne 1-or[string]@($change.approvedPredecessorSha256)[0]-ne[string]$payloadPins['C.json']-or[bool]$change.allowCreate){throw 'R26O23 same-bytes carrier contract changed.'}
$identity=Get-Content -LiteralPath $identityPath -Raw|ConvertFrom-Json;$thumbprint=([string]$identity.thumbprint).Replace(' ','').ToUpperInvariant();$certificate=Get-Item -LiteralPath ("Cert:\CurrentUser\My\$thumbprint") -ErrorAction Stop;if(-not$certificate.HasPrivateKey){throw 'R26O23 signer private key unavailable.'}
if($Preflight){[ordered]@{schema='argos_o3b21_r26o23_sign_preflight_v1';state='PASS_R26O23_SIGN_PREFLIGHT';signerThumbprint=$thumbprint;definitionSha256=$expectedDefinitionSha;payloadFileCount=$payloadPins.Count;selectedOrdinals=@(23);completedR25CaseRerunCount=0;targetExecuted=$false;mutationsPerformed=$false}|ConvertTo-Json -Depth 5;return}
[void](New-Item -ItemType Directory -Path $signedRoot);$created=[DateTimeOffset]::UtcNow;$requestId='REQ_'+$created.ToString('yyyyMMddTHHmmssfffZ')+'_'+([Guid]::NewGuid().ToString('N').Substring(0,12).ToUpperInvariant());$partial=Join-Path $signedRoot ($requestId+'.partial');$ready=Join-Path $signedRoot ($requestId+'.ready');[void](New-Item -ItemType Directory -Path (Join-Path $partial 'payload') -Force)
foreach($leaf in $payloadPins.Keys){[IO.File]::Copy((Join-Path $payloadRoot $leaf),(Join-Path (Join-Path $partial 'payload') $leaf),$false)};$files=@(Get-ChildItem -LiteralPath (Join-Path $partial 'payload') -File|Sort-Object Name|ForEach-Object{[ordered]@{path='payload/'+$_.Name;bytes=$_.Length;sha256=Sha $_.FullName}})
$manifest=[ordered]@{schema='argos_project_portal_request_manifest_v1';requestId=$requestId;createdUtc=$created.ToString('o');expiresUtc=$created.AddHours(24).ToString('o');targetRole='JBOD';jobClass='MAINTENANCE_PATCH';handler='';maxResultBytes=[int64]$definition.maxResultBytes;reviewOnly=$true;trainingEligible=$false;xmlEligible=$false;productionEligible=$false;productionRoutingEnabled=$false;credentialsIncluded=$false;signerThumbprint=$thumbprint;signatureAlgorithm='RSA-SHA256-PKCS1';files=$files;entryPoint=[string]$definition.entryPoint;changes=@($definition.changes);allowedTaskActions=@();rehearsal=$definition.rehearsal}
$manifestBytes=(New-Object Text.UTF8Encoding($false)).GetBytes(($manifest|ConvertTo-Json -Depth 32));Write-NewBytes (Join-Path $partial 'PORTAL_REQUEST_MANIFEST.json') $manifestBytes;$rsa=[Security.Cryptography.X509Certificates.RSACertificateExtensions]::GetRSAPrivateKey($certificate);try{$signature=$rsa.SignData($manifestBytes,[Security.Cryptography.HashAlgorithmName]::SHA256,[Security.Cryptography.RSASignaturePadding]::Pkcs1)}finally{$rsa.Dispose()};Write-NewBytes (Join-Path $partial 'PORTAL_REQUEST_MANIFEST.sig') $signature;Move-Item -LiteralPath $partial -Destination $ready
& $verifierPath -PackagePath $ready -SignerCertificatePath $publicCertificatePath -ExpectedTargetRole 'JBOD' -ExpectedJobClass 'MAINTENANCE_PATCH'|Out-Null;Add-Type -AssemblyName System.IO.Compression.FileSystem;$zipPath=Join-Path $root ($requestId+'.ready.zip');if(Test-Path -LiteralPath $zipPath){throw 'R26O23 ZIP exists.'};[IO.Compression.ZipFile]::CreateFromDirectory($ready,$zipPath,[IO.Compression.CompressionLevel]::Optimal,$false)
$gate=[ordered]@{schema='argos_o3b21_r26o23_sign_gate_v1';createdUtc=[DateTime]::UtcNow.ToString('o');state='PASS_R26O23_SIGNED_SINGLE_CASE_TARGET_PACKAGE';requestId=$requestId;packagePath=$ready;packageZipPath=$zipPath;packageZipBytes=(Get-Item -LiteralPath $zipPath).Length;packageZipSha256=Sha $zipPath;manifestSha256=Sha (Join-Path $ready 'PORTAL_REQUEST_MANIFEST.json');signatureSha256=Sha (Join-Path $ready 'PORTAL_REQUEST_MANIFEST.sig');signerThumbprint=$thumbprint;exactPackageSignaturePassed=$true;payloadFileCount=$payloadPins.Count;pythonCacheLeafCount=0;exactPackagedEntryLeafPreflightPassed=$true;selectedOrdinals=@(23);completedR25CaseRerunCount=0;allowedTaskActionCount=0;signed=$true;published=$false;targetExecuted=$false;mutationsPerformed=$false};Write-NewJson $gatePath $gate;$gate|ConvertTo-Json -Depth 10
