#Requires -Version 5.1
[CmdletBinding(DefaultParameterSetName='Preflight')]
param([Parameter(ParameterSetName='Preflight')][switch]$Preflight,[Parameter(Mandatory=$true,ParameterSetName='Sign')][switch]$Sign)
Set-StrictMode -Version Latest
$ErrorActionPreference='Stop'
$project=[IO.Path]::GetFullPath((Join-Path $PSScriptRoot '..\..'));$root='C:\R31VAL1PK';$payload=Join-Path $root 'payload';$definitionPath=Join-Path $root 'DEFINITION.json';$signedRoot=Join-Path $root 'signed';$gatePath=Join-Path $PSScriptRoot 'R31VAL1_SIGN_GATE.json';$buildGatePath=Join-Path $PSScriptRoot 'R31VAL1_BUILD_GATE.json';$buildGateHash='933095F855147DAB679DE803EAD7A116262A32FCBAD625081F769931E0C27A78'
$identityPath=Join-Path $project 'work\PROJECT_PORTAL_REVIEW_ONLY\state\LAPTOP_SIGNING_IDENTITY.json';$certificatePath=Join-Path $project 'work\PROJECT_PORTAL_REVIEW_ONLY\enrollment\ARGOS_PROJECT_PORTAL_LAPTOP_SIGNER_PUBLIC.cer';$verifier=Join-Path $project 'work\PROJECT_PORTAL_REVIEW_ONLY\scripts\Test-SignedPortalPackage.ps1'
function Sha([string]$Path){(Get-FileHash -LiteralPath $Path -Algorithm SHA256 -ErrorAction Stop).Hash}
function New-Bytes([string]$Path,[byte[]]$Bytes){if(Test-Path -LiteralPath $Path){throw "Create-new path exists: $Path"};[IO.File]::WriteAllBytes($Path,$Bytes)}
function New-Json([string]$Path,[object]$Value){if(Test-Path -LiteralPath $Path){throw "Create-new path exists: $Path"};[IO.File]::WriteAllText($Path,(($Value|ConvertTo-Json -Depth 20)+[Environment]::NewLine),(New-Object Text.UTF8Encoding($false)))}
foreach($path in @($definitionPath,$buildGatePath,$identityPath,$certificatePath,$verifier)){if(-not(Test-Path -LiteralPath $path -PathType Leaf)){throw "Signing dependency absent: $path"}};if((Sha $buildGatePath)-ne$buildGateHash){throw 'R31VAL1 build gate changed.'}
$buildGate=Get-Content -LiteralPath $buildGatePath -Raw|ConvertFrom-Json;if([string]$buildGate.state-ne'PASS_R31VAL1_UNSIGNED_ALL_CURRENT_RECIPE_PACKAGE_BUILT'-or[int]$buildGate.payloadFileCount-ne26-or[string]$buildGate.definitionSha256-ne(Sha $definitionPath)){throw 'R31VAL1 build evidence changed.'}
$actual=@(Get-ChildItem -LiteralPath $payload -File|Sort-Object Name);if($actual.Count-ne26){throw 'R31VAL1 payload cardinality changed.'};foreach($row in @($buildGate.payloadFiles)){$path=Join-Path $payload ([string]$row.path);if(-not(Test-Path -LiteralPath $path -PathType Leaf)-or(Sha $path)-ne[string]$row.sha256-or(Get-Item -LiteralPath $path).Length-ne[int64]$row.bytes){throw "R31VAL1 payload changed: $($row.path)"}}
$definition=Get-Content -LiteralPath $definitionPath -Raw|ConvertFrom-Json;if([string]$definition.targetRole-ne'JBOD'-or[string]$definition.jobClass-ne'MAINTENANCE_PATCH'-or[string]$definition.entryPoint-ne'payload/Invoke-R31VAL1.ps1'-or[string]$definition.rehearsal.requiredState-ne'PASS_O3B21_R31VAL1_ALL_CURRENT_RECIPE_EXECUTIONS_COMPLETE'-or@($definition.changes).Count-ne1-or@($definition.allowedTaskActions).Count-ne0){throw 'R31VAL1 definition bounds changed.'};$change=@($definition.changes)[0];if([string]$change.destination-ne'C:/ProgramData/ArgosEdgeLabRO/AllWaferProcessorV2/PROCESSOR_CONFIG.json'-or[string]$change.installedSha256-ne'CDFD888129D0144C9942D027B0C4583FEEF3619D6D65B060B3001686357879D8'-or[bool]$change.allowCreate){throw 'R31VAL1 same-bytes carrier changed.'}
$identity=Get-Content -LiteralPath $identityPath -Raw|ConvertFrom-Json;$thumb=([string]$identity.thumbprint).Replace(' ','').ToUpperInvariant();$cert=Get-Item -LiteralPath ("Cert:\CurrentUser\My\$thumb") -ErrorAction Stop;if(-not$cert.HasPrivateKey){throw 'Signer private key unavailable.'};if(Test-Path -LiteralPath $signedRoot){throw 'R31VAL1 signed root exists.'};if(Test-Path -LiteralPath $gatePath){throw 'R31VAL1 sign gate exists.'}
if($Preflight){[ordered]@{schema='argos_o3b21_r31val1_sign_preflight_v1';state='PASS_R31VAL1_SIGN_PREFLIGHT';signerThumbprint=$thumb;definitionSha256=Sha $definitionPath;payloadFileCount=26;maximumCaseCount=120;syntheticTestCount=80;targetExecuted=$false;mutationsPerformed=$false}|ConvertTo-Json;return}
[void](New-Item -ItemType Directory -Path $signedRoot);$created=[DateTimeOffset]::UtcNow;$requestId='REQ_'+$created.ToString('yyyyMMddTHHmmssfffZ')+'_'+([Guid]::NewGuid().ToString('N').Substring(0,12).ToUpperInvariant());$partial=Join-Path $signedRoot ($requestId+'.partial');$ready=Join-Path $signedRoot ($requestId+'.ready');[void](New-Item -ItemType Directory -Path (Join-Path $partial 'payload') -Force)
foreach($item in $actual){[IO.File]::Copy($item.FullName,(Join-Path (Join-Path $partial 'payload') $item.Name),$false)};$files=@(Get-ChildItem -LiteralPath (Join-Path $partial 'payload') -File|Sort-Object Name|ForEach-Object{[ordered]@{path='payload/'+$_.Name;bytes=$_.Length;sha256=Sha $_.FullName}})
$manifest=[ordered]@{schema='argos_project_portal_request_manifest_v1';requestId=$requestId;createdUtc=$created.ToString('o');expiresUtc=$created.AddHours(24).ToString('o');targetRole='JBOD';jobClass='MAINTENANCE_PATCH';handler='';maxResultBytes=[int64]$definition.maxResultBytes;reviewOnly=$true;trainingEligible=$false;xmlEligible=$false;productionEligible=$false;productionRoutingEnabled=$false;credentialsIncluded=$false;signerThumbprint=$thumb;signatureAlgorithm='RSA-SHA256-PKCS1';files=$files;entryPoint=[string]$definition.entryPoint;changes=@($definition.changes);allowedTaskActions=@();rehearsal=$definition.rehearsal}
$bytes=(New-Object Text.UTF8Encoding($false)).GetBytes(($manifest|ConvertTo-Json -Depth 32));New-Bytes (Join-Path $partial 'PORTAL_REQUEST_MANIFEST.json') $bytes;$rsa=[Security.Cryptography.X509Certificates.RSACertificateExtensions]::GetRSAPrivateKey($cert);try{$signature=$rsa.SignData($bytes,[Security.Cryptography.HashAlgorithmName]::SHA256,[Security.Cryptography.RSASignaturePadding]::Pkcs1)}finally{$rsa.Dispose()};New-Bytes (Join-Path $partial 'PORTAL_REQUEST_MANIFEST.sig') $signature;Move-Item -LiteralPath $partial -Destination $ready
& $verifier -PackagePath $ready -SignerCertificatePath $certificatePath -ExpectedTargetRole 'JBOD' -ExpectedJobClass 'MAINTENANCE_PATCH'|Out-Null;Add-Type -AssemblyName System.IO.Compression.FileSystem;$zip=Join-Path $root ($requestId+'.ready.zip');[IO.Compression.ZipFile]::CreateFromDirectory($ready,$zip,[IO.Compression.CompressionLevel]::Optimal,$false)
$gate=[ordered]@{schema='argos_o3b21_r31val1_sign_gate_v1';createdUtc=[DateTime]::UtcNow.ToString('o');state='PASS_R31VAL1_SIGNED_ALL_CURRENT_RECIPE_PACKAGE';requestId=$requestId;packagePath=$ready;packageZipPath=$zip;packageZipBytes=(Get-Item -LiteralPath $zip).Length;packageZipSha256=Sha $zip;manifestSha256=Sha (Join-Path $ready 'PORTAL_REQUEST_MANIFEST.json');signatureSha256=Sha (Join-Path $ready 'PORTAL_REQUEST_MANIFEST.sig');signerThumbprint=$thumb;exactPackageSignaturePassed=$true;payloadFileCount=26;pythonCacheLeafCount=0;maximumCaseCount=120;syntheticTestCount=80;allowedTaskActionCount=0;signed=$true;published=$false;targetExecuted=$false;mutationsPerformed=$false};New-Json $gatePath $gate;$gate|ConvertTo-Json -Depth 10
