#Requires -Version 5.1
[CmdletBinding(DefaultParameterSetName='Preflight')]
param([Parameter(ParameterSetName='Preflight')][switch]$Preflight,[Parameter(Mandatory=$true,ParameterSetName='Test')][switch]$Test)
Set-StrictMode -Version Latest
$ErrorActionPreference='Stop'
$project=[IO.Path]::GetFullPath((Join-Path $PSScriptRoot '..\..'));$requestId='REQ_20260901T225534688Z_673F2FFD0E09';$zip='C:\R31VAL2PK\REQ_20260901T225534688Z_673F2FFD0E09.ready.zip';$zipHash='E107AB251E2CD4230247F69DCCC7BD0AFB1B1819AA3C1C36BB8646E30895D56B';$extract='C:\R31VAL2V1';$gate=Join-Path $PSScriptRoot 'R31VAL2_FINAL_ZIP_REHEARSAL_GATE.json';$cert=Join-Path $project 'work\PROJECT_PORTAL_REVIEW_ONLY\enrollment\ARGOS_PROJECT_PORTAL_LAPTOP_SIGNER_PUBLIC.cer';$verifier=Join-Path $project 'work\PROJECT_PORTAL_REVIEW_ONLY\scripts\Test-SignedPortalPackage.ps1'
function Sha([string]$Path){(Get-FileHash -LiteralPath $Path -Algorithm SHA256 -ErrorAction Stop).Hash}
function New-Json([string]$Path,[object]$Value){if(Test-Path -LiteralPath $Path){throw "Create-new path exists: $Path"};[IO.File]::WriteAllText($Path,(($Value|ConvertTo-Json -Depth 20)+[Environment]::NewLine),(New-Object Text.UTF8Encoding($false)))}
if(-not(Test-Path -LiteralPath $zip -PathType Leaf)-or(Sha $zip)-ne$zipHash){throw 'R31VAL2 final ZIP absent or changed.'};foreach($path in @($cert,$verifier)){if(-not(Test-Path -LiteralPath $path -PathType Leaf)){throw "R31VAL2 rehearsal dependency absent: $path"}};if(Test-Path -LiteralPath $extract){throw 'R31VAL2 rehearsal extraction root exists.'};if(Test-Path -LiteralPath $gate){throw 'R31VAL2 rehearsal gate exists.'};if($Preflight){[ordered]@{schema='argos_o3b21_r31val2_final_zip_rehearsal_preflight_v1';state='PASS_R31VAL2_FINAL_ZIP_REHEARSAL_PREFLIGHT';requestId=$requestId;zipSha256=$zipHash;freshExtractionRoot=$extract;targetExecuted=$false;mutationsPerformed=$false}|ConvertTo-Json;return}
Add-Type -AssemblyName System.IO.Compression.FileSystem;[IO.Compression.ZipFile]::ExtractToDirectory($zip,$extract);$verified=& $verifier -PackagePath $extract -SignerCertificatePath $cert -ExpectedTargetRole 'JBOD' -ExpectedJobClass 'MAINTENANCE_PATCH';if([string]$verified.State-ne'PASS_SIGNED_PORTAL_PACKAGE'){throw 'R31VAL2 extracted signature verification failed.'};$entry=Join-Path $extract 'payload\Invoke-R31VAL2.ps1';$leafText=& powershell.exe -NoProfile -ExecutionPolicy Bypass -File $entry -PackageLeafPreflight;if($LASTEXITCODE-ne0){throw 'R31VAL2 packaged entry preflight failed.'};$leaf=$leafText|ConvertFrom-Json;if([string]$leaf.state-ne'PASS_R31VAL2_EXACT_PACKAGED_LEAVES'){throw 'R31VAL2 packaged entry state changed.'}
$python=(Get-Command python -ErrorAction Stop).Source;$testStates=[ordered]@{};foreach($revision in 28,29,30,31){$state=& $python -B (Join-Path $extract ("payload\Test-BacksideNotchOpenCvR$revision.py"));if($LASTEXITCODE-ne0-or[string]$state-notmatch("^PASS_R${revision}_PACKAGED_SYNTHETIC_")){throw "R31VAL2 packaged R$revision tests failed."};$testStates["r${revision}"]=[string]$state};$archive=[IO.Compression.ZipFile]::OpenRead($zip);try{$entryCount=$archive.Entries.Count}finally{$archive.Dispose()};$value=[ordered]@{schema='argos_o3b21_r31val2_final_zip_rehearsal_gate_v1';createdUtc=[DateTime]::UtcNow.ToString('o');state='PASS_R31VAL2_FINAL_ZIP_WINDOWS_PS51_REHEARSAL';requestId=$requestId;zipPath=$zip;zipBytes=(Get-Item -LiteralPath $zip).Length;zipSha256=$zipHash;freshExtractionRoot=$extract;archiveEntryCount=$entryCount;signedPackageState=[string]$verified.State;signerThumbprint=[string]$verified.SignerThumbprint;packagedEntryState=[string]$leaf.state;packagedSyntheticTestStates=$testStates;payloadFileCount=26;exactCaseCount=298;currentRecipeCount=265;maximumConcurrentChildren=4;syntheticTestCount=80;targetExecuted=$false;mutationsPerformed=$false;reviewOnly=$true;productionRoutingEnabled=$false};New-Json $gate $value;$value|ConvertTo-Json -Depth 10
