#Requires -Version 5.1
[CmdletBinding(DefaultParameterSetName='Preflight')]
param([Parameter(ParameterSetName='Preflight')][switch]$Preflight,[Parameter(Mandatory=$true,ParameterSetName='Test')][switch]$Test)
Set-StrictMode -Version Latest
$ErrorActionPreference='Stop'
$project=[IO.Path]::GetFullPath((Join-Path $PSScriptRoot '..\..'));$requestId='REQ_20260902T002021713Z_1A03204809E3';$zip='C:\R32C953L1PK\REQ_20260902T002021713Z_1A03204809E3.ready.zip';$zipHash='AADEA88B0D3EE28743A2A73A573BB92565EE8197D92A151855AE24D8714BEBB8';$extract='C:\R32C953L1V1';$gate=Join-Path $PSScriptRoot 'R32C953L1_FINAL_ZIP_REHEARSAL_GATE.json';$cert=Join-Path $project 'work\PROJECT_PORTAL_REVIEW_ONLY\enrollment\ARGOS_PROJECT_PORTAL_LAPTOP_SIGNER_PUBLIC.cer';$verifier=Join-Path $project 'work\PROJECT_PORTAL_REVIEW_ONLY\scripts\Test-SignedPortalPackage.ps1'
function Sha([string]$Path){(Get-FileHash -LiteralPath $Path -Algorithm SHA256 -ErrorAction Stop).Hash}
function New-Json([string]$Path,[object]$Value){if(Test-Path -LiteralPath $Path){throw "Create-new path exists: $Path"};[IO.File]::WriteAllText($Path,(($Value|ConvertTo-Json -Depth 20)+[Environment]::NewLine),(New-Object Text.UTF8Encoding($false)))}
if(-not(Test-Path -LiteralPath $zip -PathType Leaf)-or(Sha $zip)-ne$zipHash){throw 'R32C953L1 final ZIP absent or changed.'};foreach($path in @($cert,$verifier)){if(-not(Test-Path -LiteralPath $path -PathType Leaf)){throw "R32C953L1 rehearsal dependency absent: $path"}};if(Test-Path -LiteralPath $extract){throw 'R32C953L1 rehearsal extraction root exists.'};if(Test-Path -LiteralPath $gate){throw 'R32C953L1 rehearsal gate exists.'}
if($Preflight){[ordered]@{schema='argos_o3b21_r32c953l1_final_zip_rehearsal_preflight_v1';state='PASS_R32C953L1_FINAL_ZIP_REHEARSAL_PREFLIGHT';requestId=$requestId;zipSha256=$zipHash;freshExtractionRoot=$extract;targetExecuted=$false;mutationsPerformed=$false}|ConvertTo-Json;return}
Add-Type -AssemblyName System.IO.Compression.FileSystem;[IO.Compression.ZipFile]::ExtractToDirectory($zip,$extract);$verified=& $verifier -PackagePath $extract -SignerCertificatePath $cert -ExpectedTargetRole 'JBOD' -ExpectedJobClass 'MAINTENANCE_PATCH';if([string]$verified.State-ne'PASS_SIGNED_PORTAL_PACKAGE'){throw 'R32C953L1 extracted signature verification failed.'}
$entry=Join-Path $extract 'payload\Invoke-R32C953L1.ps1';$leafText=& powershell.exe -NoProfile -ExecutionPolicy Bypass -File $entry -PackageLeafPreflight;if($LASTEXITCODE-ne0){throw 'R32C953L1 packaged entry preflight failed.'};$leaf=$leafText|ConvertFrom-Json;if([string]$leaf.state-ne'PASS_R32C953L1_EXACT_PACKAGED_LAUNCH_LEAVES'-or[int]$leaf.expectedPairCount-ne953-or[int]$leaf.currentPairCount-ne978-or[int]$leaf.excludedPairCount-ne25){throw 'R32C953L1 packaged entry state changed.'}
$python=(Get-Command python -ErrorAction Stop).Source;$selectionState=& $python -B (Join-Path $extract 'payload\Test-RunR32Frozen953Corpus.py');if($LASTEXITCODE-ne0-or[string]$selectionState-ne'PASS_R32_FROZEN_953_SELECTION_7_OF_7'){throw 'R32C953L1 packaged selection tests failed.'};$testStates=[ordered]@{};foreach($revision in 28,29,30,31,32){$state=& $python -B (Join-Path $extract ("payload\Test-BacksideNotchOpenCvR$revision.py"));if($LASTEXITCODE-ne0-or[string]$state-notmatch("^PASS_R${revision}_PACKAGED_SYNTHETIC_")){throw "R32C953L1 packaged R$revision tests failed."};$testStates["r${revision}"]=[string]$state}
$archive=[IO.Compression.ZipFile]::OpenRead($zip);try{$entryCount=$archive.Entries.Count}finally{$archive.Dispose()};$value=[ordered]@{schema='argos_o3b21_r32c953l1_final_zip_rehearsal_gate_v1';createdUtc=[DateTime]::UtcNow.ToString('o');state='PASS_R32C953L1_FINAL_ZIP_WINDOWS_PS51_REHEARSAL';requestId=$requestId;zipPath=$zip;zipBytes=(Get-Item -LiteralPath $zip).Length;zipSha256=$zipHash;freshExtractionRoot=$extract;archiveEntryCount=$entryCount;signedPackageState=[string]$verified.State;signerThumbprint=[string]$verified.SignerThumbprint;packagedEntryState=[string]$leaf.state;selectionTestState=[string]$selectionState;packagedSyntheticDetectorTestStates=$testStates;payloadFileCount=28;currentPairCount=978;excludedPairCount=25;expectedPairCount=953;syntheticDetectorTestCount=95;selectionTestCount=7;targetExecuted=$false;mutationsPerformed=$false;reviewOnly=$true;productionRoutingEnabled=$false};New-Json $gate $value;$value|ConvertTo-Json -Depth 10
