#Requires -Version 5.1
[CmdletBinding(DefaultParameterSetName='Preflight')]
param([Parameter(ParameterSetName='Preflight')][switch]$Preflight,[Parameter(Mandatory=$true,ParameterSetName='Test')][switch]$Test)
Set-StrictMode -Version Latest
$ErrorActionPreference='Stop'
$project=[IO.Path]::GetFullPath((Join-Path $PSScriptRoot '..\..'));$requestId='REQ_20260901T221440855Z_AA1D598B751C';$zip='C:\R30VAL1PK\REQ_20260901T221440855Z_AA1D598B751C.ready.zip';$zipHash='7A69ED41EF1CCD7F0B0E63EE3609B630B09979696E93B450EF2B98B85CEC726F';$extract='C:\R30VAL1V1';$gate=Join-Path $PSScriptRoot 'R30VAL1_FINAL_ZIP_REHEARSAL_GATE.json';$cert=Join-Path $project 'work\PROJECT_PORTAL_REVIEW_ONLY\enrollment\ARGOS_PROJECT_PORTAL_LAPTOP_SIGNER_PUBLIC.cer';$verifier=Join-Path $project 'work\PROJECT_PORTAL_REVIEW_ONLY\scripts\Test-SignedPortalPackage.ps1'
function Sha([string]$Path){(Get-FileHash -LiteralPath $Path -Algorithm SHA256 -ErrorAction Stop).Hash}
function New-Json([string]$Path,[object]$Value){if(Test-Path -LiteralPath $Path){throw "Create-new path exists: $Path"};[IO.File]::WriteAllText($Path,(($Value|ConvertTo-Json -Depth 20)+[Environment]::NewLine),(New-Object Text.UTF8Encoding($false)))}
if(-not(Test-Path -LiteralPath $zip -PathType Leaf)-or(Sha $zip)-ne$zipHash){throw 'R30VAL1 final ZIP absent or changed.'};foreach($path in @($cert,$verifier)){if(-not(Test-Path -LiteralPath $path -PathType Leaf)){throw "R30VAL1 rehearsal dependency absent: $path"}};if(Test-Path -LiteralPath $extract){throw 'R30VAL1 rehearsal extraction root exists.'};if(Test-Path -LiteralPath $gate){throw 'R30VAL1 rehearsal gate exists.'}
if($Preflight){[ordered]@{schema='argos_o3b21_r30val1_final_zip_rehearsal_preflight_v1';state='PASS_R30VAL1_FINAL_ZIP_REHEARSAL_PREFLIGHT';requestId=$requestId;zipSha256=$zipHash;freshExtractionRoot=$extract;targetExecuted=$false;mutationsPerformed=$false}|ConvertTo-Json;return}
Add-Type -AssemblyName System.IO.Compression.FileSystem;[IO.Compression.ZipFile]::ExtractToDirectory($zip,$extract);$verified=& $verifier -PackagePath $extract -SignerCertificatePath $cert -ExpectedTargetRole 'JBOD' -ExpectedJobClass 'MAINTENANCE_PATCH';if([string]$verified.State-ne'PASS_SIGNED_PORTAL_PACKAGE'){throw 'R30VAL1 extracted signature verification failed.'}
$entry=Join-Path $extract 'payload\Invoke-R30VAL1.ps1';$leafText=& powershell.exe -NoProfile -ExecutionPolicy Bypass -File $entry -PackageLeafPreflight;if($LASTEXITCODE-ne0){throw 'R30VAL1 packaged entry preflight failed.'};$leaf=$leafText|ConvertFrom-Json;if([string]$leaf.state-ne'PASS_R30VAL1_EXACT_PACKAGED_LEAVES'){throw 'R30VAL1 packaged entry state changed.'}
$python=(Get-Command python -ErrorAction Stop).Source;$r28=& $python -B (Join-Path $extract 'payload\Test-BacksideNotchOpenCvR28.py');if($LASTEXITCODE-ne0-or[string]$r28-ne'PASS_R28_PACKAGED_SYNTHETIC_33_OF_33'){throw 'R30VAL1 packaged R28 tests failed.'};$r29=& $python -B (Join-Path $extract 'payload\Test-BacksideNotchOpenCvR29.py');if($LASTEXITCODE-ne0-or[string]$r29-ne'PASS_R29_PACKAGED_SYNTHETIC_13_OF_13'){throw 'R30VAL1 packaged R29 tests failed.'};$r30=& $python -B (Join-Path $extract 'payload\Test-BacksideNotchOpenCvR30.py');if($LASTEXITCODE-ne0-or[string]$r30-ne'PASS_R30_PACKAGED_SYNTHETIC_13_OF_13'){throw 'R30VAL1 packaged R30 tests failed.'}
$archive=[IO.Compression.ZipFile]::OpenRead($zip);try{$entryCount=$archive.Entries.Count}finally{$archive.Dispose()}
$value=[ordered]@{schema='argos_o3b21_r30val1_final_zip_rehearsal_gate_v1';createdUtc=[DateTime]::UtcNow.ToString('o');state='PASS_R30VAL1_FINAL_ZIP_WINDOWS_PS51_REHEARSAL';requestId=$requestId;zipPath=$zip;zipBytes=(Get-Item -LiteralPath $zip).Length;zipSha256=$zipHash;freshExtractionRoot=$extract;archiveEntryCount=$entryCount;signedPackageState=[string]$verified.State;signerThumbprint=[string]$verified.SignerThumbprint;packagedEntryState=[string]$leaf.state;packagedR28SyntheticTestState=[string]$r28;packagedR29SyntheticTestState=[string]$r29;packagedR30SyntheticTestState=[string]$r30;payloadFileCount=24;caseCount=70;syntheticTestCount=59;targetExecuted=$false;mutationsPerformed=$false;reviewOnly=$true;productionRoutingEnabled=$false};New-Json $gate $value;$value|ConvertTo-Json -Depth 10
