#Requires -Version 5.1
[CmdletBinding()]
param([Parameter(Mandatory=$true)][string]$InvocationManifest,[switch]$Preflight,[switch]$Stage)
$ErrorActionPreference='Stop';Set-StrictMode -Version Latest
if([bool]$Preflight -eq [bool]$Stage){throw 'Specify exactly one mode.'}
function A([bool]$v,[string]$m){if(-not$v){throw$m}}
function Get-O3B9Hash([string]$p){$s=[IO.File]::Open($p,[IO.FileMode]::Open,[IO.FileAccess]::Read,[IO.FileShare]::Read);$h=[Security.Cryptography.SHA256]::Create();try{([BitConverter]::ToString($h.ComputeHash($s))).Replace('-','')}finally{$h.Dispose();$s.Dispose()}}
function Copy-H([string]$s,[string]$d){$i=New-Object IO.FileStream($s,[IO.FileMode]::Open,[IO.FileAccess]::Read,[IO.FileShare]::Read,8388608,[IO.FileOptions]::SequentialScan);$o=New-Object IO.FileStream($d,[IO.FileMode]::CreateNew,[IO.FileAccess]::Write,[IO.FileShare]::None,8388608,[IO.FileOptions]::SequentialScan);$h=[Security.Cryptography.SHA256]::Create();$b=New-Object byte[] 8388608;$n=[int64]0;try{while(($r=$i.Read($b,0,$b.Length))-gt0){$o.Write($b,0,$r);[void]$h.TransformBlock($b,0,$r,$null,0);$n+=$r};[void]$h.TransformFinalBlock($b,0,0);$o.Flush($true);[pscustomobject]@{bytes=$n;sha256=([BitConverter]::ToString($h.Hash)).Replace('-','')}}finally{$h.Dispose();$o.Dispose();$i.Dispose()}}
$inv=Get-Content -LiteralPath ([IO.Path]::GetFullPath($InvocationManifest)) -Raw|ConvertFrom-Json
A([string]$inv.schema-eq'argos_ocv03_o3b9_approved_stage_invocation_v1')'O3B9 invocation schema changed.'
$src=[IO.Path]::GetFullPath([string]$inv.sourceRoot).TrimEnd('\');$dst=[IO.Path]::GetFullPath([string]$inv.outputRoot).TrimEnd('\');$partial=$dst+'.partial';$failed=$dst+'.failed'
A(-not$src.Equals($dst,[StringComparison]::OrdinalIgnoreCase)-and$src.Length+32-lt200-and$dst.Length+32-lt200)'O3B9 roots are unsafe.'
$rows=@($inv.sources);A($rows.Count-eq2)'O3B9 requires two sources.'
$seen=@{};foreach($row in $rows){$c=[string]$row.channel;$sn=[string]$row.sourceName;$on=[string]$row.outputName;A($c-in@('BF_BACKSIDE','DF_BACKSIDE')-and-not$seen.ContainsKey($c)-and$sn-match'^[A-Za-z0-9_-]{1,32}\.bmp$'-and$on-match'^[A-Za-z0-9_-]{1,32}\.bmp$'-and[string]$row.expectedSha256-match'^[A-F0-9]{64}$'-and[int64]$row.expectedBytes-gt0-and[int64]$row.expectedBytes-le1000000000)'O3B9 source contract changed.';$seen[$c]=$true}
if($Preflight){[ordered]@{schema='argos_ocv03_o3b9_approved_stage_preflight_v1';state='PASS_O3B9_APPROVED_STAGE_PREFLIGHT';sourceRoot=$src;outputRoot=$dst;sourceCount=2;mutationsPerformed=$false;imageBytesRead=$false;reviewOnly=$true;productionRoutingEnabled=$false}|ConvertTo-Json -Depth 5;return}
A([string]$env:COMPUTERNAME-eq[string]$inv.expectedComputerName)'O3B9 computer changed.';A(Test-Path -LiteralPath $src -PathType Container)'O3B9 source root absent.';foreach($p in @($dst,$partial,$failed)){A(-not(Test-Path -LiteralPath $p))"O3B9 create-new target exists: $p"}
[void](New-Item -ItemType Directory -Path $partial);$results=New-Object Collections.Generic.List[object]
try{foreach($row in $rows){$sp=Join-Path $src ([string]$row.sourceName);$dp=Join-Path $partial ([string]$row.outputName);$before=Get-Item -LiteralPath $sp -Force;A(-not$before.PSIsContainer-and[long]$before.Length-eq[int64]$row.expectedBytes)'O3B9 source length changed.';$beforeTime=$before.LastWriteTimeUtc.ToString('o');$copy=Copy-H $sp $dp;$after=Get-Item -LiteralPath $sp -Force;A($copy.bytes-eq[int64]$row.expectedBytes-and$copy.sha256-eq[string]$row.expectedSha256-and[long]$after.Length-eq[long]$before.Length-and$after.LastWriteTimeUtc.ToString('o')-eq$beforeTime)'O3B9 source/hash stability failed.';$outHash=Get-O3B9Hash $dp;A($outHash-eq$copy.sha256)'O3B9 output hash failed.';$results.Add([pscustomobject]@{channel=[string]$row.channel;sourceName=[string]$row.sourceName;sourceBytes=[long]$copy.bytes;sourceSha256=[string]$copy.sha256;sourceLastWriteTimeUtc=$beforeTime;outputName=[string]$row.outputName;outputBytes=[long](Get-Item -LiteralPath $dp).Length;outputSha256=$outHash;sourceStableDuringCopy=$true})}}catch{if(Test-Path -LiteralPath $partial){Move-Item -LiteralPath $partial -Destination $failed};throw}
$result=[ordered]@{schema='argos_ocv03_o3b9_approved_stage_result_v1';createdUtc=[DateTime]::UtcNow.ToString('o');state='PASS_O3B9_EXACT_PAIR_IN_APPROVED_DATA_ROOT';sourceRoot=$src;outputRoot=$dst;sources=$results.ToArray();sourceImageReadCount=2;imageDecoded=$false;pixelProcessingPerformed=$false;sourceMutationPerformed=$false;sourceDeletionPerformed=$false;taskOrExistingProcessActionPerformed=$false;providerActivated=$false;thresholdOrAlgorithmChanged=$false;holdsCleared=$false;reviewOnly=$true;productionRoutingEnabled=$false}
[IO.File]::WriteAllText((Join-Path $partial 'O3B9_RESULT.json'),(($result|ConvertTo-Json -Depth 8)+[Environment]::NewLine),(New-Object Text.UTF8Encoding($false)));Move-Item -LiteralPath $partial -Destination $dst;$result|ConvertTo-Json -Depth 8
