#Requires -Version 5.1
[CmdletBinding()]
param([switch]$Preflight,[switch]$Build)
$ErrorActionPreference='Stop';Set-StrictMode -Version Latest
if([bool]$Preflight-eq[bool]$Build){throw 'Specify exactly one of -Preflight or -Build.'}
$project=[IO.Path]::GetFullPath((Join-Path $PSScriptRoot '..\..'));$requestId='REQ_20260827T165500111Z_62629419D3R4'
$endpoint=Join-Path $PSScriptRoot 'Invoke-O3D3R4HotspotEndpoint.ps1';$core=Join-Path $project 'work\PATTERNED_FIDUCIAL_INVENTORY\tools\NativeFrontsideWaferPoseOpenCvV2.py';$r5=Join-Path $project 'work\PATTERNED_FIDUCIAL_INVENTORY\tools\NativeFrontsideWaferPoseOpenCvV2R5.py';$r6=Join-Path $project 'work\PATTERNED_FIDUCIAL_INVENTORY\tools\NativeFrontsideWaferPoseOpenCvV2R6.py';$job=Join-Path $PSScriptRoot 'O3D3R4_HOTSPOT_JOB.json';$definitionPath=Join-Path $PSScriptRoot 'MAINTENANCE_DEFINITION_R4.json'
$signedPartial=Join-Path $PSScriptRoot 'signed_r4.partial';$signedRoot=Join-Path $PSScriptRoot 'signed_r4';$readyRoot=Join-Path $signedRoot ($requestId+'.ready');$finalPartial=Join-Path $PSScriptRoot 'final_r4.partial';$finalRoot=Join-Path $PSScriptRoot 'final_r4';$zipName=$requestId+'.ready.zip';$zipPath=Join-Path $finalRoot $zipName;$gatePath=Join-Path $PSScriptRoot 'O3D3R4_FINAL_PACKAGE_GATE.json'
$identityPath=Join-Path $project 'work\PROJECT_PORTAL_REVIEW_ONLY\state\LAPTOP_SIGNING_IDENTITY.json';$publicCertificate=Join-Path $project 'work\PROJECT_PORTAL_REVIEW_ONLY\enrollment\ARGOS_PROJECT_PORTAL_LAPTOP_SIGNER_PUBLIC.cer';$packageTester=Join-Path $project 'work\PROJECT_PORTAL_REVIEW_ONLY\scripts\Test-SignedPortalPackage.ps1'
$endpointSha='588839399168B016AD619DEF1BEDF09F2434385BA2B28A5C68E9D63416641211';$coreSha='304219822CC3C7CC8E0ED81BD89E230529057E47E0E7DA4C95FE041F3AF69FAC';$r5Sha='47F70976D0F3AE0461166D7D3438FE7B11FFE71E8257FD918554F7909E0B9E24';$r6Sha='90839F14CEEED7C2DFC6E1601195F6927C4631E508F9EB859E77A93745D3FB30';$jobSha='F7DB6FE811D58DAA3F410C5AD8E4F063BBD6E961004BDAF1BF2470BB74392717';$definitionSha='1C6D05144B15591ED7206D89876316DF25DAD8149367680D61C900B5A549E0AA';$rehearsalSha='15882526314DE28312C183836E570B161B45D5BECD0A7C860D9AA9766BEC1F76'
function Assert-True([bool]$Condition,[string]$Message){if(-not$Condition){throw $Message}};function Get-Sha([string]$Path){(Get-FileHash -LiteralPath $Path -Algorithm SHA256).Hash};function Write-NewJson([string]$Path,[object]$Value,[int]$Depth=20){Assert-True (-not(Test-Path -LiteralPath $Path)) "Create-new package JSON exists: $Path";[IO.File]::WriteAllText($Path,(($Value|ConvertTo-Json -Depth $Depth)+[Environment]::NewLine),(New-Object Text.UTF8Encoding($false)))}
$pins=@([pscustomobject]@{p=$endpoint;s=$endpointSha},[pscustomobject]@{p=$core;s=$coreSha},[pscustomobject]@{p=$r5;s=$r5Sha},[pscustomobject]@{p=$r6;s=$r6Sha},[pscustomobject]@{p=$job;s=$jobSha},[pscustomobject]@{p=$definitionPath;s=$definitionSha},[pscustomobject]@{p=(Join-Path $PSScriptRoot 'O3D3R4_ENDPOINT_REHEARSAL_GATE.json');s=$rehearsalSha},[pscustomobject]@{p=(Join-Path $project 'work\FIDUCIAL_OPENCV_JBOD_INSTALL_FOI1\FOI1_TERMINAL_RESPONSE_GATE.json');s='E54585857204BDC2FE9A4632BAF3308987F195F91FFE00B9E98A0D78E56B169C'},[pscustomobject]@{p=(Join-Path $project 'work\OPENCV_PROVIDER_PLATFORM_V1\OCV01_PLATFORM_GATE.json');s='F0A6B44976C570FCE4CCAB28839AC4DEC702B51B9EEE87859738D1332DB11190'},[pscustomobject]@{p=(Join-Path $project 'work\JBOD_ENDPOINT_MAINTENANCE_PATH_C1E\C1E_QUEUE_SAFETY_PASS.json');s='170015C259C3EC8FC0B369F070748A555336F8FB312636819B7F99EBCE85A65D'},[pscustomobject]@{p=(Join-Path $project 'work\OPENCV_EDGE_NOTCH_O3C2\O3C2_EXACT_RESPONSE_COLLECTION_GATE.json');s='665C1DDDFD1E1FBDECED11C5C9F382D147E3AB1F7904BF191A5F9026E43063AD'})
foreach($pin in $pins){Assert-True (Test-Path -LiteralPath $pin.p -PathType Leaf) "Missing O3D3R4 build dependency: $($pin.p)";Assert-True ((Get-Sha $pin.p)-eq$pin.s) "Changed O3D3R4 build dependency: $($pin.p)"};foreach($tool in @($identityPath,$publicCertificate,$packageTester)){Assert-True (Test-Path -LiteralPath $tool -PathType Leaf) "Missing O3D3R4 build tool: $tool"}
foreach($path in @($signedPartial,$signedRoot,$finalPartial,$finalRoot,$gatePath)){Assert-True (-not(Test-Path -LiteralPath $path)) "O3D3R4 build output exists: $path"}
$definition=Get-Content -LiteralPath $definitionPath -Raw|ConvertFrom-Json;Assert-True ([string]$definition.entryPoint-eq'payload/Invoke-O3D3R4HotspotEndpoint.ps1'-and[string]$definition.rehearsal.requiredState-eq'PASS_O3D3R4_HOTSPOT_EDGE_NOTCH_EXECUTED'-and[int]$definition.timeoutContract.endpointWorkerOuterTimeoutSeconds-eq900-and[int]$definition.timeoutContract.opencvChildTimeoutSeconds-eq780) 'O3D3R4 definition contract changed.'
$files=@([ordered]@{source=$endpoint;path='payload/Invoke-O3D3R4HotspotEndpoint.ps1';bytes=[int64](Get-Item $endpoint).Length;sha256=$endpointSha},[ordered]@{source=$core;path='payload/NativeFrontsideWaferPoseOpenCvV2.py';bytes=[int64](Get-Item $core).Length;sha256=$coreSha},[ordered]@{source=$r5;path='payload/NativeFrontsideWaferPoseOpenCvV2R5.py';bytes=[int64](Get-Item $r5).Length;sha256=$r5Sha},[ordered]@{source=$r6;path='payload/NativeFrontsideWaferPoseOpenCvV2R6.py';bytes=[int64](Get-Item $r6).Length;sha256=$r6Sha},[ordered]@{source=$job;path='payload/O3D3R4_HOTSPOT_JOB.json';bytes=[int64](Get-Item $job).Length;sha256=$jobSha})
$identity=Get-Content -LiteralPath $identityPath -Raw|ConvertFrom-Json;$thumbprint=([string]$identity.thumbprint).Replace(' ','').ToUpperInvariant();$store=New-Object Security.Cryptography.X509Certificates.X509Store('My',[Security.Cryptography.X509Certificates.StoreLocation]::CurrentUser);$store.Open([Security.Cryptography.X509Certificates.OpenFlags]::ReadOnly);try{$matches=@($store.Certificates|Where-Object{([string]$_.Thumbprint).Replace(' ','').ToUpperInvariant()-eq$thumbprint});Assert-True ($matches.Count-eq1) 'O3D3R4 signer cardinality changed.';$certificate=$matches[0]}finally{$store.Close();$store.Dispose()};Assert-True $certificate.HasPrivateKey 'O3D3R4 signer private key unavailable.'
if($Preflight){[ordered]@{schema='argos_o3d3r4_build_preflight_v1';createdUtc=[DateTime]::UtcNow.ToString('o');state='PASS_O3D3R4_BUILD_PREFLIGHT';requestId=$requestId;payloadFileCount=5;endpointSha256=$endpointSha;jobSha256=$jobSha;definitionSha256=$definitionSha;rehearsalGateSha256=$rehearsalSha;signerThumbprint=$thumbprint;mutationsPerformed=$false;targetExecuted=$false;reviewOnly=$true;productionRoutingEnabled=$false}|ConvertTo-Json -Depth 8;return}
$created=[DateTimeOffset]::UtcNow;$manifest=[ordered]@{schema='argos_project_portal_request_manifest_v1';requestId=$requestId;createdUtc=$created.ToString('o');expiresUtc=$created.AddHours(24).ToString('o');targetRole='JBOD';jobClass='MAINTENANCE_PATCH';handler='';maxResultBytes=[int64]$definition.maxResultBytes;reviewOnly=$true;trainingEligible=$false;xmlEligible=$false;productionEligible=$false;productionRoutingEnabled=$false;credentialsIncluded=$false;signerThumbprint=$thumbprint;signatureAlgorithm='RSA-SHA256-PKCS1';files=@($files|ForEach-Object{[ordered]@{path=$_.path;bytes=$_.bytes;sha256=$_.sha256}});entryPoint=[string]$definition.entryPoint;changes=@($definition.changes);entryPointMutations=@($definition.entryPointMutations);entryPointOutputs=@($definition.entryPointOutputs);sourceProcessingContract=$definition.sourceProcessingContract;timeoutContract=$definition.timeoutContract;allowedTaskActions=@($definition.allowedTaskActions);allowedProcessActions=@($definition.allowedProcessActions);rehearsal=$definition.rehearsal}
$partialReady=Join-Path $signedPartial ($requestId+'.ready');[void](New-Item -ItemType Directory -Path (Join-Path $partialReady 'payload'));foreach($file in $files){Copy-Item -LiteralPath $file.source -Destination (Join-Path $partialReady $file.path.Replace('/','\')) -ErrorAction Stop};$manifestPath=Join-Path $partialReady 'PORTAL_REQUEST_MANIFEST.json';$signaturePath=Join-Path $partialReady 'PORTAL_REQUEST_MANIFEST.sig';$utf8=New-Object Text.UTF8Encoding($false);$manifestBytes=$utf8.GetBytes(($manifest|ConvertTo-Json -Depth 32));[IO.File]::WriteAllBytes($manifestPath,$manifestBytes);$rsa=[Security.Cryptography.X509Certificates.RSACertificateExtensions]::GetRSAPrivateKey($certificate);try{$signature=$rsa.SignData($manifestBytes,[Security.Cryptography.HashAlgorithmName]::SHA256,[Security.Cryptography.RSASignaturePadding]::Pkcs1)}finally{$rsa.Dispose()};[IO.File]::WriteAllBytes($signaturePath,$signature);[void](New-Item -ItemType Directory -Path $signedRoot);Move-Item -LiteralPath $partialReady -Destination $readyRoot;Remove-Item -LiteralPath $signedPartial -Force
$test=& $packageTester -PackagePath $readyRoot -SignerCertificatePath $publicCertificate -ExpectedTargetRole JBOD -ExpectedJobClass MAINTENANCE_PATCH;Assert-True ([string]$test.State-eq'PASS_SIGNED_PORTAL_PACKAGE') 'O3D3R4 signed package verification failed.'
Add-Type -AssemblyName System.IO.Compression.FileSystem;[void](New-Item -ItemType Directory -Path $finalPartial);$partialZip=Join-Path $finalPartial $zipName;$extract=Join-Path $finalPartial 'extract';[IO.Compression.ZipFile]::CreateFromDirectory($readyRoot,$partialZip,[IO.Compression.CompressionLevel]::Optimal,$false);[IO.Compression.ZipFile]::ExtractToDirectory($partialZip,$extract);$expected=@{};foreach($file in $files){$expected[$file.path]=$file.sha256};$expected['PORTAL_REQUEST_MANIFEST.json']=Get-Sha (Join-Path $readyRoot 'PORTAL_REQUEST_MANIFEST.json');$expected['PORTAL_REQUEST_MANIFEST.sig']=Get-Sha (Join-Path $readyRoot 'PORTAL_REQUEST_MANIFEST.sig');$leaves=@(Get-ChildItem -LiteralPath $extract -Recurse -File);Assert-True ($leaves.Count-eq7) 'O3D3R4 ZIP file count changed.';foreach($item in $expected.GetEnumerator()){$path=Join-Path $extract $item.Key.Replace('/','\');Assert-True (Test-Path -LiteralPath $path -PathType Leaf) "O3D3R4 ZIP leaf absent: $($item.Key)";Assert-True ((Get-Sha $path)-eq[string]$item.Value) "O3D3R4 ZIP leaf changed: $($item.Key)"}
$zipSha=Get-Sha $partialZip;$gate=[ordered]@{schema='argos_o3d3r4_final_package_gate_v1';createdUtc=[DateTime]::UtcNow.ToString('o');state='PASS_O3D3R4_FINAL_PACKAGE_GATE';requestId=$requestId;requestZip=('work/OPENCV_EDGE_NOTCH_O3D3/final_r4/'+$zipName);requestZipBytes=[int64](Get-Item $partialZip).Length;requestZipSha256=$zipSha;requestManifestSha256=$expected['PORTAL_REQUEST_MANIFEST.json'];requestSignatureSha256=$expected['PORTAL_REQUEST_MANIFEST.sig'];payloadFileCount=5;endpointSha256=$endpointSha;coreSha256=$coreSha;r5Sha256=$r5Sha;r6Sha256=$r6Sha;jobSha256=$jobSha;maintenanceDefinitionSha256=$definitionSha;rehearsalGateSha256=$rehearsalSha;exactFinalZipExtractionPassed=$true;exactFinalZipPayloadHashesPassed=$true;exactPackageSignaturePassed=$true;matchingSignedTerminalResponseRequired=$true;requestRetryAuthorized=$false;knownNotchLocationConsumed=$false;notchAnglePriorConsumed=$false;fixedAngularSearchWindowConsumed=$false;regressionLabelsConsumed=$false;providerActivated=$false;reviewOnly=$true;trainingEligible=$false;xmlEligible=$false;productionEligible=$false;productionRoutingEnabled=$false;publicationAuthorized=$false};Write-NewJson $gatePath $gate 12;Move-Item -LiteralPath $finalPartial -Destination $finalRoot;$gate|ConvertTo-Json -Depth 12
