#Requires -Version 5.1
[CmdletBinding()]
param([switch]$Preflight,[switch]$Publish)
$ErrorActionPreference='Stop';Set-StrictMode -Version Latest
if([bool]$Preflight-eq[bool]$Publish){throw 'Specify exactly one of -Preflight or -Publish.'}
$project=[IO.Path]::GetFullPath((Join-Path $PSScriptRoot '..\..'));$requestId='REQ_20260827T165500111Z_62629419D3R4';$zip=Join-Path $PSScriptRoot ('final_r4\'+$requestId+'.ready.zip');$zipSha='C023B2AA688BDAA70C2CE9104D939592CEDE53FFAF11DF26960C248757483BC3';$share='U:\ProjectPortalRO\requests';$destination=Join-Path $share ($requestId+'.ready.zip');$upload=$destination+'.upload';$processed=Join-Path $share ('processed\'+$requestId+'.ready.zip');$gatePath=Join-Path $PSScriptRoot 'O3D3R4_PUBLISH_GATE.json'
function Assert-True([bool]$Condition,[string]$Message){if(-not$Condition){throw $Message}};function Get-Sha([string]$Path){(Get-FileHash -LiteralPath $Path -Algorithm SHA256).Hash};function Write-NewJson([string]$Path,[object]$Value){Assert-True (-not(Test-Path -LiteralPath $Path)) "O3D3R4 publisher gate exists: $Path";[IO.File]::WriteAllText($Path,(($Value|ConvertTo-Json -Depth 10)+[Environment]::NewLine),(New-Object Text.UTF8Encoding($false)))}
$pins=@([pscustomobject]@{p=$zip;s=$zipSha},[pscustomobject]@{p=(Join-Path $PSScriptRoot 'O3D3R4_FINAL_PACKAGE_GATE.json');s='77DB0A71579A6FE2961CD55864BE75337FCE9518FAB9EF584CB19779073566C9'},[pscustomobject]@{p=(Join-Path $PSScriptRoot 'O3D3R4_EXACT_PACKAGE_REHEARSAL_GATE.json');s='3158778E53A16C2B224E57983A9417E5747C6BB7B2278DFBC9D447E201C3D25E'},[pscustomobject]@{p=(Join-Path $PSScriptRoot 'O3D3R4_ENDPOINT_REHEARSAL_GATE.json');s='15882526314DE28312C183836E570B161B45D5BECD0A7C860D9AA9766BEC1F76'},[pscustomobject]@{p=(Join-Path $project 'work\OPENCV_EDGE_NOTCH_O3C2\O3C2_EXACT_RESPONSE_COLLECTION_GATE.json');s='665C1DDDFD1E1FBDECED11C5C9F382D147E3AB1F7904BF191A5F9026E43063AD'})
foreach($pin in $pins){Assert-True (Test-Path -LiteralPath $pin.p -PathType Leaf) "O3D3R4 publisher dependency absent: $($pin.p)";Assert-True ((Get-Sha $pin.p)-eq$pin.s) "O3D3R4 publisher dependency changed: $($pin.p)"};Assert-True (Test-Path -LiteralPath $share -PathType Container) 'Persistent U: request share absent.';Assert-True (-not(Test-Path -LiteralPath $destination)-and-not(Test-Path -LiteralPath $upload)-and-not(Test-Path -LiteralPath $processed)-and-not(Test-Path -LiteralPath $gatePath)) 'O3D3R4 request or publisher artifact already exists; retry is prohibited.'
$branch=(git -C $project branch --show-current|Out-String).Trim();Assert-True ($branch-eq'codex/fiducial-opencv-d-drive') 'O3D3R4 publisher branch changed.';$status=(git -C $project status --porcelain|Out-String).Trim();Assert-True ([string]::IsNullOrWhiteSpace($status)) 'O3D3R4 publisher requires a clean worktree.';$local=(git -C $project rev-parse HEAD|Out-String).Trim();$remote=(git -C $project rev-parse origin/codex/fiducial-opencv-d-drive|Out-String).Trim();Assert-True ($local-eq$remote) 'O3D3R4 local/remote tips differ.'
if($Preflight){[ordered]@{schema='argos_o3d3r4_publish_preflight_v1';createdUtc=[DateTime]::UtcNow.ToString('o');state='PASS_O3D3R4_PUBLISH_PREFLIGHT';requestId=$requestId;requestZipSha256=$zipSha;branch=$branch;commit=$local;share=$share;destination=$destination;requestRetryAuthorized=$false;mutationsPerformed=$false;gatewayAcceptanceIsExecutionEvidence=$false;reviewOnly=$true;productionRoutingEnabled=$false}|ConvertTo-Json -Depth 8;return}
$sourceStream=[IO.File]::Open($zip,[IO.FileMode]::Open,[IO.FileAccess]::Read,[IO.FileShare]::Read);try{$targetStream=[IO.File]::Open($upload,[IO.FileMode]::CreateNew,[IO.FileAccess]::Write,[IO.FileShare]::None);try{$sourceStream.CopyTo($targetStream);$targetStream.Flush()}finally{$targetStream.Dispose()}}finally{$sourceStream.Dispose()};Assert-True ((Get-Sha $upload)-eq$zipSha) 'O3D3R4 upload copy changed.';[IO.File]::Move($upload,$destination);Assert-True ((Get-Sha $destination)-eq$zipSha) 'O3D3R4 published ZIP changed.'
$gate=[ordered]@{schema='argos_o3d3r4_publish_gate_v1';createdUtc=[DateTime]::UtcNow.ToString('o');state='PASS_O3D3R4_PUBLISHED_ONCE';requestId=$requestId;requestZipSha256=$zipSha;destination=$destination;destinationSha256=Get-Sha $destination;branch=$branch;commit=$local;publicationCount=1;requestRetryAuthorized=$false;matchingSignedTerminalResponseRequired=$true;gatewayAcceptanceIsExecutionEvidence=$false;providerActivated=$false;reviewOnly=$true;productionRoutingEnabled=$false};Write-NewJson $gatePath $gate;$gate|ConvertTo-Json -Depth 10
