[CmdletBinding()]
param([switch]$Preflight,[switch]$Apply)
$ErrorActionPreference='Stop';Set-StrictMode -Version Latest
if(([bool]$Preflight)-eq([bool]$Apply)){throw 'Specify exactly one of -Preflight or -Apply.'}
$project='C:\Users\joshua.conn\Desktop\ArgosDev\ArgosEdgeLab';$root=Join-Path $project 'work\R7';$requestId='REQ_R7_0821_1605_X1'
$definitionPath=Join-Path $root 'pkg\MAINTENANCE_DEFINITION.json';$payloadRoot=Join-Path $root 'pkg\payload';$outputRoot=Join-Path $root 'signed_short'
$identityPath=Join-Path $project 'work\PROJECT_PORTAL_REVIEW_ONLY\state\LAPTOP_SIGNING_IDENTITY.json';$pathTool=Join-Path $project 'utilities\Confirm-ArgosPathBudget.ps1'
foreach($path in @($definitionPath,$payloadRoot,$identityPath,$pathTool)){if(-not(Test-Path -LiteralPath $path)){throw "F2 signing input missing: $path"}}
$definition=Get-Content -LiteralPath $definitionPath -Raw|ConvertFrom-Json
if([string]$definition.targetRole-ne'JBOD'-or[string]$definition.jobClass-ne'MAINTENANCE_PATCH'-or@($definition.changes).Count-ne1-or@($definition.allowedTaskActions).Count-ne0){throw 'R7 maintenance definition contract refused.'}
$payloadFiles=@(Get-ChildItem -LiteralPath $payloadRoot -File|Sort-Object Name|ForEach-Object{[pscustomobject]@{source=$_.FullName;path=('payload/'+$_.Name);bytes=[int64]$_.Length;sha256=(Get-FileHash -LiteralPath $_.FullName -Algorithm SHA256).Hash}})
if($payloadFiles.Count-ne1-or[string]$payloadFiles[0].path-ne'payload/R7.ps1'){throw 'R7 payload set changed.'}
$entry=$payloadFiles[0];$entryChange=@($definition.changes|Where-Object{$_.source-eq'payload/R7.ps1'})[0]
if([string]$definition.entryPoint-ne'payload/R7.ps1'-or[string]$entryChange.installedSha256-ne[string]$entry.sha256-or-not[bool]$entryChange.allowCreate-or@($entryChange.approvedPredecessorSha256).Count-ne1-or[string]$entryChange.approvedPredecessorSha256[0]-ne[string]$entry.sha256-or[string]$definition.rehearsal.requiredState-ne'PASS_R7_EXACT_PROCESSED_RESPONSE_REIMPORTED'){throw 'R7 entrypoint contract changed.'}
$identity=Get-Content -LiteralPath $identityPath -Raw|ConvertFrom-Json;$thumbprint=([string]$identity.thumbprint).Replace(' ','').ToUpperInvariant();$certificate=Get-Item -LiteralPath ("Cert:\CurrentUser\My\$thumbprint") -ErrorAction Stop;if(-not$certificate.HasPrivateKey){throw 'Portal signer private key is unavailable.'}
$ready=Join-Path $outputRoot ($requestId+'.ready');$partial=Join-Path $outputRoot ($requestId+'.partial');foreach($path in @($ready,$partial)){if(Test-Path -LiteralPath $path){throw "Refusing existing F2 request path: $path"}}
$planned=@((Join-Path $partial 'PORTAL_REQUEST_MANIFEST.json'),(Join-Path $partial 'PORTAL_REQUEST_MANIFEST.sig'),(Join-Path $ready 'PORTAL_REQUEST_MANIFEST.json'),(Join-Path $ready 'PORTAL_REQUEST_MANIFEST.sig'))+@($payloadFiles|ForEach-Object{Join-Path $partial ([string]$_.path).Replace('/','\')})+@($payloadFiles|ForEach-Object{Join-Path $ready ([string]$_.path).Replace('/','\')})
$pathGate=&$pathTool -CandidatePath $planned -ReservedSuffixCharacters 32 -AsJson|ConvertFrom-Json;if([string]$pathGate.state-ne'PASS_PATH_BUDGET'){throw 'F2 signing path gate failed.'}
if($Preflight){[ordered]@{schema='argos_r7_signing_preflight_v1';createdUtc=[DateTime]::UtcNow.ToString('o');state='PASS_R7_SIGNING_PREFLIGHT';requestId=$requestId;entrypointSha256=[string]$entry.sha256;payloadFileCount=$payloadFiles.Count;mutationsPerformed=$false;reviewOnly=$true;productionRoutingEnabled=$false}|ConvertTo-Json -Depth 5;return}
$created=[DateTimeOffset]::UtcNow;$manifest=[ordered]@{schema='argos_project_portal_request_manifest_v1';requestId=$requestId;createdUtc=$created.ToString('o');expiresUtc=$created.AddHours(24).ToString('o');targetRole='JBOD';jobClass='MAINTENANCE_PATCH';handler='';maxResultBytes=[int64]$definition.maxResultBytes;reviewOnly=$true;trainingEligible=$false;xmlEligible=$false;productionEligible=$false;productionRoutingEnabled=$false;credentialsIncluded=$false;signerThumbprint=$thumbprint;signatureAlgorithm='RSA-SHA256-PKCS1';files=@($payloadFiles|ForEach-Object{[ordered]@{path=$_.path;bytes=$_.bytes;sha256=$_.sha256}});entryPoint=[string]$definition.entryPoint;changes=@($definition.changes);allowedTaskActions=@($definition.allowedTaskActions);rehearsal=$definition.rehearsal}
[void](New-Item -ItemType Directory -Path (Join-Path $partial 'payload') -Force);foreach($row in $payloadFiles){Copy-Item -LiteralPath $row.source -Destination (Join-Path $partial ([string]$row.path).Replace('/','\'))}
$bytes=(New-Object Text.UTF8Encoding($false)).GetBytes(($manifest|ConvertTo-Json -Depth 32));[IO.File]::WriteAllBytes((Join-Path $partial 'PORTAL_REQUEST_MANIFEST.json'),$bytes);$rsa=[Security.Cryptography.X509Certificates.RSACertificateExtensions]::GetRSAPrivateKey($certificate);try{$signature=$rsa.SignData($bytes,[Security.Cryptography.HashAlgorithmName]::SHA256,[Security.Cryptography.RSASignaturePadding]::Pkcs1)}finally{$rsa.Dispose()};[IO.File]::WriteAllBytes((Join-Path $partial 'PORTAL_REQUEST_MANIFEST.sig'),$signature);Move-Item -LiteralPath $partial -Destination $ready
[ordered]@{schema='argos_r7_signing_result_v1';createdUtc=[DateTime]::UtcNow.ToString('o');state='PASS_R7_SIGNED_REQUEST';requestId=$requestId;packagePath=$ready;manifestSha256=(Get-FileHash -LiteralPath (Join-Path $ready 'PORTAL_REQUEST_MANIFEST.json') -Algorithm SHA256).Hash;signatureSha256=(Get-FileHash -LiteralPath (Join-Path $ready 'PORTAL_REQUEST_MANIFEST.sig') -Algorithm SHA256).Hash;entrypointSha256=[string]$entry.sha256;reviewOnly=$true;productionRoutingEnabled=$false}|ConvertTo-Json -Depth 5
