[CmdletBinding()]
param([switch]$Preflight,[switch]$Apply,[string]$InvocationManifest)
$ErrorActionPreference='Stop';Set-StrictMode -Version Latest;if(([bool]$Preflight)-eq([bool]$Apply)){throw 'Specify exactly one of -Preflight or -Apply.'}
$project='C:\Users\joshua.conn\Desktop\ArgosDev\ArgosEdgeLab';$root=Join-Path $project 'work\R7';$requestId='REQ_R7_0821_1605_X1';$source=Join-Path $root 'final\REQ_R7_0821_1605_X1.ready.zip';$finalGatePath=$source+'.gate.json';$priorTerminalPath=Join-Path $project 'work\R6\R6_TERMINAL_RESPONSE_GATE.json'
$pathTool=Join-Path $project 'utilities\Confirm-ArgosPathBudget.ps1';$preactionTool=Join-Path $project 'utilities\Confirm-ArgosZeroRecurrencePreaction.ps1';$audit=Join-Path $project 'work\ARGOS_HISTORY_NO_REPEAT_AUDIT_20260820.json';$share='\\shm-cifs\Department\DE-1302_FAB_BE_Engineering\60_Saw_VI_Sort\600_General\Joshua.conn\AVI_Images\Argos\Uploads\InspectionRevs';$queueRoot=Join-Path $share 'ProjectPortalRO\requests';$readyRoot='U:\ProjectPortalRO\requests';$archiveRoot=Join-Path $root 'published';$publishGate=Join-Path $root 'R7_PUBLISH_GATE_JBOD.json';$preactionPath=Join-Path $root 'PREACTION_PUBLISH_JBOD.json';$isRehearsal=$false
if(-not[string]::IsNullOrWhiteSpace($InvocationManifest)){if(-not(Test-Path -LiteralPath $InvocationManifest -PathType Leaf)){throw 'F2 rehearsal manifest missing.'};$rm=Get-Content -LiteralPath $InvocationManifest -Raw|ConvertFrom-Json;if([string]$rm.schema-ne'argos_r7_publish_rehearsal_v1'-or-not[bool]$rm.rehearsal){throw 'F2 rehearsal manifest changed.'};$queueRoot=[IO.Path]::GetFullPath([string]$rm.queueRoot);$readyRoot=$queueRoot;$archiveRoot=[IO.Path]::GetFullPath([string]$rm.archiveRoot);$publishGate=[IO.Path]::GetFullPath([string]$rm.publishGate);$preactionPath=[IO.Path]::GetFullPath([string]$rm.preactionPath);foreach($p in @($queueRoot,$archiveRoot,$publishGate,$preactionPath)){if(-not$p.StartsWith('C:\R7P\',[StringComparison]::OrdinalIgnoreCase)-and-not$p.StartsWith($root.TrimEnd('\')+'\',[StringComparison]::OrdinalIgnoreCase)){throw "F2 rehearsal path escaped: $p"}};$isRehearsal=$true}
$readyName=$requestId+'.ready.zip';$uploadName=$readyName+'.upload';$ready=$readyRoot.TrimEnd('\')+'\'+$readyName;$upload=$readyRoot.TrimEnd('\')+'\'+$uploadName;$archive=Join-Path $archiveRoot $readyName;$processed=if($isRehearsal){Join-Path (Join-Path $queueRoot 'processed') $readyName}else{'I:\ProjectPortalRO\requests\processed\'+$readyName}
function Sha([string]$Path){return (Get-FileHash -LiteralPath $Path -Algorithm SHA256).Hash}
function Queue-State([string]$Root,[int64]$Bytes,[string]$Hash){$items=@(Get-ChildItem -LiteralPath $Root -File -ErrorAction Stop|Where-Object{$_.Name-match'\.ready\.zip(\.upload)?$'});if($items.Count-eq0){return [pscustomobject]@{state='NEW';foreign=0}};if($items.Count-ne1-or@($readyName,$uploadName)-notcontains[string]$items[0].Name){throw ('Foreign or ambiguous portal request queue: '+(($items|Select-Object -First 5|ForEach-Object{$_.Name})-join', '))};if([int64]$items[0].Length-ne$Bytes-or(Sha $items[0].FullName)-ne$Hash){throw 'Own-name F2 queue artifact changed.'};return [pscustomobject]@{state=if([string]$items[0].Name-eq$uploadName){'EXACT_UPLOAD'}else{'EXACT_READY'};foreign=0}}
foreach($path in @($source,$finalGatePath,$preactionPath,$priorTerminalPath,$pathTool,$preactionTool,$audit)){if(-not(Test-Path -LiteralPath $path -PathType Leaf)){throw "F2 publish input missing: $path"}};if(-not(Test-Path -LiteralPath $queueRoot -PathType Container)){throw 'F2 request queue unavailable.'};if(Test-Path -LiteralPath $processed){throw "F2 transport token already exists in processed archive: $processed"};if(Test-Path -LiteralPath $publishGate){throw "Fresh F2 publish gate required: $publishGate"};if(Test-Path -LiteralPath $archive){throw "Fresh F2 publication archive required: $archive"}
&$preactionTool -AuditPath $audit -ContractPath $preactionPath -ProjectRoot $project|Out-Null;$finalGate=Get-Content -Raw -LiteralPath $finalGatePath|ConvertFrom-Json;$requestSha=Sha $source;$requestBytes=[int64](Get-Item -LiteralPath $source).Length
if([string]$finalGate.state-ne'PASS_R7_EXACT_PACKAGE_READY_FOR_ONE_TIME_JBOD_PUBLICATION'-or[string]$finalGate.requestId-ne$requestId-or[string]$finalGate.zipSha256-ne$requestSha-or[int64]$finalGate.zipBytes-ne$requestBytes-or-not[bool]$finalGate.publicationAuthorized-or[bool]$finalGate.taskRestartImplemented-or-not[bool]$finalGate.signatureVerified-or-not[bool]$finalGate.reviewOnly-or[bool]$finalGate.productionRoutingEnabled){throw 'R7 final publication contract changed.'}
$priorTerminal=Get-Content -Raw -LiteralPath $priorTerminalPath|ConvertFrom-Json;if([string]$priorTerminal.requestId-ne'REQ_R6_0821_1600_X1'-or[string]$priorTerminal.state-ne'FAIL_R6_SIGNED_TERMINAL_RESPONSE'-or[string]$priorTerminal.endpointState-ne'FAILED'-or-not[bool]$priorTerminal.terminal-or-not[bool]$priorTerminal.signatureVerified){throw 'R7 predecessor is not the exact signed terminal R6 optional-property failure response.'}
$queue=Queue-State $queueRoot $requestBytes $requestSha;$pathCandidates=@($source,$upload,$ready,$processed,$archive,$publishGate);if($pathCandidates.Count-ne6){throw 'F2 publish path candidate boundary failed.'};$pathGate=&$pathTool -CandidatePath $pathCandidates -ReservedSuffixCharacters 32 -AsJson|ConvertFrom-Json;if([string]$pathGate.state-ne'PASS_PATH_BUDGET'){throw 'F2 publish path gate failed.'};$existing=if($isRehearsal){$null}else{Get-PSDrive U -ErrorAction SilentlyContinue};if(-not$isRehearsal-and$null-ne$existing-and-not([IO.Path]::GetFullPath([string]$existing.Root).TrimEnd('\')).Equals([IO.Path]::GetFullPath($share).TrimEnd('\'),[StringComparison]::OrdinalIgnoreCase)){throw 'Existing U: mapping is not pinned.'}
if($Preflight){[ordered]@{schema='argos_f3_publish_preflight_v1';createdUtc=[DateTime]::UtcNow.ToString('o');state='PASS_R7_PUBLISH_PREFLIGHT';requestId=$requestId;sourceSha256=$requestSha;sourceBytes=$requestBytes;priorTerminalRequestId=[string]$priorTerminal.requestId;priorTerminalResponseId=[string]$priorTerminal.responseId;exactResumeState=[string]$queue.state;pathState=[string]$pathGate.state;processedArchiveCollisionChecked=$true;rehearsal=$isRehearsal;mutationsPerformed=$false;reviewOnly=$true;productionRoutingEnabled=$false}|ConvertTo-Json -Depth 6;return}
if(-not$isRehearsal-and$null-eq$existing){New-PSDrive -Name U -PSProvider FileSystem -Root $share -Scope Script -ErrorAction Stop|Out-Null};[void](New-Item -ItemType Directory -Path $archiveRoot -Force);$appliedState=[string]$queue.state;if($queue.state-eq'NEW'){Copy-Item -LiteralPath $source -Destination $upload -ErrorAction Stop;if([int64](Get-Item -LiteralPath $upload).Length-ne$requestBytes-or(Sha $upload)-ne$requestSha){throw 'F2 uploaded bytes changed.'};Move-Item -LiteralPath $upload -Destination $ready -ErrorAction Stop;$appliedState='CREATED_READY'}elseif($queue.state-eq'EXACT_UPLOAD'){Move-Item -LiteralPath $upload -Destination $ready -ErrorAction Stop;$appliedState='RESUMED_UPLOAD_TO_READY'}
if(-not(Test-Path -LiteralPath $ready -PathType Leaf)-or[int64](Get-Item -LiteralPath $ready).Length-ne$requestBytes-or(Sha $ready)-ne$requestSha){throw 'F2 published ready artifact changed.'};Copy-Item -LiteralPath $source -Destination $archive -ErrorAction Stop;if((Sha $archive)-ne$requestSha){throw 'F2 publication archive changed.'};$result=[ordered]@{schema='argos_f3_publish_gate_v1';createdUtc=[DateTime]::UtcNow.ToString('o');state=if($isRehearsal){'PASS_R7_EXACT_PUBLISHER_CREATE_NEW_REHEARSAL'}else{'PASS_R7_EXACT_SIGNED_REQUEST_PUBLISHED_CREATE_NEW'};requestId=$requestId;sourceSha256=$requestSha;sourceBytes=$requestBytes;sharedPath=$ready;archivePath=$archive;applyState=$appliedState;pendingRequestsAtApply=0;overwritePerformed=$false;processedArchiveCollisionChecked=$true;rehearsal=$isRehearsal;priorTerminalRequestId=[string]$priorTerminal.requestId;priorTerminalResponseId=[string]$priorTerminal.responseId;reviewOnly=$true;productionRoutingEnabled=$false};[IO.File]::WriteAllText($publishGate,(($result|ConvertTo-Json -Depth 7)+[Environment]::NewLine),(New-Object Text.UTF8Encoding($false)));$result|ConvertTo-Json -Depth 7
