#Requires -Version 5.1
[CmdletBinding()]
param([Parameter(Mandatory=$true)][string]$InvocationManifest,[switch]$Preflight,[switch]$Collect)
$ErrorActionPreference='Stop';Set-StrictMode -Version Latest
if(([bool]$Preflight)-eq([bool]$Collect)){throw 'Specify exactly one of -Preflight or -Collect.'}
function Assert-O3F14([bool]$Condition,[string]$Message){if(-not$Condition){throw $Message}}
function Get-O3F14Hash([string]$Path){return (Get-FileHash -LiteralPath $Path -Algorithm SHA256).Hash}
function Get-O3F14BytesHash([byte[]]$Bytes){$sha=[Security.Cryptography.SHA256]::Create();try{return ([BitConverter]::ToString($sha.ComputeHash($Bytes))).Replace('-','')}finally{$sha.Dispose()}}
function Write-O3F14Bytes([Parameter(Mandatory=$true)][AllowEmptyCollection()][byte[]]$Bytes){$PSCmdlet.WriteObject($Bytes,$false)}
function Read-O3F14Entry([IO.Compression.ZipArchive]$Archive,[string]$Name,[int64]$MaximumBytes){$entry=$Archive.GetEntry($Name);Assert-O3F14 ($null-ne$entry-and$entry.Length-le$MaximumBytes) "O3F14 response entry absent or oversized: $Name";$stream=$entry.Open();$memory=New-Object IO.MemoryStream;try{$stream.CopyTo($memory);Write-O3F14Bytes -Bytes ([byte[]]$memory.ToArray())}finally{$stream.Dispose();$memory.Dispose()}}
function Write-O3F14Json([string]$Path,[object]$Value){Assert-O3F14 (-not(Test-Path -LiteralPath $Path)) "O3F14 collection gate exists: $Path";[IO.File]::WriteAllText($Path,(($Value|ConvertTo-Json -Depth 16)+[Environment]::NewLine),(New-Object Text.UTF8Encoding($false)))}
$expectedRunnerSha256='CAAFD1AC8C19E33D95BA8283963A4D0ED0189FF566C9923822BF3EC37956171E'
$expectedAliasPlanSha256='2ACA89A702CCC9E8B346EF2E31EF3C34382DF59D23D9DF3E5B431A4E37AD7D9C'
$expectedSubstSha256='158598ED3D590937C964B43DD91546FFCABAB5636B6CE619B4FFC43224013BB6'
$project=[IO.Path]::GetFullPath((Join-Path $PSScriptRoot '..\..'));$invocationPath=[IO.Path]::GetFullPath($InvocationManifest);$expected=Join-Path $PSScriptRoot 'O3F14_RESPONSE_COLLECTION_INVOCATION.json';Assert-O3F14 ($invocationPath.Equals($expected,[StringComparison]::OrdinalIgnoreCase)) 'O3F14 collection invocation path changed.'
$invoke=Get-Content -LiteralPath $invocationPath -Raw|ConvertFrom-Json;Assert-O3F14 ([string]$invoke.schema-eq'argos_ocv03_o3f14_response_collection_invocation_v1'-and[string]$invoke.state-eq'FROZEN_EXACT_RESPONSE_COLLECTION_INVOCATION'-and[string]$invoke.collectorSha256-eq(Get-O3F14Hash $PSCommandPath)) 'O3F14 collection invocation is not frozen.'
$sourceZip=[IO.Path]::GetFullPath([string]$invoke.sourceZip);Assert-O3F14 (Test-Path -LiteralPath $sourceZip -PathType Leaf) 'O3F14 response ZIP is absent.';Assert-O3F14 ((Get-Item $sourceZip).Length-eq[int64]$invoke.sourceZipBytes-and(Get-O3F14Hash $sourceZip)-eq[string]$invoke.sourceZipSha256) 'O3F14 response ZIP identity changed.'
$certificate=Join-Path $project ([string]$invoke.endpointCertificate);Assert-O3F14 ((Get-O3F14Hash $certificate)-eq[string]$invoke.endpointCertificateSha256) 'O3F14 endpoint certificate changed.'
Add-Type -AssemblyName System.IO.Compression;Add-Type -AssemblyName System.IO.Compression.FileSystem;$archive=[IO.Compression.ZipFile]::OpenRead($sourceZip)
try{$names=@($archive.Entries|ForEach-Object{[string]$_.FullName}|Sort-Object);$expectedNames=@('MAINTENANCE.stderr.txt','MAINTENANCE.stdout.txt','PORTAL_RESPONSE_MANIFEST.json','PORTAL_RESPONSE_MANIFEST.sig','RESULT.json')|Sort-Object;Assert-O3F14 ($names.Count-eq5-and@(Compare-Object $expectedNames $names).Count-eq0) 'O3F14 response entry set changed.';$manifestBytes=Read-O3F14Entry $archive 'PORTAL_RESPONSE_MANIFEST.json' 65536;$signatureBytes=Read-O3F14Entry $archive 'PORTAL_RESPONSE_MANIFEST.sig' 8192;$stdoutBytes=Read-O3F14Entry $archive 'MAINTENANCE.stdout.txt' 1048576;$stderrBytes=Read-O3F14Entry $archive 'MAINTENANCE.stderr.txt' 65536;$resultBytes=Read-O3F14Entry $archive 'RESULT.json' 65536}finally{$archive.Dispose()}
Assert-O3F14 ($stderrBytes.Length-eq0) 'O3F14 maintenance stderr is not empty.';$manifest=[Text.Encoding]::UTF8.GetString($manifestBytes)|ConvertFrom-Json;$endpoint=[Text.Encoding]::UTF8.GetString($stdoutBytes)|ConvertFrom-Json;$maintenance=[Text.Encoding]::UTF8.GetString($resultBytes)|ConvertFrom-Json
Assert-O3F14 ([string]$manifest.requestId-eq[string]$invoke.requestId-and[string]$manifest.responseId-eq[string]$invoke.responseId-and[string]$manifest.state-eq'PASS_MAINTENANCE_PATCH'-and[string]$manifest.sourceRole-eq'JBOD') 'O3F14 response correlation/state changed.'
$cert=New-Object Security.Cryptography.X509Certificates.X509Certificate2($certificate);$rsa=[Security.Cryptography.X509Certificates.RSACertificateExtensions]::GetRSAPublicKey($cert);try{$valid=$rsa.VerifyData($manifestBytes,$signatureBytes,[Security.Cryptography.HashAlgorithmName]::SHA256,[Security.Cryptography.RSASignaturePadding]::Pkcs1)}finally{$rsa.Dispose()};Assert-O3F14 ($valid-and$cert.Thumbprint.ToUpperInvariant()-eq[string]$invoke.expectedSignerThumbprint) 'O3F14 response signature failed.'
$actual=@{'MAINTENANCE.stderr.txt'=$stderrBytes;'MAINTENANCE.stdout.txt'=$stdoutBytes;'RESULT.json'=$resultBytes};Assert-O3F14 (@($manifest.files).Count-eq3) 'O3F14 response declared-file count changed.';foreach($record in @($manifest.files)){$name=[string]$record.path;Assert-O3F14 ($actual.ContainsKey($name)) "O3F14 unexpected response file: $name";$bytes=[byte[]]$actual[$name];Assert-O3F14 ($bytes.Length-eq[int64]$record.bytes-and(Get-O3F14BytesHash $bytes)-eq[string]$record.sha256) "O3F14 response file hash changed: $name"}
Assert-O3F14 ([string]$maintenance.state-eq'PASS_MAINTENANCE_PATCH'-and[int]$maintenance.exitCode-eq0-and[string]$maintenance.entryPoint-eq'payload/Invoke-O3F14StagedEndpoint.ps1') 'O3F14 maintenance result changed.'
Assert-O3F14 ([string]$endpoint.schema-eq'argos_ocv03_o3f14_staged_endpoint_result_v1'-and[string]$endpoint.state-eq'COMPLETE_O3F14_GATE_AND_DEV6_RESULTS_RETURNED_REVIEW_ONLY'-and-not[bool]$endpoint.rehearsal-and@($endpoint.dev6.cases).Count-eq6) 'O3F14 endpoint terminal result changed.'
Assert-O3F14 ([string]::Join('|',@($endpoint.stages))-ceq'SELF_TEST|PREFLIGHT|ROOT_CONTRACT|GATE|DEV6'-and[int]$endpoint.ownedChildCount-eq5-and@($endpoint.childProcessIds).Count-eq5) 'O3F14 endpoint stage/owned-child contract changed.'
Assert-O3F14 ([string]$endpoint.selfTest.state-eq'PASS_O3F14_STAGED_RUNNER_SELF_TEST'-and-not[bool]$endpoint.selfTest.mutationsPerformed-and[string]$endpoint.selfTest.runnerSha256-eq$expectedRunnerSha256) 'O3F14 current runner SELF_TEST identity changed.'
Assert-O3F14 ([string]$endpoint.rootContract.schema-eq'argos_ocv03_o3f14_exact_runner_root_contract_v1'-and[string]$endpoint.rootContract.state-eq'PASS_O3F14_EXACT_REAL_RUNNER_ROOT_CONTRACT'-and[string]$endpoint.rootContract.runnerSha256-eq$expectedRunnerSha256-and[string]$endpoint.rootContract.gateRoot-eq'D:/O3F9G14'-and[string]$endpoint.rootContract.dev6Root-eq'D:/O3F9D14'-and[string]::Join('|',@($endpoint.rootContract.gateTerminalKeys))-ceq'commands|stage|state|summarySha256'-and[string]::Join('|',@($endpoint.rootContract.dev6TerminalKeys))-ceq'aliasEvidence|executedCount|newProviderHoldCount|results|selectedCount|stage|state|stateCounts|summarySha256'-and-not[bool]$endpoint.rootContract.simulatedFilesystem-and[bool]$endpoint.rootContract.incompatibleO3F14PrefixRejected-and-not[bool]$endpoint.rootContract.sourceImageBytesRead-and-not[bool]$endpoint.rootContract.outputCreated-and-not[bool]$endpoint.rootContract.mutationsPerformed) 'O3F14 live root/schema-contract evidence changed.'
$aliasContract=$endpoint.rootContract.aliasContract
Assert-O3F14 ([string]$aliasContract.planSha256-eq$expectedAliasPlanSha256-and[string]$aliasContract.schema-eq'argos_ocv03_o3f12_dev6_source_alias_plan_v1'-and[string]$aliasContract.state-eq'FROZEN_FOR_BUILD'-and[string]$aliasContract.aliasDrive-ceq'Q:'-and[int]$aliasContract.caseCount-eq6-and[int]$aliasContract.canonicalLeafCount-eq12-and[int]$aliasContract.aliasLeafCount-eq12-and[bool]$aliasContract.broadRootSlot16Rejected-and-not[bool]$aliasContract.sourceImageBytesRead-and[string]$aliasContract.substSha256-eq$expectedSubstSha256-and([string]$aliasContract.substPath).Replace('\','/')-ceq'C:/Windows/System32/subst.exe'-and-not[bool]$aliasContract.lifecycle.exercised-and[bool]$aliasContract.lifecycle.metadataStaticChecksOnly) 'O3F14 frozen root source-alias contract changed.'
$dev6ChildExitCode=[int]$endpoint.dev6.childExitCode;$dev6State=[string]$endpoint.dev6.state;$dev6Cases=@($endpoint.dev6.cases);$dev6ExecutedCount=[int]$endpoint.dev6.executedCount;$dev6HoldCount=[int]$endpoint.dev6.newProviderHoldCount
$dev6Pass=($dev6ChildExitCode-eq0-and$dev6State-ceq'COMPLETE_O3F14_DEV6'-and$dev6ExecutedCount-eq6-and$dev6HoldCount-eq0)
$dev6Hold=($dev6ChildExitCode-eq2-and$dev6State-ceq'HOLD_O3F14_DEV6_EXECUTION'-and$dev6HoldCount-ge1-and($dev6ExecutedCount+$dev6HoldCount)-eq6)
Assert-O3F14 ([string]$endpoint.gate.state-eq'COMPLETE_O3F14_GATE'-and($dev6Pass-or$dev6Hold)-and[int]$endpoint.dev6.selectedCount-eq6-and$dev6Cases.Count-eq6-and@($dev6Cases|ForEach-Object{[string]$_.identity}|Sort-Object -Unique).Count-eq6-and@($dev6Cases|ForEach-Object{[string]$_.safeId}|Sort-Object -Unique).Count-eq6) 'O3F14 GATE/DEV6 exact exit-state/count contract changed.'
$projectedProviderHolds=@($dev6Cases|Where-Object{[string]$_.finalState-eq'HOLD_O3F14_R11_PROVIDER_ERROR'})
Assert-O3F14 (($dev6Pass-and$projectedProviderHolds.Count-eq0)-or($dev6Hold-and$projectedProviderHolds.Count-eq$dev6HoldCount)) 'O3F14 projected provider-hold identities do not match the signed hold count.'
$aliasEvidence=$endpoint.dev6.aliasEvidence;$aliasCases=@($aliasEvidence.cases)
Assert-O3F14 ([string]$aliasEvidence.state-eq'COMPLETE_O3F14_Q_ALIAS_LIFECYCLE'-and[string]$aliasEvidence.aliasDrive-ceq'Q:'-and[string]$aliasEvidence.aliasAnchorKind-eq'CASE_SLOT_ROOT'-and[string]$aliasEvidence.sourceAliasPlanSha256-eq$expectedAliasPlanSha256-and[bool]$aliasEvidence.frozenPlanExactOrderedMatch-and[int]$aliasEvidence.prevalidatedCaseCount-eq6-and[int]$aliasEvidence.executedCaseCount-eq6-and[bool]$aliasEvidence.allMappingsRemovedAndVerifiedAbsent-and$aliasCases.Count-eq6) 'O3F14 DEV6 alias-evidence header changed.'
for($aliasIndex=0;$aliasIndex-lt6;$aliasIndex++){$aliasCase=$aliasCases[$aliasIndex];Assert-O3F14 ([int]$aliasCase.ordinal-eq($aliasIndex+1)-and-not[string]::IsNullOrWhiteSpace([string]$aliasCase.identity)-and[bool]$aliasCase.exactTargetVerified-and[bool]$aliasCase.sameFileVerified-and[bool]$aliasCase.ownedMappingRemoved-and[bool]$aliasCase.verifiedAbsentAfterRemove) "O3F14 DEV6 alias cleanup evidence changed at ordinal $($aliasIndex+1)."}
Assert-O3F14 (@($aliasCases|ForEach-Object{[string]$_.identity}|Sort-Object -Unique).Count-eq6) 'O3F14 DEV6 alias-evidence identities are not six unique cases.'
$aliasBackstop=$endpoint.dev6.endpointAliasCleanupBackstop
Assert-O3F14 ([string]$endpoint.sourceAliasPlanSha256-eq$expectedAliasPlanSha256-and[string]$endpoint.temporarySourceAliasDrive-ceq'Q:'-and[bool]$endpoint.temporarySourceAliasVerifiedAbsentAfterDev6-and[string]$aliasBackstop.aliasDrive-ceq'Q:'-and-not[bool]$aliasBackstop.mappingObserved-and-not[bool]$aliasBackstop.removedByBackstop-and[bool]$aliasBackstop.verifiedAbsent-and-not[bool]$aliasBackstop.matchedAllowedTarget) 'O3F14 endpoint Q: cleanup proof changed.'
Assert-O3F14 ([bool]$endpoint.sourceImageBytesRead-and[bool]$endpoint.reviewOnly-and-not[bool]$endpoint.productionRoutingEnabled-and-not[bool]$endpoint.sourceMutationPerformed-and-not[bool]$endpoint.sourceDeletionPerformed-and-not[bool]$endpoint.providerActivated-and-not[bool]$endpoint.requestRetryAuthorized-and-not[bool]$endpoint.holdsAutomaticallyCleared-and[int]$endpoint.taskActionCount-eq0-and[int]$endpoint.existingProcessQueryCount-eq0) 'O3F14 endpoint authority widened.'
$localRoot=[IO.Path]::GetFullPath([string]$invoke.localRoot);$gatePath=Join-Path $PSScriptRoot 'O3F14_RESPONSE_COLLECTION_GATE.json';Assert-O3F14 (-not(Test-Path -LiteralPath $localRoot)-and-not(Test-Path -LiteralPath $gatePath)) 'O3F14 create-new collection target exists.'
if($Preflight){[ordered]@{schema='argos_ocv03_o3f14_response_collection_preflight_v1';state='PASS_O3F14_RESPONSE_COLLECTION_PREFLIGHT';requestId=[string]$invoke.requestId;responseId=[string]$invoke.responseId;responseZipSha256=[string]$invoke.sourceZipSha256;signatureVerified=$true;endpointState=[string]$endpoint.state;stages=@($endpoint.stages);ownedChildCount=[int]$endpoint.ownedChildCount;runnerSha256=$expectedRunnerSha256;sourceAliasPlanSha256=$expectedAliasPlanSha256;rootContract=$endpoint.rootContract;aliasEvidence=$aliasEvidence;endpointAliasCleanupBackstop=$aliasBackstop;temporarySourceAliasDrive=[string]$endpoint.temporarySourceAliasDrive;temporarySourceAliasVerifiedAbsentAfterDev6=[bool]$endpoint.temporarySourceAliasVerifiedAbsentAfterDev6;sourceImageBytesRead=[bool]$endpoint.sourceImageBytesRead;holdsAutomaticallyCleared=[bool]$endpoint.holdsAutomaticallyCleared;dev6ChildExitCode=$dev6ChildExitCode;dev6State=$dev6State;dev6Disposition=$(if($dev6Hold){'EXPLICIT_HOLD'}else{'COMPLETE'});dev6CaseCount=6;dev6NewProviderHoldCount=$dev6HoldCount;mutationsPerformed=$false;requestRetryAuthorized=$false;reviewOnly=$true;productionRoutingEnabled=$false}|ConvertTo-Json -Depth 16;return}
[void](New-Item -ItemType Directory -Path $localRoot);$localZip=Join-Path $localRoot ([IO.Path]::GetFileName($sourceZip));Copy-Item -LiteralPath $sourceZip -Destination $localZip;Assert-O3F14 ((Get-O3F14Hash $localZip)-eq[string]$invoke.sourceZipSha256) 'O3F14 local response copy changed.';$extract=Join-Path $localRoot ([string]$invoke.responseId+'.ready');[IO.Compression.ZipFile]::ExtractToDirectory($localZip,$extract)
$gate=[ordered]@{schema='argos_ocv03_o3f14_response_collection_gate_v1';state='PASS_O3F14_MATCHING_SIGNED_RESPONSE_COLLECTED';requestId=[string]$invoke.requestId;responseId=[string]$invoke.responseId;responseZipPath=$localZip;responseZipSha256=[string]$invoke.sourceZipSha256;signatureVerified=$true;endpointState=[string]$endpoint.state;stages=@($endpoint.stages);ownedChildCount=[int]$endpoint.ownedChildCount;runnerSha256=$expectedRunnerSha256;sourceAliasPlanSha256=$expectedAliasPlanSha256;rootContract=$endpoint.rootContract;aliasEvidence=$aliasEvidence;endpointAliasCleanupBackstop=$aliasBackstop;temporarySourceAliasDrive=[string]$endpoint.temporarySourceAliasDrive;temporarySourceAliasVerifiedAbsentAfterDev6=[bool]$endpoint.temporarySourceAliasVerifiedAbsentAfterDev6;sourceImageBytesRead=[bool]$endpoint.sourceImageBytesRead;holdsAutomaticallyCleared=[bool]$endpoint.holdsAutomaticallyCleared;gateState=[string]$endpoint.gate.state;gateSummarySha256=[string]$endpoint.gate.summarySha256;dev6ChildExitCode=$dev6ChildExitCode;dev6State=$dev6State;dev6Disposition=$(if($dev6Hold){'EXPLICIT_HOLD'}else{'COMPLETE'});dev6SelectedCount=[int]$endpoint.dev6.selectedCount;dev6ExecutedCount=$dev6ExecutedCount;dev6NewProviderHoldCount=$dev6HoldCount;dev6SummarySha256=[string]$endpoint.dev6.summarySha256;dev6StateCounts=$endpoint.dev6.stateCounts;dev6Cases=$dev6Cases;explicitProviderHoldCases=$projectedProviderHolds;requestRetryAuthorized=$false;sourceMutationPerformed=$false;providerActivated=$false;reviewOnly=$true;productionRoutingEnabled=$false};Write-O3F14Json $gatePath $gate;$gate|ConvertTo-Json -Depth 16
