#Requires -Version 5.1
[CmdletBinding()]
param([switch]$Preflight,[switch]$Rehearsal,[string]$InvocationManifest='')

$ErrorActionPreference='Stop'
Set-StrictMode -Version Latest
$liveInvocationSha256='00100836FE711D27A99C7B1CCC886B525BE75806D9BB1A3B7A63BE41020089DC'
function Assert-True([bool]$Condition,[string]$Message){if(-not$Condition){throw $Message}}
function Get-Sha([string]$Path){$s=[IO.File]::OpenRead($Path);$h=[Security.Cryptography.SHA256]::Create();try{return([BitConverter]::ToString($h.ComputeHash($s))).Replace('-','')}finally{$h.Dispose();$s.Dispose()}}
function Assert-PathBudget([string]$Path,[int]$Reserve=32){$f=[IO.Path]::GetFullPath($Path);$p=@($f.Split([char[]]@('\','/'),[StringSplitOptions]::RemoveEmptyEntries));$m=if($p.Count){[int](($p|ForEach-Object{$_.Length}|Measure-Object -Maximum).Maximum)}else{0};Assert-True (($f.Length+$Reserve)-lt200) "O3M8 unsafe path: $f";Assert-True ($m-le80) "O3M8 unsafe component: $f"}
function Write-NewJson([string]$Path,[object]$Value,[int]$Depth=24){Assert-True (-not(Test-Path -LiteralPath $Path)) "O3M8 create-new JSON exists: $Path";[IO.File]::WriteAllText($Path,(($Value|ConvertTo-Json -Depth $Depth)+[Environment]::NewLine),(New-Object Text.UTF8Encoding($false)))}
function Get-ProcessorRows([string]$Token){return @(Get-CimInstance Win32_Process -Filter "Name='powershell.exe' OR Name='pwsh.exe'" -ErrorAction Stop|Where-Object{[string]$_.CommandLine-like('*'+$Token+'*')}|Sort-Object ProcessId|ForEach-Object{[pscustomobject]@{processId=[uint32]$_.ProcessId;creationDate=[string]$_.CreationDate;commandLine=[string]$_.CommandLine}})}
function Invoke-Python([string]$Python,[string]$Engine,[string[]]$Arguments,[string]$DependencyRoot){
  $si=New-Object Diagnostics.ProcessStartInfo;$si.FileName=$Python;$quoted=@('"'+$Engine+'"')+@($Arguments|ForEach-Object{'"'+([string]$_).Replace('"','\"')+'"'});$si.Arguments=$quoted-join' ';$si.UseShellExecute=$false;$si.CreateNoWindow=$true;$si.RedirectStandardOutput=$true;$si.RedirectStandardError=$true;$si.EnvironmentVariables['PYTHONDONTWRITEBYTECODE']='1';$si.EnvironmentVariables['ARGOS_O3M1_R6_ROOT']=$DependencyRoot;$si.EnvironmentVariables['ARGOS_O3M1_TOPOLOGY_ROOT']=$DependencyRoot
  $p=New-Object Diagnostics.Process;$p.StartInfo=$si;Assert-True $p.Start() 'O3M8 Python did not start.';$o=$p.StandardOutput.ReadToEndAsync();$e=$p.StandardError.ReadToEndAsync();if(-not$p.WaitForExit(900000)){try{$p.Kill()}catch{};[void]$p.WaitForExit(5000);throw'O3M8 Python exceeded 900 seconds.'};$p.WaitForExit();$r=[pscustomobject]@{exitCode=$p.ExitCode;stdout=[string]$o.Result;stderr=[string]$e.Result};$p.Dispose();Assert-True ($r.stdout.Length-le1048576-and$r.stderr.Length-le1048576) 'O3M8 Python output exceeded bound.';return $r
}

$manifestPath=if([string]::IsNullOrWhiteSpace($InvocationManifest)){Join-Path $PSScriptRoot 'O3M9_ENDPOINT_LIVE_INVOCATION.json'}else{[IO.Path]::GetFullPath($InvocationManifest)}
Assert-True (Test-Path -LiteralPath $manifestPath -PathType Leaf) 'O3M8 invocation absent.'
if(-not$Rehearsal){Assert-True ((Get-Sha $manifestPath)-eq$liveInvocationSha256) 'O3M8 live invocation changed.'}
$inv=Get-Content -LiteralPath $manifestPath -Raw|ConvertFrom-Json;$expectedState=if($Rehearsal){'FROZEN_REHEARSAL_CONTRACT'}else{'FROZEN_LIVE_CONTRACT'}
Assert-True ([string]$inv.schema-eq'argos_o3m8_endpoint_invocation_v1'-and[string]$inv.state-eq$expectedState) 'O3M8 invocation identity changed.'
Assert-True ($env:COMPUTERNAME.Equals([string]$inv.expectedComputerName,[StringComparison]::OrdinalIgnoreCase)) "O3M8 wrong computer: $env:COMPUTERNAME"
Assert-True ([bool]$inv.sourceImageReadAuthorized-and[bool]$inv.detectorRerunAuthorized-and-not[bool]$inv.thresholdOrAlgorithmChangeAuthorized-and[bool]$inv.frontsideOnly-and-not[bool]$inv.backsidePixelsConsumed-and-not[bool]$inv.argosRotationMetadataConsumed) 'O3M8 image-processing authority changed.'
Assert-True (-not[bool]$inv.requestRetryAuthorized-and[bool]$inv.reviewOnly-and-not[bool]$inv.trainingEligible-and-not[bool]$inv.xmlEligible-and-not[bool]$inv.productionEligible-and-not[bool]$inv.productionRoutingEnabled) 'O3M8 authority widened.'
$payloadRoot=if([string]::IsNullOrWhiteSpace([string]$inv.payloadRoot)){$PSScriptRoot}else{[IO.Path]::GetFullPath([string]$inv.payloadRoot)}
$engine=if([string]::IsNullOrWhiteSpace([string]$inv.enginePath)){Join-Path $payloadRoot 'FullPerimeterWaferTopologyOpenCvR7.py'}else{[IO.Path]::GetFullPath([string]$inv.enginePath)}
$job=if([string]::IsNullOrWhiteSpace([string]$inv.jobPath)){Join-Path $payloadRoot 'O3M9_SLOT16_JOB.json'}else{[IO.Path]::GetFullPath([string]$inv.jobPath)}
$runtime=[IO.Path]::GetFullPath([string]$inv.runtimePath);$runtimeInstall=[IO.Path]::GetFullPath([string]$inv.runtimeInstallationPath);$sourceRoot=[IO.Path]::GetFullPath([string]$inv.sourceRoot);$output=[IO.Path]::GetFullPath([string]$inv.outputRoot);$outputPartial=$output+'.partial';$outputFailed=$output+'.failed';$export=[IO.Path]::GetFullPath([string]$inv.exportRoot);$exportPartial=$export+'.partial';$exportFailed=$export+'.failed';$zipName=[string]$inv.exportZipName;$zipPartial=Join-Path $exportPartial $zipName;$zipFinal=Join-Path $export $zipName;$alias=[string]$inv.sourceAliasDrive;$aliasPath=$alias+'\';$subst=Join-Path $env:SystemRoot 'System32\subst.exe'
Assert-True ($alias-eq'F:') 'O3M8 alias changed.'
foreach($p in @($engine,$job,$runtime,$runtimeInstall)){Assert-True (Test-Path -LiteralPath $p -PathType Leaf) "O3M8 dependency absent: $p";Assert-PathBudget $p}
Assert-True ((Get-Sha $engine)-eq[string]$inv.engineSha256-and(Get-Sha $job)-eq[string]$inv.jobSha256-and(Get-Sha $runtime)-eq[string]$inv.runtimeSha256-and(Get-Sha $runtimeInstall)-eq[string]$inv.runtimeInstallationSha256) 'O3M8 primary dependency hash changed.'
foreach($d in @($inv.dependencyFiles)){$p=Join-Path $payloadRoot ([string]$d.path);Assert-True (Test-Path -LiteralPath $p -PathType Leaf) "O3M8 Python dependency absent: $p";Assert-True ((Get-Sha $p)-eq[string]$d.sha256) "O3M8 Python dependency changed: $p";Assert-PathBudget $p}
Assert-True (@($inv.dependencyFiles).Count-eq4) 'O3M8 dependency cardinality changed.'
$cmd=Get-Command -Name $runtime -CommandType Application -ErrorAction Stop;Assert-True ([IO.Path]::GetFullPath($cmd.Source).Equals($runtime,[StringComparison]::OrdinalIgnoreCase)) 'O3M8 runtime command resolution changed.'
foreach($p in @($sourceRoot,$output,$outputPartial,$outputFailed,$export,$exportPartial,$exportFailed,$zipPartial,$zipFinal)){Assert-PathBudget $p}
foreach($p in @($output,$outputPartial,$outputFailed,$export,$exportPartial,$exportFailed)){Assert-True (-not(Test-Path -LiteralPath $p)) "O3M8 create-new target exists: $p"}
Assert-True (-not(Test-Path -LiteralPath $aliasPath)-and$null-eq(Get-PSDrive -Name F -ErrorAction SilentlyContinue)) 'O3M8 F: already in use.'
$processorBefore=@(Get-ProcessorRows ([string]$inv.processorCommandToken))
$rp=Invoke-Python $runtime $engine @('--runtime-preflight') $payloadRoot;Assert-True ($rp.exitCode-eq0) ('O3M8 runtime preflight failed: '+$rp.stderr.Trim());$rv=$rp.stdout.Trim()|ConvertFrom-Json;Assert-True ([bool]$rv.imageBytesDecoded-eq$false-and[bool]$rv.mutationsPerformed-eq$false) 'O3M8 runtime preflight mutated.'
$pp=Invoke-Python $runtime $engine @('--preflight','--job',$job) $payloadRoot;Assert-True ($pp.exitCode-eq0) ('O3M8 provider preflight failed: '+$pp.stderr.Trim());$pv=$pp.stdout.Trim()|ConvertFrom-Json;Assert-True ([string]$pv.state-eq'PASS_O3M7_SPLIT_METHOD_PREFLIGHT'-and-not[bool]$pv.sourceMetadataRead-and-not[bool]$pv.sourceImageBytesRead-and-not[bool]$pv.outputCreated) 'O3M8 provider preflight contract changed.'
if($Preflight){[ordered]@{schema='argos_o3m8_endpoint_preflight_v1';createdUtc=[DateTime]::UtcNow.ToString('o');state='PASS_O3M8_ENDPOINT_PREFLIGHT';revision=[string]$inv.revision;rehearsal=[bool]$Rehearsal;sourceMetadataRead=$false;sourceImageBytesRead=$false;pixelsDecoded=$false;outputCreated=$false;mutationsPerformed=$false;processorProcessCount=$processorBefore.Count;backsidePixelsConsumed=$false;argosRotationMetadataConsumed=$false;reviewOnly=$true;productionRoutingEnabled=$false}|ConvertTo-Json -Depth 8;return}
$aliasCreated=$false;$outputCommitted=$false;$exportCommitted=$false;$terminal=$null
try{
  $t=&$subst $alias $sourceRoot 2>&1|Out-String;Assert-True ($LASTEXITCODE-eq0-and(Test-Path -LiteralPath $aliasPath -PathType Container)) ('O3M8 alias creation failed: '+$t.Trim());$aliasCreated=$true
  $run=Invoke-Python $runtime $engine @('--run','--job',$job,'--output-root',$outputPartial) $payloadRoot;Assert-True ($run.exitCode-eq0) ('O3M8 provider failed: '+$run.stderr.Trim());$runValue=$run.stdout.Trim()|ConvertFrom-Json;Assert-True ([string]$runValue.state-eq'COMPLETE_REVIEW_ONLY_FULL_PERIMETER_TOPOLOGY'-and[int]$runValue.pairCount-eq1-and[int]$runValue.imageInputCount-eq2) 'O3M8 provider terminal changed.'
  $manifestPartial=Join-Path $outputPartial 'MANIFEST.json';Assert-True (Test-Path -LiteralPath $manifestPartial -PathType Leaf) 'O3M8 manifest absent.';$m=Get-Content -LiteralPath $manifestPartial -Raw|ConvertFrom-Json;Assert-True ([string]$m.schema-eq'argos_ocv03_full_perimeter_topology_manifest_v1'-and[int]$m.inputCount-eq2-and[bool]$m.inputHashesMatched-and@($m.results).Count-eq1) 'O3M8 manifest identity changed.';Assert-True ([bool]$m.fullPerimeterInference-and-not[bool]$m.argosRotationMetadataConsumed-and-not[bool]$m.orientationMetadataConsumed-and-not[bool]$m.knownNotchLocationConsumed-and-not[bool]$m.backsidePixelsConsumed) 'O3M8 inference boundary changed.';Assert-True (-not[bool]$m.sourceMutationPerformed-and-not[bool]$m.providerActivated-and-not[bool]$m.processorTouched-and-not[bool]$m.holdCleared-and[bool]$m.reviewOnly-and-not[bool]$m.productionEligible) 'O3M8 authority widened.'
  Move-Item -LiteralPath $outputPartial -Destination $output;$outputCommitted=$true;$manifestFinal=Join-Path $output 'MANIFEST.json';$manifestSha=Get-Sha $manifestFinal
  [void][IO.Directory]::CreateDirectory($exportPartial);Add-Type -AssemblyName System.IO.Compression.FileSystem;[IO.Compression.ZipFile]::CreateFromDirectory($output,$zipPartial,[IO.Compression.CompressionLevel]::Optimal,$false);$zi=Get-Item $zipPartial;Assert-True ($zi.Length-gt0-and$zi.Length-le[int64]$inv.maximumExportZipBytes) 'O3M8 export ZIP size changed.';$zipSha=Get-Sha $zipPartial;$archive=[IO.Compression.ZipFile]::OpenRead($zipPartial);try{$entryCount=@($archive.Entries).Count}finally{$archive.Dispose()}
  $em=[ordered]@{schema='argos_o3m8_review_export_v1';createdUtc=[DateTime]::UtcNow.ToString('o');state='PASS_O3M8_SLOT16_REVIEW_EXPORT';revision=[string]$inv.revision;renderManifestSha256=$manifestSha;zipName=$zipName;zipBytes=[int64]$zi.Length;zipSha256=$zipSha;zipEntryCount=$entryCount;sourceImageReadCount=2;sourceHashesMatched=$true;detectorRerunPerformed=$true;thresholdOrAlgorithmChanged=$false;backsidePixelsConsumed=$false;argosRotationMetadataConsumed=$false;sourceMutationPerformed=$false;processorTouched=$false;providerActivated=$false;requestRetryAuthorized=$false;reviewOnly=$true;productionRoutingEnabled=$false};Write-NewJson (Join-Path $exportPartial 'EXPORT_MANIFEST.json') $em 12;Move-Item $exportPartial $export;$exportCommitted=$true
  $terminal=[ordered]@{schema='argos_o3m8_endpoint_result_v1';createdUtc=[DateTime]::UtcNow.ToString('o');state='PASS_O3M8_SLOT16_SPLIT_METHOD_RENDERED_FOR_DATA_PULL';revision=[string]$inv.revision;rehearsal=[bool]$Rehearsal;renderManifestPath=$manifestFinal;renderManifestSha256=$manifestSha;detectorState=[string]$m.results[0].state;eligiblePhysicalCandidateCount=@($m.results[0].eligiblePhysicalCandidateIndices).Count;physicalCandidateCount=@($m.results[0].physicalIndentationCandidates).Count;exportRelativePath='OCV03ReviewExports/O3M9_20260827T230100Z/'+$zipName;exportZipPath=$zipFinal;exportZipBytes=[int64]$zi.Length;exportZipSha256=$zipSha;zipEntryCount=$entryCount;sourceImageReadCount=2;sourceHashesMatched=$true;detectorRerunPerformed=$true;thresholdOrAlgorithmChanged=$false;backsidePixelsConsumed=$false;argosRotationMetadataConsumed=$false;sourceMutationPerformed=$false;processorTouched=$false;providerActivated=$false;requestRetryAuthorized=$false;reviewOnly=$true;productionRoutingEnabled=$false}
}catch{if($exportCommitted-and(Test-Path $export)-and-not(Test-Path $exportFailed)){Move-Item $export $exportFailed -ErrorAction SilentlyContinue}elseif(Test-Path $exportPartial){Move-Item $exportPartial $exportFailed -ErrorAction SilentlyContinue};if($outputCommitted-and(Test-Path $output)-and-not(Test-Path $outputFailed)){Move-Item $output $outputFailed -ErrorAction SilentlyContinue}elseif(Test-Path $outputPartial){Move-Item $outputPartial $outputFailed -ErrorAction SilentlyContinue};throw}finally{if($aliasCreated){$t=&$subst $alias /D 2>&1|Out-String;if($LASTEXITCODE-ne0-or(Test-Path $aliasPath)-or$null-ne(Get-PSDrive -Name F -ErrorAction SilentlyContinue)){throw('O3M8 alias removal failed: '+$t.Trim())}}}
$processorAfter=@(Get-ProcessorRows ([string]$inv.processorCommandToken));Assert-True (($processorBefore|ConvertTo-Json -Depth 6 -Compress)-eq($processorAfter|ConvertTo-Json -Depth 6 -Compress)) 'O3M8 processor identity changed.';$terminal.processorProcessCount=$processorAfter.Count;$terminal.processorIdentityUnchanged=$true;$terminal.sourceAliasRemoved=$true;$terminal|ConvertTo-Json -Depth 12
