#Requires -Version 5.1
[CmdletBinding()]
param([Parameter(Mandatory=$true)][string]$InvocationManifest,[switch]$Preflight,[switch]$Collect)

$ErrorActionPreference='Stop'
Set-StrictMode -Version Latest
if(([bool]$Preflight)-eq([bool]$Collect)){throw 'Specify exactly one of -Preflight or -Collect.'}
function Assert-True([bool]$Condition,[string]$Message){if(-not $Condition){throw $Message}}
function Get-Sha([string]$Path){return (Get-FileHash -LiteralPath $Path -Algorithm SHA256).Hash}
function Resolve-ProjectFile([string]$Project,[string]$Relative){$full=[IO.Path]::GetFullPath((Join-Path $Project $Relative.Replace('/','\')));Assert-True ($full.StartsWith($Project.TrimEnd('\')+'\',[StringComparison]::OrdinalIgnoreCase)) "O3K1 collector dependency escaped project: $Relative";Assert-True (Test-Path -LiteralPath $full -PathType Leaf) "O3K1 collector dependency absent: $Relative";return $full}
function Write-NewJson([string]$Path,[object]$Value){Assert-True (-not(Test-Path -LiteralPath $Path)) "O3K1 collection gate exists: $Path";[IO.File]::WriteAllText($Path,(($Value|ConvertTo-Json -Depth 12)+[Environment]::NewLine),(New-Object Text.UTF8Encoding($false)))}

$project=[IO.Path]::GetFullPath((Join-Path $PSScriptRoot '..\..'))
$invocationPath=[IO.Path]::GetFullPath($InvocationManifest)
$expectedInvocationSha='3AC11D6B9476FAB6E88035B1B95C88E8AFE2E9855F1B6D0596032CB47E287E4B'
Assert-True (Test-Path -LiteralPath $invocationPath -PathType Leaf) 'O3K1 response invocation is absent.'
Assert-True ((Get-Sha $invocationPath)-eq$expectedInvocationSha) 'O3K1 response invocation changed.'
$invocation=Get-Content -LiteralPath $invocationPath -Raw|ConvertFrom-Json
Assert-True ([string]$invocation.schema-eq'argos_o3k1_render_response_collection_invocation_v1'-and[string]$invocation.state-eq'FROZEN_EXACT_MATCHING_RESPONSE') 'O3K1 response invocation identity changed.'
Assert-True ([bool]$invocation.matchingSignedTerminalResponseOnly-and-not[bool]$invocation.requestRetryAuthorized-and-not[bool]$invocation.imageBytesReadByCollector-and-not[bool]$invocation.sourceImageBytesReadByCollector) 'O3K1 response selection or image boundary changed.'
Assert-True ([bool]$invocation.reviewOnly-and-not[bool]$invocation.trainingEligible-and-not[bool]$invocation.xmlEligible-and-not[bool]$invocation.productionEligible-and-not[bool]$invocation.productionRoutingEnabled) 'O3K1 response collector authority widened.'
$observation=Resolve-ProjectFile $project ([string]$invocation.matchingResponseObservation);Assert-True ((Get-Sha $observation)-eq[string]$invocation.matchingResponseObservationSha256) 'O3K1 matching observation changed.';$observationValue=Get-Content -LiteralPath $observation -Raw|ConvertFrom-Json;Assert-True ([string]$observationValue.state-eq'PASS_O3K1_EXACT_MATCHING_RENDER_RESPONSE_OBSERVED'-and[int]$observationValue.matchingResponseCount-eq1) 'O3K1 matching response is not singular.'
$publication=Resolve-ProjectFile $project ([string]$invocation.publicationGate);Assert-True ((Get-Sha $publication)-eq[string]$invocation.publicationGateSha256) 'O3K1 publication gate changed.';$publicationValue=Get-Content -LiteralPath $publication -Raw|ConvertFrom-Json;Assert-True ([string]$publicationValue.state-eq'PASS_O3K1_RENDER_REQUEST_PUBLISHED_ONCE'-and[int]$publicationValue.publicationCount-eq1-and-not[bool]$publicationValue.requestRetryAuthorized) 'O3K1 publication evidence changed.'
$verifier=Resolve-ProjectFile $project ([string]$invocation.verifier);$certificate=Resolve-ProjectFile $project ([string]$invocation.endpointCertificate);Assert-True ((Get-Sha $verifier)-eq[string]$invocation.verifierSha256-and(Get-Sha $certificate)-eq[string]$invocation.endpointCertificateSha256) 'O3K1 verifier or certificate changed.'
$sourceZip=[IO.Path]::GetFullPath([string]$invocation.sourceZip);Assert-True (Test-Path -LiteralPath $sourceZip -PathType Leaf) 'O3K1 matching response ZIP is absent.';Assert-True ((Get-Item -LiteralPath $sourceZip).Length-eq[int64]$invocation.sourceZipBytes-and(Get-Sha $sourceZip)-eq[string]$invocation.sourceZipSha256) 'O3K1 matching response ZIP changed.'
$tempRoot=[IO.Path]::GetFullPath([string]$invocation.temporaryRoot);$tempZip=[IO.Path]::GetFullPath([string]$invocation.temporaryZip);$tempExtract=[IO.Path]::GetFullPath([string]$invocation.temporaryExtractionRoot);$gatePath=[IO.Path]::GetFullPath((Join-Path $project ([string]$invocation.collectionGate).Replace('/','\')))
foreach($target in @($tempRoot,$gatePath)){Assert-True (-not(Test-Path -LiteralPath $target)) "O3K1 create-new collection target exists: $target"}
Add-Type -AssemblyName System.IO.Compression.FileSystem
$archive=[IO.Compression.ZipFile]::OpenRead($sourceZip)
try{$names=@($archive.Entries|ForEach-Object{[string]$_.FullName}|Sort-Object);$expected=@('MAINTENANCE.stderr.txt','MAINTENANCE.stdout.txt','PORTAL_RESPONSE_MANIFEST.json','PORTAL_RESPONSE_MANIFEST.sig','RESULT.json')|Sort-Object;Assert-True ($names.Count-eq5-and@(Compare-Object -ReferenceObject $expected -DifferenceObject $names).Count-eq0) 'O3K1 response ZIP entry set changed.';$manifestEntry=$archive.GetEntry('PORTAL_RESPONSE_MANIFEST.json');Assert-True ($null-ne$manifestEntry-and$manifestEntry.Length-le65536) 'O3K1 response manifest is absent or unbounded.';$reader=New-Object IO.StreamReader($manifestEntry.Open(),[Text.Encoding]::UTF8,$true);try{$manifest=$reader.ReadToEnd()|ConvertFrom-Json}finally{$reader.Dispose()}}finally{$archive.Dispose()}
Assert-True ([string]$manifest.requestId-eq[string]$invocation.requestId-and[string]$manifest.responseId-eq[string]$invocation.responseId-and[string]$manifest.sourceRole-eq[string]$invocation.expectedSourceRole-and[string]$manifest.state-eq[string]$invocation.expectedManifestState) 'O3K1 response manifest correlation changed.'
if($Preflight){[ordered]@{schema='argos_o3k1_render_response_collection_preflight_v1';createdUtc=[DateTime]::UtcNow.ToString('o');state='PASS_O3K1_RENDER_RESPONSE_COLLECTION_PREFLIGHT';requestId=[string]$invocation.requestId;responseId=[string]$invocation.responseId;sourceZipSha256=[string]$invocation.sourceZipSha256;manifestState=[string]$manifest.state;signatureVerified=$false;mutationsPerformed=$false;imageBytesRead=$false;requestRetryAuthorized=$false;reviewOnly=$true;productionRoutingEnabled=$false}|ConvertTo-Json -Depth 8;return}

[void][IO.Directory]::CreateDirectory($tempRoot)
[IO.File]::Copy($sourceZip,$tempZip,$false)
Assert-True ((Get-Sha $tempZip)-eq[string]$invocation.sourceZipSha256) 'O3K1 temporary response copy changed.'
[IO.Compression.ZipFile]::ExtractToDirectory($tempZip,$tempExtract)
$verification=& $verifier -PackagePath $tempExtract -EndpointCertificatePath $certificate -ExpectedSourceRole JBOD -ExpectedRequestId ([string]$invocation.requestId)
Assert-True ([string]$verification.State-eq'PASS_SIGNED_PORTAL_RESPONSE'-and[string]$verification.EndpointState-eq[string]$invocation.expectedManifestState-and[string]$verification.SignerThumbprint-eq[string]$invocation.expectedSignerThumbprint) 'O3K1 JBOD signature or terminal correlation failed.'
$endpointResult=Get-Content -LiteralPath (Join-Path $tempExtract 'MAINTENANCE.stdout.txt') -Raw|ConvertFrom-Json
Assert-True ([string]$endpointResult.schema-eq'argos_o3k1_endpoint_result_v1'-and[string]$endpointResult.state-eq[string]$invocation.expectedEndpointState-and[string]$endpointResult.revision-eq[string]$invocation.expectedEndpointRevision-and-not[bool]$endpointResult.rehearsal) 'O3K1 endpoint terminal result changed.'
Assert-True ([string]$endpointResult.renderManifestSha256-eq[string]$invocation.expectedRenderManifestSha256-and[string]$endpointResult.exportRelativePath-eq[string]$invocation.expectedExportRelativePath-and[int64]$endpointResult.exportZipBytes-eq[int64]$invocation.expectedExportZipBytes-and[string]$endpointResult.exportZipSha256-eq[string]$invocation.expectedExportZipSha256) 'O3K1 rendered export proof changed.'
Assert-True ([int]$endpointResult.assetFileCount-eq18-and[int]$endpointResult.candidateCount-eq3-and[int]$endpointResult.channelRenderCount-eq6-and[int]$endpointResult.sourceImageReadCount-eq4-and[bool]$endpointResult.sourceHashesMatched) 'O3K1 render cardinality or source proof changed.'
Assert-True (-not[bool]$endpointResult.detectorRerunPerformed-and-not[bool]$endpointResult.thresholdOrAlgorithmChanged-and-not[bool]$endpointResult.sourceMutationPerformed-and-not[bool]$endpointResult.sourceDeletionPerformed-and-not[bool]$endpointResult.taskOrProcessActionPerformed-and-not[bool]$endpointResult.providerActivated-and[bool]$endpointResult.processorIdentityUnchanged-and[bool]$endpointResult.sourceAliasRemoved) 'O3K1 endpoint crossed a protected boundary.'
$maintenance=Get-Content -LiteralPath (Join-Path $tempExtract 'RESULT.json') -Raw|ConvertFrom-Json
Assert-True ([string]$maintenance.schema-eq'argos_project_portal_maintenance_result_v1'-and[string]$maintenance.state-eq'PASS_MAINTENANCE_PATCH'-and[int]$maintenance.changedFiles-eq1-and[int]$maintenance.exitCode-eq0) 'O3K1 maintenance result changed.'
$gate=[ordered]@{schema='argos_o3k1_render_response_collection_gate_v1';createdUtc=[DateTime]::UtcNow.ToString('o');state='PASS_O3K1_MATCHING_SIGNED_RENDER_RESPONSE_COLLECTED';requestId=[string]$invocation.requestId;responseId=[string]$invocation.responseId;responseZipPath=$tempZip;responseZipBytes=[int64]$invocation.sourceZipBytes;responseZipSha256=[string]$invocation.sourceZipSha256;responseManifestSha256=Get-Sha (Join-Path $tempExtract 'PORTAL_RESPONSE_MANIFEST.json');responseSignatureSha256=Get-Sha (Join-Path $tempExtract 'PORTAL_RESPONSE_MANIFEST.sig');signatureVerified=$true;signerThumbprint=[string]$verification.SignerThumbprint;endpointState=[string]$endpointResult.state;renderManifestSha256=[string]$endpointResult.renderManifestSha256;exportRelativePath=[string]$endpointResult.exportRelativePath;exportZipBytes=[int64]$endpointResult.exportZipBytes;exportZipSha256=[string]$endpointResult.exportZipSha256;sourceImageReadCount=4;sourceHashesMatched=$true;detectorRerunPerformed=$false;thresholdOrAlgorithmChanged=$false;sourceMutationPerformed=$false;sourceDeletionPerformed=$false;taskOrProcessActionPerformed=$false;processorIdentityUnchanged=$true;providerActivated=$false;requestRetryAuthorized=$false;dataPullNowEligible=$true;gatewayAcceptanceIsExecutionEvidence=$false;reviewOnly=$true;trainingEligible=$false;xmlEligible=$false;productionEligible=$false;productionRoutingEnabled=$false}
Write-NewJson $gatePath $gate
$gate|ConvertTo-Json -Depth 10
