#Requires -Version 5.1
[CmdletBinding()]
param([switch]$Preflight,[switch]$Collect)
$ErrorActionPreference='Stop';Set-StrictMode -Version Latest
if(([bool]$Preflight)-eq([bool]$Collect)){throw 'Specify exactly one of -Preflight or -Collect.'}
function A([bool]$c,[string]$m){if(-not$c){throw$m}}
function Get-ExactSha256([string]$p){return(Get-FileHash -LiteralPath $p -Algorithm SHA256).Hash}
function BH([byte[]]$b){$s=[Security.Cryptography.SHA256]::Create();try{return([BitConverter]::ToString($s.ComputeHash([byte[]]$b))).Replace('-','')}finally{$s.Dispose()}}
function RB([IO.Compression.ZipArchive]$z,[string]$n,[int64]$max){$e=$z.GetEntry($n);A($null-ne$e -and $e.Length-le$max)"Missing/large response entry: $n";$s=$e.Open();$m=New-Object IO.MemoryStream;try{$s.CopyTo($m);return ,([byte[]]$m.ToArray())}finally{$m.Dispose();$s.Dispose()}}
function W([string]$p,[byte[]]$b){$s=New-Object IO.FileStream($p,[IO.FileMode]::CreateNew,[IO.FileAccess]::Write,[IO.FileShare]::None);try{$s.Write($b,0,$b.Length)}finally{$s.Dispose()}}
function J([string]$p,[object]$v){$b=(New-Object Text.UTF8Encoding($false)).GetBytes((($v|ConvertTo-Json -Depth 14)+[Environment]::NewLine));W $p $b}
$project=[IO.Path]::GetFullPath((Join-Path $PSScriptRoot '..\..'));$requestId='REQ_O2S17B2_20260826';$responseId='R_C20829E77751_20260826202155992_b7e4ed8e';$source='U:\ProjectPortalRO\responses\R_C20829E77751_20260826202155992_b7e4ed8e.ready.zip';$zipBytes=2318240;$zipSha='147871B6A92A5436911F3613BA0BCC309BC86F5F5937BD6504FE84F80F254255';$manifestSha='9AF6363C373177FCCAAE2A1A1EF267D752C9477F46EB88608C7354CB6DF7D2F6';$resultSha='6543F1215C3A171B8C5EC278D0FBC938C7F33FA4F894AC49559CA224BB7D6C1E';$payloadSha='980085612277B0EC51B6FF7E21A8CF3A8F738CD7C6205E7408A80F374EF9273A';$bfSha='46ACA8C9C32850EF052C1BF7F26550EFD474E00372B0F43F0DD391AFEA1A431D';$dfSha='012365504979E0A89E387FBD735E0E60B9B49899FC9A516D05C0BAE0ACC631E9'
$pre=Join-Path $PSScriptRoot 'PREACTION_S17B2_COLLECT.json';A((Get-ExactSha256 $pre)-eq'470EEC9F5A64B2C238422C51E14F2E0AAC8E987DB5360FE9A516DF1EF4791B7E')'Collect preaction changed.';& (Join-Path $project 'utilities\Confirm-ArgosZeroRecurrencePreaction.ps1') -AuditPath (Join-Path $project 'work\ARGOS_HISTORY_NO_REPEAT_AUDIT_20260820.json') -ContractPath $pre -ProjectRoot $project -Preflight|Out-Null
A((Test-Path -LiteralPath $source -PathType Leaf) -and (Get-Item -LiteralPath $source).Length-eq$zipBytes -and (Get-ExactSha256 $source)-eq$zipSha)'Response ZIP changed.'
Add-Type -AssemblyName System.IO.Compression.FileSystem;$z=[IO.Compression.ZipFile]::OpenRead($source)
try{$names=@($z.Entries|ForEach-Object{$_.FullName});A($names.Count-eq4 -and @(Compare-Object @('DATA_PULL_PAYLOAD.zip','PORTAL_RESPONSE_MANIFEST.json','PORTAL_RESPONSE_MANIFEST.sig','RESULT.json') $names).Count-eq0)'Response entry set changed.';$mb=RB $z 'PORTAL_RESPONSE_MANIFEST.json' 1048576;$sb=RB $z 'PORTAL_RESPONSE_MANIFEST.sig' 4096;$rb=RB $z 'RESULT.json' 1048576;$pe=$z.GetEntry('DATA_PULL_PAYLOAD.zip');$ps=$pe.Open();$sha=[Security.Cryptography.SHA256]::Create();try{$ph=([BitConverter]::ToString($sha.ComputeHash($ps))).Replace('-','')}finally{$sha.Dispose();$ps.Dispose()}}finally{$z.Dispose()}
A((BH $mb)-eq$manifestSha -and (BH $rb)-eq$resultSha -and $ph-eq$payloadSha)'Signed response content changed.';$m=[Text.Encoding]::UTF8.GetString($mb)|ConvertFrom-Json;$r=[Text.Encoding]::UTF8.GetString($rb)|ConvertFrom-Json
A([string]$m.requestId-eq$requestId -and [string]$m.responseId-eq$responseId -and [string]$m.state-eq'PASS_DATA_PULL' -and [string]$m.signerThumbprint-eq'DF46FA4B81065AB273A88F4E1FA8AC0F2EE518CC' -and [bool]$m.reviewOnly -and -not[bool]$m.productionRoutingEnabled)'Signed manifest changed.'
$cert=New-Object Security.Cryptography.X509Certificates.X509Certificate2((Join-Path $project 'work\PROJECT_PORTAL_REVIEW_ONLY\enrollment\active\JBOD_ENDPOINT_SIGNER.cer'));$rsa=[Security.Cryptography.X509Certificates.RSACertificateExtensions]::GetRSAPublicKey($cert);try{$sig=$rsa.VerifyData($mb,$sb,[Security.Cryptography.HashAlgorithmName]::SHA256,[Security.Cryptography.RSASignaturePadding]::Pkcs1)}finally{$rsa.Dispose()};A($sig -and $cert.Thumbprint-eq'DF46FA4B81065AB273A88F4E1FA8AC0F2EE518CC')'Response signature failed.'
A([string]$r.schema-eq'argos_project_portal_data_pull_result_v2' -and [string]$r.state-eq'PASS_DATA_PULL' -and [string]$r.approvedRoot-eq'JBOD_PROCESSOR_REVIEW' -and [string]$r.containerSha256-eq$payloadSha -and @($r.files).Count-eq2)'DATA_PULL result changed.'
$bf=@($r.files|Where-Object{[string]$_.relativePath-like'*/BF_SCRIBE_ORIENTED_DETECTOR_INPUT.png'});$df=@($r.files|Where-Object{[string]$_.relativePath-like'*/DF_SCRIBE_ORIENTED_DETECTOR_INPUT.png'});A($bf.Count-eq1 -and $df.Count-eq1 -and [string]$bf[0].sha256-eq$bfSha -and [string]$df[0].sha256-eq$dfSha -and [int64]$bf[0].bytes-eq1642696 -and [int64]$df[0].bytes-eq672445)'Slot17 hash rows changed.'
$out=Join-Path $PSScriptRoot 'collected_metadata';$gate=Join-Path $PSScriptRoot 'S17B2_TERMINAL_RESPONSE_GATE.json';A(-not(Test-Path -LiteralPath $out) -and -not(Test-Path -LiteralPath $gate))'Collection output exists.';$path=& (Join-Path $project 'utilities\Confirm-ArgosPathBudget.ps1') -CandidatePath @((Join-Path $out 'PORTAL_RESPONSE_MANIFEST.json'),(Join-Path $out 'RESULT.json'),(Join-Path $out 'PORTAL_RESPONSE_MANIFEST.sig'),$gate) -ReservedSuffixCharacters 32 -AsJson|ConvertFrom-Json;A([string]$path.state-eq'PASS_PATH_BUDGET')'Collection path budget failed.'
$g=[ordered]@{schema='argos_s17b2_terminal_response_gate_v1';collectedUtc=[DateTime]::UtcNow.ToString('o');state='PASS_S17B2_SIGNED_SLOT17_ORIENTED_INPUT_HASH_BINDING';disposition='APPROVED_BASELINE';requestId=$requestId;responseId=$responseId;endpointState='PASS_DATA_PULL';signedResponseVerified=$true;signerThumbprint=[string]$m.signerThumbprint;sourceZip=$source;sourceZipBytes=$zipBytes;sourceZipSha256=$zipSha;responseManifestSha256=$manifestSha;resultSha256=$resultSha;payloadSha256=$payloadSha;bfPath=[string]$bf[0].relativePath;bfBytes=[int64]$bf[0].bytes;bfSha256=$bfSha;dfPath=[string]$df[0].relativePath;dfBytes=[int64]$df[0].bytes;dfSha256=$dfSha;sourceImageBytesReadByEndpoint=$true;payloadImagesExtractedLocally=$false;pixelsDecoded=$false;requestRetried=$false;taskOrProcessActionPerformed=$false;sourceMutationPerformed=$false;providerActivated=$false;slots22Through25Exposed=$false;reviewOnly=$true;trainingEligible=$false;xmlEligible=$false;productionEligible=$false;productionRoutingEnabled=$false}
if($Preflight){$g.state='PASS_S17B2_RESPONSE_COLLECTION_PREFLIGHT';$g.mutationsPerformed=$false;$g|ConvertTo-Json -Depth 14;return}
[void][IO.Directory]::CreateDirectory($out);W (Join-Path $out 'PORTAL_RESPONSE_MANIFEST.json') $mb;W (Join-Path $out 'PORTAL_RESPONSE_MANIFEST.sig') $sb;W (Join-Path $out 'RESULT.json') $rb;J $gate $g;$g|ConvertTo-Json -Depth 14
