#Requires -Version 5.1
[CmdletBinding()]
param([Parameter(Mandatory=$true)][string]$InvocationManifest,[switch]$Preflight,[switch]$Publish)
Set-StrictMode -Version Latest
$ErrorActionPreference='Stop'
function Require([bool]$Condition,[string]$Message){if(-not$Condition){throw $Message}}
function Sha([string]$Path){(Get-FileHash -LiteralPath $Path -Algorithm SHA256 -ErrorAction Stop).Hash}
function Need([object]$Value,[string]$Name){$property=$Value.PSObject.Properties[$Name];if($null-eq$property){throw "F32N1 publication invocation missing $Name"};$property.Value}
function Repo([string]$Root,[string]$Relative){Require (-not[IO.Path]::IsPathRooted($Relative)) "F32N1 dependency must be repository-relative: $Relative";$prefix=[IO.Path]::GetFullPath($Root).TrimEnd('\')+'\';$path=[IO.Path]::GetFullPath((Join-Path $prefix $Relative.Replace('/','\')));Require ($path.StartsWith($prefix,[StringComparison]::OrdinalIgnoreCase)) "F32N1 dependency escapes repository: $Relative";$path}
function Pinned([string]$Path,[string]$Hash,[string]$Label){Require (Test-Path -LiteralPath $Path -PathType Leaf) "$Label absent: $Path";Require ((Sha $Path)-ceq$Hash) "$Label hash changed"}
function Drive([string]$Share){$ps=Get-PSDrive -Name U -PSProvider FileSystem -ErrorAction Stop;$disk=Get-CimInstance Win32_LogicalDisk -Filter "DeviceID='U:'" -ErrorAction Stop;Require ([string]$ps.DisplayRoot-ceq$Share) 'Persistent U: DisplayRoot changed';Require ([string]$disk.ProviderName-ceq$Share-and[int]$disk.DriveType-eq4) 'Persistent U: provider identity changed'}
function Pending([string]$Root){@(Get-ChildItem -LiteralPath $Root -File -ErrorAction Stop|Where-Object{$_.Name-cmatch'\.ready\.zip(?:\.upload)?$'})}
function ZipManifest([string]$Path){Add-Type -AssemblyName System.IO.Compression.FileSystem;$zip=[IO.Compression.ZipFile]::OpenRead($Path);try{$entry=$zip.GetEntry('PORTAL_REQUEST_MANIFEST.json');Require ($null-ne$entry-and$entry.Length-ge2-and$entry.Length-le1048576) 'F32N1 request manifest ZIP entry absent or oversized';$reader=New-Object IO.StreamReader($entry.Open(),(New-Object Text.UTF8Encoding($false,$true)),$true);try{$reader.ReadToEnd()|ConvertFrom-Json}finally{$reader.Dispose()}}finally{$zip.Dispose()}}
function New-Json([string]$Path,[object]$Value){Require (-not(Test-Path -LiteralPath $Path)) "Create-new JSON exists: $Path";[IO.File]::WriteAllText($Path,(($Value|ConvertTo-Json -Depth 24)+[Environment]::NewLine),(New-Object Text.UTF8Encoding($false)))}
Require ($Preflight-xor$Publish) 'Specify exactly one of -Preflight or -Publish';Require ([string]$PSVersionTable.PSEdition-ceq'Desktop'-and[int]$PSVersionTable.PSVersion.Major-eq5-and[int]$PSVersionTable.PSVersion.Minor-eq1) 'F32N1 publisher requires Windows PowerShell 5.1'
$project=[IO.Path]::GetFullPath((Join-Path $PSScriptRoot '..\..'));$expected=Join-Path $PSScriptRoot 'F32N1_PUBLISH_INVOCATION.json';$invPath=[IO.Path]::GetFullPath($InvocationManifest);Require ($invPath.Equals($expected,[StringComparison]::OrdinalIgnoreCase)) 'F32N1 publication invocation path changed';$inv=Get-Content -LiteralPath $invPath -Raw|ConvertFrom-Json
Require ([string](Need $inv 'schema')-ceq'argos_ocv03_f32n1_publish_invocation_v1'-and[string](Need $inv 'state')-ceq'FROZEN_F32N1_EXACTLY_ONCE_PUBLICATION') 'F32N1 publication invocation identity changed';Require ([string](Need $inv 'publisherSha256')-ceq(Sha $PSCommandPath)) 'F32N1 publisher bytes changed';Require ([int](Need $inv 'maximumPublications')-eq1-and-not[bool](Need $inv 'requestRetryAuthorized')) 'F32N1 publication authority changed'
$requestId=[string](Need $inv 'requestId');Require ($requestId-cmatch'^REQ_[0-9]{8}T[0-9]{9}Z_[0-9A-F]{12}$') 'F32N1 request ID shape changed';$source=[IO.Path]::GetFullPath([string](Need $inv 'sourceZip'));$sourceHash=[string](Need $inv 'sourceZipSha256');$sourceBytes=[int64](Need $inv 'sourceZipBytes');Pinned $source $sourceHash 'F32N1 source ZIP';Require ((Get-Item -LiteralPath $source).Length-eq$sourceBytes) 'F32N1 source ZIP bytes changed'
$manifest=ZipManifest $source;Require ([string]$manifest.schema-ceq'argos_project_portal_request_manifest_v1'-and[string]$manifest.requestId-ceq$requestId-and[string]$manifest.targetRole-ceq'JBOD'-and[string]$manifest.jobClass-ceq'MAINTENANCE_PATCH'-and[string]$manifest.entryPoint-ceq'payload/Invoke-F32N1.ps1') 'F32N1 request identity changed';Require ([bool]$manifest.reviewOnly-and-not[bool]$manifest.trainingEligible-and-not[bool]$manifest.xmlEligible-and-not[bool]$manifest.productionEligible-and-not[bool]$manifest.productionRoutingEnabled-and-not[bool]$manifest.requestRetryAuthorized) 'F32N1 request authority widened'
Require ([int]$manifest.sourceProcessingContract.expectedPairCount-eq4-and[int]$manifest.sourceProcessingContract.expectedSourceLeafCount-eq8-and[string]$manifest.sourceProcessingContract.neutralJobSha256-eq'5691BDACCAE668392FE4866851C0F5DE06FE4D6507C627CCCA0B3EEB97A53211'-and[string]$manifest.sourceProcessingContract.runnerSha256-eq'55733DFF1638BA8B00365BC3B7A1D1B0808A06F061D74C5086DEB3664166EA6C') 'F32N1 source contract changed'
Require ([bool]$manifest.timeoutContract.childContinuesAfterLaunchResponse-and[int]$manifest.timeoutContract.bootstrapProgressTimeoutSeconds-eq60-and@($manifest.entryPointOutputs|Where-Object{[bool]$_.requiredAtLaunch}).Count-eq1-and[string]@($manifest.entryPointOutputs|Where-Object{[bool]$_.requiredAtLaunch})[0].path-eq'D:/F32N1S/PROGRESS.json') 'F32N1 launch-only output contract changed'
$routePath=Repo $project ([string](Need $inv 'routeGatePath'));$preactionPath=Repo $project ([string](Need $inv 'preactionContractPath'));$rehearsalPath=Repo $project ([string](Need $inv 'rehearsalGatePath'));$priorPath=Repo $project ([string](Need $inv 'priorTerminalGatePath'));$ols7Path=Repo $project ([string](Need $inv 'ols7EndpointEvidencePath'))
Pinned $routePath ([string](Need $inv 'routeGateSha256')) 'F32N1 route gate';Pinned $preactionPath ([string](Need $inv 'preactionContractSha256')) 'F32N1 preaction contract';Pinned $rehearsalPath ([string](Need $inv 'rehearsalGateSha256')) 'F32N1 rehearsal gate';Pinned $priorPath ([string](Need $inv 'priorTerminalGateSha256')) 'F32N1 prior terminal gate';Pinned $ols7Path ([string](Need $inv 'ols7EndpointEvidenceSha256')) 'OLS7 post-OCR-launch endpoint evidence'
$rzv3Path=[IO.Path]::GetFullPath([string](Need $inv 'r18zv3ProgressEvidencePath'));$ols7Response=[IO.Path]::GetFullPath([string](Need $inv 'ols7SignedResponsePath'));Pinned $rzv3Path ([string](Need $inv 'r18zv3ProgressEvidenceSha256')) 'R18ZV3 direct launch/progress evidence';Pinned $ols7Response ([string](Need $inv 'ols7SignedResponseSha256')) 'OLS7 post-OCR-launch signed response'
$route=Get-Content -LiteralPath $routePath -Raw|ConvertFrom-Json;$preaction=Get-Content -LiteralPath $preactionPath -Raw|ConvertFrom-Json;$rehearsal=Get-Content -LiteralPath $rehearsalPath -Raw|ConvertFrom-Json;$prior=Get-Content -LiteralPath $priorPath -Raw|ConvertFrom-Json;$rzv3=Get-Content -LiteralPath $rzv3Path -Raw|ConvertFrom-Json;$ols7=Get-Content -LiteralPath $ols7Path -Raw|ConvertFrom-Json
Require ([string]$route.state-ceq'PASS_F32N1_COMPLETE_ROUTE_PATH_GATE'-and[string]$route.requestId-ceq$requestId-and[int]$route.payloadFileCount-eq37-and-not[bool]$route.routeImplementationChanged) 'F32N1 route gate changed'
Require ([string]$preaction.state-ceq'PASS_PREACTION_CONTRACT'-and[string]$rehearsal.state-ceq'PASS_F32N1_EXACT_PACKAGED_REHEARSAL') 'F32N1 preaction or packaged rehearsal changed';Require ([string]$prior.launchRequestId-ceq'REQ_20260903T233132021Z_2FA7A30A3BB4'-and[bool]$prior.launchResponseSignatureVerified-and[bool]$prior.resultsPullResponseSignatureVerified) 'Qualified R13T5 predecessor is not signed-terminal'
Require ([string]$rzv3.state-ceq'PASS_ARGOS_ADMIN_CLIPBOARD_ACTION'-and[string]$rzv3.remoteResult.state-ceq'PASS_R18ZV3_CURRENT_STATE_OBSERVATION'-and[string]$rzv3.computerName-ceq'A1025645101'-and-not[bool]$rzv3.remoteResult.mutationsPerformed) 'R18ZV3 direct evidence changed';Require ([string]$ols7.remoteResult.state-ceq'PASS_OLS7_ENDPOINT_STATE_OBSERVATION'-and-not[bool]$ols7.remoteResult.pending-and[string]$ols7.remoteResult.ledger.state-ceq'PASS_MAINTENANCE_PATCH'-and[bool]$ols7.remoteResult.ledger.responseExists) 'OLS7 coexistence evidence changed'
$share='\\shm-cifs\Department\DE-1302_FAB_BE_Engineering\60_Saw_VI_Sort\600_General\Joshua.conn\AVI_Images\Argos\Uploads\InspectionRevs';Require ([string](Need $inv 'expectedPersistentShare')-ceq$share) 'F32N1 publication share changed';Drive $share
$requestRoot='U:\ProjectPortalRO\requests';Require (Test-Path -LiteralPath $requestRoot -PathType Container) 'Project Portal request root unavailable';$ready=Join-Path $requestRoot ($requestId+'.ready.zip');$upload=$ready+'.upload';$gatePath=Join-Path $PSScriptRoot 'F32N1_PUBLISH_GATE.json';$attemptPath=Join-Path $PSScriptRoot 'F32N1_PUBLISH_ATTEMPT.json';Require (-not(Test-Path -LiteralPath $gatePath)) 'F32N1 publication gate already exists';Require (-not(Test-Path -LiteralPath $attemptPath)) 'F32N1 publication attempt already consumed'
$pending=@(Pending $requestRoot);Require ($pending.Count-eq0) ('F32N1 publication blocked by pending request: '+(($pending|ForEach-Object{$_.Name})-join', '));Require (-not(Test-Path -LiteralPath $upload)-and-not(Test-Path -LiteralPath $ready)) 'Exact F32N1 request path already exists'
$pre=[ordered]@{schema='argos_ocv03_f32n1_publish_preflight_v1';createdUtc=[DateTime]::UtcNow.ToString('o');state='PASS_F32N1_EXACTLY_ONCE_PUBLICATION_PREFLIGHT';requestId=$requestId;sourceZip=$source;sourceZipBytes=$sourceBytes;sourceZipSha256=$sourceHash;pendingRequestCount=0;r18zv3RunsIndependently=$true;postR18zv3Ols7RoundTripPassed=$true;ocrCompletionRequired=$false;expectedPersistentShare=$share;uploadPath=$upload;readyPath=$ready;publicationCountMaximum=1;requestRetryAuthorized=$false;mutationsPerformed=$false;reviewOnly=$true;productionRoutingEnabled=$false}
if($Preflight){$pre|ConvertTo-Json -Depth 10;return}
$attempt=[ordered]@{schema='argos_ocv03_f32n1_publish_attempt_v1';createdUtc=[DateTime]::UtcNow.ToString('o');state='STARTED_F32N1_SINGLE_PUBLICATION_ATTEMPT';requestId=$requestId;sourceZipSha256=$sourceHash;sourceZipBytes=$sourceBytes;attemptCount=1;committedBeforeExternalWrite=$true;requestRetryAuthorized=$false};New-Json $attemptPath $attempt
$input=[IO.File]::Open($source,[IO.FileMode]::Open,[IO.FileAccess]::Read,[IO.FileShare]::Read);$output=$null;try{$output=New-Object IO.FileStream($upload,[IO.FileMode]::CreateNew,[IO.FileAccess]::Write,[IO.FileShare]::None);$input.CopyTo($output,1048576);$output.Flush()}finally{if($null-ne$output){$output.Dispose()};$input.Dispose()}
Require ((Get-Item -LiteralPath $upload).Length-eq$sourceBytes-and(Sha $upload)-ceq$sourceHash) 'F32N1 upload verification failed; retained as no-retry hold';Drive $share;$transition=@(Pending $requestRoot);Require ($transition.Count-eq1-and$transition[0].FullName.Equals($upload,[StringComparison]::OrdinalIgnoreCase)-and-not(Test-Path -LiteralPath $ready)) 'F32N1 queue changed before commit; upload retained as no-retry hold';[IO.File]::Move($upload,$ready)
$readyObserved=Test-Path -LiteralPath $ready -PathType Leaf;if($readyObserved){Require ((Get-Item -LiteralPath $ready).Length-eq$sourceBytes-and(Sha $ready)-ceq$sourceHash) 'Published F32N1 request verification failed; no retry authorized'}
$gate=[ordered]@{schema='argos_ocv03_f32n1_publish_gate_v1';createdUtc=[DateTime]::UtcNow.ToString('o');state='PASS_F32N1_PUBLISHED_EXACTLY_ONCE_AWAITING_MATCHING_SIGNED_LAUNCH_RESPONSE';disposition='PENDING_GATE';requestId=$requestId;sourceZip=$source;publishedPath=$ready;publishedBytes=$sourceBytes;publishedSha256=$sourceHash;publicationCount=1;createNewUpload=$true;atomicSameDirectoryUploadToReadyRename=$true;readyObservedAfterCommit=$readyObserved;overwritePerformed=$false;automaticRetryAuthorized=$false;ocrCompletionRequired=$false;mappingCreatedOrRemoved=$false;sourceMutationOrDeletionPerformed=$false;existingTaskOrProcessActionCount=0;imageBytesRead=$false;providerActivated=$false;holdsAutomaticallyCleared=$false;completionClaimed=$false;reviewOnly=$true;trainingEligible=$false;xmlEligible=$false;productionEligible=$false;productionRoutingEnabled=$false};New-Json $gatePath $gate;$gate|ConvertTo-Json -Depth 12
