#Requires -Version 5.1
[CmdletBinding()]
param([switch]$Preflight,[switch]$Sign)
Set-StrictMode -Version Latest
$ErrorActionPreference='Stop'
if(([bool]$Preflight)-eq([bool]$Sign)){throw 'Specify exactly one of -Preflight or -Sign.'}
function Require([bool]$Condition,[string]$Message){if(-not$Condition){throw $Message}}
function Sha([string]$Path){(Get-FileHash -LiteralPath $Path -Algorithm SHA256 -ErrorAction Stop).Hash}
function New-Bytes([string]$Path,[byte[]]$Bytes){Require (-not(Test-Path -LiteralPath $Path)) "Create-new path exists: $Path";[IO.File]::WriteAllBytes($Path,$Bytes)}
function New-Json([string]$Path,[object]$Value){Require (-not(Test-Path -LiteralPath $Path)) "Create-new JSON exists: $Path";[IO.File]::WriteAllText($Path,(($Value|ConvertTo-Json -Depth 20)+[Environment]::NewLine),(New-Object Text.UTF8Encoding($false)))}
$project=[IO.Path]::GetFullPath((Join-Path $PSScriptRoot '..\..'))
$root='C:\F32N1P2';$payload=Join-Path $root 'payload';$definitionPath=Join-Path $root 'DEFINITION.json'
$buildGatePath=Join-Path $PSScriptRoot 'F32N1_BUILD_GATE.json';$signGatePath=Join-Path $PSScriptRoot 'F32N1_SIGN_GATE.json';$finalRoot=Join-Path $PSScriptRoot 'final_f32n1';$signedRoot=Join-Path $root 'signed';$routeGatePath=Join-Path $finalRoot 'F32N1_PREPUBLICATION_PATH_GATE.json'
$identityPath=Join-Path $project 'work\PROJECT_PORTAL_REVIEW_ONLY\state\LAPTOP_SIGNING_IDENTITY.json';$certificatePath=Join-Path $project 'work\PROJECT_PORTAL_REVIEW_ONLY\enrollment\ARGOS_PROJECT_PORTAL_LAPTOP_SIGNER_PUBLIC.cer';$verifier=Join-Path $project 'work\PROJECT_PORTAL_REVIEW_ONLY\scripts\Test-SignedPortalPackage.ps1'
$priorRoutePath=Join-Path $project 'work\OPENCV_EDGE_NOTCH_O3F15L4E3\final_o3f15l4e3\O3F15L4E3_PREPUBLICATION_PATH_R4_GATE.json';$priorRouteHash='94B829E7EAEB852F6CAB6EABA68CCD68B950DC2BB3C69B07607A8E1469B9E6DB'
foreach($path in @($definitionPath,$buildGatePath,$identityPath,$certificatePath,$verifier,$priorRoutePath)){Require (Test-Path -LiteralPath $path -PathType Leaf) "F32N1 signing dependency absent: $path"}
Require ((Sha $priorRoutePath)-eq$priorRouteHash) 'Inherited complete route gate changed'
$buildGate=Get-Content -LiteralPath $buildGatePath -Raw|ConvertFrom-Json;$definition=Get-Content -LiteralPath $definitionPath -Raw|ConvertFrom-Json;$priorRoute=Get-Content -LiteralPath $priorRoutePath -Raw|ConvertFrom-Json
Require ([string]$buildGate.state-eq'PASS_F32N1_UNSIGNED_PACKAGE_BUILT'-and[string]$buildGate.definitionSha256-eq(Sha $definitionPath)-and[int]$buildGate.payloadFileCount-eq37) 'F32N1 build evidence changed'
Require ([string]$definition.state-eq'FROZEN_FOR_SIGNING'-and[string]$definition.targetRole-eq'JBOD'-and[string]$definition.jobClass-eq'MAINTENANCE_PATCH'-and[string]$definition.entryPoint-eq'payload/Invoke-F32N1.ps1') 'F32N1 definition is not frozen for signing'
Require (@($definition.changes).Count-eq1-and@($definition.allowedTaskActions).Count-eq0-and@($definition.allowedProcessActions).Count-eq2-and[int]$definition.sourceProcessingContract.expectedPairCount-eq4-and[int]$definition.sourceProcessingContract.expectedSourceLeafCount-eq8-and[string]$definition.sourceProcessingContract.side-eq'FRONT') 'F32N1 maintenance bounds changed'
Require ([bool]$definition.reviewOnly-and-not[bool]$definition.trainingEligible-and-not[bool]$definition.xmlEligible-and-not[bool]$definition.productionEligible-and-not[bool]$definition.productionRoutingEnabled-and-not[bool]$definition.requestRetryAuthorized) 'F32N1 authority widened'
$change=@($definition.changes)[0];$carrierHash='6B7CC6E643265545297BA4DED1E6B37AB262349572194B13F79264EF77D8DCE4'
Require ([string]$change.source-eq'payload/OCV03_NotchReviewOpenCvV1.py'-and[string]$change.destination-eq'C:/ProgramData/ArgosEdgeLabRO/AllWaferProcessorV2/OCV03_NotchReviewOpenCvV1.py'-and[string]$change.installedSha256-eq$carrierHash-and@($change.approvedPredecessorSha256).Count-eq1-and([string]@($change.approvedPredecessorSha256)[0])-eq$carrierHash-and-not[bool]$change.allowCreate-and[bool]$change.sameBytesCarrier-and-not[bool]$change.installedSemanticChange) 'F32N1 same-bytes carrier changed'
Require ([string]$buildGate.endpointWorkerSha256-eq'CB6700714E20DAC2D3C097095A2800C92ECAAC75F29878F4C86326493B246250'-and[string]$buildGate.installedRouteConfigEvidenceSha256-eq'465107D861E8D2C376A419B1C15841BE3A5757C6498C36CA56B9A95A2F0B76DB'-and[string]$buildGate.queueSafetyGateSha256-eq'170015C259C3EC8FC0B369F070748A555336F8FB312636819B7F99EBCE85A65D'-and[string]$buildGate.completeRouteGateSha256-eq'932C792DA3095FA43FF1749775D7F4BD3473FA6043ABE86C449FBA16A3914F3A') 'Inherited portal route evidence changed'
Require ([string]$priorRoute.state-eq'PASS_O3F15L4E3_COMPLETE_ROUTE_PATH_R4_GATE'-and[string]$priorRoute.pathDisposition-eq'PASS_ALL_CONSTRUCTED_LEAVES_EFFECTIVE_LT_200_COMPONENT_LE_80'-and[bool]$priorRoute.reviewOnly-and-not[bool]$priorRoute.requestRetryAuthorized) 'Inherited route gate state changed'
$actual=@(Get-ChildItem -LiteralPath $payload -Force|Sort-Object Name);Require ($actual.Count-eq37-and@($actual|Where-Object{-not$_.PSIsContainer}).Count-eq37) 'F32N1 payload cardinality changed'
foreach($row in @($buildGate.payloadFiles)){$path=Join-Path $payload ([string]$row.path);Require (Test-Path -LiteralPath $path -PathType Leaf) "F32N1 payload absent: $($row.path)";Require ((Get-Item -LiteralPath $path).Length-eq[int64]$row.bytes-and(Sha $path)-eq[string]$row.sha256) "F32N1 payload changed: $($row.path)"}
function Get-RouteGate([string]$RequestId,[string[]]$PayloadLeaves,[string]$ManifestHash,[string]$SignatureHash,[string]$Lifecycle){
    $oldId=[string]$priorRoute.requestId;$rows=New-Object Collections.Generic.List[object];$payloadParents=@{}
    foreach($row in @($priorRoute.routePaths)){$path=([string]$row.path).Replace($oldId,$RequestId).Replace('O3F15L4E3','F32N1').Replace('o3f15l4e3','f32n1');$match=[regex]::Match($path,'(?i)^(.*[\\/]payload[\\/])[^\\/]+$');if($match.Success){$key=[string]$row.stage+'|'+$match.Groups[1].Value;$payloadParents[$key]=[pscustomobject]@{stage=[string]$row.stage;prefix=$match.Groups[1].Value}}else{$rows.Add([pscustomobject]@{stage=[string]$row.stage;path=$path})}}
    Require ($payloadParents.Count-eq11) 'Inherited payload route-stage count changed'
    foreach($parent in @($payloadParents.Values)){foreach($leaf in $PayloadLeaves){$rows.Add([pscustomobject]@{stage=[string]$parent.stage;path=[string]$parent.prefix+$leaf})}}
    foreach($item in @(
        [pscustomobject]@{stage='jbod_runtime';path='D:\F32N1RT\AnnularUnwrapCandidateFirstOpenCvR27.py'},
        [pscustomobject]@{stage='jbod_result';path='D:\ArgosProjectPortalRO\OCV03ReviewExports\F32N1\cases\C0004\PAIR_OVERVIEW.png'},
        [pscustomobject]@{stage='jbod_result';path='D:\ArgosProjectPortalRO\OCV03ReviewExports\F32N1\cases\C0004\DF_CROP_999.png'},
        [pscustomobject]@{stage='jbod_result';path='D:\ArgosProjectPortalRO\OCV03ReviewExports\F32N1\SOURCE_POPULATION_GATE.json'},
        [pscustomobject]@{stage='jbod_result';path='D:\ArgosProjectPortalRO\OCV03ReviewExports\F32N1\NEUTRAL_POPULATION_FREEZE.json'},
        [pscustomobject]@{stage='jbod_result';path='D:\ArgosProjectPortalRO\OCV03ReviewExports\F32N1\RESULTS.json'},
        [pscustomobject]@{stage='jbod_mirror';path='D:\F32N1S\NEUTRAL_POPULATION_FREEZE.json'},
        [pscustomobject]@{stage='jbod_alias';path='Q:\BrightfieldFrontsideWafer\resizedImage\62636-134_Slot01_BrightfieldFrontsideWafer_PM2_resizedImage.bmp'},
        [pscustomobject]@{stage='jbod_alias';path='Q:\DarkfieldFrontsideWafer\resizedImage\62636-134_Slot01_DarkfieldFrontsideWafer_PM2_resizedImage.bmp'})){$rows.Add($item)}
    $semantic=$rows.ToArray();$normalized=@($semantic|ForEach-Object{[IO.Path]::GetFullPath([string]$_.path)}|Sort-Object -Unique)
    $budget=& (Join-Path $project 'utilities\Confirm-ArgosPathBudget.ps1') -CandidatePath $normalized -ReservedSuffixCharacters 32 -AsJson|ConvertFrom-Json;Require ([string]$budget.state-eq'PASS_PATH_BUDGET') 'F32N1 complete route path budget failed'
    $measure=@{};foreach($candidate in @($budget.candidates)){$measure[[IO.Path]::GetFullPath([string]$candidate.path)]=$candidate}
    $finalRows=@($semantic|ForEach-Object{$key=[IO.Path]::GetFullPath([string]$_.path);$m=$measure[$key];Require ($null-ne$m) "F32N1 route measurement absent: $key";[pscustomobject]@{stage=[string]$_.stage;path=$key;rawLength=[int]$m.pathLength;effectiveLength=[int]$m.effectiveLength;maximumComponentLength=[int]$m.longestComponentLength;disposition=[string]$m.disposition}})
    $maxRow=$finalRows|Sort-Object effectiveLength -Descending|Select-Object -First 1;Require ([int]$maxRow.effectiveLength-lt200-and@($finalRows|Where-Object{[int]$_.maximumComponentLength-gt80}).Count-eq0) 'F32N1 route limit changed'
    [ordered]@{schema='argos_ocv03_f32n1_complete_route_path_gate_v1';createdUtc=[DateTime]::UtcNow.ToString('o');state=$(if($Lifecycle-eq'FROZEN'){'PASS_F32N1_COMPLETE_ROUTE_PATH_GATE'}else{'PASS_F32N1_COMPLETE_ROUTE_PATH_PREFLIGHT'});lifecycle=$Lifecycle;requestId=$RequestId;manifestSha256=$ManifestHash;signatureSha256=$SignatureHash;installedRouteRevision='O3F15L4E3_R4_INHERITED_BY_O3F8R13T5';endpointWorkerSha256=[string]$buildGate.endpointWorkerSha256;installedRouteConfigEvidenceSha256=[string]$buildGate.installedRouteConfigEvidenceSha256;inheritedQueueSafetyGateSha256=[string]$buildGate.queueSafetyGateSha256;completeRouteGateSha256=[string]$buildGate.completeRouteGateSha256;routeImplementationChanged=$false;payloadFileCount=$PayloadLeaves.Count;routePathCount=$finalRows.Count;maximumEffectiveLength=[int]$maxRow.effectiveLength;maximumComponentLength=($finalRows|Measure-Object maximumComponentLength -Maximum).Maximum;reservedSuffixCharacters=32;routePaths=$finalRows;disposition='PASS';published=$false;targetExecuted=$false;reviewOnly=$true}
}
$identity=Get-Content -LiteralPath $identityPath -Raw|ConvertFrom-Json;$thumb=([string]$identity.thumbprint).Replace(' ','').ToUpperInvariant();$certificate=Get-Item -LiteralPath ("Cert:\CurrentUser\My\$thumb") -ErrorAction Stop;Require ([bool]$certificate.HasPrivateKey) 'F32N1 signer private key unavailable'
$plannedRequest='REQ_20260911T235959999Z_0123456789AB';$plannedReady=Join-Path $signedRoot ($plannedRequest+'.ready');$plannedZip=Join-Path $finalRoot ($plannedRequest+'.ready.zip')
$pathGate=& (Join-Path $project 'utilities\Confirm-ArgosPathBudget.ps1') -CandidatePath @($finalRoot,$signedRoot,(Join-Path $plannedReady 'payload\AnnularUnwrapCandidateFirstOpenCvR27.py'),(Join-Path $plannedReady 'PORTAL_REQUEST_MANIFEST.json'),$plannedZip,$signGatePath,$routeGatePath) -ReservedSuffixCharacters 32 -AsJson|ConvertFrom-Json;Require ([string]$pathGate.state-eq'PASS_PATH_BUDGET') 'F32N1 final package path gate failed'
$plannedRoute=Get-RouteGate $plannedRequest @($actual.Name) ('0'*64) ('0'*64) 'DRAFT';Require ([string]$plannedRoute.state-eq'PASS_F32N1_COMPLETE_ROUTE_PATH_PREFLIGHT') 'F32N1 route preflight changed'
foreach($path in @($finalRoot,$signedRoot,$signGatePath)){Require (-not(Test-Path -LiteralPath $path)) "Create-new F32N1 signing target exists: $path"}
if($Preflight){[ordered]@{schema='argos_ocv03_f32n1_sign_preflight_v1';state='PASS_F32N1_SIGN_PREFLIGHT';definitionSha256=Sha $definitionPath;buildGateSha256=Sha $buildGatePath;payloadFileCount=$actual.Count;finalRoot=$finalRoot;pathState=[string]$pathGate.state;routePathState=[string]$plannedRoute.state;routeMaximumEffectiveLength=[int]$plannedRoute.maximumEffectiveLength;signerThumbprint=$thumb;expectedPairCount=4;side='FRONT';targetExecuted=$false;mutationsPerformed=$false;reviewOnly=$true;productionRoutingEnabled=$false}|ConvertTo-Json -Depth 8;return}
[void](New-Item -ItemType Directory -Path $finalRoot);[void](New-Item -ItemType Directory -Path $signedRoot)
$created=[DateTimeOffset]::UtcNow;$requestId='REQ_'+$created.ToString('yyyyMMddTHHmmssfffZ')+'_'+([Guid]::NewGuid().ToString('N').Substring(0,12).ToUpperInvariant());$partial=Join-Path $signedRoot ($requestId+'.partial');$ready=Join-Path $signedRoot ($requestId+'.ready')
[void](New-Item -ItemType Directory -Path (Join-Path $partial 'payload') -Force);foreach($item in $actual){[IO.File]::Copy($item.FullName,(Join-Path (Join-Path $partial 'payload') $item.Name),$false)}
$files=@(Get-ChildItem -LiteralPath (Join-Path $partial 'payload') -File|Sort-Object Name|ForEach-Object{[ordered]@{path='payload/'+$_.Name;bytes=[int64]$_.Length;sha256=Sha $_.FullName}});Require ($files.Count-eq37) 'F32N1 signed payload cardinality changed'
$manifest=[ordered]@{schema='argos_project_portal_request_manifest_v1';requestId=$requestId;createdUtc=$created.ToString('o');expiresUtc=$created.AddHours(24).ToString('o');targetRole='JBOD';jobClass='MAINTENANCE_PATCH';handler='';maxResultBytes=[int64]$definition.maxResultBytes;reviewOnly=$true;trainingEligible=$false;xmlEligible=$false;productionEligible=$false;productionRoutingEnabled=$false;credentialsIncluded=$false;signerThumbprint=$thumb;signatureAlgorithm='RSA-SHA256-PKCS1';files=$files;entryPoint=[string]$definition.entryPoint;changes=@($definition.changes);entryPointMutations=@($definition.entryPointMutations);entryPointOutputs=@($definition.entryPointOutputs);sourceProcessingContract=$definition.sourceProcessingContract;timeoutContract=$definition.timeoutContract;allowedTaskActions=@();allowedProcessActions=@($definition.allowedProcessActions);rehearsal=$definition.rehearsal;requestRetryAuthorized=$false}
$bytes=(New-Object Text.UTF8Encoding($false)).GetBytes(($manifest|ConvertTo-Json -Depth 32));New-Bytes (Join-Path $partial 'PORTAL_REQUEST_MANIFEST.json') $bytes
$rsa=[Security.Cryptography.X509Certificates.RSACertificateExtensions]::GetRSAPrivateKey($certificate);try{$signature=$rsa.SignData($bytes,[Security.Cryptography.HashAlgorithmName]::SHA256,[Security.Cryptography.RSASignaturePadding]::Pkcs1)}finally{$rsa.Dispose()};New-Bytes (Join-Path $partial 'PORTAL_REQUEST_MANIFEST.sig') $signature
Move-Item -LiteralPath $partial -Destination $ready;& $verifier -PackagePath $ready -SignerCertificatePath $certificatePath -ExpectedTargetRole JBOD -ExpectedJobClass MAINTENANCE_PATCH|Out-Null
Add-Type -AssemblyName System.IO.Compression.FileSystem;$zip=Join-Path $finalRoot ($requestId+'.ready.zip');[IO.Compression.ZipFile]::CreateFromDirectory($ready,$zip,[IO.Compression.CompressionLevel]::Optimal,$false)
$manifestHash=Sha (Join-Path $ready 'PORTAL_REQUEST_MANIFEST.json');$signatureHash=Sha (Join-Path $ready 'PORTAL_REQUEST_MANIFEST.sig');$route=Get-RouteGate $requestId @($actual.Name) $manifestHash $signatureHash 'FROZEN';New-Json $routeGatePath $route
$gate=[ordered]@{schema='argos_ocv03_f32n1_sign_gate_v1';createdUtc=[DateTime]::UtcNow.ToString('o');state='PASS_F32N1_SIGNED_LAUNCH_ONLY_PACKAGE';requestId=$requestId;finalRoot=$finalRoot;packagePath=$ready;packageZipPath=$zip;packageZipBytes=[int64](Get-Item -LiteralPath $zip).Length;packageZipSha256=Sha $zip;manifestSha256=$manifestHash;signatureSha256=$signatureHash;routeGatePath=$routeGatePath;routeGateSha256=Sha $routeGatePath;routeMaximumEffectiveLength=[int]$route.maximumEffectiveLength;signerThumbprint=$thumb;exactPackageSignaturePassed=$true;payloadFileCount=$files.Count;pythonCacheLeafCount=0;contractSha256=[string]$buildGate.contractSha256;expectedPairCount=4;expectedSourceLeafCount=8;side='FRONT';runnerSha256=[string]$buildGate.runnerSha256;adapterSha256=[string]$buildGate.adapterSha256;neutralJobSha256=[string]$buildGate.neutralJobSha256;unreadHoldoutPartitionSha256=[string]$buildGate.unreadHoldoutPartitionSha256;endpointWorkerSha256=[string]$buildGate.endpointWorkerSha256;installedRouteConfigEvidenceSha256=[string]$buildGate.installedRouteConfigEvidenceSha256;queueSafetyGateSha256=[string]$buildGate.queueSafetyGateSha256;completeRouteGateSha256=[string]$buildGate.completeRouteGateSha256;allowedTaskActionCount=0;completionClaimed=$false;signed=$true;published=$false;targetExecuted=$false;mutationsPerformed=$false;reviewOnly=$true;productionRoutingEnabled=$false}
New-Json $signGatePath $gate;$gate|ConvertTo-Json -Depth 10
