[CmdletBinding()]
param([switch]$Preflight,[switch]$Collect)

$ErrorActionPreference='Stop';Set-StrictMode -Version Latest
if(([bool]$Preflight)-eq([bool]$Collect)){throw 'Specify exactly one of -Preflight or -Collect.'}
$project='C:\Users\joshua.conn\Desktop\ArgosDev\ArgosEdgeLab';$root=Join-Path $project 'work\V40';$requestId='REQ_V40_0821_1615_X1';$requestCreatedUtc=[DateTimeOffset]::Parse('2026-08-21T16:13:00Z',[Globalization.CultureInfo]::InvariantCulture,[Globalization.DateTimeStyles]::RoundtripKind);$localRoot='C:\V40S1'
$publishGatePath=Join-Path $root 'C2V40_PUBLISH_GATE_JBOD.json';$routeGatePath=Join-Path $root 'C2V40_RESPONSE_ROUTE_GATE.json';$terminalGatePath=Join-Path $root 'C2V40_TERMINAL_RESPONSE_GATE.json';$preactionPath=Join-Path $root 'PREACTION_COLLECT_JBOD.json'
$audit=Join-Path $project 'work\ARGOS_HISTORY_NO_REPEAT_AUDIT_20260820.json';$preactionTool=Join-Path $project 'utilities\Confirm-ArgosZeroRecurrencePreaction.ps1';$pathTool=Join-Path $project 'utilities\Confirm-ArgosPathBudget.ps1';$responseVerifier=Join-Path $project 'work\PROJECT_PORTAL_REVIEW_ONLY\scripts\Test-SignedPortalResponse.ps1';$certPath=Join-Path $project 'work\PROJECT_PORTAL_REVIEW_ONLY\enrollment\active\JBOD_ENDPOINT_SIGNER.cer'
$share='\\shm-cifs\Department\DE-1302_FAB_BE_Engineering\60_Saw_VI_Sort\600_General\Joshua.conn\AVI_Images\Argos\Uploads\InspectionRevs';$requestRoot=Join-Path $share 'ProjectPortalRO\requests';$responseRoot=Join-Path $share 'ProjectPortalRO\responses';$shortResponseRoot='U:\ProjectPortalRO\responses'
$utf8=New-Object Text.UTF8Encoding($false,$true);$utf8NoBom=New-Object Text.UTF8Encoding($false)
function Bytes-Sha([byte[]]$Bytes){$sha=[Security.Cryptography.SHA256]::Create();try{return([BitConverter]::ToString($sha.ComputeHash($Bytes))).Replace('-','')}finally{$sha.Dispose()}}
function Exact-Entry([IO.Compression.ZipArchive]$Archive,[string]$Name){$entries=@($Archive.Entries|Where-Object{[string]$_.FullName-eq$Name});if($entries.Count-ne1){throw "C2R expected one response entry: $Name"};return $entries[0]}
function Read-Entry([IO.Compression.ZipArchiveEntry]$Entry,[int64]$Maximum){if($Entry.Length-gt$Maximum){throw "C2R response entry too large: $($Entry.FullName)"};$stream=$Entry.Open();try{$memory=New-Object IO.MemoryStream;try{$stream.CopyTo($memory);return,$memory.ToArray()}finally{$memory.Dispose()}}finally{$stream.Dispose()}}
function Write-NewJson([string]$Path,[object]$Value){if(Test-Path -LiteralPath $Path){throw "C2R evidence already exists: $Path"};$partial=$Path+'.partial';if(Test-Path -LiteralPath $partial){throw "C2R evidence partial exists: $partial"};[IO.File]::WriteAllText($partial,(($Value|ConvertTo-Json -Depth 16)+[Environment]::NewLine),$utf8NoBom);Move-Item -LiteralPath $partial -Destination $Path}
foreach($path in @($publishGatePath,$preactionPath,$audit,$preactionTool,$pathTool,$responseVerifier,$certPath)){if(-not(Test-Path -LiteralPath $path -PathType Leaf)){throw "C2R response prerequisite missing: $path"}}
if(Test-Path -LiteralPath $terminalGatePath){throw "C2R terminal gate already exists: $terminalGatePath"};if(Test-Path -LiteralPath $routeGatePath){throw "C2R response route gate already exists: $routeGatePath"};if(Test-Path -LiteralPath $localRoot){throw "Fresh C2R response root required: $localRoot"}
&$preactionTool -AuditPath $audit -ContractPath $preactionPath -ProjectRoot $project|Out-Null
$publish=Get-Content -Raw -LiteralPath $publishGatePath|ConvertFrom-Json;if([string]$publish.requestId-ne$requestId-or[string]$publish.state-ne'PASS_C2V40_EXACT_SIGNED_REQUEST_PUBLISHED_CREATE_NEW'-or[bool]$publish.overwritePerformed-or[int]$publish.pendingRequestsAtApply-ne0-or-not[bool]$publish.processedArchiveCollisionChecked){throw 'C2V40 publication contract changed.'}
if(-not(Test-Path -LiteralPath $responseRoot -PathType Container)){throw 'C2R response share unavailable.'}
Add-Type -AssemblyName System.IO.Compression.FileSystem
$pending=@(Get-ChildItem -LiteralPath $requestRoot -File -ErrorAction Stop|Where-Object{$_.Name-match'\.ready\.zip(\.upload)?$'})
$certificate=New-Object Security.Cryptography.X509Certificates.X509Certificate2($certPath);$candidates=New-Object Collections.Generic.List[object]
foreach($item in @(Get-ChildItem -LiteralPath $responseRoot -File -Filter '*.ready.zip' -ErrorAction Stop|Sort-Object LastWriteTimeUtc -Descending|Select-Object -First 100)){
    $archive=[IO.Compression.ZipFile]::OpenRead($item.FullName);try{try{$manifestBytes=Read-Entry (Exact-Entry $archive 'PORTAL_RESPONSE_MANIFEST.json') 1048576}catch{continue};$manifest=$utf8.GetString($manifestBytes)|ConvertFrom-Json;if([string]$manifest.requestId-ne$requestId){continue};$responseCreatedUtc=[DateTimeOffset]::Parse([string]$manifest.createdUtc,[Globalization.CultureInfo]::InvariantCulture,[Globalization.DateTimeStyles]::RoundtripKind);if($responseCreatedUtc-le$requestCreatedUtc){continue};$signatureBytes=Read-Entry (Exact-Entry $archive 'PORTAL_RESPONSE_MANIFEST.sig') 4096;$rsa=[Security.Cryptography.X509Certificates.RSACertificateExtensions]::GetRSAPublicKey($certificate);try{$valid=$rsa.VerifyData($manifestBytes,$signatureBytes,[Security.Cryptography.HashAlgorithmName]::SHA256,[Security.Cryptography.RSASignaturePadding]::Pkcs1)}finally{$rsa.Dispose()};if(-not$valid){throw 'C2R endpoint response signature is invalid.'};foreach($record in @($manifest.files)){$entry=Exact-Entry $archive ([string]$record.path);$declared=[int64]$record.bytes;if($declared-lt0-or$declared-gt4194304){throw "C2R response file size is invalid: $($record.path)"};$bytes=Read-Entry $entry ([Math]::Max($declared,[int64]1));if($bytes.LongLength-ne$declared-or(Bytes-Sha $bytes)-ne[string]$record.sha256){throw "C2R response file changed: $($record.path)"}};$candidates.Add([pscustomobject]@{item=$item;manifest=$manifest;zipSha256=(Get-FileHash -Algorithm SHA256 -LiteralPath $item.FullName).Hash;zipBytes=$item.Length})}finally{$archive.Dispose()}
}
if($candidates.Count-eq0){if($Preflight){[ordered]@{schema='argos_c2r_response_pending_v1';createdUtc=[DateTime]::UtcNow.ToString('o');state='PENDING_C2R_SIGNED_TERMINAL_RESPONSE';requestId=$requestId;pendingRequests=$pending.Count;responseCandidates=0;mutationsPerformed=$false;reviewOnly=$true;productionRoutingEnabled=$false}|ConvertTo-Json -Depth 5;return};throw 'C2R response unavailable.'}
if($candidates.Count-ne1){throw "Expected one C2R response; found $($candidates.Count)."};if($pending.Count-ne0){throw ('Portal request remains pending: '+(($pending|Select-Object -First 5|ForEach-Object{$_.Name})-join', '))}
$candidate=$candidates[0];$responseId=[string]$candidate.manifest.responseId;if($responseId-notmatch'^R_[A-F0-9]{12}_[0-9]{17}(?:_[A-Fa-f0-9]{8})?$'){throw 'C2R response identity is not path bounded.'}
$shortZip=$shortResponseRoot.TrimEnd('\')+'\'+$candidate.item.Name;$localZip=Join-Path $localRoot ($responseId+'.ready.zip');$partial=Join-Path $localRoot ($responseId+'.partial');$ready=Join-Path $localRoot ($responseId+'.ready')
$pathGate=&$pathTool -CandidatePath @($shortZip,$localZip,(Join-Path $partial 'PORTAL_RESPONSE_MANIFEST.json'),(Join-Path $ready 'MAINTENANCE.stdout.txt'),$routeGatePath,$terminalGatePath) -ReservedSuffixCharacters 32 -AsJson|ConvertFrom-Json;if([string]$pathGate.state-ne'PASS_PATH_BUDGET'){throw 'C2R response path gate failed.'}
if($Preflight){[ordered]@{schema='argos_c2r_response_available_preflight_v1';createdUtc=[DateTime]::UtcNow.ToString('o');state='PASS_C2R_SIGNED_RESPONSE_AVAILABLE_PREFLIGHT';requestId=$requestId;responseId=$responseId;endpointState=[string]$candidate.manifest.state;responseZipSha256=[string]$candidate.zipSha256;responseZipBytes=[int64]$candidate.zipBytes;signatureVerified=$true;pathState=[string]$pathGate.state;mutationsPerformed=$false;reviewOnly=$true;productionRoutingEnabled=$false}|ConvertTo-Json -Depth 6;return}
$existing=Get-PSDrive U -ErrorAction SilentlyContinue;if($null-eq$existing){New-PSDrive -Name U -PSProvider FileSystem -Root $share -Scope Script -ErrorAction Stop|Out-Null}elseif(-not([IO.Path]::GetFullPath([string]$existing.Root).TrimEnd('\')).Equals([IO.Path]::GetFullPath($share).TrimEnd('\'),[StringComparison]::OrdinalIgnoreCase)){throw 'C2R collector U: mapping is not pinned.'}
if(-not(Test-Path -LiteralPath $shortZip -PathType Leaf)-or(Get-FileHash -Algorithm SHA256 -LiteralPath $shortZip).Hash-ne[string]$candidate.zipSha256){throw 'C2R short-path response artifact changed.'}
[void](New-Item -ItemType Directory -Path $localRoot);Copy-Item -LiteralPath $shortZip -Destination $localZip;[void](New-Item -ItemType Directory -Path $partial);[IO.Compression.ZipFile]::ExtractToDirectory($localZip,$partial);&$responseVerifier -PackagePath $partial -EndpointCertificatePath $certPath -ExpectedSourceRole JBOD -ExpectedRequestId $requestId|Out-Null;Move-Item -LiteralPath $partial -Destination $ready
$manifest=Get-Content -Raw -LiteralPath (Join-Path $ready 'PORTAL_RESPONSE_MANIFEST.json')|ConvertFrom-Json;$stdout=$null;$success=$false
if([string]$manifest.state-eq'PASS_MAINTENANCE_PATCH'){$stdoutText=Get-Content -Raw -LiteralPath (Join-Path $ready 'MAINTENANCE.stdout.txt');if([string]::IsNullOrWhiteSpace($stdoutText)){throw 'C2V35 PASS response has empty maintenance stdout.'};$stdout=$stdoutText|ConvertFrom-Json;$success=[string]$stdout.state-eq'PASS_C2V35_BOUNDED_LIVE_SNAPSHOT'}
$route=[ordered]@{schema='argos_c2v22_response_route_gate_v1';createdUtc=[DateTime]::UtcNow.ToString('o');state='PASS_C2V40_EXACT_SIGNED_RESPONSE_ROUTE';requestId=$requestId;responseId=$responseId;responseZipSha256=[string]$candidate.zipSha256;responseZipBytes=[int64]$candidate.zipBytes;shareArtifact=$shortZip;localZip=$localZip;localReady=$ready;signatureVerified=$true;pathState=[string]$pathGate.state;shareResponseRetained=$true;reviewOnly=$true;productionRoutingEnabled=$false};Write-NewJson $routeGatePath $route
if($success){$terminal=[ordered]@{schema='argos_c2v29_terminal_response_gate_v1';createdUtc=[DateTime]::UtcNow.ToString('o');state='PASS_C2V40_SIGNED_TERMINAL_RESPONSE';terminal=$true;requestId=$requestId;responseId=$responseId;endpointState=[string]$manifest.state;stdoutState=[string]$stdout.state;responseZipSha256=[string]$candidate.zipSha256;responseZipBytes=[int64]$candidate.zipBytes;signatureVerified=$true;lot=[string]$stdout.lot;scanDate=[string]$stdout.scanDate;disposition=[string]$stdout.disposition;configSha256=[string]$stdout.configSha256;targetRequestSha256=[string]$stdout.targetRequestSha256;targetResponseId=[string]$stdout.targetResponseId;targetPackageLocations=@($stdout.targetPackageLocations);targetPackageSnapshots=@($stdout.targetPackageSnapshots);responseAcquisitionKeys=@($stdout.responseAcquisitionKeys);processedPayload=$stdout.processedPayload;responseShape=$stdout.responseShape;runtimePaths=$stdout.runtimePaths;runtimeHashes=$stdout.runtimeHashes;exporterSha256=[string]$stdout.exporterSha256;lastQueuedMatchesTarget=[bool]$stdout.lastQueuedMatchesTarget;lastQueuedRequest=$stdout.lastQueuedRequest;lastImportedMatchesTarget=[bool]$stdout.lastImportedMatchesTarget;lastImportedResponse=$stdout.lastImportedResponse;frontCatalogRows=[int]$stdout.frontCatalogRows;distinctFrontPhysicalIdentities=[int]$stdout.distinctFrontPhysicalIdentities;frontSlots=@($stdout.frontSlots);frontPhysicalIdentities=@($stdout.frontPhysicalIdentities);frontRows=@($stdout.frontRows);targetLedgerRows=@($stdout.targetLedgerRows);dashboardReadiness=$stdout.dashboardReadiness;targetDashboardExclusions=@($stdout.targetDashboardExclusions);targetProposals=@($stdout.targetProposals);targetConfirmedRows=@($stdout.targetConfirmedRows);priorLotScribes=@($stdout.priorLotScribes);targetVerifiedRows=@($stdout.targetVerifiedRows);targetActiveHolds=@($stdout.targetActiveHolds);candidateAuditFilesInspected=[int]$stdout.candidateAuditFilesInspected;targetCandidateResolutions=@($stdout.targetCandidateResolutions);dashboardSessions=@($stdout.dashboardSessions);catalogAcceptance=[bool]$stdout.catalogAcceptance;guiAcceptance=[bool]$stdout.guiAcceptance;fullQueueEnumerationPerformed=[bool]$stdout.fullQueueEnumerationPerformed;catalogReadPerformed=[bool]$stdout.catalogReadPerformed;dashboardReadPerformed=[bool]$stdout.dashboardReadPerformed;historicalRootEnumerationPerformed=[bool]$stdout.historicalRootEnumerationPerformed;imageFilesRead=[bool]$stdout.imageFilesRead;sourceDeletionPerformed=[bool]$stdout.sourceDeletionPerformed;inspectionTasksChanged=[bool]$stdout.inspectionTasksChanged;trayRestarted=[bool]$stdout.trayRestarted;waferAborted=[bool]$stdout.waferAborted;reviewOnly=$true;xmlExportEnabled=[bool]$stdout.xmlExportEnabled;productionRoutingEnabled=$false}}
else{$failurePath=Join-Path $ready 'FAILURE.json';$stderrPath=Join-Path $ready 'MAINTENANCE.stderr.txt';$failureSha=if(Test-Path -LiteralPath $failurePath){(Get-FileHash -Algorithm SHA256 -LiteralPath $failurePath).Hash}else{''};$stderrSha=if(Test-Path -LiteralPath $stderrPath){(Get-FileHash -Algorithm SHA256 -LiteralPath $stderrPath).Hash}else{''};$terminal=[ordered]@{schema='argos_c2v24_terminal_response_gate_v1';createdUtc=[DateTime]::UtcNow.ToString('o');state='FAIL_C2V40_SIGNED_TERMINAL_RESPONSE';terminal=$true;requestId=$requestId;responseId=$responseId;endpointState=[string]$manifest.state;detail=[string]$manifest.detail;responseZipSha256=[string]$candidate.zipSha256;responseZipBytes=[int64]$candidate.zipBytes;signatureVerified=$true;failureJsonSha256=$failureSha;stderrSha256=$stderrSha;successPropertiesDereferenced=$false;reviewOnly=$true;productionRoutingEnabled=$false}}
$confirmedCount=if($success){@($terminal.targetConfirmedRows).Count}else{0};$verifiedCount=if($success){@($terminal.targetVerifiedRows).Count}else{0};$resolutionCount=if($success){@($terminal.targetCandidateResolutions).Count}else{0};$guiAccepted=if($success){[bool]$terminal.guiAcceptance}else{$false};Write-NewJson $terminalGatePath $terminal;[ordered]@{schema='argos_c2v29_collector_result_v1';createdUtc=[DateTime]::UtcNow.ToString('o');state=[string]$terminal.state;requestId=$requestId;responseId=$responseId;endpointState=[string]$manifest.state;signatureVerified=$true;terminalGatePath=$terminalGatePath;terminalGateSha256=(Get-FileHash -LiteralPath $terminalGatePath -Algorithm SHA256).Hash;targetConfirmedRows=$confirmedCount;targetVerifiedRows=$verifiedCount;targetCandidateResolutions=$resolutionCount;guiAcceptance=$guiAccepted;reviewOnly=$true;productionRoutingEnabled=$false}|ConvertTo-Json -Depth 5
