[CmdletBinding()]
param([switch]$Preflight,[switch]$Build)
$ErrorActionPreference='Stop';Set-StrictMode -Version Latest;if(([bool]$Preflight)-eq([bool]$Build)){throw 'Specify exactly one of -Preflight or -Build.'}
$project='C:\Users\joshua.conn\Desktop\ArgosDev\ArgosEdgeLab';$root=Join-Path $project 'work\V40';$requestId='REQ_V40_0821_1615_X1'
$signed=Join-Path $project 'work\V40\signed_short\REQ_V40_0821_1615_X1.ready';$definitionPath=Join-Path $root 'pkg\MAINTENANCE_DEFINITION.json'
$final=Join-Path $root 'final';$zip=Join-Path $final ($requestId+'.ready.zip');$extractRoot='C:\V40Z1';$extract=Join-Path $extractRoot ($requestId+'.ready')
$archiveGate=Join-Path $root 'C2V40_ARCHIVE_GATE.json';$routeGate=Join-Path $root 'C2V40_ROUTE_GATE.json';$pathTool=Join-Path $project 'utilities\Confirm-ArgosPathBudget.ps1'
$verifier=Join-Path $project 'work\PROJECT_PORTAL_REVIEW_ONLY\scripts\Test-SignedPortalPackage.ps1';$public=Join-Path $project 'work\PROJECT_PORTAL_REVIEW_ONLY\enrollment\ARGOS_PROJECT_PORTAL_LAPTOP_SIGNER_PUBLIC.cer'
foreach($p in @($signed,$definitionPath,$pathTool,$verifier,$public)){if(-not(Test-Path -LiteralPath $p)){throw "C2V build input missing: $p"}}
foreach($p in @($final,$extractRoot,$archiveGate,$routeGate)){if(Test-Path -LiteralPath $p){throw "Fresh C2V build path required: $p"}}
&$verifier -PackagePath $signed -SignerCertificatePath $public -ExpectedTargetRole JBOD -ExpectedJobClass MAINTENANCE_PATCH|Out-Null
$manifestPath=Join-Path $signed 'PORTAL_REQUEST_MANIFEST.json';$manifestSha=(Get-FileHash -Algorithm SHA256 -LiteralPath $manifestPath).Hash;$manifest=Get-Content -LiteralPath $manifestPath -Raw|ConvertFrom-Json
if([string]$manifest.requestId-ne$requestId-or[string]$manifest.entryPoint-ne'payload/C2V.ps1'){throw 'C2V signed manifest changed.'}
$requestLeaves=@('PORTAL_REQUEST_MANIFEST.json','PORTAL_REQUEST_MANIFEST.sig')+@($manifest.files|ForEach-Object{[string]$_.path});$paths=New-Object Collections.Generic.List[string]
function Add([string]$Path){$paths.Add([IO.Path]::GetFullPath($Path))}
$portal='C:\ProgramData\ArgosProjectPortalRO'
foreach($p in @($zip,$archiveGate,$routeGate,'U:\ProjectPortalRO\requests\REQ_V40_0821_1615_X1.ready.zip.upload','U:\ProjectPortalRO\requests\REQ_V40_0821_1615_X1.ready.zip','C:\APR\S\requests\REQ_V40_0821_1615_X1.ready.zip','C:\APR\S\requests\processed\REQ_V40_0821_1615_X1.ready.zip')){Add $p}
foreach($route in @((Join-Path $portal 'requests_to_jbod\pending\REQ_V40_0821_1615_X1.ready'),(Join-Path $portal 'requests_from_gateway\pending\REQ_V40_0821_1615_X1.ready'),(Join-Path $portal 'endpoint_jbod\incoming\REQ_V40_0821_1615_X1.ready'))){foreach($leaf in $requestLeaves){Add (Join-Path $route $leaf.Replace('/','\'))}}
$responseId='R_0123456789AB_20260820235959999_a1b2c3d4'
foreach($route in @((Join-Path $portal ('to_gateway\pending\'+$responseId+'.ready')),(Join-Path $portal ('to_gateway\sent\'+$responseId+'.ready')),'C:\APR\R\pending\'+$responseId+'.ready','C:\APR\A\'+$responseId+'.ready','C:\V40S1\'+$responseId+'.ready')){foreach($leaf in @('PORTAL_RESPONSE_MANIFEST.json','PORTAL_RESPONSE_MANIFEST.sig','MAINTENANCE.stdout.txt','MAINTENANCE.stderr.txt','RESULT.json','FAILURE.json')){Add (Join-Path $route $leaf)}}
$budget=&$pathTool -CandidatePath $paths.ToArray() -ReservedSuffixCharacters 32 -AsJson|ConvertFrom-Json;if([string]$budget.state-ne'PASS_PATH_BUDGET'){throw 'C2V route path gate failed.'}
if($Preflight){[ordered]@{schema='argos_c2v13_prepare_preflight_v1';createdUtc=[DateTime]::UtcNow.ToString('o');state='PASS_C2V40_PREPARE_PREFLIGHT';requestId=$requestId;requestManifestSha256=$manifestSha;routePaths=@($budget.candidates).Count;maximumEffectiveLength=[int](($budget.candidates|Measure-Object effectiveLength -Maximum).Maximum);mutationsPerformed=$false;reviewOnly=$true;productionRoutingEnabled=$false}|ConvertTo-Json -Depth 5;return}
Add-Type -AssemblyName System.IO.Compression.FileSystem;[void](New-Item -ItemType Directory -Path $final);[IO.Compression.ZipFile]::CreateFromDirectory($signed,$zip,[IO.Compression.CompressionLevel]::Optimal,$false);[void](New-Item -ItemType Directory -Path $extract);[IO.Compression.ZipFile]::ExtractToDirectory($zip,$extract);&$verifier -PackagePath $extract -SignerCertificatePath $public -ExpectedTargetRole JBOD -ExpectedJobClass MAINTENANCE_PATCH|Out-Null
$files=@(Get-ChildItem -LiteralPath $signed -File -Recurse|ForEach-Object{$_.FullName.Substring($signed.Length).TrimStart('\')});foreach($relative in $files){if((Get-FileHash -Algorithm SHA256 -LiteralPath (Join-Path $signed $relative)).Hash-ne(Get-FileHash -Algorithm SHA256 -LiteralPath (Join-Path $extract $relative)).Hash){throw "C2V extracted file changed: $relative"}}
$archive=[ordered]@{schema='argos_c2v13_archive_gate_v1';createdUtc=[DateTime]::UtcNow.ToString('o');state='PASS_C2V40_EXACT_ARCHIVE';requestId=$requestId;requestManifestSha256=$manifestSha;zipSha256=(Get-FileHash -Algorithm SHA256 -LiteralPath $zip).Hash;zipBytes=(Get-Item -LiteralPath $zip).Length;extractedRoot=$extract;files=$files.Count;signatureVerified=$true;reviewOnly=$true;productionRoutingEnabled=$false};[IO.File]::WriteAllText($archiveGate,(($archive|ConvertTo-Json -Depth 6)+[Environment]::NewLine),(New-Object Text.UTF8Encoding($false)))
$longest=@($budget.candidates|Sort-Object effectiveLength -Descending|Select-Object -First 1)[0];$route=[ordered]@{schema='argos_c2v13_route_gate_v1';createdUtc=[DateTime]::UtcNow.ToString('o');state='PASS_C2V40_COMPLETE_ROUTE_GATE';requestId=$requestId;requestManifestSha256=$manifestSha;endpointWorkerSha256='244A5ECD88020BF80C217271368C836E0AB82E7B76FDEA9D0D9AC07E0AA034E6';responseIdShape='R_{12HEX}_{17DIGIT}_{8HEX}';routePathRowsEvaluated=@($budget.candidates).Count;maximumPlannedEffectiveLength=[int]$longest.effectiveLength;longestPath=[string]$longest.path;reviewOnly=$true;productionRoutingEnabled=$false};[IO.File]::WriteAllText($routeGate,(($route|ConvertTo-Json -Depth 6)+[Environment]::NewLine),(New-Object Text.UTF8Encoding($false)));[pscustomobject]@{archive=$archive;route=$route}|ConvertTo-Json -Depth 8
