[CmdletBinding()]
param([switch]$Preflight,[switch]$Rehearsal,[string]$InvocationManifest)

$ErrorActionPreference='Stop'
Set-StrictMode -Version Latest
if(([bool]$Preflight)-eq([bool]$Rehearsal)){throw 'Specify exactly one of -Preflight or -Rehearsal.'}
$project='C:\Users\joshua.conn\Desktop\ArgosDev\ArgosEdgeLab';$work=Join-Path $project 'work\V40';$requestId='REQ_V40_0821_1615_X1'
$requestRoot=Join-Path $work 'signed_short\REQ_V40_0821_1615_X1.ready';$source=$work;$definition=Join-Path $source 'pkg\MAINTENANCE_DEFINITION.json';$target=Join-Path $source 'pkg\payload\PROCESSOR_CONFIG.json';$destination='C:\ProgramData\ArgosEdgeLabRO\AllWaferProcessorV2\PROCESSOR_CONFIG.json'
$worker=Join-Path $project 'work\JBOD_ENDPOINT_MAINTENANCE_PATH_C1E\pkg\payload\W.ps1';$requestVerifier=Join-Path $project 'work\PROJECT_PORTAL_REVIEW_ONLY\scripts\Test-SignedPortalPackage.ps1';$responseVerifier=Join-Path $project 'work\PROJECT_PORTAL_REVIEW_ONLY\scripts\Test-SignedPortalResponse.ps1';$public=Join-Path $project 'work\PROJECT_PORTAL_REVIEW_ONLY\enrollment\ARGOS_PROJECT_PORTAL_LAPTOP_SIGNER_PUBLIC.cer';$identity=Get-Content -LiteralPath (Join-Path $project 'work\PROJECT_PORTAL_REVIEW_ONLY\state\LAPTOP_SIGNING_IDENTITY.json') -Raw|ConvertFrom-Json
$testRoot='C:\V40E1';$gatePath=Join-Path $work 'C2V40_EXACT_ENDPOINT_GATE.json';$targetSha='CDFD888129D0144C9942D027B0C4583FEEF3619D6D65B060B3001686357879D8';$workerSha='244A5ECD88020BF80C217271368C836E0AB82E7B76FDEA9D0D9AC07E0AA034E6';$utf8=New-Object Text.UTF8Encoding($false)
if(-not[string]::IsNullOrWhiteSpace($InvocationManifest)){$i=Get-Content -LiteralPath ([IO.Path]::GetFullPath($InvocationManifest)) -Raw|ConvertFrom-Json;if([string]$i.schema-ne'argos_jbod_lot_validate_c2v_endpoint_test_invocation_v1'){throw 'C2V endpoint invocation contract refused.'};$requestRoot=[IO.Path]::GetFullPath([string]$i.requestRoot);$testRoot=[IO.Path]::GetFullPath([string]$i.testRoot);$gatePath=[IO.Path]::GetFullPath([string]$i.gatePath)}
foreach($path in @($requestRoot,$definition,$target,$destination,$worker,$requestVerifier,$responseVerifier,$public)){if(-not(Test-Path -LiteralPath $path)){throw "C2V endpoint input missing: $path"}}
if((Get-FileHash -LiteralPath $target -Algorithm SHA256).Hash-ne$targetSha-or(Get-FileHash -LiteralPath $worker -Algorithm SHA256).Hash-ne$workerSha){throw 'C2V endpoint fixture hash changed.'}
foreach($path in @($testRoot,$gatePath)){if(Test-Path -LiteralPath $path){throw "Fresh C2V endpoint path required: $path"}}
$manifestPath=Join-Path $requestRoot 'PORTAL_REQUEST_MANIFEST.json';$manifestSha=(Get-FileHash -LiteralPath $manifestPath -Algorithm SHA256).Hash;&$requestVerifier -PackagePath $requestRoot -SignerCertificatePath $public -ExpectedTargetRole JBOD|Out-Null
if($Preflight){[ordered]@{schema='argos_jbod_lot_validate_c2v_endpoint_preflight_v1';createdUtc=[DateTime]::UtcNow.ToString('o');state='PASS_C2V_EXACT_ENDPOINT_PREFLIGHT';requestId=$requestId;requestManifestSha256=$manifestSha;exactWorkerSha256=$workerSha;targetConfigSha256=$targetSha;testRootExists=$false;mutationsPerformed=$false;reviewOnly=$true;productionRoutingEnabled=$false}|ConvertTo-Json -Depth 5;return}
function Write-Json([string]$Path,[object]$Value){$parent=Split-Path -Parent $Path;if(-not(Test-Path -LiteralPath $parent -PathType Container)){[void](New-Item -ItemType Directory -Path $parent -Force)};[IO.File]::WriteAllText($Path,(($Value|ConvertTo-Json -Depth 32)+[Environment]::NewLine),$utf8)}
function Set-Destination([string]$Mode){if($Mode-eq'target'){Copy-Item -LiteralPath $target -Destination $destination -Force}elseif($Mode-eq'bad'){[IO.File]::WriteAllText($destination,"{`"schema`":`"unapproved`"}`r`n",$utf8)}else{throw "Unknown C2V mode: $Mode"}}
function New-Fixture([string]$Name,[bool]$Valid,[bool]$FailedPayloadWithoutRequestRows=$false){
    $root=Join-Path $testRoot $Name;$state=Join-Path $root 'f\s';$bridge=Join-Path $root 'f\b';$stamp='2026-08-19T19:30:00';$targetHash='5C08CE4E6D8A4603B14BFC1692B30CE4E64CAE538A7D1FA7CE94C66CC095518C';$responseId='INSITE_RESP__5C08CE4E6D8A4603B14BFC1692B30CE4'
    foreach($path in @((Join-Path $state 'catalog'),(Join-Path $state 'processor'),(Join-Path $state 'dashboard'),(Join-Path $state 'identity\proposals'),(Join-Path $state 'identity\confirmed'),(Join-Path $state 'identity\candidate_resolutions'),(Join-Path $state 'metadata\verified'),(Join-Path $state 'metadata\holds'),(Join-Path $bridge 'response_inbox\pending'),(Join-Path $bridge 'response_inbox\processed'),(Join-Path $bridge 'response_inbox\failed'),(Join-Path $bridge 'state'),(Join-Path $bridge 'query'))){[void](New-Item -ItemType Directory -Path $path -Force)}
    foreach($name in @('Import-JbodCandidateInsiteSnapshot.ps1','ArgosScribeCandidateLotResolver.psm1','Import-JbodLiveInsiteSnapshot.ps1','Invoke-JbodAllWaferInventory.ps1','Invoke-JbodAllWaferProcessingPass.ps1','Update-JbodDashboardManifest.ps1','Invoke-JbodScribeProposalPass.ps1')){[IO.File]::WriteAllText((Join-Path $state $name),('fixture '+$name),$utf8)}
    $scribeRuntime=Join-Path $state 'runtime\scribe';[void](New-Item -ItemType Directory -Path $scribeRuntime -Force);[IO.File]::WriteAllText((Join-Path $scribeRuntime 'Invoke-ScribeMultiChannelPolarityReader.ps1'),'fixture nested multi-channel reader',$utf8)
    [IO.File]::WriteAllText((Join-Path $bridge 'Invoke-JbodAutomaticInsiteBridgeWorker.ps1'),'fixture worker',$utf8)
    [IO.File]::WriteAllText((Join-Path $state 'Export-JbodPendingInsiteRequestV2.ps1'),'fixture confirmed-first exporter',$utf8)
    $catalogRows=@();$dashboardWafers=@()
    for($slot=1;$slot-le10;$slot++){
        $slotName='Slot'+$slot.ToString('00');$physical='62631-586_20260819193000_'+$slotName;$identity=$physical+'__FRONTSIDE'
        $catalogRows+=[ordered]@{identity=$identity;physicalIdentity=$physical;lot='62631-586';scanTimestampLocal=$stamp;slot=$slotName;domain='FRONTSIDE';routeState='READY_FRONTSIDE_SCRATCH_TEST'}
        $dashboardWafers+=[ordered]@{identity=$physical;lot='62631-586';frontsideBfRaw=('D:\A2\o\'+$slotName+'\BF.png');frontsideDfRaw=('D:\A2\o\'+$slotName+'\DF.png')}
    }
    Write-Json (Join-Path $state 'catalog\ALL_WAFER_CATALOG.json') ([ordered]@{acquisitions=$catalogRows;reviewOnly=$true;xmlExportEnabled=$false})
    Write-Json (Join-Path $state 'dashboard_manifest.json') ([ordered]@{scanSessions=@([ordered]@{lot='62631-586';scanTimestampLocal=$stamp;wafers=$dashboardWafers});xmlExportEnabled=$false})
    for($history=0;$history-lt25;$history++){[void](New-Item -ItemType Directory -Path (Join-Path $state ('identity\proposals\62631-586_HISTORICAL_'+$history.ToString('00'))) -Force)}
    $exactProposal=Join-Path $state 'identity\proposals\62631-586_20260819193000_Slot01';Write-Json (Join-Path $exactProposal 'SCRIBE_PROPOSAL.json') ([ordered]@{state='SCRIBE_IDENTITY_CONFIRMATION_HOLD';proposal='';failure='fixture'})
    Write-Json (Join-Path $exactProposal 'scribe\multi_channel\MULTI_CHANNEL_READER_SUMMARY.json') ([ordered]@{state='SCRIBE_M12_CANDIDATES_REQUIRE_EXACT_MES_VERIFICATION';consensusState='MULTIPLE_IMAGE_SUPPORTED_M12_CANDIDATES';candidateCount=2;uniqueImageCandidate='';candidates=@([ordered]@{string='ABCDEF123456'},[ordered]@{string='ABCDEF123457';directImageFirstSupport=$true;maximumScore=0.9;supportCount=2})})
    Write-Json (Join-Path $state 'identity\confirmed\ACTIVE_CONFIRMED_SCRIBE_OVERLAY.json') ([ordered]@{schema='argos_confirmed_scribe_overlay_v1';rows=@([ordered]@{acquisitionKey='62631-586_20260819193000_SLOT01';scribe='ABCDEF123456';identityState='IMAGE_CONFIRMED_CURRENT_PIXELS_EXACT_UNIQUE_MES_REVIEW_ONLY';scribeChecksumState='SEMI_M12_CURRENT_IMAGE_CANDIDATE_EXACT_UNIQUE_MES';imageReadAuthority='CURRENT_BF_DF_MULTI_CHANNEL_POLARITY_CANONICAL_M12_EXACT_UNIQUE_MES'},[ordered]@{acquisitionKey='62631-586_20260815100000_SLOT01';scribe='ABCDEF123456';identityState='HUMAN_CONFIRMED_REVIEW_ONLY';scribeChecksumState='HUMAN';imageReadAuthority='HUMAN'});reviewOnly=$true;productionEligible=$false})
    Write-Json (Join-Path $state 'metadata\verified\ACTIVE_VERIFIED_METADATA_OVERLAY.json') ([ordered]@{schema='argos_verified_scribe_mes_metadata_overlay_v1';rows=@([ordered]@{acquisitionKey='62631-586_20260819193000_SLOT01';scribe='ABCDEF123456';metadataQualificationState='EXACT_SCAN_TIME_CONTEXT';scanTimeContextState='EXACT_PRIOR_MOVEIN_FOUND';frontsideScratchTestRouteState='FRONTSIDE_SCRATCH_TEST_NITRIDE_DIELECTRIC_ROUTE_CONFIRMED';frontsideScratchTestRouteAuthority='INSITE_MOVEIN_HISTORY_BEFORE_EXACT_ARGOS_ACQUISITION'});reviewOnly=$true;productionEligible=$false})
    Write-Json (Join-Path $state 'metadata\holds\ACTIVE_INSITE_METADATA_HOLDS.json') ([ordered]@{schema='argos_active_insite_metadata_holds_v1';state='EXPLICIT_REVIEW_ONLY_HOLDS';rows=@([ordered]@{acquisitionKey='62631-586_20260819193000_SLOT02';scribe='ABCDEF123457';state='HOLD_INSITE_FIXTURE';terminal=$false;attemptCount=1;nextRetryUtc='2026-08-21T12:00:00Z'});reviewOnly=$true;productionEligible=$false})
    Write-Json (Join-Path $state 'identity\candidate_resolutions\C_FIXTURE.json') ([ordered]@{requestContentSha256=$targetHash;sourceSnapshotSha256=('A'*64);resolutions=@([ordered]@{acquisitionKey='62631-586_20260819193000_SLOT01';resolution=[ordered]@{state='SCRIBE_CURRENT_IMAGE_MES_EXACT_UNIQUE_LOT_MATCH_REVIEW_ONLY';candidateCount=2;exactMesLotMatchCount=1;resolvedScribe='ABCDEF123456'}})})
    $responseParent=if($FailedPayloadWithoutRequestRows){'response_inbox\failed'}else{'response_inbox\processed'};$responseLeaf=if($FailedPayloadWithoutRequestRows){$responseId+'.ready.failed.fixture'}else{$responseId+'.ready'};$response=Join-Path $bridge (Join-Path $responseParent $responseLeaf);[void](New-Item -ItemType Directory -Path $response -Force);Write-Json (Join-Path $response 'INSITE_RESPONSE_MANIFEST.json') ([ordered]@{schema='argos_insite_response_relay_manifest_v1';requestContentSha256=$targetHash;recordCount=20})
    Write-Json (Join-Path $response 'INSITE_RESPONSE.json') ([ordered]@{authority='READ_ONLY_SCRIBE_FIRST_VISUAL_STATE_AND_BACKSIDE_REGIME_SNAPSHOT';lookupKey='confirmed 12-character wafer scribe';transportEnvelope='ARGOS_CURRENT_IMAGE_CANDIDATE_OVER_LEGACY_RELAY_V1';transportRequestKind='CURRENT_IMAGE_CANDIDATE';requestContentSha256=('B'*64);transportRequestContentSha256=$targetHash;transportCandidateRequestContentSha256=('B'*64);requestRows=@([ordered]@{acquisitionKey='62631-586_20260819193000_SLOT01';candidateScribes=@('ABCDEF123456','ABCDEF123457')});frontsideScratchTestRouteContract='EXACT_SACRIFICIAL_NITRIDE_DEP_ANCHOR; SAME_BLOCK_FOLLOW_ON_ALLOWED; EAGLE_OR_LV150MM_ONLY_AFTER_BLOCK; RECIPE_FOLDER_NAMES_UNUSED';records=@([ordered]@{scribe='ABCDEF123456';queryState='FOUND';lineage=[ordered]@{historyBaseLot='62631-586'};visualState=[ordered]@{processBlock='SACRIFICIAL NITRIDE DEP';step='NITRIDE_THICKNESS';resource='6-10-N'};backsideRegime=[ordered]@{state='BACKSIDE_REGIME_BARE'};acquisitionContexts=@([ordered]@{acquisitionKey='62631-586_20260819193000_SLOT01';state='EXACT_PRIOR_MOVEIN_FOUND';authority='LAST_INSITE_MOVEIN_PRECEDING_ARGOS_SCAN';scanTimestampLocal=$stamp;priorMoveIn=[ordered]@{processBlock='SACRIFICIAL NITRIDE DEP';step='NITRIDE_THICKNESS';resource='6-10-N'};frontsideScratchTestRoute=[ordered]@{state='FRONTSIDE_SCRATCH_TEST_NITRIDE_DIELECTRIC_ROUTE_CONFIRMED';authority='INSITE_MOVEIN_HISTORY_BEFORE_EXACT_ARGOS_ACQUISITION';fingerprintVersion='FRONTSIDE_SCRATCH_TEST_ROUTE_V1'}})},[ordered]@{scribe='ZZZZZZ999999';queryState='NOT_FOUND';lineage=$null;visualState=$null;backsideRegime=$null})})
    if($FailedPayloadWithoutRequestRows){Write-Json (Join-Path $response 'INSITE_RESPONSE.json') ([ordered]@{authority='READ_ONLY_SCRIBE_FIRST_VISUAL_STATE_AND_BACKSIDE_REGIME_SNAPSHOT';lookupKey='confirmed 12-character wafer scribe';records=@()});Write-Json (Join-Path $response 'IMPORT_FAILURE.json') ([ordered]@{schema='argos_insite_import_failure_v1';state='FAILED_IMPORT_FIXTURE';detail='fixture payload omits requestRows'})}
    Write-Json (Join-Path $bridge 'state\LAST_QUEUED_REQUEST.json') ([ordered]@{schema='argos_automatic_insite_request_state_v1';packageId=('INSITE_REQ__'+$targetHash.Substring(0,32));requestContentSha256=$targetHash;queuedUtc=[DateTime]::UtcNow.ToString('o')})
    if(-not$FailedPayloadWithoutRequestRows){Write-Json (Join-Path $bridge 'state\LAST_IMPORTED_RESPONSE.json') ([ordered]@{schema='argos_insite_import_state_v1';packageId=$responseId;requestContentSha256=$targetHash;importedUtc=[DateTime]::UtcNow.ToString('o')})}
    $fixtureState=if($Valid){$state}else{Join-Path $root 'missing_state'};$inv=Join-Path $root 'INVOCATION.json';Write-Json $inv ([ordered]@{schema='argos_jbod_front_catalog_probe_rehearsal_v1';rehearsal=$true;configPath=$destination;stateRoot=$fixtureState;bridgeRoot=$bridge});$inv
}
function Invoke-Case([string]$Name,[string]$Mode,[bool]$Valid,[string]$ExpectedState,[string]$ExpectedHash,[bool]$FailedPayloadWithoutRequestRows=$false){
    $case=Join-Path $testRoot $Name;foreach($r in @('incoming','processed','responses','state')){[void](New-Item -ItemType Directory -Path (Join-Path $case $r) -Force)};$inv=New-Fixture $Name $Valid $FailedPayloadWithoutRequestRows;Set-Destination $Mode;$before=(Get-FileHash -LiteralPath $destination -Algorithm SHA256).Hash;Copy-Item -LiteralPath $requestRoot -Destination (Join-Path $case 'incoming') -Recurse
    $cfg=[ordered]@{schema='argos_project_portal_endpoint_config_v1';role='JBOD';reviewOnly=$true;productionRoutingEnabled=$false;incomingRoot=Join-Path $case 'incoming';processedRoot=Join-Path $case 'processed';responseOutbox=Join-Path $case 'responses';stateRoot=Join-Path $case 'state';requestVerifierPath=$requestVerifier;laptopSignerCertificatePath=$public;endpointSignerThumbprint=[string]$identity.thumbprint;endpointSignerStoreLocation='CurrentUser';approvedMaintenanceRoots=@('C:\ProgramData\ArgosEdgeLabRO\AllWaferProcessorV2');approvedDataRoots=@();status=[ordered]@{tasks=@();hashFiles=@();jsonFiles=@();logs=@()};handlers=@()};$cfgPath=Join-Path $case 'ENDPOINT_CONFIG.json';Write-Json $cfgPath $cfg
    $prior=[Environment]::GetEnvironmentVariable('ARGOS_C2V_REHEARSAL_MANIFEST','Process');try{$env:ARGOS_C2V_REHEARSAL_MANIFEST=$inv;&"$env:SystemRoot\System32\WindowsPowerShell\v1.0\powershell.exe" -NoProfile -ExecutionPolicy Bypass -File $worker -ConfigPath $cfgPath -Once;if($LASTEXITCODE-ne0){throw "C2V endpoint process failed: $Name"}}finally{[Environment]::SetEnvironmentVariable('ARGOS_C2V_REHEARSAL_MANIFEST',$prior,'Process')}
    $responses=@(Get-ChildItem -LiteralPath (Join-Path $case 'responses') -Directory -Filter '*.ready');if($responses.Count-ne1){throw "C2V response count failed: $Name"};&$responseVerifier -PackagePath $responses[0].FullName -EndpointCertificatePath $public -ExpectedSourceRole JBOD -ExpectedRequestId $requestId|Out-Null;$m=Get-Content -LiteralPath (Join-Path $responses[0].FullName 'PORTAL_RESPONSE_MANIFEST.json') -Raw|ConvertFrom-Json;$after=(Get-FileHash -LiteralPath $destination -Algorithm SHA256).Hash
    if([string]$m.state-ne$ExpectedState-or$after-ne$ExpectedHash){throw "C2V endpoint outcome mismatch: $Name / $($m.state) / $after"}
    if($ExpectedState-eq'PASS_MAINTENANCE_PATCH'){
        $stdout=Get-Content -LiteralPath (Join-Path $responses[0].FullName 'MAINTENANCE.stdout.txt') -Raw|ConvertFrom-Json
        if($FailedPayloadWithoutRequestRows){if(@($stdout.targetPackageLocations)-notcontains'failed'-or@($stdout.responseAcquisitionKeys).Count-ne0-or@($stdout.targetPackageSnapshots|Where-Object{[string]$_.state-eq'failed'-and$null-ne$_.failure}).Count-ne1-or[bool]$stdout.lastImportedMatchesTarget){throw "C2V35 failed-payload optional-field contract failed: $Name"}}elseif([string]$stdout.state-ne'PASS_C2V35_BOUNDED_LIVE_SNAPSHOT'-or[string]$stdout.disposition-ne'PASS_TEN_62631_586_FRONTS_VISIBLE'-or-not[bool]$stdout.rehearsal-or-not[bool]$stdout.catalogAcceptance-or-not[bool]$stdout.guiAcceptance-or[int]$stdout.distinctFrontPhysicalIdentities-ne10-or-not[bool]$stdout.lastImportedMatchesTarget-or-not[bool]$stdout.lastQueuedMatchesTarget-or@($stdout.targetPackageLocations)-notcontains'processed'-or@($stdout.runtimeHashes.PSObject.Properties).Count-ne9-or-not[bool]$stdout.processedPayload.exists-or[int]$stdout.processedPayload.targetContextCount-ne1-or[string]$stdout.responseShape.transportEnvelope-ne'ARGOS_CURRENT_IMAGE_CANDIDATE_OVER_LEGACY_RELAY_V1'-or[int]$stdout.responseShape.requestRowCount-ne1-or[int]$stdout.responseShape.allAcquisitionContextCount-ne1-or@($stdout.targetConfirmedRows).Count-ne1-or@($stdout.priorLotScribes).Count-ne1-or@($stdout.targetVerifiedRows).Count-ne1-or@($stdout.targetActiveHolds).Count-ne1-or@($stdout.targetCandidateResolutions).Count-ne1-or[string]$stdout.exporterSha256-cnotmatch'^[A-F0-9]{64}$'-or@($stdout.targetProposals).Count-ne10-or@($stdout.targetProposals|Where-Object{[string]$_.physicalIdentity-like'*HISTORICAL*'}).Count-ne0-or@($stdout.targetProposals|Where-Object{[int]$_.candidateCount-eq2}).Count-ne1-or[bool]$stdout.inspectionTasksChanged-or[bool]$stdout.sourceDeletionPerformed-or[bool]$stdout.fullQueueEnumerationPerformed-or[bool]$stdout.imageFilesRead){throw "C2V35 stdout contract failed: $Name"}
    }
    [pscustomobject]@{case=$Name;predecessorMode=$Mode;beforeSha256=$before;endpointState=[string]$m.state;installedSha256=$after;responseId=[string]$m.responseId;signatureVerified=$true}
}
[void](New-Item -ItemType Directory -Path $testRoot);$backup=Join-Path $testRoot 'LOCAL_CONFIG_BEFORE.bin';Copy-Item -LiteralPath $destination -Destination $backup;$beforeSha=(Get-FileHash -LiteralPath $backup -Algorithm SHA256).Hash;$results=New-Object Collections.Generic.List[object]
try{$results.Add((Invoke-Case 'target' 'target' $true 'PASS_MAINTENANCE_PATCH' $targetSha));$results.Add((Invoke-Case 'target_idempotent' 'target' $true 'PASS_MAINTENANCE_PATCH' $targetSha));$results.Add((Invoke-Case 'failed_payload_without_request_rows' 'target' $true 'PASS_MAINTENANCE_PATCH' $targetSha $true));$badBytes=$utf8.GetBytes("{`"schema`":`"unapproved`"}`r`n");$sha=[Security.Cryptography.SHA256]::Create();try{$badSha=([BitConverter]::ToString($sha.ComputeHash($badBytes))).Replace('-','')}finally{$sha.Dispose()};$results.Add((Invoke-Case 'unapproved' 'bad' $true 'FAILED' $badSha));$results.Add((Invoke-Case 'runtime_failure' 'target' $false 'FAILED' $targetSha));$results.Add((Invoke-Case 'control_after_failure' 'target' $true 'PASS_MAINTENANCE_PATCH' $targetSha))}finally{Copy-Item -LiteralPath $backup -Destination $destination -Force;if((Get-FileHash -LiteralPath $destination -Algorithm SHA256).Hash-ne$beforeSha){throw 'C2V local config restoration failed.'}}
$gate=[ordered]@{schema='argos_jbod_front_catalog_probe_exact_endpoint_gate_v1';createdUtc=[DateTime]::UtcNow.ToString('o');state='PASS_C2V40_EXACT_ENDPOINT_GATE';requestId=$requestId;requestManifestSha256=$manifestSha;exactWorkerSha256=$workerSha;installedApprovedMaintenanceRoots=@('C:\ProgramData\ArgosEdgeLabRO\AllWaferProcessorV2');tenFrontCatalogFixturePassed=$true;tenFrontDashboardFixturePassed=$true;responseInboxProcessedFixturePassed=$true;failedPayloadWithoutRequestRowsFixturePassed=$true;lastQueuedPointerFixturePassed=$true;runtimeHashInventoryFixturePassed=$true;approvedPredecessorAccepted=$true;targetIdempotenceAccepted=$true;unapprovedPredecessorRefusedBeforeMutation=$true;runtimeVerifierFailureRolledBack=$true;controlAfterRuntimeFailurePassed=$true;responseSignaturesVerified=$results.Count;localConfigRestoredSha256=$beforeSha;results=$results.ToArray();sourceDeletionPerformed=$false;inspectionTasksChanged=$false;waferAborted=$false;reviewOnly=$true;productionRoutingEnabled=$false};Write-Json $gatePath $gate;$gate|ConvertTo-Json -Depth 10
