
#Requires -Version 5.1
[CmdletBinding()]
param([switch]$Preflight,[switch]$Build)
$ErrorActionPreference='Stop'; Set-StrictMode -Version Latest
function Assert-O3B8([bool]$Condition,[string]$Message){if(-not$Condition){throw $Message}}
function Get-O3B8Hash([string]$Path){return (Get-FileHash -LiteralPath $Path -Algorithm SHA256).Hash}
function Assert-O3B8Pin([string]$Path,[string]$Hash){Assert-O3B8 (Test-Path -LiteralPath $Path -PathType Leaf) "O3B8 file missing: $Path";Assert-O3B8 ((Get-O3B8Hash $Path)-eq$Hash) "O3B8 file changed: $Path"}
$modeCount=0;if($Preflight){$modeCount++};if($Build){$modeCount++};Assert-O3B8 ($modeCount-eq1) 'Select exactly one O3B8 action.'
$project=[IO.Path]::GetFullPath((Join-Path $PSScriptRoot '..\..'));$planPath=Join-Path $PSScriptRoot 'O3B8_PACKAGE_PLAN.json';Assert-O3B8Pin $planPath '2421EFB23CF7B5D9194C5315E660E96BB3B0CF17CFEE5D5D3E1577A39B43F2E9'
$plan=Get-Content -LiteralPath $planPath -Raw|ConvertFrom-Json;$sourcePlanPath=Join-Path $project ([string]$plan.sourcePayloadPlan.path);Assert-O3B8Pin $sourcePlanPath ([string]$plan.sourcePayloadPlan.sha256);$sourcePlan=Get-Content -LiteralPath $sourcePlanPath -Raw|ConvertFrom-Json
$definitionPath=Join-Path $project ([string]$plan.maintenanceDefinition.path);Assert-O3B8Pin $definitionPath ([string]$plan.maintenanceDefinition.sha256);$definition=Get-Content -LiteralPath $definitionPath -Raw|ConvertFrom-Json
$identityPath=Join-Path $project 'work\PROJECT_PORTAL_REVIEW_ONLY\state\LAPTOP_SIGNING_IDENTITY.json';Assert-O3B8Pin $identityPath '3FD8164D1869375156FB7566D206FEAB97AE8A9E7D377B0AD4E03739ED697289';$identity=Get-Content -LiteralPath $identityPath -Raw|ConvertFrom-Json
$thumb=([string]$identity.thumbprint).Replace(' ','').ToUpperInvariant();$certificate=Get-Item -LiteralPath ("Cert:\CurrentUser\My\$thumb");Assert-O3B8 ([bool]$certificate.HasPrivateKey) 'O3B8 signer private key is absent.'
$stage=[IO.Path]::GetFullPath([string]$plan.stageRoot);$payload=[IO.Path]::GetFullPath([string]$plan.payloadRoot);$signed=[IO.Path]::GetFullPath([string]$plan.signedRoot);$ready=Join-Path $signed ([string]$plan.readyName);$partial=$ready.Replace('.ready','.partial');$final=Join-Path $project ([string]$plan.finalRoot);$zip=Join-Path $final (([string]$plan.readyName)+'.zip')
Assert-O3B8 ($stage-eq'C:\B8P'-and[string]$plan.requestId-eq'REQ_O3B8_20260828A') 'O3B8 stage or request identity changed.';foreach($path in @($stage,$ready,$partial,$final,$zip)){Assert-O3B8 (-not(Test-Path -LiteralPath $path)) "O3B8 create-new path exists: $path"}
foreach($row in @($sourcePlan.files)){Assert-O3B8Pin (Join-Path $project ([string]$row.source)) ([string]$row.sha256)}
if($Preflight){[ordered]@{schema='argos_ocv03_o3b8_build_preflight_v1';state='PASS_O3B8_BUILD_PREFLIGHT';requestId=[string]$plan.requestId;payloadCount=@($sourcePlan.files).Count;stageRoot=$stage;signerThumbprint=$thumb;mutationsPerformed=$false;sourceImageBytesRead=$false;publications=0;reviewOnly=$true;productionRoutingEnabled=$false}|ConvertTo-Json -Depth 6;return}
[void](New-Item -ItemType Directory -Path $payload);foreach($row in @($sourcePlan.files)){$destination=Join-Path $payload ([string]$row.path);$parent=Split-Path -Parent $destination;if(-not(Test-Path -LiteralPath $parent)){[void](New-Item -ItemType Directory -Path $parent)};Copy-Item -LiteralPath (Join-Path $project ([string]$row.source)) -Destination $destination;Assert-O3B8Pin $destination ([string]$row.sha256)}
[void](New-Item -ItemType Directory -Path (Join-Path $partial 'payload'));Copy-Item -Path (Join-Path $payload '*') -Destination (Join-Path $partial 'payload') -Recurse
$records=@(Get-ChildItem -LiteralPath (Join-Path $partial 'payload') -Recurse -File|Sort-Object FullName|ForEach-Object{$relative=$_.FullName.Substring($partial.Length+1).Replace('\','/');[ordered]@{path=$relative;bytes=[int64]$_.Length;sha256=Get-O3B8Hash $_.FullName}});Assert-O3B8 ($records.Count-eq[int]$plan.expectedPayloadFileCount) 'O3B8 payload count changed.'
$created=[DateTimeOffset]::UtcNow;$manifest=[ordered]@{schema='argos_project_portal_request_manifest_v1';requestId=[string]$plan.requestId;createdUtc=$created.ToString('o');expiresUtc=$created.AddHours(24).ToString('o');targetRole='JBOD';jobClass='MAINTENANCE_PATCH';handler='';maxResultBytes=[int64]$definition.maxResultBytes;reviewOnly=$true;trainingEligible=$false;xmlEligible=$false;productionEligible=$false;productionRoutingEnabled=$false;credentialsIncluded=$false;signerThumbprint=$thumb;signatureAlgorithm='RSA-SHA256-PKCS1';files=$records;entryPoint=[string]$definition.entryPoint;changes=@($definition.changes);entryPointMutations=@($definition.entryPointMutations);entryPointOutputs=@($definition.entryPointOutputs);sourceProcessingContract=$definition.sourceProcessingContract;timeoutContract=$definition.timeoutContract;allowedTaskActions=@($definition.allowedTaskActions);allowedProcessActions=@($definition.allowedProcessActions);rehearsal=$definition.rehearsal;requestRetryAuthorized=$false}
$bytes=(New-Object Text.UTF8Encoding($false)).GetBytes(($manifest|ConvertTo-Json -Depth 32));[IO.File]::WriteAllBytes((Join-Path $partial 'PORTAL_REQUEST_MANIFEST.json'),$bytes);$rsa=[Security.Cryptography.X509Certificates.RSACertificateExtensions]::GetRSAPrivateKey($certificate);try{$signature=$rsa.SignData($bytes,[Security.Cryptography.HashAlgorithmName]::SHA256,[Security.Cryptography.RSASignaturePadding]::Pkcs1)}finally{$rsa.Dispose()};[IO.File]::WriteAllBytes((Join-Path $partial 'PORTAL_REQUEST_MANIFEST.sig'),$signature)
Move-Item -LiteralPath $partial -Destination $ready;[void](New-Item -ItemType Directory -Path $final);Add-Type -AssemblyName System.IO.Compression.FileSystem;[IO.Compression.ZipFile]::CreateFromDirectory($ready,$zip,[IO.Compression.CompressionLevel]::Optimal,$false)
[ordered]@{schema='argos_ocv03_o3b8_build_result_v1';state='SIGNED_O3B8_PACKAGE_READY_LOCAL_ONLY';requestId=[string]$plan.requestId;readyDirectory=$ready;zip=$zip;zipBytes=(Get-Item -LiteralPath $zip).Length;zipSha256=Get-O3B8Hash $zip;payloadCount=$records.Count;publications=0;reviewOnly=$true;productionRoutingEnabled=$false}|ConvertTo-Json -Depth 6
