#Requires -Version 5.1
[CmdletBinding()]
param([switch]$Preflight,[switch]$Gate)
$ErrorActionPreference='Stop';Set-StrictMode -Version Latest
if(([bool]$Preflight)-eq([bool]$Gate)){throw 'Select exactly one O3B8 package-test action.'}
function Assert-O3B8([bool]$Condition,[string]$Message){if(-not$Condition){throw $Message}}
function Get-O3B8Sha([string]$Path){return(Get-FileHash -LiteralPath $Path -Algorithm SHA256).Hash}
$project=[IO.Path]::GetFullPath((Join-Path $PSScriptRoot '..\..'));$zip=Join-Path $PSScriptRoot 'final\REQ_O3B8_20260828A.ready.zip';$expectedZip='BED3E048D6AFF6330A68A7EF3493353E9F954DD737BFEA5925331D63E25CE327';$root='C:\B8E';$successOut='C:\B8S';$failureOut='C:\B8F';$gatePath=Join-Path $PSScriptRoot 'O3B8_EXACT_PACKAGE_REHEARSAL_GATE.json'
$certificate=Join-Path $project 'work\PROJECT_PORTAL_REVIEW_ONLY\enrollment\ARGOS_PROJECT_PORTAL_LAPTOP_SIGNER_PUBLIC.cer';$tester=Join-Path $project 'work\PROJECT_PORTAL_REVIEW_ONLY\scripts\Test-SignedPortalPackage.ps1'
foreach($path in @($zip,$certificate,$tester)){Assert-O3B8 (Test-Path -LiteralPath $path -PathType Leaf) "O3B8 package-test prerequisite missing: $path"};Assert-O3B8 ((Get-O3B8Sha $zip)-eq$expectedZip) 'O3B8 final ZIP changed.'
foreach($path in @($root,$successOut,$successOut+'.partial',$successOut+'.failed',$failureOut,$failureOut+'.partial',$failureOut+'.failed',$gatePath)){Assert-O3B8 (-not(Test-Path -LiteralPath $path)) "O3B8 create-new rehearsal path exists: $path"}
Assert-O3B8 (-not(Test-Path -LiteralPath 'Q:\')-and$null-eq(Get-PSDrive -Name Q -ErrorAction SilentlyContinue)) 'O3B8 rehearsal Q: is already in use.'
if($Preflight){[ordered]@{schema='argos_ocv03_o3b8_exact_package_rehearsal_preflight_v1';state='PASS_O3B8_EXACT_PACKAGE_REHEARSAL_PREFLIGHT';requestZipSha256=$expectedZip;fixtureRoot=$root;successRoot=$successOut;failureRoot=$failureOut;mutationsPerformed=$false;sourceImageBytesRead=$false;reviewOnly=$true;productionRoutingEnabled=$false}|ConvertTo-Json -Depth 6;return}
[void](New-Item -ItemType Directory -Path $root);$extract=Join-Path $root 'x';Add-Type -AssemblyName System.IO.Compression.FileSystem;[IO.Compression.ZipFile]::ExtractToDirectory($zip,$extract)
$packageResult=& $tester -PackagePath $extract -SignerCertificatePath $certificate -ExpectedTargetRole JBOD -ExpectedJobClass MAINTENANCE_PATCH;Assert-O3B8 ([string]$packageResult.State-eq'PASS_SIGNED_PORTAL_PACKAGE') 'O3B8 signed package verification failed.'
$manifest=Get-Content -LiteralPath (Join-Path $extract 'PORTAL_REQUEST_MANIFEST.json') -Raw|ConvertFrom-Json;$payload=Join-Path $extract 'payload';$endpoint=Join-Path $payload 'Invoke-O3B8Endpoint.ps1';$provider=Join-Path $payload 'Invoke-O3B8ShortStage.ps1';$live=Join-Path $payload 'O3B8_LIVE_INVOCATION.json';$anchor=Join-Path $payload 'tools\OCV03_NotchReviewOpenCvV1.py'
Assert-O3B8 ([string]$manifest.requestId-eq'REQ_O3B8_20260828A'-and@($manifest.files).Count-eq4-and@($manifest.changes).Count-eq1-and[string]$manifest.entryPoint-eq'payload/Invoke-O3B8Endpoint.ps1') 'O3B8 signed manifest contract changed.'
Assert-O3B8 ((Get-O3B8Sha $endpoint)-eq'53713070F46F81AC790B9958DA64C9C9D01AE02C7A53FBB42C21A3B11431BB19'-and(Get-O3B8Sha $provider)-eq'AA2ABC5A051EB0425B832CB7BC3F92DA437F4BF1D0F9914229A22EFA18B4357F'-and(Get-O3B8Sha $live)-eq'C995892127835B85041160F3A7EFB8F26FCF5A55CC0FA4785E253F701D0139F2'-and(Get-O3B8Sha $anchor)-eq'6B7CC6E643265545297BA4DED1E6B37AB262349572194B13F79264EF77D8DCE4') 'O3B8 extracted payload changed.'
$sourceRoot=Join-Path $root 'src';[void](New-Item -ItemType Directory -Path (Join-Path $sourceRoot 'bf'));[void](New-Item -ItemType Directory -Path (Join-Path $sourceRoot 'df'));$bf=Join-Path $sourceRoot 'bf\source.bmp';$df=Join-Path $sourceRoot 'df\source.bmp';[IO.File]::WriteAllBytes($bf,[byte[]](0..255));[IO.File]::WriteAllBytes($df,[byte[]](255..0));$bfTime=[DateTime]::Parse('2026-08-20T17:43:47.3679403Z').ToUniversalTime();$dfTime=[DateTime]::Parse('2026-08-20T17:44:00.8381748Z').ToUniversalTime();[IO.File]::SetLastWriteTimeUtc($bf,$bfTime);[IO.File]::SetLastWriteTimeUtc($df,$dfTime)
function New-O3B8Invocation([string]$OutputRoot,[string]$BfTimestamp){return [ordered]@{schema='argos_ocv03_o3b8_short_stage_invocation_v1';state='FROZEN_SHORT_STAGE_CONTRACT';expectedComputerName=$env:COMPUTERNAME;sourceRoot=$sourceRoot;outputRoot=$OutputRoot;aliasDrive='Q:';substPath=(Join-Path $env:SystemRoot 'System32\subst.exe');sources=@([ordered]@{channel='BF_BACKSIDE';relativePath='bf/source.bmp';expectedBytes=256;expectedLastWriteTimeUtc=$BfTimestamp;outputName='BF.bmp'},[ordered]@{channel='DF_BACKSIDE';relativePath='df/source.bmp';expectedBytes=256;expectedLastWriteTimeUtc=$dfTime.ToString('o');outputName='DF.bmp'});sourceImageReadAuthorized=$true;sourceMutationAuthorized=$false;sourceDeletionAuthorized=$false;imageDecodeAuthorized=$false;pixelProcessingAuthorized=$false;taskActionAuthorized=$false;existingProcessActionAuthorized=$false;providerActivationAuthorized=$false;thresholdOrAlgorithmChangeAuthorized=$false;holdClearanceAuthorized=$false;reviewOnly=$true;productionRoutingEnabled=$false}}
$utf8=New-Object Text.UTF8Encoding($false);$successManifest=Join-Path $root 'success.json';[IO.File]::WriteAllText($successManifest,((New-O3B8Invocation $successOut $bfTime.ToString('o'))|ConvertTo-Json -Depth 12),$utf8);$success=& $endpoint -Rehearsal -InvocationManifest $successManifest|ConvertFrom-Json
Assert-O3B8 ([string]$success.state-eq'PASS_O3B8_EXACT_BACKSIDE_PAIR_STAGED'-and[bool]$success.aliasRemoved-and@($success.sources).Count-eq2) 'O3B8 exact extracted success rehearsal failed.'
$failureManifest=Join-Path $root 'failure.json';[IO.File]::WriteAllText($failureManifest,((New-O3B8Invocation $failureOut '2026-08-20T00:00:00.0000000Z')|ConvertTo-Json -Depth 12),$utf8);$caught=$false;try{& $endpoint -Rehearsal -InvocationManifest $failureManifest|Out-Null}catch{$caught=$true;$failureMessage=$_.Exception.Message}
Assert-O3B8 ($caught-and-not(Test-Path -LiteralPath $failureOut)-and(Test-Path -LiteralPath ($failureOut+'.failed') -PathType Container)-and-not(Test-Path -LiteralPath 'Q:\')) 'O3B8 injected-failure quarantine or alias cleanup failed.'
$gateValue=[ordered]@{schema='argos_ocv03_o3b8_exact_package_rehearsal_gate_v1';createdUtc=[DateTime]::UtcNow.ToString('o');state='PASS_O3B8_EXACT_PACKAGE_REHEARSAL';requestId='REQ_O3B8_20260828A';requestZipSha256=$expectedZip;signatureVerified=$true;payloadCount=4;exactExtractedSuccessState=[string]$success.state;sourceAndOutputHashesMatched=$true;injectedFailureCaught=$caught;injectedFailureMessage=$failureMessage;injectedFailureQuarantined=$true;sourceAliasRemovedAfterSuccess=$true;sourceAliasRemovedAfterFailure=$true;sourceMutationPerformed=$false;taskOrExistingProcessActionPerformed=$false;providerActivated=$false;requestRetryAuthorized=$false;fixtureRoot=$root;fixturePreserved=$true;reviewOnly=$true;productionRoutingEnabled=$false};[IO.File]::WriteAllText($gatePath,(($gateValue|ConvertTo-Json -Depth 10)+[Environment]::NewLine),$utf8);$gateValue|ConvertTo-Json -Depth 10
