#Requires -Version 5.1
[CmdletBinding()]
param([switch]$Preflight, [switch]$Publish)

$ErrorActionPreference = 'Stop'
Set-StrictMode -Version Latest
if (([bool]$Preflight) -eq ([bool]$Publish)) { throw 'Specify exactly one of -Preflight or -Publish.' }
if ([string]$PSVersionTable.PSEdition -ne 'Desktop' -or $PSVersionTable.PSVersion.Major -ne 5 -or $PSVersionTable.PSVersion.Minor -ne 1) { throw 'R18W4S21 publisher requires Windows PowerShell 5.1 exactly.' }
function Require([bool]$Condition,[string]$Message){ if(-not $Condition){ throw $Message } }
function Get-Sha256([string]$Path){ (Get-FileHash -LiteralPath $Path -Algorithm SHA256).Hash }
function Require-Pin([string]$Path,[string]$Sha256){ Require (Test-Path -LiteralPath $Path -PathType Leaf) "Missing dependency: $Path"; Require ((Get-Sha256 $Path) -eq $Sha256) "Changed dependency: $Path" }
function Normalize-Root([string]$Value){ if([string]::IsNullOrWhiteSpace($Value)){return ''}; $Value.Trim().TrimEnd('\').Replace('/','\') }
function Read-ZipEntryBytes([IO.Compression.ZipArchive]$Zip,[string]$Name,[int64]$MaximumBytes){ $m=@($Zip.Entries|Where-Object{[string]::Equals(([string]$_.FullName).Replace('\','/'),$Name,[StringComparison]::OrdinalIgnoreCase)}); Require ($m.Count -eq 1 -and [int64]$m[0].Length -le $MaximumBytes) "Missing, duplicated, or oversized entry: $Name"; $i=$m[0].Open();$o=New-Object IO.MemoryStream;try{$i.CopyTo($o);return ,([byte[]]$o.ToArray())}finally{$o.Dispose();$i.Dispose()} }
function Write-JsonCreateNew([string]$Path,[object]$Value){ $b=(New-Object Text.UTF8Encoding($false)).GetBytes((($Value|ConvertTo-Json -Depth 16)+[Environment]::NewLine));$s=New-Object IO.FileStream($Path,[IO.FileMode]::CreateNew,[IO.FileAccess]::Write,[IO.FileShare]::None);try{$s.Write($b,0,$b.Length)}finally{$s.Dispose()} }

$project=[IO.Path]::GetFullPath((Join-Path $PSScriptRoot '..\..'))
$requestId='REQ_S21_20260905212322_S9RHWN0X00G4K59QB7Q1120VDR';$branch='codex/opencv-scribe-deciphering'
$zipSha='CF86A6880CB6FB343DE440CD50865583C97608E1768C104B444706C5C7E45749';$sourceZip=Join-Path $PSScriptRoot ('final\'+$requestId+'.ready.zip')
$packageGatePath=Join-Path $PSScriptRoot 'R18W4S21_FINAL_PACKAGE_GATE.json';$routeGatePath=Join-Path $PSScriptRoot 'R18W4S21_COMPLETE_ROUTE_GATE.json';$freezeGatePath=Join-Path $PSScriptRoot 'R18W4S21_PRESIGNATURE_FREEZE_GATE.json';$definitionPath=Join-Path $PSScriptRoot 'R18W4S21_DATA_PULL_DEFINITION.json';$authorityPath=Join-Path $PSScriptRoot 'R18W4S21_PUBLICATION_AUTHORITY.json';$preactionPath=Join-Path $PSScriptRoot 'PREACTION_R18W4S21_PUBLICATION.json';$collisionPath=Join-Path $PSScriptRoot 'R18W4S21_PREPUBLICATION_REQUEST_ID_UNIQUENESS_GATE.json';$signedGatePath=Join-Path $PSScriptRoot 'R18W4S21_SIGNED_UNPUBLISHED_GATE.json'
$historyPath=Join-Path $project 'work\ARGOS_HISTORY_NO_REPEAT_AUDIT_20260820.json';$preactionTool=Join-Path $project 'utilities\Confirm-ArgosZeroRecurrencePreaction.ps1';$certPath=Join-Path $project 'work\PROJECT_PORTAL_REVIEW_ONLY\enrollment\ARGOS_PROJECT_PORTAL_LAPTOP_SIGNER_PUBLIC.cer';$publishGatePath=Join-Path $PSScriptRoot 'R18W4S21_PUBLISH_GATE.json'
$shareRoot='\\shm-cifs\Department\DE-1302_FAB_BE_Engineering\60_Saw_VI_Sort\600_General\Joshua.conn\AVI_Images\Argos\Uploads\InspectionRevs';$requestRoot='U:\ProjectPortalRO\requests';$responseRoot='U:\ProjectPortalRO\responses';$readyPath=$requestRoot+'\'+$requestId+'.ready.zip';$uploadPath=$readyPath+'.upload';$processedPath=$requestRoot+'\processed\'+$requestId+'.ready.zip'
Require-Pin $sourceZip $zipSha;Require-Pin $packageGatePath 'C6518EC5DF7DBA031EB8F655C8290FEA37A393FB5E5E66D138DB22DA1B12B5D9';Require-Pin $routeGatePath 'E11779A60F5721E59021DAA2B0DC2BB03ABECF50C575392C6C37B08C5F9FFD1A';Require-Pin $freezeGatePath '7CED699C45C3D51759ECAB5B03E0A24FAF41276030337E5D24469BF63B6F8883';Require-Pin $definitionPath '0FC0E85CB455FA4201BA8DBDEEAC85F553204F7C66867216BBC853B9152F8044';Require-Pin $signedGatePath '25AE85F176C9EFFEB681AAB8D7F91911EEF814F5774D5FC8ECB1087915C98AD1';Require-Pin $authorityPath 'EF6906C784DFA350E2F5ABC4D3B1C2594CF592AE5FCC8F7F37F4E4F16E75E708';Require-Pin $preactionPath '20002BC8E3BDD160B8E107862AC00EB42AEE79D94CA2D1C1CBB7E621957A85E0';Require-Pin $certPath '2B434D0CF6A0D6D69AAE3D280032EFF00807D423CA3B3D7F2EFC1C6BB628BFFF'
$pj=(& $preactionTool -AuditPath $historyPath -ContractPath $preactionPath -ProjectRoot $project -Preflight|Out-String)|ConvertFrom-Json;Require ([string]$pj.state -eq 'PASS_ARGOS_ZERO_RECURRENCE_PREACTION') 'Publication preaction failed.'
$packageGate=Get-Content $packageGatePath -Raw|ConvertFrom-Json;$routeGate=Get-Content $routeGatePath -Raw|ConvertFrom-Json;$freezeGate=Get-Content $freezeGatePath -Raw|ConvertFrom-Json;$definition=Get-Content $definitionPath -Raw|ConvertFrom-Json;$authority=Get-Content $authorityPath -Raw|ConvertFrom-Json;$collision=Get-Content $collisionPath -Raw|ConvertFrom-Json
Require ([string]$packageGate.state -eq 'PASS_R18W4S21_FINAL_PACKAGE_GATE_SIGNED_UNPUBLISHED' -and [string]$packageGate.requestId -eq $requestId -and [int]$packageGate.requestedFileCount -eq 2 -and -not [bool]$packageGate.retryAuthorized) 'Final package gate changed.'
Require ([string]$routeGate.state -eq 'PASS_R18W4S21_COMPLETE_ROUTE_GATE_SIGNED_UNPUBLISHED' -and [int]$routeGate.routePathCount -eq 40 -and [int]$routeGate.maximumEffectiveLength -lt 200 -and [int]$routeGate.maximumComponentLength -le 80 -and [int]$routeGate.reservedSuffixCharacters -eq 32 -and @($routeGate.routeRows|Where-Object{$_.state -ne 'PASS_PATH_BUDGET'}).Count -eq 0) 'Route gate changed.'
Require ([string]$freezeGate.state -eq 'PASS_R18W4S21_PRESIGNATURE_FREEZE' -and [string]$freezeGate.requestId -eq $requestId) 'Freeze gate changed.'
Require ([string]$authority.state -eq 'PASS_R18W4S21_PUBLICATION_AUTHORITY' -and [string]$authority.operatorAuthority -eq ('PUBLISH for '+$requestId) -and [int]$authority.maximumPublications -eq 1 -and -not [bool]$authority.retryAuthorized) 'Publication authority changed.'
Require ([string]$collision.state -eq 'PASS_R18W4S21_REQUEST_ID_UNIQUENESS_ZERO_COLLISIONS' -and [int]$collision.collisionCount -eq 0 -and [bool]$collision.allAccessibleNamespacesScanned -and -not [bool]$collision.zipPayloadOrImageMembersRead) 'Prepublication collision gate failed.'
Require ((([DateTimeOffset]::UtcNow)-[DateTimeOffset]::Parse([string]$collision.checkedUtc)).TotalMinutes -le 15) 'Prepublication collision gate is stale.'
Require (-not(Test-Path $publishGatePath)) 'Publication gate exists; republish refused.'
Add-Type -AssemblyName System.IO.Compression;Add-Type -AssemblyName System.IO.Compression.FileSystem;$z=[IO.Compression.ZipFile]::OpenRead($sourceZip);try{Require(@($z.Entries).Count -eq 2)'ZIP membership changed.';$mb=Read-ZipEntryBytes $z 'PORTAL_REQUEST_MANIFEST.json' 1048576;$sb=Read-ZipEntryBytes $z 'PORTAL_REQUEST_MANIFEST.sig' 8192}finally{$z.Dispose()};$m=(New-Object Text.UTF8Encoding($false,$true)).GetString($mb)|ConvertFrom-Json;$c=New-Object Security.Cryptography.X509Certificates.X509Certificate2($certPath);$rsa=[Security.Cryptography.X509Certificates.RSACertificateExtensions]::GetRSAPublicKey($c);try{$sig=$rsa.VerifyData($mb,$sb,[Security.Cryptography.HashAlgorithmName]::SHA256,[Security.Cryptography.RSASignaturePadding]::Pkcs1)}finally{$rsa.Dispose()};Require $sig 'Signature verification failed.'
$ep=@($definition.parameters.relativePaths|ForEach-Object{[string]$_});$mp=@($m.parameters.relativePaths|ForEach-Object{[string]$_});Require([string]$m.requestId -eq $requestId -and [string]$m.targetRole -eq 'JBOD' -and [string]$m.jobClass -eq 'DATA_PULL' -and @($m.files).Count -eq 0)'Manifest identity changed.';Require([DateTimeOffset]::UtcNow -lt [DateTimeOffset]::Parse([string]$m.expiresUtc))'Request expired.';Require([string]$m.parameters.approvedRoot -eq 'JBOD_PROCESSOR_REVIEW' -and [int]$m.parameters.maximumFiles -eq 2 -and [int64]$m.parameters.maximumBytes -eq 50331648 -and $mp.Count -eq 2 -and @(Compare-Object $ep $mp -SyncWindow 0).Count -eq 0)'Signed scope changed.'
$cb=(& git -C $project branch --show-current|Out-String).Trim();$lt=(& git -C $project rev-parse HEAD|Out-String).Trim();$rt=(& git -C $project rev-parse ('origin/'+$branch)|Out-String).Trim();$st=@(& git -C $project status --porcelain=v1 --untracked-files=all);Require($cb -eq $branch -and $lt -eq $rt)'Branch tip mismatch.';Require(@($st|Where-Object{$_ -ne '?? work/OPENCV_SCRIBE_R18W4S21/R18W4S21_PREPUBLICATION_REQUEST_ID_UNIQUENESS_GATE.json'}).Count -eq 0)'Unexpected worktree change.'
$d=Get-PSDrive U -ErrorAction Stop;$disk=Get-CimInstance Win32_LogicalDisk -Filter "DeviceID='U:'";Require($null-ne$disk -and [int]$disk.DriveType -eq 4 -and (Normalize-Root $d.DisplayRoot).Equals((Normalize-Root $shareRoot),[StringComparison]::OrdinalIgnoreCase) -and (Normalize-Root $disk.ProviderName).Equals((Normalize-Root $shareRoot),[StringComparison]::OrdinalIgnoreCase))'Persistent U mapping changed.';Require(Test-Path $requestRoot -PathType Container)'Request root unavailable.';Require(Test-Path $responseRoot -PathType Container)'Response root unavailable.';Require(-not(Test-Path $uploadPath)-and-not(Test-Path $readyPath)-and-not(Test-Path $processedPath))'Request already exists.';$pending=@(Get-ChildItem $requestRoot -File|Where-Object{$_.Name-like'*.ready.zip'-or$_.Name-like'*.ready.zip.upload'});Require($pending.Count-eq 0)'Another request is pending.'
$bytes=[int64](Get-Item $sourceZip).Length;$result=[ordered]@{schema='argos_opencv_scribe_r18w4s21_publish_gate_v1';publishedUtc=[DateTime]::UtcNow.ToString('o');state=$(if($Preflight){'PASS_R18W4S21_PUBLISH_PREFLIGHT'}else{'PASS_R18W4S21_EXACT_SIGNED_DATA_PULL_PUBLISHED_CREATE_NEW'});requestId=$requestId;publishedPath=$readyPath;bytes=$bytes;sha256=$zipSha;signatureVerified=$true;expiresUtc=[string]$m.expiresUtc;pendingRequestCount=0;branch=$branch;localTip=$lt;remoteTip=$rt;createNew=$true;overwritePerformed=$false;maximumPublicationsAuthorized=1;retryAuthorized=$false;matchingSignedTerminalResponseCollectionOnly=$true;expectedResponseSourceRole='JBOD';expectedResponseSignerThumbprint='DF46FA4B81065AB273A88F4E1FA8AC0F2EE518CC';persistentUMapping=$true;requestedRelativePaths=$mp;maximumFiles=2;maximumBytes=50331648;imageBytesRead=$false;sourceMutationPerformed=$false;identityAccepted=$false;reviewOnly=$true;productionRoutingEnabled=$false;mutationsPerformed=$false};if($Preflight){$result|ConvertTo-Json -Depth 16;return}
$ss=[IO.File]::Open($sourceZip,[IO.FileMode]::Open,[IO.FileAccess]::Read,[IO.FileShare]::Read);$ts=New-Object IO.FileStream($uploadPath,[IO.FileMode]::CreateNew,[IO.FileAccess]::Write,[IO.FileShare]::None);try{$ss.CopyTo($ts);$ts.Flush($true)}finally{$ts.Dispose();$ss.Dispose()};Require([int64](Get-Item $uploadPath).Length -eq $bytes -and (Get-Sha256 $uploadPath)-eq$zipSha)'Upload verification failed.';Require(-not(Test-Path $readyPath))'Ready path appeared.';Move-Item -LiteralPath $uploadPath -Destination $readyPath;$result.mutationsPerformed=$true;Write-JsonCreateNew $publishGatePath $result;$result|ConvertTo-Json -Depth 16
