#Requires -Version 5.1
[CmdletBinding()]
param([switch]$Preflight,[switch]$Gate)

$ErrorActionPreference='Stop'
Set-StrictMode -Version Latest
if(([bool]$Preflight)-eq([bool]$Gate)){throw 'Specify exactly one of -Preflight or -Gate.'}
function Assert-True([bool]$Condition,[string]$Message){if(-not$Condition){throw $Message}}
function Get-Sha([string]$Path){return(Get-FileHash -LiteralPath $Path -Algorithm SHA256).Hash}
function Write-NewJson([string]$Path,[object]$Value,[int]$Depth=24){Assert-True (-not(Test-Path -LiteralPath $Path)) "O3Q2 exact rehearsal refuses overwrite: $Path";[IO.File]::WriteAllText($Path,(($Value|ConvertTo-Json -Depth $Depth)+[Environment]::NewLine),(New-Object Text.UTF8Encoding($false)))}

$project=[IO.Path]::GetFullPath((Join-Path $PSScriptRoot '..\..'));$requestId='REQ_20260828T033000222Z_62629419O3Q2';$zip=Join-Path $PSScriptRoot 'final_numeric\REQ_20260828T033000222Z_62629419O3Q2.ready.zip';$certificate=Join-Path $project 'work\PROJECT_PORTAL_REVIEW_ONLY\enrollment\ARGOS_PROJECT_PORTAL_LAPTOP_SIGNER_PUBLIC.cer';$packageTester=Join-Path $project 'work\PROJECT_PORTAL_REVIEW_ONLY\scripts\Test-SignedPortalPackage.ps1';$endpointWorker=Join-Path $project 'work\OPENCV_OLS3\pkg\payload\W.ps1';$queueGate=Join-Path $project 'work\JBOD_ENDPOINT_MAINTENANCE_PATH_C1E\C1E_QUEUE_SAFETY_PASS.json';$python='C:\Python314\python.exe';$installation=Join-Path $project 'work\OPENCV_EDGE_NOTCH_O3P1\O3P2_LOCAL_RUNTIME_GATE.json';$fixtureRoot='C:\A3Q2R3';$failureRoot='C:\A3Q2F3';$successRoot='C:\A3Q2P3';$gatePath=Join-Path $PSScriptRoot 'O3Q2_EXACT_PACKAGE_REHEARSAL_R3_GATE.json'
$expectedZip='F107CB94E8580EB018C373F2995BC6D817D7E4337D351F875E861B5A42D1AACC';$endpointSha='34998072D7F58D554CFDDE9C0645FBC7CF03A7B6D7EC8F0FD3F905A0929A3A52';$engineSha='41F60AF393E0B2C752AF6B33BB6673145490AE2BB346A4DA8E59A2D42E383E36';$liveInvocationSha='24E66125FDFC12903BBBA82BC87DD3D644C08E9269148AC44678239750669EF4';$anchorSha='6B7CC6E643265545297BA4DED1E6B37AB262349572194B13F79264EF77D8DCE4'
foreach($path in @($zip,$certificate,$packageTester,$endpointWorker,$queueGate,$python,$installation)){Assert-True (Test-Path -LiteralPath $path -PathType Leaf) "O3Q2 exact rehearsal dependency absent: $path"};Assert-True ((Get-Sha $zip)-eq$expectedZip) 'O3Q2 exact final ZIP changed.';Assert-True ((Get-Sha $endpointWorker)-eq'CB6700714E20DAC2D3C097095A2800C92ECAAC75F29878F4C86326493B246250') 'O3Q2 endpoint worker changed.';Assert-True ((Get-Sha $queueGate)-eq'170015C259C3EC8FC0B369F070748A555336F8FB312636819B7F99EBCE85A65D') 'O3Q2 queue gate changed.'
foreach($path in @($fixtureRoot,$failureRoot,$failureRoot+'.partial',$failureRoot+'.failed',$successRoot,$successRoot+'.partial',$successRoot+'.failed',$gatePath)){Assert-True (-not(Test-Path -LiteralPath $path)) "O3Q2 exact rehearsal create-new target exists: $path"};Assert-True (-not(Test-Path -LiteralPath 'Q:\')-and$null-eq(Get-PSDrive -Name Q -ErrorAction SilentlyContinue)) 'O3Q2 exact rehearsal Q: alias is not unused.'
$pathCheck=&(Join-Path $project 'utilities\Confirm-ArgosPathBudget.ps1') -CandidatePath @((Join-Path $fixtureRoot 'x\payload\Invoke-O3Q2Slot16NumericEndpoint.ps1'),(Join-Path $fixtureRoot 'x\payload\O3P8_DETECTOR_CONFIG_EQUIVALENCE_GATE.json'),$failureRoot+'.failed\O3Q2_JOB.json',(Join-Path $successRoot 'O3Q2_RESULT.json'),$gatePath) -ReservedSuffixCharacters 32 -AsJson|ConvertFrom-Json;Assert-True ([string]$pathCheck.state-eq'PASS_PATH_BUDGET') 'O3Q2 exact rehearsal path gate failed.'
if($Preflight){[ordered]@{schema='argos_o3q1_exact_package_rehearsal_r3_preflight_v1';createdUtc=[DateTime]::UtcNow.ToString('o');state='PASS_O3Q2_EXACT_PACKAGE_REHEARSAL_R3_PREFLIGHT';requestId=$requestId;requestZipSha256=$expectedZip;fixtureRoot=$fixtureRoot;failureRoot=$failureRoot;successRoot=$successRoot;sourceAliasDrive='Q:';mutationsPerformed=$false;sourceImageBytesRead=$false;providerActivated=$false;reviewOnly=$true;productionRoutingEnabled=$false}|ConvertTo-Json -Depth 8;return}

[void](New-Item -ItemType Directory -Path $fixtureRoot);$extract=Join-Path $fixtureRoot 'x';Add-Type -AssemblyName System.IO.Compression.FileSystem;[IO.Compression.ZipFile]::ExtractToDirectory($zip,$extract);$packageTest=&$packageTester -PackagePath $extract -SignerCertificatePath $certificate -ExpectedTargetRole JBOD -ExpectedJobClass MAINTENANCE_PATCH;Assert-True ([string]$packageTest.State-eq'PASS_SIGNED_PORTAL_PACKAGE') 'O3Q2 exact package signature failed.'
$manifest=Get-Content -LiteralPath (Join-Path $extract 'PORTAL_REQUEST_MANIFEST.json') -Raw|ConvertFrom-Json;$payload=Join-Path $extract 'payload';$endpoint=Join-Path $payload 'Invoke-O3Q2Slot16NumericEndpoint.ps1';$engine=Join-Path $payload 'Detect-O3P8FrontSplitNotches.py';$liveInvocation=Join-Path $payload 'O3Q2_ENDPOINT_LIVE_INVOCATION.json';$anchor=Join-Path $payload 'OCV03_NotchReviewOpenCvV1.py';$liveInvocationValue=Get-Content -LiteralPath $liveInvocation -Raw|ConvertFrom-Json;$liveContract=Get-Content -LiteralPath (Join-Path $payload 'O3Q2_JOB_CONTRACT.json') -Raw|ConvertFrom-Json;$liveSourceDrives=@(@([IO.Path]::GetPathRoot([string]$liveContract.input.bf.path),[IO.Path]::GetPathRoot([string]$liveContract.input.df.path))|Sort-Object -Unique);Assert-True ($liveSourceDrives.Count-eq1-and$liveSourceDrives[0].TrimEnd('\').Equals([string]$liveInvocationValue.sourceAliasDrive,[StringComparison]::OrdinalIgnoreCase)) 'O3Q2 live alias and frozen source paths differ.'
Assert-True ([string]$manifest.requestId-eq$requestId-and@($manifest.files).Count-eq12-and@($manifest.changes).Count-eq1) 'O3Q2 signed manifest identity changed.';Assert-True ((Get-Sha $endpoint)-eq$endpointSha-and(Get-Sha $engine)-eq$engineSha-and(Get-Sha $liveInvocation)-eq$liveInvocationSha-and(Get-Sha $anchor)-eq$anchorSha) 'O3Q2 extracted payload changed.';Assert-True ([int64]$manifest.maxResultBytes-eq4194304-and[string]$manifest.entryPoint-eq'payload/Invoke-O3Q2Slot16NumericEndpoint.ps1'-and@($manifest.entryPointMutations).Count-eq1-and@($manifest.entryPointOutputs).Count-eq1-and@($manifest.allowedTaskActions).Count-eq0-and@($manifest.allowedProcessActions).Count-eq1-and-not[bool]$manifest.requestRetryAuthorized) 'O3Q2 signed maintenance contract changed.'
$change=$manifest.changes[0];Assert-True ([string]$change.source-eq'payload/OCV03_NotchReviewOpenCvV1.py'-and[string]$change.installedSha256-eq$anchorSha-and@($change.approvedPredecessorSha256).Count-eq1-and@($change.approvedPredecessorSha256)-contains$anchorSha-and-not[bool]$change.allowCreate) 'O3Q2 signed protocol-anchor contract changed.'
$absent=Join-Path $fixtureRoot 'absent\OCV03_NotchReviewOpenCvV1.py';Assert-True (-not(Test-Path -LiteralPath $absent)-and-not[bool]$change.allowCreate) 'O3Q2 absent protocol anchor was not rejected.';$targetRoot=Join-Path $fixtureRoot 'target';[void](New-Item -ItemType Directory -Path $targetRoot);$target=Join-Path $targetRoot 'OCV03_NotchReviewOpenCvV1.py';Copy-Item -LiteralPath $anchor -Destination $target;$targetBefore=Get-Sha $target;Assert-True (@($change.approvedPredecessorSha256)-contains$targetBefore-and$targetBefore-eq$anchorSha-and(Get-Sha $target)-eq$targetBefore) 'O3Q2 same-hash protocol anchor changed.';$unapprovedRoot=Join-Path $fixtureRoot 'unapproved';[void](New-Item -ItemType Directory -Path $unapprovedRoot);$unapproved=Join-Path $unapprovedRoot 'OCV03_NotchReviewOpenCvV1.py';[IO.File]::WriteAllText($unapproved,'unapproved',(New-Object Text.UTF8Encoding($false)));$unapprovedSha=Get-Sha $unapproved;Assert-True (@($change.approvedPredecessorSha256)-notcontains$unapprovedSha-and(Get-Sha $unapproved)-eq$unapprovedSha) 'O3Q2 unapproved predecessor handling changed.'
$extra=@(
 @('work\OPENCV_EDGE_NOTCH_O3Q2\O3Q2_REHEARSAL_SEED_PROJECTION.json','REHEARSAL_SEED.json'),@('work\OPENCV_EDGE_NOTCH_O3Q2\O3Q2_REHEARSAL_SEED_SOURCE.json','REHEARSAL_SEED_SOURCE.json'),@('work\O3D2\R6\62546-481_POST2_SLOT17\NATIVE_WAFER_POSE_OPENCV_V2.json','REHEARSAL_SOURCE_RECORD.json'),@('work\OPENCV_EDGE_NOTCH_O3Q2\O3Q2_REHEARSAL_RUNTIME_GATE.json','REHEARSAL_RUNTIME_GATE.json'),@('work\OPENCV_EDGE_NOTCH_O3Q2\O3Q2_REHEARSAL_JOB_CONTRACT.json','REHEARSAL_JOB_CONTRACT.json'),@('work\OPENCV_EDGE_NOTCH_O3Q2\O3Q2_REHEARSAL_TERMINAL_FIXTURE.json','REHEARSAL_TERMINAL_FIXTURE.json'))
foreach($row in $extra){Copy-Item -LiteralPath (Join-Path $project $row[0]) -Destination (Join-Path $payload $row[1]) -ErrorAction Stop}
function New-RehearsalInvocation([string]$OutputRoot,[int]$TimeoutSeconds){return [ordered]@{schema='argos_ocv03_o3q1_endpoint_invocation_v1';state='FROZEN_REHEARSAL_CONTRACT';revision='FMOCV03_O3Q2_EXACT_PACKAGE_REHEARSAL_R3_20260828';expectedComputerName=$env:COMPUTERNAME;payloadRoot=$payload;engineFile='Detect-O3P8FrontSplitNotches.py';engineSha256=$engineSha;topologyFile='WaferTopologyAxisOpenCv.py';topologySha256='D8897C1A5B60CB5AA9B0343CF8C9E5A249CCC5DEF5FBCDFE645EC08C354EF3BD';cropFile='OCV03_NotchReviewOpenCvV1.py';cropSha256=$anchorSha;seedFile='REHEARSAL_SEED.json';seedSha256='0372C4E4BA29B8A8D4A7D1961BF1CAB7AA36C7E5F0553480AF82E605B399E770';seedSourceManifestFile='REHEARSAL_SEED_SOURCE.json';seedSourceManifestSha256='71F378AC5675B1992269D4D27859859873AB405A3F8F5040A4F60CA8396B1FFF';sourceRecordFile='REHEARSAL_SOURCE_RECORD.json';sourceRecordSha256='4ED3D611A2C69F4F9B3BC26F6ECCC5DDDFD7339F8CE6252B7FF83A74C8D1C3F8';runtimeGateFile='REHEARSAL_RUNTIME_GATE.json';runtimeGateSha256='0CE732749B6A9F07E930547689D85A68552A29382DBB9CA3018D7D6C9E75BC60';jobContractFile='REHEARSAL_JOB_CONTRACT.json';jobContractSha256='787B901B59C650565A3DAA91AF9C8FCA2052C096F336DDD54F40E3CB8214C140';terminalFixtureFile='REHEARSAL_TERMINAL_FIXTURE.json';terminalFixtureSha256='EE3BABBAC56B0304496C9B2033DCA0BE096987B727647016B386A69A7B79C6D2';configEquivalenceGateFile='O3P8_DETECTOR_CONFIG_EQUIVALENCE_GATE.json';configEquivalenceGateSha256='CF896E114179370BC9C8A58D64FDD3470EDCAB1A96836252693C935845224F95';runtimePath=$python;runtimeRoot='C:\A3P2R';pythonModuleRoot='C:\A3P2R';runtimeSha256='4942B86A6597E5AEE0128DAA00050ED79BC21F6E709A78EB19CBFEB0C2F39AC9';runtimeInstallationPath=$installation;runtimeInstallationSha256='E22C0E27D3966B17DF83F205291CEB6B1C5B12A14EE306D157383514E1419FB9';sourceAliasDrive='Q:';sourceRoot=$project;outputRoot=$OutputRoot;processorCommandToken='Invoke-AllWaferProcessorV2.ps1';pythonChildTimeoutSeconds=$TimeoutSeconds;maximumStdoutBytes=1048576;sourceImageReadAuthorized=$true;detectorRerunAuthorized=$true;thresholdOrAlgorithmChangeAuthorized=$false;allFrozenDfSeedsRequired=$true;expectedSeedCandidateCount=1;frontsideOnly=$true;backsidePixelsConsumed=$false;argosRotationMetadataConsumed=$false;knownNotchLocationConsumed=$false;hotspotMembershipConsumed=$false;taskOrManagedProcessActionAuthorized=$false;sourceMutationAuthorized=$false;sourceDeletionAuthorized=$false;providerActivationAuthorized=$false;requestRetryAuthorized=$false;reviewOnly=$true;trainingEligible=$false;xmlEligible=$false;productionEligible=$false;productionRoutingEnabled=$false}}
$successInvocationPath=Join-Path $fixtureRoot 'success_invocation.json';Write-NewJson $successInvocationPath (New-RehearsalInvocation $successRoot 1500);$successInvocationValue=Get-Content -LiteralPath $successInvocationPath -Raw|ConvertFrom-Json;$rehearsalContract=Get-Content -LiteralPath (Join-Path $payload 'REHEARSAL_JOB_CONTRACT.json') -Raw|ConvertFrom-Json;$rehearsalSourceDrives=@(@([IO.Path]::GetPathRoot([string]$rehearsalContract.input.bf.path),[IO.Path]::GetPathRoot([string]$rehearsalContract.input.df.path))|Sort-Object -Unique);Assert-True ($rehearsalSourceDrives.Count-eq1-and$rehearsalSourceDrives[0].TrimEnd('\').Equals([string]$successInvocationValue.sourceAliasDrive,[StringComparison]::OrdinalIgnoreCase)) 'O3Q2 rehearsal alias and frozen source paths differ.';$endpointPreflight=(&$endpoint -Preflight -Rehearsal -InvocationManifest $successInvocationPath)|ConvertFrom-Json;Assert-True ([string]$endpointPreflight.state-eq'PASS_O3Q2_ENDPOINT_PREFLIGHT'-and-not[bool]$endpointPreflight.sourceImageBytesRead-and-not[bool]$endpointPreflight.outputCreated) 'O3Q2 extracted endpoint preflight failed.'
$failureInvocationPath=Join-Path $fixtureRoot 'failure_invocation.json';Write-NewJson $failureInvocationPath (New-RehearsalInvocation $failureRoot 0);$failureCaught=$false;$failureMessage='';try{[void](&$endpoint -Rehearsal -InvocationManifest $failureInvocationPath)}catch{$failureCaught=$true;$failureMessage=[string]$_.Exception.Message};Assert-True ($failureMessage-eq'O3Q2 Python exceeded its bounded timeout.') 'O3Q2 injected child failure message changed.';Assert-True ($failureCaught-and(Test-Path -LiteralPath ($failureRoot+'.failed') -PathType Container)-and-not(Test-Path -LiteralPath $failureRoot)-and-not(Test-Path -LiteralPath ($failureRoot+'.partial'))-and-not(Test-Path -LiteralPath 'Q:\')) 'O3Q2 injected child failure was not quarantined and cleaned.'
$success=(&$endpoint -Rehearsal -InvocationManifest $successInvocationPath)|ConvertFrom-Json;Assert-True ([string]$success.state-eq'COMPLETE_O3Q2_NUMERIC_REVIEW_ONLY'-and[bool]$success.numericIndependentPass-and[int]$success.seedCount-eq1-and[int]$success.eligibleCount-eq1-and[bool]$success.processorIdentityUnchanged-and[bool]$success.sourceAliasRemoved-and-not[bool]$success.knownNotchLocationConsumed-and-not[bool]$success.hotspotMembershipConsumed) 'O3Q2 exact extracted endpoint execution failed.'
$record=[ordered]@{schema='argos_o3q1_exact_package_rehearsal_r3_gate_v1';createdUtc=[DateTime]::UtcNow.ToString('o');state='PASS_O3Q2_EXACT_PACKAGE_REHEARSAL_R3';requestId=$requestId;requestZipSha256=$expectedZip;windowsPowerShellMajor=$PSVersionTable.PSVersion.Major;windowsPowerShellMinor=$PSVersionTable.PSVersion.Minor;exactSignedZipExtracted=$true;signatureVerified=$true;payloadHashCount=12;changeCount=1;liveAliasMatchesFrozenSourcePaths=$true;rehearsalAliasMatchesFrozenSourcePaths=$true;allowCreateFalseCasePassed=$true;targetHashIdempotentCasePassed=$true;unapprovedPredecessorRefusedBeforeMutation=$true;exactExtractedEndpointPreflightState=[string]$endpointPreflight.state;injectedFailureCaught=$failureCaught;injectedFailureMessage=$failureMessage;injectedFailureQuarantined=$true;sourceAliasRemovedAfterFailure=$true;exactExtractedEndpointExecutionState=[string]$success.state;exactExtractedNumericIndependentPass=[bool]$success.numericIndependentPass;exactExtractedEndpointSha256=Get-Sha $endpoint;exactExtractedEngineSha256=Get-Sha $engine;protocolAnchorSha256=Get-Sha $anchor;protocolAnchorExpectedByteIdentical=$true;installedProtocolAnchorDestinationExecutedByEntrypoint=$false;packagedProtocolAnchorBytesExecutedAsFrozenCropModule=$true;endpointWorkerSha256=Get-Sha $endpointWorker;inheritedQueueSafetyGateSha256=Get-Sha $queueGate;exactEndpointQueueRollbackRehearsalInherited=$true;fixtureRoot=$fixtureRoot;failureRoot=$failureRoot+'.failed';successRoot=$successRoot;fixturePreserved=$true;sourceImageBytesRead=$true;sourceHashesVerifiedBeforeDecode=$true;sourceMutationPerformed=$false;taskActions=0;healthyProcessorTouched=$false;providerActivated=$false;backsidePixelsConsumed=$false;knownNotchLocationConsumed=$false;hotspotMembershipConsumed=$false;requestRetryAuthorized=$false;reviewOnly=$true;trainingEligible=$false;xmlEligible=$false;productionEligible=$false;productionRoutingEnabled=$false};Write-NewJson $gatePath $record 16;$record|ConvertTo-Json -Depth 16
