#Requires -Version 5.1
[CmdletBinding()]
param([Parameter(Mandatory=$true)][string]$InvocationManifest,[switch]$Preflight,[switch]$Collect)
$ErrorActionPreference='Stop';Set-StrictMode -Version Latest
if(([bool]$Preflight)-eq([bool]$Collect)){throw 'Specify exactly one of -Preflight or -Collect.'}
function Assert-O3F11([bool]$Condition,[string]$Message){if(-not$Condition){throw $Message}}
function Get-O3F11Hash([string]$Path){return (Get-FileHash -LiteralPath $Path -Algorithm SHA256).Hash}
function Get-O3F11BytesHash([byte[]]$Bytes){$sha=[Security.Cryptography.SHA256]::Create();try{return ([BitConverter]::ToString($sha.ComputeHash($Bytes))).Replace('-','')}finally{$sha.Dispose()}}
function Write-O3F11Bytes([Parameter(Mandatory=$true)][AllowEmptyCollection()][byte[]]$Bytes){$PSCmdlet.WriteObject($Bytes,$false)}
function Read-O3F11Entry([IO.Compression.ZipArchive]$Archive,[string]$Name,[int64]$MaximumBytes){$entry=$Archive.GetEntry($Name);Assert-O3F11 ($null-ne$entry-and$entry.Length-le$MaximumBytes) "O3F11 response entry absent or oversized: $Name";$stream=$entry.Open();$memory=New-Object IO.MemoryStream;try{$stream.CopyTo($memory);Write-O3F11Bytes -Bytes ([byte[]]$memory.ToArray())}finally{$stream.Dispose();$memory.Dispose()}}
function Write-O3F11Json([string]$Path,[object]$Value){Assert-O3F11 (-not(Test-Path -LiteralPath $Path)) "O3F11 collection gate exists: $Path";[IO.File]::WriteAllText($Path,(($Value|ConvertTo-Json -Depth 16)+[Environment]::NewLine),(New-Object Text.UTF8Encoding($false)))}
$project=[IO.Path]::GetFullPath((Join-Path $PSScriptRoot '..\..'));$invocationPath=[IO.Path]::GetFullPath($InvocationManifest);$expected=Join-Path $PSScriptRoot 'O3F11_RESPONSE_COLLECTION_INVOCATION.json';Assert-O3F11 ($invocationPath.Equals($expected,[StringComparison]::OrdinalIgnoreCase)) 'O3F11 collection invocation path changed.'
$invoke=Get-Content -LiteralPath $invocationPath -Raw|ConvertFrom-Json;Assert-O3F11 ([string]$invoke.schema-eq'argos_ocv03_o3f11_response_collection_invocation_v1'-and[string]$invoke.state-eq'FROZEN_EXACT_RESPONSE_COLLECTION_INVOCATION'-and[string]$invoke.collectorSha256-eq(Get-O3F11Hash $PSCommandPath)) 'O3F11 collection invocation is not frozen.'
$sourceZip=[IO.Path]::GetFullPath([string]$invoke.sourceZip);Assert-O3F11 (Test-Path -LiteralPath $sourceZip -PathType Leaf) 'O3F11 response ZIP is absent.';Assert-O3F11 ((Get-Item $sourceZip).Length-eq[int64]$invoke.sourceZipBytes-and(Get-O3F11Hash $sourceZip)-eq[string]$invoke.sourceZipSha256) 'O3F11 response ZIP identity changed.'
$certificate=Join-Path $project ([string]$invoke.endpointCertificate);Assert-O3F11 ((Get-O3F11Hash $certificate)-eq[string]$invoke.endpointCertificateSha256) 'O3F11 endpoint certificate changed.'
Add-Type -AssemblyName System.IO.Compression;Add-Type -AssemblyName System.IO.Compression.FileSystem;$archive=[IO.Compression.ZipFile]::OpenRead($sourceZip)
try{$names=@($archive.Entries|ForEach-Object{[string]$_.FullName}|Sort-Object);$expectedNames=@('MAINTENANCE.stderr.txt','MAINTENANCE.stdout.txt','PORTAL_RESPONSE_MANIFEST.json','PORTAL_RESPONSE_MANIFEST.sig','RESULT.json')|Sort-Object;Assert-O3F11 ($names.Count-eq5-and@(Compare-Object $expectedNames $names).Count-eq0) 'O3F11 response entry set changed.';$manifestBytes=Read-O3F11Entry $archive 'PORTAL_RESPONSE_MANIFEST.json' 65536;$signatureBytes=Read-O3F11Entry $archive 'PORTAL_RESPONSE_MANIFEST.sig' 8192;$stdoutBytes=Read-O3F11Entry $archive 'MAINTENANCE.stdout.txt' 1048576;$stderrBytes=Read-O3F11Entry $archive 'MAINTENANCE.stderr.txt' 65536;$resultBytes=Read-O3F11Entry $archive 'RESULT.json' 65536}finally{$archive.Dispose()}
Assert-O3F11 ($stderrBytes.Length-eq0) 'O3F11 maintenance stderr is not empty.';$manifest=[Text.Encoding]::UTF8.GetString($manifestBytes)|ConvertFrom-Json;$endpoint=[Text.Encoding]::UTF8.GetString($stdoutBytes)|ConvertFrom-Json;$maintenance=[Text.Encoding]::UTF8.GetString($resultBytes)|ConvertFrom-Json
Assert-O3F11 ([string]$manifest.requestId-eq[string]$invoke.requestId-and[string]$manifest.responseId-eq[string]$invoke.responseId-and[string]$manifest.state-eq'PASS_MAINTENANCE_PATCH'-and[string]$manifest.sourceRole-eq'JBOD') 'O3F11 response correlation/state changed.'
$cert=New-Object Security.Cryptography.X509Certificates.X509Certificate2($certificate);$rsa=[Security.Cryptography.X509Certificates.RSACertificateExtensions]::GetRSAPublicKey($cert);try{$valid=$rsa.VerifyData($manifestBytes,$signatureBytes,[Security.Cryptography.HashAlgorithmName]::SHA256,[Security.Cryptography.RSASignaturePadding]::Pkcs1)}finally{$rsa.Dispose()};Assert-O3F11 ($valid-and$cert.Thumbprint.ToUpperInvariant()-eq[string]$invoke.expectedSignerThumbprint) 'O3F11 response signature failed.'
$actual=@{'MAINTENANCE.stderr.txt'=$stderrBytes;'MAINTENANCE.stdout.txt'=$stdoutBytes;'RESULT.json'=$resultBytes};Assert-O3F11 (@($manifest.files).Count-eq3) 'O3F11 response declared-file count changed.';foreach($record in @($manifest.files)){$name=[string]$record.path;Assert-O3F11 ($actual.ContainsKey($name)) "O3F11 unexpected response file: $name";$bytes=[byte[]]$actual[$name];Assert-O3F11 ($bytes.Length-eq[int64]$record.bytes-and(Get-O3F11BytesHash $bytes)-eq[string]$record.sha256) "O3F11 response file hash changed: $name"}
Assert-O3F11 ([string]$maintenance.state-eq'PASS_MAINTENANCE_PATCH'-and[int]$maintenance.exitCode-eq0-and[string]$maintenance.entryPoint-eq'payload/Invoke-O3F11StagedEndpoint.ps1') 'O3F11 maintenance result changed.'
Assert-O3F11 ([string]$endpoint.schema-eq'argos_ocv03_o3f11_staged_endpoint_result_v1'-and[string]$endpoint.state-eq'COMPLETE_O3F11_GATE_AND_DEV6_REVIEW_ONLY'-and@($endpoint.dev6.cases).Count-eq6) 'O3F11 endpoint terminal result changed.'
Assert-O3F11 ([string]::Join('|',@($endpoint.stages))-ceq'SELF_TEST|PREFLIGHT|ROOT_CONTRACT|GATE|DEV6'-and[int]$endpoint.ownedChildCount-eq5-and@($endpoint.childProcessIds).Count-eq5) 'O3F11 endpoint stage/owned-child contract changed.'
Assert-O3F11 ([string]$endpoint.rootContract.schema-eq'argos_ocv03_o3f11_exact_runner_root_contract_v1'-and[string]$endpoint.rootContract.state-eq'PASS_O3F11_EXACT_REAL_RUNNER_ROOT_CONTRACT'-and[string]$endpoint.rootContract.runnerSha256-eq'606AFE5DF058F0298CFE333D9091DF3F5F0B5F222EC03C40E73006773F587D72'-and[string]$endpoint.rootContract.gateRoot-eq'D:/O3F9G11'-and[string]$endpoint.rootContract.dev6Root-eq'D:/O3F9D11'-and[string]::Join('|',@($endpoint.rootContract.gateTerminalKeys))-ceq'commands|stage|state|summarySha256'-and[string]::Join('|',@($endpoint.rootContract.dev6TerminalKeys))-ceq'executedCount|newProviderHoldCount|results|selectedCount|stage|state|stateCounts|summarySha256'-and-not[bool]$endpoint.rootContract.simulatedFilesystem-and[bool]$endpoint.rootContract.incompatibleO3F11PrefixRejected-and-not[bool]$endpoint.rootContract.sourceImageBytesRead-and-not[bool]$endpoint.rootContract.outputCreated-and-not[bool]$endpoint.rootContract.mutationsPerformed) 'O3F11 live root/schema-contract evidence changed.'
Assert-O3F11 ([string]$endpoint.gate.state-eq'COMPLETE_O3F9_GATE'-and[string]$endpoint.dev6.state-eq'COMPLETE_O3F9_DEV6'-and[int]$endpoint.dev6.selectedCount-eq6-and[int]$endpoint.dev6.executedCount-eq6-and[int]$endpoint.dev6.newProviderHoldCount-eq0) 'O3F11 GATE/DEV6 completion contract changed.'
Assert-O3F11 ([bool]$endpoint.sourceImageBytesRead-and[bool]$endpoint.reviewOnly-and-not[bool]$endpoint.productionRoutingEnabled-and-not[bool]$endpoint.sourceMutationPerformed-and-not[bool]$endpoint.sourceDeletionPerformed-and-not[bool]$endpoint.providerActivated-and-not[bool]$endpoint.requestRetryAuthorized-and-not[bool]$endpoint.holdsAutomaticallyCleared-and[int]$endpoint.taskActionCount-eq0-and[int]$endpoint.existingProcessQueryCount-eq0) 'O3F11 endpoint authority widened.'
$localRoot=[IO.Path]::GetFullPath([string]$invoke.localRoot);$gatePath=Join-Path $PSScriptRoot 'O3F11_RESPONSE_COLLECTION_GATE.json';Assert-O3F11 (-not(Test-Path -LiteralPath $localRoot)-and-not(Test-Path -LiteralPath $gatePath)) 'O3F11 create-new collection target exists.'
if($Preflight){[ordered]@{schema='argos_ocv03_o3f11_response_collection_preflight_v1';state='PASS_O3F11_RESPONSE_COLLECTION_PREFLIGHT';requestId=[string]$invoke.requestId;responseId=[string]$invoke.responseId;responseZipSha256=[string]$invoke.sourceZipSha256;signatureVerified=$true;endpointState=[string]$endpoint.state;stages=@($endpoint.stages);ownedChildCount=[int]$endpoint.ownedChildCount;rootContract=$endpoint.rootContract;sourceImageBytesRead=[bool]$endpoint.sourceImageBytesRead;holdsAutomaticallyCleared=[bool]$endpoint.holdsAutomaticallyCleared;dev6CaseCount=6;mutationsPerformed=$false;requestRetryAuthorized=$false;reviewOnly=$true;productionRoutingEnabled=$false}|ConvertTo-Json -Depth 10;return}
[void](New-Item -ItemType Directory -Path $localRoot);$localZip=Join-Path $localRoot ([IO.Path]::GetFileName($sourceZip));Copy-Item -LiteralPath $sourceZip -Destination $localZip;Assert-O3F11 ((Get-O3F11Hash $localZip)-eq[string]$invoke.sourceZipSha256) 'O3F11 local response copy changed.';$extract=Join-Path $localRoot ([string]$invoke.responseId+'.ready');[IO.Compression.ZipFile]::ExtractToDirectory($localZip,$extract)
$gate=[ordered]@{schema='argos_ocv03_o3f11_response_collection_gate_v1';state='PASS_O3F11_MATCHING_SIGNED_RESPONSE_COLLECTED';requestId=[string]$invoke.requestId;responseId=[string]$invoke.responseId;responseZipPath=$localZip;responseZipSha256=[string]$invoke.sourceZipSha256;signatureVerified=$true;endpointState=[string]$endpoint.state;stages=@($endpoint.stages);ownedChildCount=[int]$endpoint.ownedChildCount;rootContract=$endpoint.rootContract;sourceImageBytesRead=[bool]$endpoint.sourceImageBytesRead;holdsAutomaticallyCleared=[bool]$endpoint.holdsAutomaticallyCleared;gateState=[string]$endpoint.gate.state;gateSummarySha256=[string]$endpoint.gate.summarySha256;dev6State=[string]$endpoint.dev6.state;dev6SelectedCount=[int]$endpoint.dev6.selectedCount;dev6ExecutedCount=[int]$endpoint.dev6.executedCount;dev6NewProviderHoldCount=[int]$endpoint.dev6.newProviderHoldCount;dev6SummarySha256=[string]$endpoint.dev6.summarySha256;dev6StateCounts=$endpoint.dev6.stateCounts;dev6Cases=@($endpoint.dev6.cases);requestRetryAuthorized=$false;sourceMutationPerformed=$false;providerActivated=$false;reviewOnly=$true;productionRoutingEnabled=$false};Write-O3F11Json $gatePath $gate;$gate|ConvertTo-Json -Depth 16
