#Requires -Version 5.1
[CmdletBinding()]
param([Parameter(Mandatory=$true)][string]$InvocationManifest,[switch]$Preflight,[switch]$Build)

$ErrorActionPreference='Stop'
Set-StrictMode -Version Latest
if(([bool]$Preflight)-eq([bool]$Build)){throw 'Specify exactly one of -Preflight or -Build.'}
function Assert-True([bool]$Condition,[string]$Message){if(-not$Condition){throw $Message}}
function Get-Sha([string]$Path){return(Get-FileHash -LiteralPath $Path -Algorithm SHA256).Hash}
function Assert-Pin([string]$Path,[string]$Hash,[string]$State=''){Assert-True (Test-Path -LiteralPath $Path -PathType Leaf) "O3Q1 build dependency absent: $Path";Assert-True ((Get-Sha $Path)-eq$Hash) "O3Q1 build dependency changed: $Path";if($State){$value=Get-Content -LiteralPath $Path -Raw|ConvertFrom-Json;Assert-True ([string]$value.state-eq$State) "O3Q1 gate state changed: $Path"}}
function Write-NewJson([string]$Path,[object]$Value,[int]$Depth=16){Assert-True (-not(Test-Path -LiteralPath $Path)) "O3Q1 create-new JSON exists: $Path";[IO.File]::WriteAllText($Path,(($Value|ConvertTo-Json -Depth $Depth)+[Environment]::NewLine),(New-Object Text.UTF8Encoding($false)))}

$project=[IO.Path]::GetFullPath((Join-Path $PSScriptRoot '..\..'))
$invocationPath=[IO.Path]::GetFullPath($InvocationManifest);$expectedInvocationPath=[IO.Path]::GetFullPath((Join-Path $PSScriptRoot 'O3Q1_BUILD_INVOCATION.json'));Assert-True ($invocationPath.Equals($expectedInvocationPath,[StringComparison]::OrdinalIgnoreCase)) 'O3Q1 build invocation path changed.'
$invocation=Get-Content -LiteralPath $invocationPath -Raw|ConvertFrom-Json;Assert-True ([string]$invocation.schema-eq'argos_o3q1_build_invocation_v1'-and[string]$invocation.state-eq'FROZEN_EXACT_BUILD_INVOCATION') 'O3Q1 build invocation state changed.';Assert-True ([string]$invocation.powerShellScriptSha256-eq(Get-Sha $PSCommandPath)) 'O3Q1 invocation does not pin the exact builder.'
$requestId='REQ_20260828T031000111Z_62629419O3Q1';Assert-True ([string]$invocation.requestId-eq$requestId-and[int]$invocation.maximumRequestsAuthorized-eq1-and-not[bool]$invocation.requestRetryAuthorized) 'O3Q1 build authority changed.'
$requestName=$requestId+'.ready';$zipName=$requestName+'.zip';$staging='C:\A3Q1B';$partial=Join-Path $staging 'p';$ready=Join-Path (Join-Path $staging 's') $requestName;$finalRoot=Join-Path $PSScriptRoot 'final_numeric';$finalZip=Join-Path $finalRoot $zipName;$gatePath=Join-Path $PSScriptRoot 'O3Q1_FINAL_PACKAGE_GATE.json'
$definition=Join-Path $PSScriptRoot 'MAINTENANCE_DEFINITION.json';$identity=Join-Path $project 'work\PROJECT_PORTAL_REVIEW_ONLY\state\LAPTOP_SIGNING_IDENTITY.json';$certificate=Join-Path $project 'work\PROJECT_PORTAL_REVIEW_ONLY\enrollment\ARGOS_PROJECT_PORTAL_LAPTOP_SIGNER_PUBLIC.cer';$packageTester=Join-Path $project 'work\PROJECT_PORTAL_REVIEW_ONLY\scripts\Test-SignedPortalPackage.ps1';$pathTool=Join-Path $project 'utilities\Confirm-ArgosPathBudget.ps1';$queueGate=Join-Path $project 'work\JBOD_ENDPOINT_MAINTENANCE_PATH_C1E\C1E_QUEUE_SAFETY_PASS.json';$routeGate=Join-Path $project 'work\OPENCV_EDGE_NOTCH_O3D3\O3D3R4_COMPLETE_ROUTE_GATE.json';$recoveryIntent=Join-Path $PSScriptRoot 'O3Q1_RECOVERY_INTENT.json';$rehearsalGate=Join-Path $PSScriptRoot 'O3Q1_ENDPOINT_REHEARSAL_GATE.json'
$definitionSha='365CCA4D93AF32C36034C1643368E53D43962B61FD94E15054C232608BEB5FE9';$recoverySha='DE5A5684B25CB88A2A6CC82CA13A2B7806400A5FCA082E5B75FE1ED2526A87C1';$rehearsalSha='C34ABFDA997469225F7D511BD8FB8E82D71DCB48D20E7A814B9511EF55194441'
$files=@(
 [ordered]@{source=(Join-Path $PSScriptRoot 'Invoke-O3Q1Slot16NumericEndpoint.ps1');path='payload/Invoke-O3Q1Slot16NumericEndpoint.ps1';sha256='6B61E80C6BB3B347B9AAD74469E51D3BD3D42EE0B305C8996217FE1DEC758AB9'},
 [ordered]@{source=(Join-Path $project 'work\OPENCV_EDGE_NOTCH_O3P8\Detect-O3P8FrontSplitNotches.py');path='payload/Detect-O3P8FrontSplitNotches.py';sha256='41F60AF393E0B2C752AF6B33BB6673145490AE2BB346A4DA8E59A2D42E383E36'},
 [ordered]@{source=(Join-Path $project 'work\OPENCV_EDGE_NOTCH_O3L8\WaferTopologyAxisOpenCv.py');path='payload/WaferTopologyAxisOpenCv.py';sha256='D8897C1A5B60CB5AA9B0343CF8C9E5A249CCC5DEF5FBCDFE645EC08C354EF3BD'},
 [ordered]@{source=(Join-Path $project 'work\OPENCV_EDGE_NOTCH_O3K1\OCV03_NotchReviewOpenCvV1.py');path='payload/OCV03_NotchReviewOpenCvV1.py';sha256='6B7CC6E643265545297BA4DED1E6B37AB262349572194B13F79264EF77D8DCE4'},
 [ordered]@{source=(Join-Path $PSScriptRoot 'O3Q1_SLOT16_SEED_PROJECTION.json');path='payload/O3Q1_SLOT16_SEED_PROJECTION.json';sha256='D9C4FC8A24E4CC4BA98C2B1A4D60E3954328B285FAAEE2FFA6B714100C526F9A'},
 [ordered]@{source=(Join-Path $project 'work\OPENCV_EDGE_NOTCH_O3N1\local_review_r2\assets\MANIFEST.json');path='payload/O3N1_NUMERIC_MANIFEST.json';sha256='69FDAD4AB4DCF06A8A38C76EA009F0DA178896E8D0291668670AB9ADD24A05C8'},
 [ordered]@{source=(Join-Path $project 'work\O3J1R\files\S16.json');path='payload/S16_SOURCE_RECORD.json';sha256='FBBF0609AD337D495E90E73C6F175E6D255287730B81498CE23C4C83536760B1'},
 [ordered]@{source=(Join-Path $PSScriptRoot 'O3Q1_RUNTIME_GATE.json');path='payload/O3Q1_RUNTIME_GATE.json';sha256='301BA078FDC1A267438AB217D29D67492AE4D544FD188919E43AC7DB2E5008BC'},
 [ordered]@{source=(Join-Path $PSScriptRoot 'O3Q1_JOB_CONTRACT.json');path='payload/O3Q1_JOB_CONTRACT.json';sha256='AE8FA5C4F5175F5D4EF2200DD79B257CB1DA0BA1F5B4928AE5BBA4A6D9C05539'},
 [ordered]@{source=(Join-Path $PSScriptRoot 'O3Q1_TERMINAL_GATE_FIXTURE.json');path='payload/O3Q1_TERMINAL_GATE_FIXTURE.json';sha256='9C4A41CDB7423416961CD445C4574B81693652E1DB939226727182AE768FF59A'},
 [ordered]@{source=(Join-Path $project 'work\OPENCV_EDGE_NOTCH_O3P8\O3P8_DETECTOR_CONFIG_EQUIVALENCE_GATE.json');path='payload/O3P8_DETECTOR_CONFIG_EQUIVALENCE_GATE.json';sha256='CF896E114179370BC9C8A58D64FDD3470EDCAB1A96836252693C935845224F95'},
 [ordered]@{source=(Join-Path $PSScriptRoot 'O3Q1_ENDPOINT_LIVE_INVOCATION.json');path='payload/O3Q1_ENDPOINT_LIVE_INVOCATION.json';sha256='1B88F6D6A5A5CCAEC04929BF03CF3ED0B5501F918658E50E0EBD54178828AF6E'}
)
foreach($file in $files){Assert-Pin $file.source $file.sha256};Assert-Pin $definition $definitionSha;Assert-Pin $recoveryIntent $recoverySha;Assert-Pin $rehearsalGate $rehearsalSha 'PASS_O3Q1_ENDPOINT_REHEARSAL';Assert-Pin $queueGate '170015C259C3EC8FC0B369F070748A555336F8FB312636819B7F99EBCE85A65D' 'PASS_JBOD_PORTAL_QUEUE_RECOVERY_V2_1_REHEARSAL';Assert-Pin $routeGate '41A4A1B808E40E7A14A8F22BA7BF9189C0B00B16639A43DDF5AB9A3FC70385D2' 'PASS_O3D3R4_COMPLETE_ROUTE_GATE'
foreach($tool in @($identity,$certificate,$packageTester,$pathTool)){Assert-True (Test-Path -LiteralPath $tool -PathType Leaf) "O3Q1 build tool absent: $tool"}
$def=Get-Content -LiteralPath $definition -Raw|ConvertFrom-Json;Assert-True ([string]$def.targetRole-eq'JBOD'-and[string]$def.jobClass-eq'MAINTENANCE_PATCH'-and[string]$def.entryPoint-eq'payload/Invoke-O3Q1Slot16NumericEndpoint.ps1') 'O3Q1 maintenance identity changed.';Assert-True (@($def.changes).Count-eq1-and@($def.entryPointMutations).Count-eq1-and@($def.entryPointOutputs).Count-eq1-and@($def.allowedTaskActions).Count-eq0-and@($def.allowedProcessActions).Count-eq1) 'O3Q1 maintenance cardinality changed.'
Assert-True ([string]$def.changes[0].source-eq'payload/OCV03_NotchReviewOpenCvV1.py'-and[string]$def.changes[0].installedSha256-eq$files[3].sha256-and@($def.changes[0].approvedPredecessorSha256).Count-eq1-and@($def.changes[0].approvedPredecessorSha256)-contains$files[3].sha256-and-not[bool]$def.changes[0].allowCreate) 'O3Q1 protocol-anchor contract changed.'
Assert-True ([bool]$def.sourceProcessingContract.sourceImageReadAuthorized-and[bool]$def.sourceProcessingContract.detectorRerunAllowed-and-not[bool]$def.sourceProcessingContract.thresholdOrAlgorithmChangeAllowed-and[bool]$def.sourceProcessingContract.allFrozenDfSeedCandidatesRequired-and[int]$def.sourceProcessingContract.expectedDfSeedCandidateCount-eq21-and-not[bool]$def.sourceProcessingContract.knownNotchLocationConsumed-and-not[bool]$def.sourceProcessingContract.hotspotMembershipConsumed-and-not[bool]$def.sourceProcessingContract.backsidePixelsConsumed-and-not[bool]$def.sourceProcessingContract.argosRotationMetadataConsumed-and[bool]$def.sourceProcessingContract.protocolAnchorInstalledBytesExpectedUnchanged-and-not[bool]$def.sourceProcessingContract.installedProtocolAnchorDestinationExecutedByEntrypoint-and[bool]$def.sourceProcessingContract.packagedProtocolAnchorBytesExecutedAsFrozenCropModule-and-not[bool]$def.requestRetryAuthorized) 'O3Q1 processing authority changed.'
Assert-True ([bool]$def.reviewOnly-and-not[bool]$def.trainingEligible-and-not[bool]$def.xmlEligible-and-not[bool]$def.productionEligible-and-not[bool]$def.productionRoutingEnabled) 'O3Q1 authority widened.'
foreach($path in @($staging,$partial,$ready,$finalRoot,$finalZip,$gatePath)){Assert-True (-not(Test-Path -LiteralPath $path)) "O3Q1 fresh build target exists: $path"}
$planned=@($ready,(Join-Path $ready 'PORTAL_REQUEST_MANIFEST.json'),(Join-Path $ready 'payload\O3P8_DETECTOR_CONFIG_EQUIVALENCE_GATE.json'),$finalZip,$gatePath,(Join-Path $staging 'x\payload\O3Q1_ENDPOINT_LIVE_INVOCATION.json'));$pathGate=&$pathTool -CandidatePath $planned -ReservedSuffixCharacters 32 -AsJson|ConvertFrom-Json;Assert-True ([string]$pathGate.state-eq'PASS_PATH_BUDGET') 'O3Q1 build path gate failed.'
if($Preflight){[ordered]@{schema='argos_o3q1_build_preflight_v1';createdUtc=[DateTime]::UtcNow.ToString('o');state='PASS_O3Q1_BUILD_PREFLIGHT';requestId=$requestId;payloadFileCount=$files.Count;definitionSha256=$definitionSha;recoveryIntentSha256=$recoverySha;rehearsalGateSha256=$rehearsalSha;pathState=[string]$pathGate.state;mutationsPerformed=$false;sourceImageBytesRead=$false;providerActivated=$false;reviewOnly=$true;productionRoutingEnabled=$false}|ConvertTo-Json -Depth 8;return}

$identityValue=Get-Content -LiteralPath $identity -Raw|ConvertFrom-Json;$thumbprint=([string]$identityValue.thumbprint).Replace(' ','').ToUpperInvariant();$store=New-Object Security.Cryptography.X509Certificates.X509Store('My',[Security.Cryptography.X509Certificates.StoreLocation]::CurrentUser);$store.Open([Security.Cryptography.X509Certificates.OpenFlags]::ReadOnly);try{$matches=@($store.Certificates|Where-Object{([string]$_.Thumbprint).Replace(' ','').ToUpperInvariant()-eq$thumbprint});Assert-True ($matches.Count-eq1) 'O3Q1 signer cardinality changed.';$signer=$matches[0]}finally{$store.Close();$store.Dispose()};Assert-True $signer.HasPrivateKey 'O3Q1 signer private key is absent.'
$created=[DateTimeOffset]::UtcNow;$manifest=[ordered]@{schema='argos_project_portal_request_manifest_v1';requestId=$requestId;createdUtc=$created.ToString('o');expiresUtc=$created.AddHours(24).ToString('o');targetRole='JBOD';jobClass='MAINTENANCE_PATCH';handler='';maxResultBytes=[int64]$def.maxResultBytes;reviewOnly=$true;trainingEligible=$false;xmlEligible=$false;productionEligible=$false;productionRoutingEnabled=$false;credentialsIncluded=$false;signerThumbprint=$thumbprint;signatureAlgorithm='RSA-SHA256-PKCS1';files=@($files|ForEach-Object{[ordered]@{path=$_.path;bytes=[int64](Get-Item -LiteralPath $_.source).Length;sha256=$_.sha256}});entryPoint=[string]$def.entryPoint;changes=@($def.changes);entryPointMutations=@($def.entryPointMutations);entryPointOutputs=@($def.entryPointOutputs);sourceProcessingContract=$def.sourceProcessingContract;timeoutContract=$def.timeoutContract;allowedTaskActions=@();allowedProcessActions=@($def.allowedProcessActions);rehearsal=$def.rehearsal;requestRetryAuthorized=$false}
$requestPartial=Join-Path $partial $requestName;$payloadPartial=Join-Path $requestPartial 'payload';[void](New-Item -ItemType Directory -Path $payloadPartial);foreach($file in $files){Copy-Item -LiteralPath $file.source -Destination (Join-Path $requestPartial $file.path.Replace('/','\')) -ErrorAction Stop}
$manifestPath=Join-Path $requestPartial 'PORTAL_REQUEST_MANIFEST.json';$signaturePath=Join-Path $requestPartial 'PORTAL_REQUEST_MANIFEST.sig';$utf8=New-Object Text.UTF8Encoding($false);$manifestBytes=$utf8.GetBytes(($manifest|ConvertTo-Json -Depth 32));[IO.File]::WriteAllBytes($manifestPath,$manifestBytes);$rsa=[Security.Cryptography.X509Certificates.RSACertificateExtensions]::GetRSAPrivateKey($signer);try{$signature=$rsa.SignData($manifestBytes,[Security.Cryptography.HashAlgorithmName]::SHA256,[Security.Cryptography.RSASignaturePadding]::Pkcs1)}finally{$rsa.Dispose()};[IO.File]::WriteAllBytes($signaturePath,$signature)
[void](New-Item -ItemType Directory -Path (Split-Path -Parent $ready));Move-Item -LiteralPath $requestPartial -Destination $ready;$packageTest=&$packageTester -PackagePath $ready -SignerCertificatePath $certificate -ExpectedTargetRole JBOD -ExpectedJobClass MAINTENANCE_PATCH;Assert-True ([string]$packageTest.State-eq'PASS_SIGNED_PORTAL_PACKAGE') 'O3Q1 signed request verification failed.'
Add-Type -AssemblyName System.IO.Compression.FileSystem;$zipPartial=Join-Path $staging $zipName;[IO.Compression.ZipFile]::CreateFromDirectory($ready,$zipPartial,[IO.Compression.CompressionLevel]::Optimal,$false);$extract=Join-Path $staging 'x';[IO.Compression.ZipFile]::ExtractToDirectory($zipPartial,$extract);$expected=@{};foreach($file in $files){$expected[$file.path]=$file.sha256};$expected['PORTAL_REQUEST_MANIFEST.json']=Get-Sha(Join-Path $ready 'PORTAL_REQUEST_MANIFEST.json');$expected['PORTAL_REQUEST_MANIFEST.sig']=Get-Sha(Join-Path $ready 'PORTAL_REQUEST_MANIFEST.sig');$leaves=@(Get-ChildItem -LiteralPath $extract -Recurse -File);Assert-True ($leaves.Count-eq($files.Count+2)) 'O3Q1 final ZIP file count changed.';foreach($item in $expected.GetEnumerator()){$leaf=Join-Path $extract $item.Key.Replace('/','\');Assert-Pin $leaf ([string]$item.Value)}
$tokens=$null;$errors=$null;[void][Management.Automation.Language.Parser]::ParseFile((Join-Path $extract 'payload\Invoke-O3Q1Slot16NumericEndpoint.ps1'),[ref]$tokens,[ref]$errors);Assert-True (@($errors).Count-eq0) 'O3Q1 extracted endpoint parser failed.';$zipSha=Get-Sha $zipPartial
$gate=[ordered]@{schema='argos_o3q1_final_package_gate_v1';createdUtc=[DateTime]::UtcNow.ToString('o');state='PASS_O3Q1_FINAL_PACKAGE_GATE';requestId=$requestId;requestZip='work/OPENCV_EDGE_NOTCH_O3Q1/final_numeric/'+$zipName;requestZipBytes=[int64](Get-Item $zipPartial).Length;requestZipSha256=$zipSha;requestManifestSha256=$expected['PORTAL_REQUEST_MANIFEST.json'];requestSignatureSha256=$expected['PORTAL_REQUEST_MANIFEST.sig'];payloadFileCount=$files.Count;maintenanceDefinitionSha256=$definitionSha;endpointSha256=$files[0].sha256;engineSha256=$files[1].sha256;seedProjectionSha256=$files[4].sha256;seedSourceManifestSha256=$files[5].sha256;sourceRecordSha256=$files[6].sha256;liveInvocationSha256=$files[11].sha256;protocolAnchorSha256=$files[3].sha256;protocolAnchorInstalledBytesExpectedUnchanged=$true;installedProtocolAnchorDestinationExecutedByEntrypoint=$false;packagedProtocolAnchorBytesExecutedAsFrozenCropModule=$true;recoveryIntentSha256=$recoverySha;rehearsalGateSha256=$rehearsalSha;inheritedQueueGateSha256=Get-Sha $queueGate;inheritedCompleteRouteGateSha256=Get-Sha $routeGate;exactFinalZipExtractionPassed=$true;exactFinalZipPayloadHashesPassed=$true;exactPackageSignaturePassed=$true;windowsPowerShell51ParserPassed=$true;sourceImageBytesRead=$false;detectorRerunPerformed=$false;thresholdOrAlgorithmChanged=$false;allFrozenDfSeedCandidateCount=21;backsidePixelsConsumed=$false;knownNotchLocationConsumed=$false;hotspotMembershipConsumed=$false;sourceMutationPerformed=$false;processorTouched=$false;providerActivated=$false;requestRetryAuthorized=$false;reviewOnly=$true;trainingEligible=$false;xmlEligible=$false;productionEligible=$false;productionRoutingEnabled=$false;publicationAuthorized=$false}
[void](New-Item -ItemType Directory -Path $finalRoot);Move-Item -LiteralPath $zipPartial -Destination $finalZip;Assert-Pin $finalZip $zipSha;Write-NewJson $gatePath $gate 16;Write-NewJson (Join-Path $finalRoot ($zipName+'.gate.json')) $gate 16;$resolvedStaging=[IO.Path]::GetFullPath($staging);Assert-True ($resolvedStaging-eq'C:\A3Q1B') 'O3Q1 staging cleanup target changed.';[IO.Directory]::Delete($resolvedStaging,$true);$gate|ConvertTo-Json -Depth 16
