#Requires -Version 5.1
[CmdletBinding()]
param([switch]$Preflight,[switch]$Rehearsal,[string]$InvocationManifest='')

$ErrorActionPreference='Stop'
Set-StrictMode -Version Latest
$liveInvocationSha256='1B88F6D6A5A5CCAEC04929BF03CF3ED0B5501F918658E50E0EBD54178828AF6E'

function Assert-True([bool]$Condition,[string]$Message){if(-not $Condition){throw $Message}}
function Get-Sha([string]$Path){$stream=[IO.File]::OpenRead($Path);$hash=[Security.Cryptography.SHA256]::Create();try{return([BitConverter]::ToString($hash.ComputeHash($stream))).Replace('-','')}finally{$hash.Dispose();$stream.Dispose()}}
function Assert-Pin([string]$Path,[string]$Hash,[string]$Label){Assert-True (Test-Path -LiteralPath $Path -PathType Leaf) "O3Q1 $Label absent: $Path";Assert-True ((Get-Sha $Path)-eq$Hash) "O3Q1 $Label changed: $Path"}
function Assert-PathBudget([string]$Path,[int]$Reserve=32){$full=[IO.Path]::GetFullPath($Path);$parts=@($full.Split([char[]]@('\','/'),[StringSplitOptions]::RemoveEmptyEntries));$maximum=if($parts.Count){[int](($parts|ForEach-Object{$_.Length}|Measure-Object -Maximum).Maximum)}else{0};Assert-True (($full.Length+$Reserve)-lt200) "O3Q1 unsafe path: $full";Assert-True ($maximum-le80) "O3Q1 unsafe component: $full"}
function Write-NewJson([string]$Path,[object]$Value,[int]$Depth=64){Assert-True (-not(Test-Path -LiteralPath $Path)) "O3Q1 create-new JSON exists: $Path";[IO.File]::WriteAllText($Path,(($Value|ConvertTo-Json -Depth $Depth)+[Environment]::NewLine),(New-Object Text.UTF8Encoding($false)))}
function Get-ProcessorRows([string]$Token){return @(Get-CimInstance Win32_Process -Filter "Name='powershell.exe' OR Name='pwsh.exe'" -ErrorAction Stop|Where-Object{[string]$_.CommandLine-like('*'+$Token+'*')}|Sort-Object ProcessId|ForEach-Object{[pscustomobject]@{processId=[uint32]$_.ProcessId;creationDate=[string]$_.CreationDate;commandLine=[string]$_.CommandLine}})}
function Invoke-Python([string]$Python,[string]$Engine,[string]$Job,[string]$ModuleRoot,[int]$TimeoutSeconds,[int]$MaximumOutputBytes){
  $start=New-Object Diagnostics.ProcessStartInfo;$start.FileName=$Python;$start.Arguments='"'+$Engine+'" --job "'+$Job+'"';$start.UseShellExecute=$false;$start.CreateNoWindow=$true;$start.RedirectStandardOutput=$true;$start.RedirectStandardError=$true;$start.EnvironmentVariables['PYTHONDONTWRITEBYTECODE']='1';$start.EnvironmentVariables['PYTHONNOUSERSITE']='1';$start.EnvironmentVariables['PYTHONPATH']=$ModuleRoot
  $process=New-Object Diagnostics.Process;$process.StartInfo=$start;Assert-True $process.Start() 'O3Q1 Python did not start.';$stdoutTask=$process.StandardOutput.ReadToEndAsync();$stderrTask=$process.StandardError.ReadToEndAsync();if(-not$process.WaitForExit($TimeoutSeconds*1000)){try{$process.Kill()}catch{};[void]$process.WaitForExit(5000);throw'O3Q1 Python exceeded its bounded timeout.'};$process.WaitForExit();$result=[pscustomobject]@{exitCode=$process.ExitCode;stdout=[string]$stdoutTask.Result;stderr=[string]$stderrTask.Result};$process.Dispose();Assert-True ($result.stdout.Length-le$MaximumOutputBytes-and$result.stderr.Length-le$MaximumOutputBytes) 'O3Q1 Python output exceeded the bound.';return $result
}
function Assert-SeedProjection([object]$Seed,[object]$Manifest,[object]$SourceRecord,[object]$Contract,[int]$ExpectedCount){
  Assert-True ([string]$Seed.schema-eq'argos_ocv03_o3q1_slot16_seed_projection_v1') 'O3Q1 seed schema changed.'
  Assert-True ([string]$Seed.identity-eq[string]$Contract.input.identity-and[string]$SourceRecord.identity-eq[string]$Contract.input.identity) 'O3Q1 identity changed.'
  Assert-True (@($Seed.physicalIndentationCandidates).Count-eq0-and@($Seed.dfOnlyBoundaryCandidates).Count-eq$ExpectedCount-and[int]$Seed.seedCandidateCount-eq$ExpectedCount) 'O3Q1 seed cardinality changed.'
  $pairId=[string]$Seed.seedSource.pairId;$rows=@($Manifest.results|Where-Object{[string]$_.pairId-eq$pairId});Assert-True (-not[string]::IsNullOrWhiteSpace($pairId)-and$rows.Count-eq1) 'O3Q1 seed source pair cardinality changed.';$sourceCandidates=@($rows[0].df.candidates);Assert-True ($sourceCandidates.Count-eq$ExpectedCount) 'O3Q1 seed source candidate cardinality changed.'
  for($index=0;$index-lt$ExpectedCount;$index++){$projected=$Seed.dfOnlyBoundaryCandidates[$index];$source=$sourceCandidates[$index];Assert-True ([int]$projected.sourceOrdinal-eq$index) "O3Q1 seed ordinal changed: $index";Assert-True ([double]$projected.centerAngleDegrees-eq[double]$source.axisCenterAngleDegrees) "O3Q1 seed angle changed: $index";Assert-True ([double]$projected.widthDegrees-eq[double]$source.widthDegrees) "O3Q1 seed width changed: $index";Assert-True ([double]$projected.maximumDepthPx-eq[double]$source.peakDepthPx) "O3Q1 seed depth changed: $index"}
  Assert-True ([int]$Seed.bf.widthPx-eq[int]$SourceRecord.bf.widthPx-and[int]$Seed.bf.heightPx-eq[int]$SourceRecord.bf.heightPx) 'O3Q1 BF dimensions changed.'
  Assert-True (($Seed.bf.fit|ConvertTo-Json -Depth 8 -Compress)-ceq($SourceRecord.bf.fit|ConvertTo-Json -Depth 8 -Compress)) 'O3Q1 BF fit projection changed.'
  Assert-True ([string]$Contract.input.bf.sha256-eq[string]$SourceRecord.sources.bfSha256-and[int64]$Contract.input.bf.bytes-eq[int64]$SourceRecord.sources.bfBytes) 'O3Q1 BF source contract changed.'
  Assert-True ([string]$Contract.input.df.sha256-eq[string]$SourceRecord.sources.dfSha256-and[int64]$Contract.input.df.bytes-eq[int64]$SourceRecord.sources.dfBytes) 'O3Q1 DF source contract changed.'
  Assert-True ([bool]$Seed.fullPerimeterInference-and-not[bool]$Seed.knownNotchLocationConsumed-and-not[bool]$Seed.notchAnglePriorConsumed-and-not[bool]$Seed.fixedAngularSearchWindowConsumed-and-not[bool]$Seed.argosRotationOrientationLocationInputConsumed-and-not[bool]$Seed.hotspotMembershipConsumed-and-not[bool]$Seed.backsidePixelsConsumed) 'O3Q1 seed authority changed.'
}
function New-Terminal([object]$EngineTerminal,[object]$Output,[string]$OutputPath,[string]$OutputSha,[int]$ExpectedCount,[bool]$IsRehearsal){
  Assert-True ([string]$EngineTerminal.state-eq'COMPLETE_O3P8_POST2_BF_TOPOLOGY_DF_RADIAL_REVIEW_ONLY'-and[int]$EngineTerminal.inputCount-eq1-and[int]$EngineTerminal.dfTopologyInvocationCount-eq0) 'O3Q1 engine terminal changed.'
  Assert-True ([string]$Output.schema-eq'argos_ocv03_o3p8_front_split_notch_result_v1'-and[string]$Output.state-eq[string]$EngineTerminal.state-and[int]$Output.inputCount-eq1-and@($Output.rows).Count-eq1-and[int]$Output.dfTopologyInvocationCount-eq0) 'O3Q1 engine output changed.'
  $row=$Output.rows[0];Assert-True ([int]$row.seedCount-eq$ExpectedCount-and@($EngineTerminal.states).Count-eq1-and[string]$EngineTerminal.states[0]-eq[string]$row.state) 'O3Q1 output seed or member-state contract changed.'
  Assert-True (-not[bool]$Output.knownNotchLocationConsumed-and-not[bool]$Output.notchAnglePriorConsumed-and-not[bool]$Output.fixedAngularSearchWindowConsumed-and-not[bool]$Output.scorerInputsConsumed-and-not[bool]$Output.backsidePixelsConsumed-and-not[bool]$Output.rasterOutputCreated-and-not[bool]$Output.sourceMutationPerformed) 'O3Q1 output authority changed.'
  $numericPass=([string]$row.state-eq'PASS_REVIEW_ONLY_UNIQUE_BF_TOPOLOGY_DF_RADIAL_NOTCH'-and[int]$row.eligibleCount-eq1-and$null-ne$row.selected)
  return [ordered]@{schema='argos_ocv03_o3q1_endpoint_result_v1';createdUtc=[DateTime]::UtcNow.ToString('o');state='COMPLETE_O3Q1_NUMERIC_REVIEW_ONLY';revision='FMOCV03_O3Q1_20260828T025500Z';rehearsal=$IsRehearsal;engineState=[string]$Output.state;numericDecision=[string]$row.state;numericIndependentPass=$numericPass;identity=[string]$row.identity;seedCount=[int]$row.seedCount;eligibleCount=[int]$row.eligibleCount;candidateLocalTopologyInsufficiencyCount=[int]$row.candidateLocalTopologyInsufficiencyCount;selected=$row.selected;engineOutputPath=$OutputPath;engineOutputSha256=$OutputSha;numericResult=$Output;allFrozenDfSeedsConsumed=$true;knownNotchLocationConsumed=$false;hotspotMembershipConsumed=$false;argosRotationMetadataConsumed=$false;backsidePixelsConsumed=$false;dfTopologyInvocationCount=0;rasterOutputCreated=$false;sourceMutationPerformed=$false;sourceDeletionPerformed=$false;processorTouched=$false;providerActivated=$false;requestRetryAuthorized=$false;reviewOnly=$true;trainingEligible=$false;xmlEligible=$false;productionEligible=$false;productionRoutingEnabled=$false}
}

$manifestPath=if([string]::IsNullOrWhiteSpace($InvocationManifest)){Join-Path $PSScriptRoot 'O3Q1_ENDPOINT_LIVE_INVOCATION.json'}else{[IO.Path]::GetFullPath($InvocationManifest)}
$expectedManifestSha256=$liveInvocationSha256
if($Rehearsal){$expectedManifestSha256=Get-Sha $manifestPath}
Assert-Pin $manifestPath $expectedManifestSha256 'invocation'
$inv=Get-Content -LiteralPath $manifestPath -Raw|ConvertFrom-Json;$expectedState=if($Rehearsal){'FROZEN_REHEARSAL_CONTRACT'}else{'FROZEN_LIVE_CONTRACT'}
Assert-True ([string]$inv.schema-eq'argos_ocv03_o3q1_endpoint_invocation_v1'-and[string]$inv.state-eq$expectedState) 'O3Q1 invocation identity changed.'
Assert-True ($env:COMPUTERNAME.Equals([string]$inv.expectedComputerName,[StringComparison]::OrdinalIgnoreCase)) "O3Q1 wrong computer: $env:COMPUTERNAME"
Assert-True ([bool]$inv.sourceImageReadAuthorized-and[bool]$inv.detectorRerunAuthorized-and-not[bool]$inv.thresholdOrAlgorithmChangeAuthorized-and[bool]$inv.allFrozenDfSeedsRequired-and[bool]$inv.frontsideOnly-and-not[bool]$inv.backsidePixelsConsumed-and-not[bool]$inv.argosRotationMetadataConsumed-and-not[bool]$inv.knownNotchLocationConsumed-and-not[bool]$inv.hotspotMembershipConsumed) 'O3Q1 image authority changed.'
Assert-True (-not[bool]$inv.taskOrManagedProcessActionAuthorized-and-not[bool]$inv.sourceMutationAuthorized-and-not[bool]$inv.sourceDeletionAuthorized-and-not[bool]$inv.providerActivationAuthorized-and-not[bool]$inv.requestRetryAuthorized-and[bool]$inv.reviewOnly-and-not[bool]$inv.trainingEligible-and-not[bool]$inv.xmlEligible-and-not[bool]$inv.productionEligible-and-not[bool]$inv.productionRoutingEnabled) 'O3Q1 authority widened.'
$payloadRoot=if([string]::IsNullOrWhiteSpace([string]$inv.payloadRoot)){$PSScriptRoot}else{[IO.Path]::GetFullPath([string]$inv.payloadRoot)}
$engine=Join-Path $payloadRoot ([string]$inv.engineFile);$topology=Join-Path $payloadRoot ([string]$inv.topologyFile);$crop=Join-Path $payloadRoot ([string]$inv.cropFile);$seed=Join-Path $payloadRoot ([string]$inv.seedFile);$seedSource=Join-Path $payloadRoot ([string]$inv.seedSourceManifestFile);$sourceRecord=Join-Path $payloadRoot ([string]$inv.sourceRecordFile);$runtimeGate=Join-Path $payloadRoot ([string]$inv.runtimeGateFile);$jobContract=Join-Path $payloadRoot ([string]$inv.jobContractFile);$fixture=Join-Path $payloadRoot ([string]$inv.terminalFixtureFile);$configGate=Join-Path $payloadRoot ([string]$inv.configEquivalenceGateFile)
foreach($pin in @(@($engine,[string]$inv.engineSha256,'engine'),@($topology,[string]$inv.topologySha256,'topology'),@($crop,[string]$inv.cropSha256,'crop'),@($seed,[string]$inv.seedSha256,'seed'),@($seedSource,[string]$inv.seedSourceManifestSha256,'seed source'),@($sourceRecord,[string]$inv.sourceRecordSha256,'source record'),@($runtimeGate,[string]$inv.runtimeGateSha256,'runtime gate'),@($jobContract,[string]$inv.jobContractSha256,'job contract'),@($fixture,[string]$inv.terminalFixtureSha256,'terminal fixture'),@($configGate,[string]$inv.configEquivalenceGateSha256,'config gate'))){Assert-Pin $pin[0] $pin[1] $pin[2];Assert-PathBudget $pin[0]}
$python=[IO.Path]::GetFullPath([string]$inv.runtimePath);$runtimeInstall=[IO.Path]::GetFullPath([string]$inv.runtimeInstallationPath);Assert-Pin $python ([string]$inv.runtimeSha256) 'runtime';Assert-Pin $runtimeInstall ([string]$inv.runtimeInstallationSha256) 'runtime installation'
$runtimeRoot=[IO.Path]::GetFullPath([string]$inv.runtimeRoot);$moduleRoot=[IO.Path]::GetFullPath([string]$inv.pythonModuleRoot);Assert-True ((Test-Path -LiteralPath $runtimeRoot -PathType Container)-and(Test-Path -LiteralPath $moduleRoot -PathType Container)) 'O3Q1 runtime root changed.'
$contract=Get-Content -LiteralPath $jobContract -Raw|ConvertFrom-Json;$seedValue=Get-Content -LiteralPath $seed -Raw|ConvertFrom-Json;$seedSourceValue=Get-Content -LiteralPath $seedSource -Raw|ConvertFrom-Json;$sourceRecordValue=Get-Content -LiteralPath $sourceRecord -Raw|ConvertFrom-Json;$configValue=Get-Content -LiteralPath $configGate -Raw|ConvertFrom-Json
Assert-True ([string]$contract.schema-eq'argos_ocv03_o3q1_job_contract_v1'-and[string]$contract.engineJobSchema-eq'argos_ocv03_o3p8_front_split_notch_job_v1'-and[int]$contract.expectedInputCount-eq1-and[int]$contract.expectedSeedCandidateCount-eq[int]$inv.expectedSeedCandidateCount) 'O3Q1 job contract changed.'
Assert-True ([string]$configValue.state-eq'PASS_O3P8_DETECTOR_CONFIG_EQUIVALENCE') 'O3Q1 O3P8 config-equivalence gate changed.'
Assert-SeedProjection $seedValue $seedSourceValue $sourceRecordValue $contract ([int]$inv.expectedSeedCandidateCount)
$sourceRoot=[IO.Path]::GetFullPath([string]$inv.sourceRoot);$output=[IO.Path]::GetFullPath([string]$inv.outputRoot);$outputPartial=$output+'.partial';$outputFailed=$output+'.failed';$outputParent=Split-Path -Parent $output;$alias=[string]$inv.sourceAliasDrive;$aliasPath=$alias+'\';$subst=Join-Path $env:SystemRoot 'System32\subst.exe';$jobPath=Join-Path $outputPartial 'O3Q1_JOB.json';$resultPartial=Join-Path $outputPartial 'O3Q1_RESULT.json';$resultFinal=Join-Path $output 'O3Q1_RESULT.json'
Assert-True ((Test-Path -LiteralPath $sourceRoot -PathType Container)-and(Test-Path -LiteralPath $outputParent -PathType Container)) 'O3Q1 source or output parent absent.'
foreach($path in @($sourceRoot,$output,$outputPartial,$outputFailed,$jobPath,$resultPartial,$resultFinal)){Assert-PathBudget $path}
foreach($path in @($output,$outputPartial,$outputFailed)){Assert-True (-not(Test-Path -LiteralPath $path)) "O3Q1 create-new target exists: $path"}
Assert-True (-not(Test-Path -LiteralPath $aliasPath)-and$null-eq(Get-PSDrive -Name $alias.TrimEnd(':') -ErrorAction SilentlyContinue)) 'O3Q1 source alias is already in use.'
$processorBefore=@(Get-ProcessorRows ([string]$inv.processorCommandToken))
if($Preflight){$fixtureValue=Get-Content -LiteralPath $fixture -Raw|ConvertFrom-Json;Assert-True ([string]$fixtureValue.schema-eq'argos_ocv03_o3q1_terminal_gate_fixture_v1') 'O3Q1 terminal fixture schema changed.';$fixtureTerminal=New-Terminal $fixtureValue.engineTerminal $fixtureValue.engineOutput ([string]$fixtureValue.engineTerminal.outputPath) ([string]$fixtureValue.engineTerminal.outputSha256) ([int]$inv.expectedSeedCandidateCount) ([bool]$Rehearsal);Assert-True ([string]$fixtureTerminal.state-eq[string]$fixtureValue.expectedTerminal.state-and[bool]$fixtureTerminal.numericIndependentPass-eq[bool]$fixtureValue.expectedTerminal.numericIndependentPass-and[int]$fixtureTerminal.seedCount-eq[int]$fixtureValue.expectedTerminal.seedCount-and[int]$fixtureTerminal.eligibleCount-eq[int]$fixtureValue.expectedTerminal.eligibleCount) 'O3Q1 terminal fixture construction changed.';[ordered]@{schema='argos_ocv03_o3q1_endpoint_preflight_v1';createdUtc=[DateTime]::UtcNow.ToString('o');state='PASS_O3Q1_ENDPOINT_PREFLIGHT';revision=[string]$inv.revision;rehearsal=[bool]$Rehearsal;seedCandidateCount=[int]$inv.expectedSeedCandidateCount;terminalFixturePassed=$true;sourceMetadataRead=$false;sourceImageBytesRead=$false;pixelsDecoded=$false;outputCreated=$false;mutationsPerformed=$false;processorProcessCount=$processorBefore.Count;backsidePixelsConsumed=$false;knownNotchLocationConsumed=$false;hotspotMembershipConsumed=$false;reviewOnly=$true;productionRoutingEnabled=$false}|ConvertTo-Json -Depth 8;return}

$aliasCreated=$false;$outputCommitted=$false;$terminal=$null
try{
  $substText=&$subst $alias $sourceRoot 2>&1|Out-String;Assert-True ($LASTEXITCODE-eq0-and(Test-Path -LiteralPath $aliasPath -PathType Container)) ('O3Q1 source alias creation failed: '+$substText.Trim());$aliasCreated=$true
  [void][IO.Directory]::CreateDirectory($outputPartial)
  $job=[ordered]@{schema=[string]$contract.engineJobSchema;revision=[string]$contract.revision;runtimeRoot=$runtimeRoot;runtimeGate=[ordered]@{path=$runtimeGate;sha256=[string]$inv.runtimeGateSha256};topologyEngine=[ordered]@{path=$topology;sha256=[string]$inv.topologySha256};cropEngine=[ordered]@{path=$crop;sha256=[string]$inv.cropSha256};expectedOpenCvVersion='5.0.0';expectedNumpyVersion='2.5.1';channelMethods=$contract.channelMethods;crop=$contract.crop;topologyConfig=$contract.topologyConfig;corroboration=$contract.corroboration;candidateLocalTopologyErrors=@($contract.candidateLocalTopologyErrors);outputPath=$resultPartial;expectedInputCount=1;inputs=@([ordered]@{identity=[string]$contract.input.identity;r6SeedResult=[ordered]@{path=$seed;sha256=[string]$inv.seedSha256};bf=$contract.input.bf;df=$contract.input.df});knownNotchLocationConsumed=$false;notchAnglePriorConsumed=$false;fixedAngularSearchWindowConsumed=$false;scorerInputsPresent=$false;sourceMutationAllowed=$false;rasterOutputAllowed=$false;liveProviderActivation=$false;backsidePixelsConsumed=$false;dfTopologyInvocationAllowed=$false;reviewOnly=$true;trainingEligible=$false;xmlEligible=$false;productionEligible=$false;productionRoutingEnabled=$false}
  Write-NewJson $jobPath $job 32
  $run=Invoke-Python $python $engine $jobPath $moduleRoot ([int]$inv.pythonChildTimeoutSeconds) ([int]$inv.maximumStdoutBytes);Assert-True ($run.exitCode-eq0) ('O3Q1 engine failed: '+$run.stderr.Trim());$engineTerminal=$run.stdout.Trim()|ConvertFrom-Json;Assert-Pin $resultPartial ([string]$engineTerminal.outputSha256) 'engine output';$outputValue=Get-Content -LiteralPath $resultPartial -Raw|ConvertFrom-Json
  $terminal=New-Terminal $engineTerminal $outputValue $resultFinal ([string]$engineTerminal.outputSha256) ([int]$inv.expectedSeedCandidateCount) ([bool]$Rehearsal)
  Move-Item -LiteralPath $outputPartial -Destination $output;$outputCommitted=$true;Assert-Pin $resultFinal ([string]$engineTerminal.outputSha256) 'committed engine output'
}catch{if($outputCommitted-and(Test-Path -LiteralPath $output)-and-not(Test-Path -LiteralPath $outputFailed)){Move-Item -LiteralPath $output -Destination $outputFailed -ErrorAction SilentlyContinue}elseif(Test-Path -LiteralPath $outputPartial){Move-Item -LiteralPath $outputPartial -Destination $outputFailed -ErrorAction SilentlyContinue};throw}finally{if($aliasCreated){$removeText=&$subst $alias /D 2>&1|Out-String;if($LASTEXITCODE-ne0-or(Test-Path -LiteralPath $aliasPath)-or$null-ne(Get-PSDrive -Name $alias.TrimEnd(':') -ErrorAction SilentlyContinue)){throw('O3Q1 source alias removal failed: '+$removeText.Trim())}}}
$processorAfter=@(Get-ProcessorRows ([string]$inv.processorCommandToken));Assert-True (($processorBefore|ConvertTo-Json -Depth 6 -Compress)-ceq($processorAfter|ConvertTo-Json -Depth 6 -Compress)) 'O3Q1 protected processor identity changed.';$terminal.processorProcessCount=$processorAfter.Count;$terminal.processorIdentityUnchanged=$true;$terminal.sourceAliasRemoved=$true;$terminal|ConvertTo-Json -Depth 64
